import type {ReleaseGateViewModel} from "@/lib/operable-release-gate/release-gate-view-model";
import styles from "./tablet-operable-release-gate.module.css";
function formatCount(value:number){return new Intl.NumberFormat("es-MX").format(value)}
export function TabletOperableReleaseGateScreen({model}:{model:ReleaseGateViewModel}){return <section className={styles.screen} aria-label="Estado operativo de liberación" data-prisma-release-gate="03Z"
  data-surface="tablet"
  data-screen="release_gate"
  data-zone="pos"
  data-panel="tablet-operable-release-gate-screen"
  data-target="tablet-operable-release-gate-screen-estado-operativo-de-liberaci-n-4"
  data-kind="badge"
  data-role="revenue-core"
><div data-surface="tablet" data-screen="pos" data-zone="unknown_group" data-panel="tablet_operable_release_gate_screen" data-target="tablet-operable-release-gate-screen-div-1" data-kind="panel" data-role="container" className={styles.hero}><div data-surface="tablet" data-screen="pos" data-zone="unknown_group" data-panel="tablet_operable_release_gate_screen" data-target="tablet-operable-release-gate-screen-div-2" data-kind="panel" data-role="container"><p className={styles.eyebrow}
  data-surface="tablet"
  data-screen="release_gate"
  data-zone="pos"
  data-panel="tablet-operable-release-gate-screen"
  data-target="tablet-operable-release-gate-screen-table-4"
  data-kind="table"
  data-role="data-display"
>Cierre de ola Tablet</p><h2
  data-surface="tablet"
  data-screen="release_gate"
  data-zone="pos"
  data-panel="tablet-operable-release-gate-screen"
  data-target="tablet-operable-release-gate-screen-text-4"
  data-kind="text"
  data-role="copy"
>{model.headline}</h2><p data-surface="tablet" data-screen="pos" data-zone="unknown_group" data-panel="tablet_operable_release_gate_screen" data-target="tablet-operable-release-gate-screen-p-3" data-kind="text" data-role="text">{model.summary}</p></div><div className={styles.scoreCard} aria-label="Calificación de preparación"
  data-surface="tablet"
  data-screen="release_gate"
  data-zone="pos"
  data-panel="tablet-operable-release-gate-screen"
  data-target="tablet-operable-release-gate-screen-calificaci-n-de-preparaci-n-4"
  data-kind="panel"
  data-role="revenue-core"
><strong
  data-surface="tablet"
  data-screen="release_gate"
  data-zone="pos"
  data-panel="tablet-operable-release-gate-screen"
  data-target="tablet-operable-release-gate-screen-element-4"
  data-kind="element"
  data-role="revenue-core"
>{model.score}%</strong><span data-surface="tablet" data-screen="pos" data-zone="unknown_group" data-panel="tablet_operable_release_gate_screen" data-target="tablet-operable-release-gate-screen-span-4" data-kind="text" data-role="text">preparación</span></div></div><div data-surface="tablet" data-screen="pos" data-zone="unknown_group" data-panel="tablet_operable_release_gate_screen" data-target="tablet-operable-release-gate-screen-div-5" data-kind="panel" data-role="container" className={styles.kpis}><article
  data-surface="tablet"
  data-screen="release_gate"
  data-zone="pos"
  data-panel="tablet-operable-release-gate-screen"
  data-target="tablet-operable-release-gate-screen-panel-4"
  data-kind="panel"
  data-role="revenue-core"
><strong
  data-surface="tablet"
  data-screen="release_gate"
  data-zone="pos"
  data-panel="tablet-operable-release-gate-screen"
  data-target="tablet-operable-release-gate-screen-element-4"
  data-kind="element"
  data-role="revenue-core"
>{formatCount(model.readyCount)}</strong><span data-surface="tablet" data-screen="pos" data-zone="unknown_group" data-panel="tablet_operable_release_gate_screen" data-target="tablet-operable-release-gate-screen-span-6" data-kind="text" data-role="text">listos</span></article><article
  data-surface="tablet"
  data-screen="release_gate"
  data-zone="pos"
  data-panel="tablet-operable-release-gate-screen"
  data-target="tablet-operable-release-gate-screen-panel-4"
  data-kind="panel"
  data-role="revenue-core"
><strong
  data-surface="tablet"
  data-screen="release_gate"
  data-zone="pos"
  data-panel="tablet-operable-release-gate-screen"
  data-target="tablet-operable-release-gate-screen-element-4"
  data-kind="element"
  data-role="revenue-core"
>{formatCount(model.attentionCount)}</strong><span data-surface="tablet" data-screen="pos" data-zone="unknown_group" data-panel="tablet_operable_release_gate_screen" data-target="tablet-operable-release-gate-screen-span-7" data-kind="text" data-role="text">por revisar</span></article><article
  data-surface="tablet"
  data-screen="release_gate"
  data-zone="pos"
  data-panel="tablet-operable-release-gate-screen"
  data-target="tablet-operable-release-gate-screen-panel-4"
  data-kind="panel"
  data-role="revenue-core"
><strong
  data-surface="tablet"
  data-screen="release_gate"
  data-zone="pos"
  data-panel="tablet-operable-release-gate-screen"
  data-target="tablet-operable-release-gate-screen-element-4"
  data-kind="element"
  data-role="revenue-core"
>{formatCount(model.blockedCount)}</strong><span data-surface="tablet" data-screen="pos" data-zone="unknown_group" data-panel="tablet_operable_release_gate_screen" data-target="tablet-operable-release-gate-screen-span-8" data-kind="text" data-role="text">bloqueados</span></article><article
  data-surface="tablet"
  data-screen="release_gate"
  data-zone="pos"
  data-panel="tablet-operable-release-gate-screen"
  data-target="tablet-operable-release-gate-screen-panel-4"
  data-kind="panel"
  data-role="revenue-core"
><strong
  data-surface="tablet"
  data-screen="release_gate"
  data-zone="pos"
  data-panel="tablet-operable-release-gate-screen"
  data-target="tablet-operable-release-gate-screen-element-4"
  data-kind="element"
  data-role="revenue-core"
>{formatCount(model.totalCount)}</strong><span data-surface="tablet" data-screen="pos" data-zone="unknown_group" data-panel="tablet_operable_release_gate_screen" data-target="tablet-operable-release-gate-screen-span-9" data-kind="text" data-role="text">gates</span></article></div><div data-surface="tablet" data-screen="pos" data-zone="unknown_group" data-panel="tablet_operable_release_gate_screen" data-target="tablet-operable-release-gate-screen-div-10" data-kind="layout" data-role="container" className={styles.grid}>{model.buckets.map((bucket)=><article className={styles.bucket} key={bucket.surface} data-status={bucket.blocked
  data-surface="tablet"
  data-screen="release_gate"
  data-zone="pos"
  data-panel="tablet-operable-release-gate-screen"
  data-target="tablet-operable-release-gate-screen-badge-4"
  data-kind="badge"
  data-role="state-feedback"
>0?"blocked":bucket.attention>0?"attention":"ready"}><div data-surface="tablet" data-screen="pos" data-zone="unknown_group" data-panel="tablet_operable_release_gate_screen" data-target="tablet-operable-release-gate-screen-div-11" data-kind="panel" data-role="container"><h3 data-surface="tablet" data-screen="pos" data-zone="unknown_group" data-panel="tablet_operable_release_gate_screen" data-target="tablet-operable-release-gate-screen-h3-12" data-kind="text" data-role="text">{bucket.label}</h3><p data-surface="tablet" data-screen="pos" data-zone="unknown_group" data-panel="tablet_operable_release_gate_screen" data-target="tablet-operable-release-gate-screen-p-13" data-kind="text" data-role="text">{bucket.total} revisiones cubiertas</p></div><strong data-surface="tablet" data-screen="pos" data-zone="unknown_group" data-panel="tablet_operable_release_gate_screen" data-target="tablet-operable-release-gate-screen-strong-14" data-kind="price" data-role="price">{bucket.ready}/{bucket.total}</strong></article>)}</div><div className={styles.panelGrid}
  data-surface="tablet"
  data-screen="release_gate"
  data-zone="pos"
  data-panel="tablet-operable-release-gate-screen"
  data-target="tablet-operable-release-gate-screen-panel-4"
  data-kind="panel"
  data-role="revenue-core"
><section className={styles.panel}
  data-surface="tablet"
  data-screen="release_gate"
  data-zone="pos"
  data-panel="tablet-operable-release-gate-screen"
  data-target="tablet-operable-release-gate-screen-panel-4"
  data-kind="panel"
  data-role="revenue-core"
><h3 data-surface="tablet" data-screen="pos" data-zone="unknown_group" data-panel="tablet_operable_release_gate_screen" data-target="tablet-operable-release-gate-screen-h3-15" data-kind="text" data-role="text">Revisiones críticas</h3><ul data-surface="tablet" data-screen="pos" data-zone="unknown_group" data-panel="tablet_operable_release_gate_screen" data-target="tablet-operable-release-gate-screen-ul-16" data-kind="panel" data-role="panel">{model.checks.map((check)=><li key={check.id} data-status={check.status}
  data-surface="tablet"
  data-screen="release_gate"
  data-zone="pos"
  data-panel="tablet-operable-release-gate-screen"
  data-target="tablet-operable-release-gate-screen-badge-4"
  data-kind="badge"
  data-role="state-feedback"
><span data-surface="tablet" data-screen="pos" data-zone="unknown_group" data-panel="tablet_operable_release_gate_screen" data-target="tablet-operable-release-gate-screen-span-17" data-kind="text" data-role="text">{check.label}</span><small>{check.description}</small><em>{check.evidence}</em></li>)}</ul></section><section className={styles.panel}
  data-surface="tablet"
  data-screen="release_gate"
  data-zone="pos"
  data-panel="tablet-operable-release-gate-screen"
  data-target="tablet-operable-release-gate-screen-panel-4"
  data-kind="panel"
  data-role="revenue-core"
><h3>Capturas esperadas</h3><ol>{model.expectedCaptures.map((capture)=><li key={capture.id}><strong>{capture.label}</strong><span data-surface="tablet" data-screen="pos" data-zone="unknown_group" data-panel="tablet_operable_release_gate_screen" data-target="tablet-operable-release-gate-screen-span-18" data-kind="text" data-role="text">{capture.route}</span><small>{capture.purpose}</small></li>)}</ol></section></div></section>}
