import { DEFAULT_SCENE_LOOK_MODEL } from "../../scene-look-model";
import type { SceneDocument } from "../authoring-workbench-contracts";

export function createSampleSceneDocument(): SceneDocument {
  return {
    scene: {
      id: "scene-main",
      title: "Executive Summary",
      description: "Wave 1 sample scene for Authoring Workbench v1.",
      look: DEFAULT_SCENE_LOOK_MODEL,
    },
    rootLayoutId: "layout-root",
    layoutNodes: {
      "layout-root": {
        id: "layout-root",
        title: "Scene Root",
        kind: "root",
        parentId: null,
        childIds: ["layout-hero", "layout-metrics", "layout-chart"],
        orderIndex: 0,
        slotId: null,
        frame: { x: 0, y: 0, width: 920, height: 620 },
        locked: true,
      },
      "layout-hero": {
        id: "layout-hero",
        title: "Hero Slot Host",
        kind: "slot-reference",
        parentId: "layout-root",
        childIds: [],
        orderIndex: 0,
        slotId: "slot-hero",
        frame: { x: 24, y: 24, width: 872, height: 112 },
        locked: false,
      },
      "layout-metrics": {
        id: "layout-metrics",
        title: "Metrics Slot Host",
        kind: "slot-reference",
        parentId: "layout-root",
        childIds: [],
        orderIndex: 1,
        slotId: "slot-metrics",
        frame: { x: 24, y: 164, width: 280, height: 180 },
        locked: false,
      },
      "layout-chart": {
        id: "layout-chart",
        title: "Chart Slot Host",
        kind: "slot-reference",
        parentId: "layout-root",
        childIds: [],
        orderIndex: 2,
        slotId: "slot-chart",
        frame: { x: 328, y: 164, width: 568, height: 324 },
        locked: false,
      },
    },
    slots: {
      "slot-hero": {
        id: "slot-hero",
        title: "Hero",
        kind: "content",
        acceptedWidgetTypes: ["text", "container"],
        acceptedCapabilities: ["textual", "layout-container"],
        widgetIds: ["widget-title"],
        maxWidgets: 2,
        locked: false,
      },
      "slot-metrics": {
        id: "slot-metrics",
        title: "Metrics",
        kind: "metric",
        acceptedWidgetTypes: ["kpi", "text"],
        acceptedCapabilities: ["metric", "textual"],
        widgetIds: ["widget-kpi"],
        maxWidgets: 3,
        locked: false,
      },
      "slot-chart": {
        id: "slot-chart",
        title: "Chart",
        kind: "chart",
        acceptedWidgetTypes: ["chart", "text"],
        acceptedCapabilities: ["chart", "textual"],
        widgetIds: ["widget-chart"],
        maxWidgets: 2,
        locked: false,
      },
    },
    widgets: {
      "widget-title": {
        id: "widget-title",
        title: "Quarter Summary",
        type: "text",
        slotId: "slot-hero",
        prefabId: "prefab-hero-text",
        capabilities: ["textual"],
        props: {
          text: "North region exceeded plan by 12% and margin remained stable.",
        },
        style: {
          background: "rgba(255,255,255,0.16)",
          foreground: "#f8fbff",
          borderStyle: "glass",
          radius: 16,
          emphasis: "strong",
        },
        visible: true,
        locked: false,
      },
      "widget-kpi": {
        id: "widget-kpi",
        title: "Revenue KPI",
        type: "kpi",
        slotId: "slot-metrics",
        prefabId: "prefab-kpi-card",
        capabilities: ["metric"],
        props: {
          label: "Revenue",
          value: "$4.2M",
          delta: "+8.4%",
        },
        style: {
          background: "rgba(10, 14, 28, 0.78)",
          foreground: "#ffffff",
          borderStyle: "solid",
          radius: 14,
          emphasis: "default",
        },
        visible: true,
        locked: false,
      },
      "widget-chart": {
        id: "widget-chart",
        title: "Regional Trend",
        type: "chart",
        slotId: "slot-chart",
        prefabId: "prefab-line-chart",
        capabilities: ["chart"],
        props: {
          chartType: "line",
          title: "Revenue Trend",
          dataSetRef: "sample.revenue.q1",
        },
        style: {
          background: "rgba(255,255,255,0.08)",
          foreground: "#ffffff",
          borderStyle: "glass",
          radius: 18,
          emphasis: "default",
        },
        visible: true,
        locked: false,
      },
    },
    meta: {
      revision: 1,
      nextId: 4,
      lastCommittedAtIso: null,
    },
  };
}
