from __future__ import annotations

# Compatibility registry.
#
# IMPORTANT: ``status`` is a legacy registry field retained for older callers.
# It is not a certification state. Use ``get_hardened_feature_specs()`` for the
# reconciled implementation/maturity view.
FEATURE_REGISTRY_VERSION = "2.0.0"
LEGACY_STATUS_FIELD = "status"
LEGACY_STATUS_SEMANTICS = (
    "Compatibility-only historical status. It proves neither current runtime "
    "binding nor contract maturity nor production certification."
)

FEATURE_SPECS = [{'id': 'operational_evidence_atlas_row_level',
  'title': 'Operational Evidence Atlas row-level',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'client_followup_atlas',
  'title': 'Client Follow-up Atlas / CLIENT_OPERATIONS_MATRIX',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'device_claim_crosscheck',
  'title': 'Device Claim Crosscheck',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'sales_lineage_matrix',
  'title': 'Sales Lineage Matrix',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'flow_health_map',
  'title': 'Flow Health Map',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'breakage_radar',
  'title': 'Breakage Radar',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'snapshot_diff_engine',
  'title': 'Snapshot Diff Engine',
  'status': 'placeholder_v1',
  'note': 'PLACEHOLDER: replace when real evidence/contract exists.'},
 {'id': 'contract_coverage_matrix',
  'title': 'Contract Coverage Matrix',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'customer_visible_scanner',
  'title': 'Customer Visible Scanner',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'surface_role_matrix',
  'title': 'Surface Role Matrix',
  'status': 'placeholder_v1',
  'note': 'PLACEHOLDER: replace when real evidence/contract exists.'},
 {'id': 'operational_timeline',
  'title': 'Operational Timeline',
  'status': 'placeholder_v1',
  'note': 'PLACEHOLDER: replace when real evidence/contract exists.'},
 {'id': 'why_this_is_red',
  'title': 'WHY_THIS_IS_RED',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'client_risk_score',
  'title': 'Client Risk Score',
  'status': 'placeholder_v1',
  'note': 'PLACEHOLDER: replace when real evidence/contract exists.'},
 {'id': 'next_best_action_engine',
  'title': 'Next Best Action Engine',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'orphan_detector',
  'title': 'Orphan Detector',
  'status': 'placeholder_v1',
  'note': 'PLACEHOLDER: replace when real evidence/contract exists.'},
 {'id': 'duplicate_detector',
  'title': 'Duplicate Detector',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'staleness_monitor',
  'title': 'Staleness Monitor',
  'status': 'placeholder_v1',
  'note': 'PLACEHOLDER: replace when real evidence/contract exists.'},
 {'id': 'schema_drift_guard',
  'title': 'Schema Drift Guard',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'fixture_contamination_scanner',
  'title': 'Fixture Contamination Scanner',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'audit_completeness_matrix',
  'title': 'Audit Completeness Matrix',
  'status': 'placeholder_v1',
  'note': 'PLACEHOLDER: replace when real evidence/contract exists.'},
 {'id': 'data_lineage_graph',
  'title': 'Data Lineage Graph',
  'status': 'placeholder_v1',
  'note': 'PLACEHOLDER: replace when real evidence/contract exists.'},
 {'id': 'impact_radius_calculator',
  'title': 'Impact Radius Calculator',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'safe_fix_recommendation_map',
  'title': 'Safe Fix Recommendation Map',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'verifier_coverage_map',
  'title': 'Verifier Coverage Map',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'runtime_evidence_links',
  'title': 'Runtime Evidence Links',
  'status': 'placeholder_v1',
  'note': 'PLACEHOLDER: replace when real evidence/contract exists.'},
 {'id': 'api_data_map',
  'title': 'API Data Map',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'secret_exposure_guard',
  'title': 'Secret Exposure Guard',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'production_gate_readiness',
  'title': 'Production Gate Readiness',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'human_operator_summary',
  'title': 'Human Operator Summary',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'machine_continuation_pack',
  'title': 'Machine Continuation Pack / CONTINUATION_SUPREME',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'atlas_query_console',
  'title': 'Atlas Query Console',
  'status': 'placeholder_v1',
  'note': 'PLACEHOLDER: replace when real evidence/contract exists.'},
 {'id': 'entity_detail_drawer',
  'title': 'Entity Detail Drawer',
  'status': 'placeholder_v1',
  'note': 'PLACEHOLDER: replace when real evidence/contract exists.'},
 {'id': 'evidence_confidence_score',
  'title': 'Evidence Confidence Score',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'ownership_map',
  'title': 'Ownership Map',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'do_not_touch_map',
  'title': 'Do Not Touch Map',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'safe_scope_guard',
  'title': 'Safe Scope Guard',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'data_quality_ruleset',
  'title': 'Data Quality Ruleset',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'reconciliation_recipes',
  'title': 'Reconciliation Recipes',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'alert_rules_export',
  'title': 'Alert Rules Export',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'evidence_bundle_index',
  'title': 'Evidence Bundle Index',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'pii_privacy_classifier',
  'title': 'PII/Privacy Classifier',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'support_ticket_generator',
  'title': 'Support Ticket Generator',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'release_readiness_matrix',
  'title': 'Release Readiness Matrix',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'historical_trend_mini_atlas',
  'title': 'Historical Trend Mini Atlas',
  'status': 'placeholder_v1',
  'note': 'PLACEHOLDER: replace when real evidence/contract exists.'},
 {'id': 'trust_source_level_per_datum',
  'title': 'Trust/source level per datum',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'atlas_manifest_plus',
  'title': 'ATLAS_MANIFEST_PLUS',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'can_patch_decision',
  'title': 'CAN_PATCH_DECISION',
  'status': 'implemented_v1',
  'note': 'Implemented v1 with safe heuristic evidence; keep improving with real contracts.'},
 {'id': 'client_setup_journey_map',
  'title': 'Client Setup Journey Map',
  'status': 'placeholder_v1',
  'note': 'PLACEHOLDER: replace when real evidence/contract exists.'},
 {'id': 'multi_tenant_leakage_guard',
  'title': 'Multi-Tenant Leakage Guard',
  'status': 'placeholder_blocked',
  'note': 'PLACEHOLDER: replace when real evidence/contract exists.'},
 {'id': 'golden_path_comparator',
  'title': 'Golden Path Comparator',
  'status': 'placeholder_v1',
  'note': 'PLACEHOLDER: replace when real evidence/contract exists.'}]


def get_hardened_feature_specs():
    from .capability_contracts import build_capability_specs
    return build_capability_specs(FEATURE_SPECS)


def validate_feature_registry():
    from .capability_contracts import validate_capability_specs
    return validate_capability_specs(get_hardened_feature_specs())
