export const pcRoutes = [
  "/",
  "/dashboard",
  "/sales-control",
  "/cash-sessions",
  "/catalog",
  "/stock",
  "/movements",
  "/counts",
  "/purchasing",
  "/receiving",
  "/replenishment",
  "/proveedores",
  "/audit",
  "/sync",
  "/devices",
  "/tablet-communication",
  "/license-runtime",
  "/data-quality",
  "/settings"
] as const;
