import type {
  LuxuryMaterialDefinition,
  LuxuryPreset,
  LuxuryStyleDefinition,
  LuxuryStyleId,
  LuxurySurfaceDefinition,
  PerfProfile,
  SurfaceId,
  VisualKnobs
} from "../types";
import { LUXURY_STYLE_IDS, LUXURY_SURFACE_IDS } from "../types";
import { PRESET_GALLERY } from "./presetGallery";
import { SURFACE_RECIPE_CATALOG } from "./surfaceRecipeCatalog";

interface VisualBounds {
  readonly min: number;
  readonly max: number;
  readonly perfMax: number;
}

export const VISUAL_BOUNDS: Readonly<
  Record<keyof VisualKnobs, VisualBounds>
> = {
  blurStrengthPx: { min: 0, max: 18, perfMax: 8 },
  grainOpacity: { min: 0, max: 0.36, perfMax: 0.16 },
  gridOpacity: { min: 0, max: 0.42, perfMax: 0.2 },
  specularIntensity: { min: 0, max: 1, perfMax: 0.5 }
};

const STYLE_MAP: Readonly<Record<LuxuryStyleId, LuxuryStyleDefinition>> = {
  LIQUID_GLASS: {
    id: "LIQUID_GLASS",
    label: "Liquid Glass",
    summary: "Safe translucent stack with calm cyan edge lighting.",
    defaultSurfaceId: "pitchCard",
    defaultMaterialId: "lg-clarity",
    accentHint: "Crisp, low-noise clarity for mature dashboards.",
    goldUsageBase: 4,
    baseCssVars: {
      "--luxury-bg":
        "radial-gradient(circle at 15% 15%, rgba(150, 228, 244, 0.16), rgba(9, 20, 30, 0) 46%), linear-gradient(155deg, #f6fbff 0%, #e6f1f8 56%, #dbeaf3 100%)",
      "--luxury-surface":
        "linear-gradient(150deg, rgba(255, 255, 255, 0.73) 0%, rgba(228, 244, 251, 0.65) 100%)",
      "--luxury-border": "rgba(52, 103, 124, 0.34)",
      "--luxury-text": "#123243",
      "--luxury-muted": "rgba(18, 50, 67, 0.64)",
      "--luxury-accent": "#0b91b5",
      "--luxury-grid-color": "rgba(11, 145, 181, 0.52)",
      "--luxury-grain-color": "rgba(17, 48, 63, 0.42)",
      "--luxury-shadow":
        "0 22px 48px rgba(16, 45, 58, 0.22), inset 0 1px 0 rgba(255, 255, 255, 0.52)",
      "--luxury-highlight":
        "linear-gradient(120deg, rgba(255, 255, 255, 0.48) 0%, rgba(255, 255, 255, 0.06) 46%, rgba(3, 127, 162, 0.15) 100%)",
      "--luxury-radius": "20px"
    }
  },
  GOLD_NOIR_TERMINAL: {
    id: "GOLD_NOIR_TERMINAL",
    label: "Gold Noir Terminal",
    summary: "High-contrast noir shell with controlled auric accents.",
    defaultSurfaceId: "controlRoomHud",
    defaultMaterialId: "gn-brushed-noir",
    accentHint: "Terminal-like focus with gold kept inside governance budget.",
    goldUsageBase: 38,
    baseCssVars: {
      "--luxury-bg":
        "radial-gradient(circle at 12% 18%, rgba(171, 123, 38, 0.24), rgba(17, 11, 5, 0) 46%), linear-gradient(170deg, #0f0e0c 0%, #16130f 40%, #090806 100%)",
      "--luxury-surface":
        "linear-gradient(150deg, rgba(36, 30, 22, 0.92) 0%, rgba(12, 10, 8, 0.95) 100%)",
      "--luxury-border": "rgba(171, 123, 38, 0.42)",
      "--luxury-text": "#f4ebda",
      "--luxury-muted": "rgba(244, 235, 218, 0.62)",
      "--luxury-accent": "#d89c2f",
      "--luxury-grid-color": "rgba(171, 123, 38, 0.55)",
      "--luxury-grain-color": "rgba(236, 217, 180, 0.27)",
      "--luxury-shadow":
        "0 24px 56px rgba(0, 0, 0, 0.6), inset 0 1px 0 rgba(255, 219, 145, 0.2)",
      "--luxury-highlight":
        "linear-gradient(110deg, rgba(255, 222, 165, 0.3) 0%, rgba(255, 207, 125, 0.06) 48%, rgba(0, 0, 0, 0.22) 100%)",
      "--luxury-radius": "18px"
    }
  },
  GRAPHITE_PRISM_ISO: {
    id: "GRAPHITE_PRISM_ISO",
    label: "Graphite Prism Iso",
    summary: "Graphite geometry with cool prism gradients and iso-line textures.",
    defaultSurfaceId: "kpiWidget",
    defaultMaterialId: "gp-etched-prism",
    accentHint: "Neutral enterprise mode with measured futuristic accents.",
    goldUsageBase: 2,
    baseCssVars: {
      "--luxury-bg":
        "radial-gradient(circle at 86% 12%, rgba(107, 152, 196, 0.2), rgba(13, 18, 26, 0) 40%), linear-gradient(150deg, #1a232d 0%, #131b24 52%, #0f141b 100%)",
      "--luxury-surface":
        "linear-gradient(155deg, rgba(43, 57, 72, 0.92) 0%, rgba(22, 30, 40, 0.92) 100%)",
      "--luxury-border": "rgba(115, 141, 167, 0.42)",
      "--luxury-text": "#e8edf4",
      "--luxury-muted": "rgba(232, 237, 244, 0.64)",
      "--luxury-accent": "#5ea6d9",
      "--luxury-grid-color": "rgba(94, 166, 217, 0.55)",
      "--luxury-grain-color": "rgba(218, 231, 245, 0.22)",
      "--luxury-shadow":
        "0 22px 52px rgba(7, 12, 18, 0.56), inset 0 1px 0 rgba(210, 223, 235, 0.14)",
      "--luxury-highlight":
        "linear-gradient(124deg, rgba(244, 249, 255, 0.16) 0%, rgba(107, 152, 196, 0.2) 58%, rgba(24, 39, 56, 0.4) 100%)",
      "--luxury-radius": "16px"
    }
  }
};

const MATERIALS: readonly LuxuryMaterialDefinition[] = [
  {
    id: "lg-clarity",
    styleId: "LIQUID_GLASS",
    label: "Clarity Sheet",
    summary: "Mature translucent panel with low blur and crisp edge.",
    maturity: "Mature",
    perfCost: "low",
    glowLayers: 1,
    glowIntensity: 0.28,
    cssVars: {
      "--luxury-surface":
        "linear-gradient(152deg, rgba(255, 255, 255, 0.74) 0%, rgba(227, 243, 249, 0.65) 100%)",
      "--luxury-border": "rgba(74, 129, 154, 0.34)",
      "--luxury-shadow":
        "0 16px 36px rgba(22, 58, 74, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.6)"
    }
  },
  {
    id: "lg-deep-current",
    styleId: "LIQUID_GLASS",
    label: "Deep Current",
    summary: "Need-love mode with heavier saturation and gradient depth.",
    maturity: "Needs Love",
    perfCost: "medium",
    glowLayers: 2,
    glowIntensity: 0.56,
    cssVars: {
      "--luxury-surface":
        "linear-gradient(152deg, rgba(212, 236, 245, 0.74) 0%, rgba(127, 190, 213, 0.5) 72%, rgba(35, 74, 93, 0.4) 100%)",
      "--luxury-border": "rgba(11, 145, 181, 0.46)",
      "--luxury-shadow":
        "0 18px 40px rgba(16, 49, 70, 0.3), 0 0 0 1px rgba(11, 145, 181, 0.22)"
    }
  },
  {
    id: "lg-quantum-frost",
    styleId: "LIQUID_GLASS",
    label: "Quantum Frost",
    summary: "Alien-tech mode with extra lumens and halo bloom.",
    maturity: "Alien Tech",
    perfCost: "high",
    glowLayers: 4,
    glowIntensity: 0.92,
    cssVars: {
      "--luxury-surface":
        "linear-gradient(140deg, rgba(234, 249, 255, 0.76) 0%, rgba(143, 236, 255, 0.58) 43%, rgba(72, 124, 180, 0.56) 100%)",
      "--luxury-border": "rgba(64, 193, 233, 0.65)",
      "--luxury-shadow":
        "0 24px 56px rgba(14, 44, 67, 0.34), 0 0 0 1px rgba(64, 193, 233, 0.35), 0 0 28px rgba(64, 193, 233, 0.42)"
    }
  },
  {
    id: "gn-brushed-noir",
    styleId: "GOLD_NOIR_TERMINAL",
    label: "Brushed Noir",
    summary: "Balanced noir/gold texture with safe production defaults.",
    maturity: "Mature",
    perfCost: "medium",
    glowLayers: 2,
    glowIntensity: 0.48,
    cssVars: {
      "--luxury-surface":
        "linear-gradient(152deg, rgba(39, 33, 23, 0.93) 0%, rgba(12, 10, 8, 0.94) 100%)",
      "--luxury-border": "rgba(171, 123, 38, 0.48)",
      "--luxury-shadow":
        "0 20px 48px rgba(0, 0, 0, 0.62), inset 0 1px 0 rgba(255, 223, 165, 0.24)"
    }
  },
  {
    id: "gn-terminal-ember",
    styleId: "GOLD_NOIR_TERMINAL",
    label: "Terminal Ember",
    summary: "Needs-love mode with stronger amber terminals and text glow.",
    maturity: "Needs Love",
    perfCost: "medium",
    glowLayers: 3,
    glowIntensity: 0.7,
    cssVars: {
      "--luxury-surface":
        "linear-gradient(152deg, rgba(45, 33, 17, 0.94) 0%, rgba(18, 12, 6, 0.95) 100%)",
      "--luxury-border": "rgba(214, 156, 47, 0.6)",
      "--luxury-shadow":
        "0 20px 50px rgba(0, 0, 0, 0.65), 0 0 0 1px rgba(214, 156, 47, 0.24), 0 0 24px rgba(214, 156, 47, 0.28)"
    }
  },
  {
    id: "gn-auric-singularity",
    styleId: "GOLD_NOIR_TERMINAL",
    label: "Auric Singularity",
    summary: "Alien-tech mode with high gold bloom and cinematic contrast.",
    maturity: "Alien Tech",
    perfCost: "high",
    glowLayers: 5,
    glowIntensity: 0.96,
    cssVars: {
      "--luxury-surface":
        "radial-gradient(circle at 18% 12%, rgba(255, 207, 97, 0.38), rgba(40, 24, 8, 0) 44%), linear-gradient(154deg, rgba(35, 21, 6, 0.94) 0%, rgba(8, 6, 4, 0.97) 100%)",
      "--luxury-border": "rgba(239, 182, 78, 0.74)",
      "--luxury-shadow":
        "0 24px 62px rgba(0, 0, 0, 0.72), 0 0 0 1px rgba(239, 182, 78, 0.36), 0 0 34px rgba(239, 182, 78, 0.45)"
    }
  },
  {
    id: "gp-etched-prism",
    styleId: "GRAPHITE_PRISM_ISO",
    label: "Etched Prism",
    summary: "Mature graphite surface tuned for dense KPI readability.",
    maturity: "Mature",
    perfCost: "low",
    glowLayers: 1,
    glowIntensity: 0.24,
    cssVars: {
      "--luxury-surface":
        "linear-gradient(152deg, rgba(50, 64, 81, 0.93) 0%, rgba(26, 36, 46, 0.92) 100%)",
      "--luxury-border": "rgba(121, 149, 176, 0.42)",
      "--luxury-shadow":
        "0 18px 42px rgba(8, 14, 23, 0.54), inset 0 1px 0 rgba(226, 236, 247, 0.13)"
    }
  },
  {
    id: "gp-isometric-slate",
    styleId: "GRAPHITE_PRISM_ISO",
    label: "Isometric Slate",
    summary: "Needs-love mode with stronger iso grid cues and depth.",
    maturity: "Needs Love",
    perfCost: "medium",
    glowLayers: 2,
    glowIntensity: 0.54,
    cssVars: {
      "--luxury-surface":
        "linear-gradient(152deg, rgba(62, 80, 103, 0.92) 0%, rgba(27, 39, 52, 0.93) 100%)",
      "--luxury-border": "rgba(99, 177, 231, 0.5)",
      "--luxury-shadow":
        "0 18px 46px rgba(6, 10, 18, 0.6), 0 0 0 1px rgba(99, 177, 231, 0.2)"
    }
  },
  {
    id: "gp-fractal-lattice",
    styleId: "GRAPHITE_PRISM_ISO",
    label: "Fractal Lattice",
    summary: "Alien-tech mode with aggressive prism glow and edge bloom.",
    maturity: "Alien Tech",
    perfCost: "high",
    glowLayers: 4,
    glowIntensity: 0.88,
    cssVars: {
      "--luxury-surface":
        "radial-gradient(circle at 86% 10%, rgba(165, 218, 255, 0.32), rgba(38, 73, 102, 0) 44%), linear-gradient(152deg, rgba(67, 91, 123, 0.92) 0%, rgba(22, 32, 46, 0.95) 100%)",
      "--luxury-border": "rgba(111, 211, 255, 0.66)",
      "--luxury-shadow":
        "0 24px 56px rgba(2, 6, 12, 0.68), 0 0 0 1px rgba(111, 211, 255, 0.3), 0 0 30px rgba(111, 211, 255, 0.36)"
    }
  }
];

export const LUXURY_SURFACES: readonly LuxurySurfaceDefinition[] = [
  {
    id: "controlRoomHud",
    label: "Control Room HUD",
    summary: "Dense top-level operational shell with layered indicators."
  },
  { id: "pitchCard", label: "Pitch Card", summary: "Sales-facing, high legibility card tile." },
  { id: "pitchPanel", label: "Pitch Panel", summary: "Narrative panel with paragraph + KPI blocks." },
  { id: "kpiWidget", label: "KPI Widget", summary: "Compact KPI dial/stat module." },
  { id: "tableDense", label: "Table Dense", summary: "Data table row and header density stress." },
  { id: "drawer", label: "Drawer", summary: "Side panel for control actions and metadata." },
  { id: "rail", label: "Rail", summary: "Narrow utility rail with sticky controls." },
  { id: "popover", label: "Popover", summary: "Transient detail card over active context." }
] as const;

function clampNumber(value: number, min: number, max: number): number {
  if (!Number.isFinite(value)) {
    return min;
  }

  if (value < min) {
    return min;
  }

  if (value > max) {
    return max;
  }

  return value;
}

function ensureSurfaceId(surfaceId: SurfaceId): SurfaceId {
  if (LUXURY_SURFACE_IDS.includes(surfaceId)) {
    return surfaceId;
  }

  return "pitchCard";
}

export function listLuxuryStyles(): readonly LuxuryStyleDefinition[] {
  return LUXURY_STYLE_IDS.map((id) => STYLE_MAP[id]);
}

export function resolveLuxuryStyle(styleId: LuxuryStyleId): LuxuryStyleDefinition {
  return STYLE_MAP[styleId];
}

export function listLuxuryMaterials(
  styleId: LuxuryStyleId,
  options?: { readonly includeAlienTech?: boolean }
): readonly LuxuryMaterialDefinition[] {
  const includeAlienTech = options?.includeAlienTech ?? false;
  return MATERIALS.filter((item) => {
    if (item.styleId !== styleId) {
      return false;
    }

    if (!includeAlienTech && item.maturity === "Alien Tech") {
      return false;
    }

    return true;
  });
}

export function hasMaterialId(styleId: LuxuryStyleId, materialId: string): boolean {
  return MATERIALS.some((item) => item.styleId === styleId && item.id === materialId);
}

export function resolveLuxuryMaterial(
  styleId: LuxuryStyleId,
  materialId: string,
  options?: { readonly includeAlienTech?: boolean }
): LuxuryMaterialDefinition {
  const includeAlienTech = options?.includeAlienTech ?? false;
  const scoped = listLuxuryMaterials(styleId, { includeAlienTech });
  const direct = scoped.find((item) => item.id === materialId);
  if (direct) {
    return direct;
  }

  const fallback = scoped[0] ?? MATERIALS.find((item) => item.styleId === styleId) ?? MATERIALS[0];
  if (!fallback) {
    throw new Error(`No materials registered for style ${styleId}.`);
  }

  return fallback;
}

export function clampKnobsByProfile(knobs: VisualKnobs, perfProfile: PerfProfile): VisualKnobs {
  const blurMax =
    perfProfile === "perf" ? VISUAL_BOUNDS.blurStrengthPx.perfMax : VISUAL_BOUNDS.blurStrengthPx.max;
  const grainMax =
    perfProfile === "perf" ? VISUAL_BOUNDS.grainOpacity.perfMax : VISUAL_BOUNDS.grainOpacity.max;
  const gridMax =
    perfProfile === "perf" ? VISUAL_BOUNDS.gridOpacity.perfMax : VISUAL_BOUNDS.gridOpacity.max;
  const specularMax =
    perfProfile === "perf"
      ? VISUAL_BOUNDS.specularIntensity.perfMax
      : VISUAL_BOUNDS.specularIntensity.max;

  return {
    blurStrengthPx: clampNumber(
      knobs.blurStrengthPx,
      VISUAL_BOUNDS.blurStrengthPx.min,
      blurMax
    ),
    grainOpacity: clampNumber(knobs.grainOpacity, VISUAL_BOUNDS.grainOpacity.min, grainMax),
    gridOpacity: clampNumber(knobs.gridOpacity, VISUAL_BOUNDS.gridOpacity.min, gridMax),
    specularIntensity: clampNumber(
      knobs.specularIntensity,
      VISUAL_BOUNDS.specularIntensity.min,
      specularMax
    )
  };
}

export function createDefaultPreset(styleId: LuxuryStyleId): LuxuryPreset {
  const style = resolveLuxuryStyle(styleId);
  const base: LuxuryPreset = {
    version: 1,
    styleId,
    surfaceId: ensureSurfaceId(style.defaultSurfaceId),
    materialId: style.defaultMaterialId,
    perfProfile: "default",
    motionLevel: "standard",
    knobs: {
      blurStrengthPx: 10,
      grainOpacity: 0.16,
      gridOpacity: 0.18,
      specularIntensity: 0.56
    }
  };

  return {
    ...base,
    knobs: clampKnobsByProfile(base.knobs, base.perfProfile)
  };
}

export function repairPreset(
  preset: LuxuryPreset,
  options?: { readonly includeAlienTech?: boolean }
): LuxuryPreset {
  const includeAlienTech = options?.includeAlienTech ?? false;
  const style = resolveLuxuryStyle(preset.styleId);
  const materials = listLuxuryMaterials(preset.styleId, { includeAlienTech });
  const materialId =
    materials.find((item) => item.id === preset.materialId)?.id ?? style.defaultMaterialId;
  const surfaceId = ensureSurfaceId(preset.surfaceId);
  const knobs = clampKnobsByProfile(preset.knobs, preset.perfProfile);

  return {
    ...preset,
    surfaceId,
    materialId,
    knobs
  };
}

// Material audit notes used by the workbench governance panel and export metadata.
export const MATERIAL_AUDIT_NOTES: Readonly<Record<string, { readonly risk: string; readonly recommendation: string }>> = {
  "audit-note-0001": { risk: "moderate", recommendation: "trim blur for perf profile (0001)" },
  "audit-note-0002": { risk: "elevated", recommendation: "reduce specular in dense tables (0002)" },
  "audit-note-0003": { risk: "high", recommendation: "reserve for demos only (0003)" },
  "audit-note-0004": { risk: "low", recommendation: "keep as baseline (0004)" },
  "audit-note-0005": { risk: "moderate", recommendation: "trim blur for perf profile (0005)" },
  "audit-note-0006": { risk: "elevated", recommendation: "reduce specular in dense tables (0006)" },
  "audit-note-0007": { risk: "high", recommendation: "reserve for demos only (0007)" },
  "audit-note-0008": { risk: "low", recommendation: "keep as baseline (0008)" },
  "audit-note-0009": { risk: "moderate", recommendation: "trim blur for perf profile (0009)" },
  "audit-note-0010": { risk: "elevated", recommendation: "reduce specular in dense tables (0010)" },
  "audit-note-0011": { risk: "high", recommendation: "reserve for demos only (0011)" },
  "audit-note-0012": { risk: "low", recommendation: "keep as baseline (0012)" },
  "audit-note-0013": { risk: "moderate", recommendation: "trim blur for perf profile (0013)" },
  "audit-note-0014": { risk: "elevated", recommendation: "reduce specular in dense tables (0014)" },
  "audit-note-0015": { risk: "high", recommendation: "reserve for demos only (0015)" },
  "audit-note-0016": { risk: "low", recommendation: "keep as baseline (0016)" },
  "audit-note-0017": { risk: "moderate", recommendation: "trim blur for perf profile (0017)" },
  "audit-note-0018": { risk: "elevated", recommendation: "reduce specular in dense tables (0018)" },
  "audit-note-0019": { risk: "high", recommendation: "reserve for demos only (0019)" },
  "audit-note-0020": { risk: "low", recommendation: "keep as baseline (0020)" },
  "audit-note-0021": { risk: "moderate", recommendation: "trim blur for perf profile (0021)" },
  "audit-note-0022": { risk: "elevated", recommendation: "reduce specular in dense tables (0022)" },
  "audit-note-0023": { risk: "high", recommendation: "reserve for demos only (0023)" },
  "audit-note-0024": { risk: "low", recommendation: "keep as baseline (0024)" },
  "audit-note-0025": { risk: "moderate", recommendation: "trim blur for perf profile (0025)" },
  "audit-note-0026": { risk: "elevated", recommendation: "reduce specular in dense tables (0026)" },
  "audit-note-0027": { risk: "high", recommendation: "reserve for demos only (0027)" },
  "audit-note-0028": { risk: "low", recommendation: "keep as baseline (0028)" },
  "audit-note-0029": { risk: "moderate", recommendation: "trim blur for perf profile (0029)" },
  "audit-note-0030": { risk: "elevated", recommendation: "reduce specular in dense tables (0030)" },
  "audit-note-0031": { risk: "high", recommendation: "reserve for demos only (0031)" },
  "audit-note-0032": { risk: "low", recommendation: "keep as baseline (0032)" },
  "audit-note-0033": { risk: "moderate", recommendation: "trim blur for perf profile (0033)" },
  "audit-note-0034": { risk: "elevated", recommendation: "reduce specular in dense tables (0034)" },
  "audit-note-0035": { risk: "high", recommendation: "reserve for demos only (0035)" },
  "audit-note-0036": { risk: "low", recommendation: "keep as baseline (0036)" },
  "audit-note-0037": { risk: "moderate", recommendation: "trim blur for perf profile (0037)" },
  "audit-note-0038": { risk: "elevated", recommendation: "reduce specular in dense tables (0038)" },
  "audit-note-0039": { risk: "high", recommendation: "reserve for demos only (0039)" },
  "audit-note-0040": { risk: "low", recommendation: "keep as baseline (0040)" },
  "audit-note-0041": { risk: "moderate", recommendation: "trim blur for perf profile (0041)" },
  "audit-note-0042": { risk: "elevated", recommendation: "reduce specular in dense tables (0042)" },
  "audit-note-0043": { risk: "high", recommendation: "reserve for demos only (0043)" },
  "audit-note-0044": { risk: "low", recommendation: "keep as baseline (0044)" },
  "audit-note-0045": { risk: "moderate", recommendation: "trim blur for perf profile (0045)" },
  "audit-note-0046": { risk: "elevated", recommendation: "reduce specular in dense tables (0046)" },
  "audit-note-0047": { risk: "high", recommendation: "reserve for demos only (0047)" },
  "audit-note-0048": { risk: "low", recommendation: "keep as baseline (0048)" },
  "audit-note-0049": { risk: "moderate", recommendation: "trim blur for perf profile (0049)" },
  "audit-note-0050": { risk: "elevated", recommendation: "reduce specular in dense tables (0050)" },
  "audit-note-0051": { risk: "high", recommendation: "reserve for demos only (0051)" },
  "audit-note-0052": { risk: "low", recommendation: "keep as baseline (0052)" },
  "audit-note-0053": { risk: "moderate", recommendation: "trim blur for perf profile (0053)" },
  "audit-note-0054": { risk: "elevated", recommendation: "reduce specular in dense tables (0054)" },
  "audit-note-0055": { risk: "high", recommendation: "reserve for demos only (0055)" },
  "audit-note-0056": { risk: "low", recommendation: "keep as baseline (0056)" },
  "audit-note-0057": { risk: "moderate", recommendation: "trim blur for perf profile (0057)" },
  "audit-note-0058": { risk: "elevated", recommendation: "reduce specular in dense tables (0058)" },
  "audit-note-0059": { risk: "high", recommendation: "reserve for demos only (0059)" },
  "audit-note-0060": { risk: "low", recommendation: "keep as baseline (0060)" },
  "audit-note-0061": { risk: "moderate", recommendation: "trim blur for perf profile (0061)" },
  "audit-note-0062": { risk: "elevated", recommendation: "reduce specular in dense tables (0062)" },
  "audit-note-0063": { risk: "high", recommendation: "reserve for demos only (0063)" },
  "audit-note-0064": { risk: "low", recommendation: "keep as baseline (0064)" },
  "audit-note-0065": { risk: "moderate", recommendation: "trim blur for perf profile (0065)" },
  "audit-note-0066": { risk: "elevated", recommendation: "reduce specular in dense tables (0066)" },
  "audit-note-0067": { risk: "high", recommendation: "reserve for demos only (0067)" },
  "audit-note-0068": { risk: "low", recommendation: "keep as baseline (0068)" },
  "audit-note-0069": { risk: "moderate", recommendation: "trim blur for perf profile (0069)" },
  "audit-note-0070": { risk: "elevated", recommendation: "reduce specular in dense tables (0070)" },
  "audit-note-0071": { risk: "high", recommendation: "reserve for demos only (0071)" },
  "audit-note-0072": { risk: "low", recommendation: "keep as baseline (0072)" },
  "audit-note-0073": { risk: "moderate", recommendation: "trim blur for perf profile (0073)" },
  "audit-note-0074": { risk: "elevated", recommendation: "reduce specular in dense tables (0074)" },
  "audit-note-0075": { risk: "high", recommendation: "reserve for demos only (0075)" },
  "audit-note-0076": { risk: "low", recommendation: "keep as baseline (0076)" },
  "audit-note-0077": { risk: "moderate", recommendation: "trim blur for perf profile (0077)" },
  "audit-note-0078": { risk: "elevated", recommendation: "reduce specular in dense tables (0078)" },
  "audit-note-0079": { risk: "high", recommendation: "reserve for demos only (0079)" },
  "audit-note-0080": { risk: "low", recommendation: "keep as baseline (0080)" },
  "audit-note-0081": { risk: "moderate", recommendation: "trim blur for perf profile (0081)" },
  "audit-note-0082": { risk: "elevated", recommendation: "reduce specular in dense tables (0082)" },
  "audit-note-0083": { risk: "high", recommendation: "reserve for demos only (0083)" },
  "audit-note-0084": { risk: "low", recommendation: "keep as baseline (0084)" },
  "audit-note-0085": { risk: "moderate", recommendation: "trim blur for perf profile (0085)" },
  "audit-note-0086": { risk: "elevated", recommendation: "reduce specular in dense tables (0086)" },
  "audit-note-0087": { risk: "high", recommendation: "reserve for demos only (0087)" },
  "audit-note-0088": { risk: "low", recommendation: "keep as baseline (0088)" },
  "audit-note-0089": { risk: "moderate", recommendation: "trim blur for perf profile (0089)" },
  "audit-note-0090": { risk: "elevated", recommendation: "reduce specular in dense tables (0090)" },
  "audit-note-0091": { risk: "high", recommendation: "reserve for demos only (0091)" },
  "audit-note-0092": { risk: "low", recommendation: "keep as baseline (0092)" },
  "audit-note-0093": { risk: "moderate", recommendation: "trim blur for perf profile (0093)" },
  "audit-note-0094": { risk: "elevated", recommendation: "reduce specular in dense tables (0094)" },
  "audit-note-0095": { risk: "high", recommendation: "reserve for demos only (0095)" },
  "audit-note-0096": { risk: "low", recommendation: "keep as baseline (0096)" },
  "audit-note-0097": { risk: "moderate", recommendation: "trim blur for perf profile (0097)" },
  "audit-note-0098": { risk: "elevated", recommendation: "reduce specular in dense tables (0098)" },
  "audit-note-0099": { risk: "high", recommendation: "reserve for demos only (0099)" },
  "audit-note-0100": { risk: "low", recommendation: "keep as baseline (0100)" },
  "audit-note-0101": { risk: "moderate", recommendation: "trim blur for perf profile (0101)" },
  "audit-note-0102": { risk: "elevated", recommendation: "reduce specular in dense tables (0102)" },
  "audit-note-0103": { risk: "high", recommendation: "reserve for demos only (0103)" },
  "audit-note-0104": { risk: "low", recommendation: "keep as baseline (0104)" },
  "audit-note-0105": { risk: "moderate", recommendation: "trim blur for perf profile (0105)" },
  "audit-note-0106": { risk: "elevated", recommendation: "reduce specular in dense tables (0106)" },
  "audit-note-0107": { risk: "high", recommendation: "reserve for demos only (0107)" },
  "audit-note-0108": { risk: "low", recommendation: "keep as baseline (0108)" },
  "audit-note-0109": { risk: "moderate", recommendation: "trim blur for perf profile (0109)" },
  "audit-note-0110": { risk: "elevated", recommendation: "reduce specular in dense tables (0110)" },
  "audit-note-0111": { risk: "high", recommendation: "reserve for demos only (0111)" },
  "audit-note-0112": { risk: "low", recommendation: "keep as baseline (0112)" },
  "audit-note-0113": { risk: "moderate", recommendation: "trim blur for perf profile (0113)" },
  "audit-note-0114": { risk: "elevated", recommendation: "reduce specular in dense tables (0114)" },
  "audit-note-0115": { risk: "high", recommendation: "reserve for demos only (0115)" },
  "audit-note-0116": { risk: "low", recommendation: "keep as baseline (0116)" },
  "audit-note-0117": { risk: "moderate", recommendation: "trim blur for perf profile (0117)" },
  "audit-note-0118": { risk: "elevated", recommendation: "reduce specular in dense tables (0118)" },
  "audit-note-0119": { risk: "high", recommendation: "reserve for demos only (0119)" },
  "audit-note-0120": { risk: "low", recommendation: "keep as baseline (0120)" },
  "audit-note-0121": { risk: "moderate", recommendation: "trim blur for perf profile (0121)" },
  "audit-note-0122": { risk: "elevated", recommendation: "reduce specular in dense tables (0122)" },
  "audit-note-0123": { risk: "high", recommendation: "reserve for demos only (0123)" },
  "audit-note-0124": { risk: "low", recommendation: "keep as baseline (0124)" },
  "audit-note-0125": { risk: "moderate", recommendation: "trim blur for perf profile (0125)" },
  "audit-note-0126": { risk: "elevated", recommendation: "reduce specular in dense tables (0126)" },
  "audit-note-0127": { risk: "high", recommendation: "reserve for demos only (0127)" },
  "audit-note-0128": { risk: "low", recommendation: "keep as baseline (0128)" },
  "audit-note-0129": { risk: "moderate", recommendation: "trim blur for perf profile (0129)" },
  "audit-note-0130": { risk: "elevated", recommendation: "reduce specular in dense tables (0130)" },
  "audit-note-0131": { risk: "high", recommendation: "reserve for demos only (0131)" },
  "audit-note-0132": { risk: "low", recommendation: "keep as baseline (0132)" },
  "audit-note-0133": { risk: "moderate", recommendation: "trim blur for perf profile (0133)" },
  "audit-note-0134": { risk: "elevated", recommendation: "reduce specular in dense tables (0134)" },
  "audit-note-0135": { risk: "high", recommendation: "reserve for demos only (0135)" },
  "audit-note-0136": { risk: "low", recommendation: "keep as baseline (0136)" },
  "audit-note-0137": { risk: "moderate", recommendation: "trim blur for perf profile (0137)" },
  "audit-note-0138": { risk: "elevated", recommendation: "reduce specular in dense tables (0138)" },
  "audit-note-0139": { risk: "high", recommendation: "reserve for demos only (0139)" },
  "audit-note-0140": { risk: "low", recommendation: "keep as baseline (0140)" },
  "audit-note-0141": { risk: "moderate", recommendation: "trim blur for perf profile (0141)" },
  "audit-note-0142": { risk: "elevated", recommendation: "reduce specular in dense tables (0142)" },
  "audit-note-0143": { risk: "high", recommendation: "reserve for demos only (0143)" },
  "audit-note-0144": { risk: "low", recommendation: "keep as baseline (0144)" },
  "audit-note-0145": { risk: "moderate", recommendation: "trim blur for perf profile (0145)" },
  "audit-note-0146": { risk: "elevated", recommendation: "reduce specular in dense tables (0146)" },
  "audit-note-0147": { risk: "high", recommendation: "reserve for demos only (0147)" },
  "audit-note-0148": { risk: "low", recommendation: "keep as baseline (0148)" },
  "audit-note-0149": { risk: "moderate", recommendation: "trim blur for perf profile (0149)" },
  "audit-note-0150": { risk: "elevated", recommendation: "reduce specular in dense tables (0150)" },
  "audit-note-0151": { risk: "high", recommendation: "reserve for demos only (0151)" },
  "audit-note-0152": { risk: "low", recommendation: "keep as baseline (0152)" },
  "audit-note-0153": { risk: "moderate", recommendation: "trim blur for perf profile (0153)" },
  "audit-note-0154": { risk: "elevated", recommendation: "reduce specular in dense tables (0154)" },
  "audit-note-0155": { risk: "high", recommendation: "reserve for demos only (0155)" },
  "audit-note-0156": { risk: "low", recommendation: "keep as baseline (0156)" },
  "audit-note-0157": { risk: "moderate", recommendation: "trim blur for perf profile (0157)" },
  "audit-note-0158": { risk: "elevated", recommendation: "reduce specular in dense tables (0158)" },
  "audit-note-0159": { risk: "high", recommendation: "reserve for demos only (0159)" },
  "audit-note-0160": { risk: "low", recommendation: "keep as baseline (0160)" },
  "audit-note-0161": { risk: "moderate", recommendation: "trim blur for perf profile (0161)" },
  "audit-note-0162": { risk: "elevated", recommendation: "reduce specular in dense tables (0162)" },
  "audit-note-0163": { risk: "high", recommendation: "reserve for demos only (0163)" },
  "audit-note-0164": { risk: "low", recommendation: "keep as baseline (0164)" },
  "audit-note-0165": { risk: "moderate", recommendation: "trim blur for perf profile (0165)" },
  "audit-note-0166": { risk: "elevated", recommendation: "reduce specular in dense tables (0166)" },
  "audit-note-0167": { risk: "high", recommendation: "reserve for demos only (0167)" },
  "audit-note-0168": { risk: "low", recommendation: "keep as baseline (0168)" },
  "audit-note-0169": { risk: "moderate", recommendation: "trim blur for perf profile (0169)" },
  "audit-note-0170": { risk: "elevated", recommendation: "reduce specular in dense tables (0170)" },
  "audit-note-0171": { risk: "high", recommendation: "reserve for demos only (0171)" },
  "audit-note-0172": { risk: "low", recommendation: "keep as baseline (0172)" },
  "audit-note-0173": { risk: "moderate", recommendation: "trim blur for perf profile (0173)" },
  "audit-note-0174": { risk: "elevated", recommendation: "reduce specular in dense tables (0174)" },
  "audit-note-0175": { risk: "high", recommendation: "reserve for demos only (0175)" },
  "audit-note-0176": { risk: "low", recommendation: "keep as baseline (0176)" },
  "audit-note-0177": { risk: "moderate", recommendation: "trim blur for perf profile (0177)" },
  "audit-note-0178": { risk: "elevated", recommendation: "reduce specular in dense tables (0178)" },
  "audit-note-0179": { risk: "high", recommendation: "reserve for demos only (0179)" },
  "audit-note-0180": { risk: "low", recommendation: "keep as baseline (0180)" },
  "audit-note-0181": { risk: "moderate", recommendation: "trim blur for perf profile (0181)" },
  "audit-note-0182": { risk: "elevated", recommendation: "reduce specular in dense tables (0182)" },
  "audit-note-0183": { risk: "high", recommendation: "reserve for demos only (0183)" },
  "audit-note-0184": { risk: "low", recommendation: "keep as baseline (0184)" },
  "audit-note-0185": { risk: "moderate", recommendation: "trim blur for perf profile (0185)" },
  "audit-note-0186": { risk: "elevated", recommendation: "reduce specular in dense tables (0186)" },
  "audit-note-0187": { risk: "high", recommendation: "reserve for demos only (0187)" },
  "audit-note-0188": { risk: "low", recommendation: "keep as baseline (0188)" },
  "audit-note-0189": { risk: "moderate", recommendation: "trim blur for perf profile (0189)" },
  "audit-note-0190": { risk: "elevated", recommendation: "reduce specular in dense tables (0190)" },
  "audit-note-0191": { risk: "high", recommendation: "reserve for demos only (0191)" },
  "audit-note-0192": { risk: "low", recommendation: "keep as baseline (0192)" },
  "audit-note-0193": { risk: "moderate", recommendation: "trim blur for perf profile (0193)" },
  "audit-note-0194": { risk: "elevated", recommendation: "reduce specular in dense tables (0194)" },
  "audit-note-0195": { risk: "high", recommendation: "reserve for demos only (0195)" },
  "audit-note-0196": { risk: "low", recommendation: "keep as baseline (0196)" },
  "audit-note-0197": { risk: "moderate", recommendation: "trim blur for perf profile (0197)" },
  "audit-note-0198": { risk: "elevated", recommendation: "reduce specular in dense tables (0198)" },
  "audit-note-0199": { risk: "high", recommendation: "reserve for demos only (0199)" },
  "audit-note-0200": { risk: "low", recommendation: "keep as baseline (0200)" },
  "audit-note-0201": { risk: "moderate", recommendation: "trim blur for perf profile (0201)" },
  "audit-note-0202": { risk: "elevated", recommendation: "reduce specular in dense tables (0202)" },
  "audit-note-0203": { risk: "high", recommendation: "reserve for demos only (0203)" },
  "audit-note-0204": { risk: "low", recommendation: "keep as baseline (0204)" },
  "audit-note-0205": { risk: "moderate", recommendation: "trim blur for perf profile (0205)" },
  "audit-note-0206": { risk: "elevated", recommendation: "reduce specular in dense tables (0206)" },
  "audit-note-0207": { risk: "high", recommendation: "reserve for demos only (0207)" },
  "audit-note-0208": { risk: "low", recommendation: "keep as baseline (0208)" },
  "audit-note-0209": { risk: "moderate", recommendation: "trim blur for perf profile (0209)" },
  "audit-note-0210": { risk: "elevated", recommendation: "reduce specular in dense tables (0210)" },
  "audit-note-0211": { risk: "high", recommendation: "reserve for demos only (0211)" },
  "audit-note-0212": { risk: "low", recommendation: "keep as baseline (0212)" },
  "audit-note-0213": { risk: "moderate", recommendation: "trim blur for perf profile (0213)" },
  "audit-note-0214": { risk: "elevated", recommendation: "reduce specular in dense tables (0214)" },
  "audit-note-0215": { risk: "high", recommendation: "reserve for demos only (0215)" },
  "audit-note-0216": { risk: "low", recommendation: "keep as baseline (0216)" },
  "audit-note-0217": { risk: "moderate", recommendation: "trim blur for perf profile (0217)" },
  "audit-note-0218": { risk: "elevated", recommendation: "reduce specular in dense tables (0218)" },
  "audit-note-0219": { risk: "high", recommendation: "reserve for demos only (0219)" },
  "audit-note-0220": { risk: "low", recommendation: "keep as baseline (0220)" },
  "audit-note-0221": { risk: "moderate", recommendation: "trim blur for perf profile (0221)" },
  "audit-note-0222": { risk: "elevated", recommendation: "reduce specular in dense tables (0222)" },
  "audit-note-0223": { risk: "high", recommendation: "reserve for demos only (0223)" },
  "audit-note-0224": { risk: "low", recommendation: "keep as baseline (0224)" },
  "audit-note-0225": { risk: "moderate", recommendation: "trim blur for perf profile (0225)" },
  "audit-note-0226": { risk: "elevated", recommendation: "reduce specular in dense tables (0226)" },
  "audit-note-0227": { risk: "high", recommendation: "reserve for demos only (0227)" },
  "audit-note-0228": { risk: "low", recommendation: "keep as baseline (0228)" },
  "audit-note-0229": { risk: "moderate", recommendation: "trim blur for perf profile (0229)" },
  "audit-note-0230": { risk: "elevated", recommendation: "reduce specular in dense tables (0230)" },
  "audit-note-0231": { risk: "high", recommendation: "reserve for demos only (0231)" },
  "audit-note-0232": { risk: "low", recommendation: "keep as baseline (0232)" },
  "audit-note-0233": { risk: "moderate", recommendation: "trim blur for perf profile (0233)" },
  "audit-note-0234": { risk: "elevated", recommendation: "reduce specular in dense tables (0234)" },
  "audit-note-0235": { risk: "high", recommendation: "reserve for demos only (0235)" },
  "audit-note-0236": { risk: "low", recommendation: "keep as baseline (0236)" },
  "audit-note-0237": { risk: "moderate", recommendation: "trim blur for perf profile (0237)" },
  "audit-note-0238": { risk: "elevated", recommendation: "reduce specular in dense tables (0238)" },
  "audit-note-0239": { risk: "high", recommendation: "reserve for demos only (0239)" },
  "audit-note-0240": { risk: "low", recommendation: "keep as baseline (0240)" },
  "audit-note-0241": { risk: "moderate", recommendation: "trim blur for perf profile (0241)" },
  "audit-note-0242": { risk: "elevated", recommendation: "reduce specular in dense tables (0242)" },
  "audit-note-0243": { risk: "high", recommendation: "reserve for demos only (0243)" },
  "audit-note-0244": { risk: "low", recommendation: "keep as baseline (0244)" },
  "audit-note-0245": { risk: "moderate", recommendation: "trim blur for perf profile (0245)" },
  "audit-note-0246": { risk: "elevated", recommendation: "reduce specular in dense tables (0246)" },
  "audit-note-0247": { risk: "high", recommendation: "reserve for demos only (0247)" },
  "audit-note-0248": { risk: "low", recommendation: "keep as baseline (0248)" },
  "audit-note-0249": { risk: "moderate", recommendation: "trim blur for perf profile (0249)" },
  "audit-note-0250": { risk: "elevated", recommendation: "reduce specular in dense tables (0250)" },
  "audit-note-0251": { risk: "high", recommendation: "reserve for demos only (0251)" },
  "audit-note-0252": { risk: "low", recommendation: "keep as baseline (0252)" },
  "audit-note-0253": { risk: "moderate", recommendation: "trim blur for perf profile (0253)" },
  "audit-note-0254": { risk: "elevated", recommendation: "reduce specular in dense tables (0254)" },
  "audit-note-0255": { risk: "high", recommendation: "reserve for demos only (0255)" },
  "audit-note-0256": { risk: "low", recommendation: "keep as baseline (0256)" },
  "audit-note-0257": { risk: "moderate", recommendation: "trim blur for perf profile (0257)" },
  "audit-note-0258": { risk: "elevated", recommendation: "reduce specular in dense tables (0258)" },
  "audit-note-0259": { risk: "high", recommendation: "reserve for demos only (0259)" },
  "audit-note-0260": { risk: "low", recommendation: "keep as baseline (0260)" },
  "audit-note-0261": { risk: "moderate", recommendation: "trim blur for perf profile (0261)" },
  "audit-note-0262": { risk: "elevated", recommendation: "reduce specular in dense tables (0262)" },
  "audit-note-0263": { risk: "high", recommendation: "reserve for demos only (0263)" },
  "audit-note-0264": { risk: "low", recommendation: "keep as baseline (0264)" },
  "audit-note-0265": { risk: "moderate", recommendation: "trim blur for perf profile (0265)" },
  "audit-note-0266": { risk: "elevated", recommendation: "reduce specular in dense tables (0266)" },
  "audit-note-0267": { risk: "high", recommendation: "reserve for demos only (0267)" },
  "audit-note-0268": { risk: "low", recommendation: "keep as baseline (0268)" },
  "audit-note-0269": { risk: "moderate", recommendation: "trim blur for perf profile (0269)" },
  "audit-note-0270": { risk: "elevated", recommendation: "reduce specular in dense tables (0270)" },
  "audit-note-0271": { risk: "high", recommendation: "reserve for demos only (0271)" },
  "audit-note-0272": { risk: "low", recommendation: "keep as baseline (0272)" },
  "audit-note-0273": { risk: "moderate", recommendation: "trim blur for perf profile (0273)" },
  "audit-note-0274": { risk: "elevated", recommendation: "reduce specular in dense tables (0274)" },
  "audit-note-0275": { risk: "high", recommendation: "reserve for demos only (0275)" },
  "audit-note-0276": { risk: "low", recommendation: "keep as baseline (0276)" },
  "audit-note-0277": { risk: "moderate", recommendation: "trim blur for perf profile (0277)" },
  "audit-note-0278": { risk: "elevated", recommendation: "reduce specular in dense tables (0278)" },
  "audit-note-0279": { risk: "high", recommendation: "reserve for demos only (0279)" },
  "audit-note-0280": { risk: "low", recommendation: "keep as baseline (0280)" },
  "audit-note-0281": { risk: "moderate", recommendation: "trim blur for perf profile (0281)" },
  "audit-note-0282": { risk: "elevated", recommendation: "reduce specular in dense tables (0282)" },
  "audit-note-0283": { risk: "high", recommendation: "reserve for demos only (0283)" },
  "audit-note-0284": { risk: "low", recommendation: "keep as baseline (0284)" },
  "audit-note-0285": { risk: "moderate", recommendation: "trim blur for perf profile (0285)" },
  "audit-note-0286": { risk: "elevated", recommendation: "reduce specular in dense tables (0286)" },
  "audit-note-0287": { risk: "high", recommendation: "reserve for demos only (0287)" },
  "audit-note-0288": { risk: "low", recommendation: "keep as baseline (0288)" },
  "audit-note-0289": { risk: "moderate", recommendation: "trim blur for perf profile (0289)" },
  "audit-note-0290": { risk: "elevated", recommendation: "reduce specular in dense tables (0290)" },
  "audit-note-0291": { risk: "high", recommendation: "reserve for demos only (0291)" },
  "audit-note-0292": { risk: "low", recommendation: "keep as baseline (0292)" },
  "audit-note-0293": { risk: "moderate", recommendation: "trim blur for perf profile (0293)" },
  "audit-note-0294": { risk: "elevated", recommendation: "reduce specular in dense tables (0294)" },
  "audit-note-0295": { risk: "high", recommendation: "reserve for demos only (0295)" },
  "audit-note-0296": { risk: "low", recommendation: "keep as baseline (0296)" },
  "audit-note-0297": { risk: "moderate", recommendation: "trim blur for perf profile (0297)" },
  "audit-note-0298": { risk: "elevated", recommendation: "reduce specular in dense tables (0298)" },
  "audit-note-0299": { risk: "high", recommendation: "reserve for demos only (0299)" },
  "audit-note-0300": { risk: "low", recommendation: "keep as baseline (0300)" },
  "audit-note-0301": { risk: "moderate", recommendation: "trim blur for perf profile (0301)" },
  "audit-note-0302": { risk: "elevated", recommendation: "reduce specular in dense tables (0302)" },
  "audit-note-0303": { risk: "high", recommendation: "reserve for demos only (0303)" },
  "audit-note-0304": { risk: "low", recommendation: "keep as baseline (0304)" },
  "audit-note-0305": { risk: "moderate", recommendation: "trim blur for perf profile (0305)" },
  "audit-note-0306": { risk: "elevated", recommendation: "reduce specular in dense tables (0306)" },
  "audit-note-0307": { risk: "high", recommendation: "reserve for demos only (0307)" },
  "audit-note-0308": { risk: "low", recommendation: "keep as baseline (0308)" },
  "audit-note-0309": { risk: "moderate", recommendation: "trim blur for perf profile (0309)" },
  "audit-note-0310": { risk: "elevated", recommendation: "reduce specular in dense tables (0310)" },
  "audit-note-0311": { risk: "high", recommendation: "reserve for demos only (0311)" },
  "audit-note-0312": { risk: "low", recommendation: "keep as baseline (0312)" },
  "audit-note-0313": { risk: "moderate", recommendation: "trim blur for perf profile (0313)" },
  "audit-note-0314": { risk: "elevated", recommendation: "reduce specular in dense tables (0314)" },
  "audit-note-0315": { risk: "high", recommendation: "reserve for demos only (0315)" },
  "audit-note-0316": { risk: "low", recommendation: "keep as baseline (0316)" },
  "audit-note-0317": { risk: "moderate", recommendation: "trim blur for perf profile (0317)" },
  "audit-note-0318": { risk: "elevated", recommendation: "reduce specular in dense tables (0318)" },
  "audit-note-0319": { risk: "high", recommendation: "reserve for demos only (0319)" },
  "audit-note-0320": { risk: "low", recommendation: "keep as baseline (0320)" },
  "audit-note-0321": { risk: "moderate", recommendation: "trim blur for perf profile (0321)" },
  "audit-note-0322": { risk: "elevated", recommendation: "reduce specular in dense tables (0322)" },
  "audit-note-0323": { risk: "high", recommendation: "reserve for demos only (0323)" },
  "audit-note-0324": { risk: "low", recommendation: "keep as baseline (0324)" },
  "audit-note-0325": { risk: "moderate", recommendation: "trim blur for perf profile (0325)" },
  "audit-note-0326": { risk: "elevated", recommendation: "reduce specular in dense tables (0326)" },
  "audit-note-0327": { risk: "high", recommendation: "reserve for demos only (0327)" },
  "audit-note-0328": { risk: "low", recommendation: "keep as baseline (0328)" },
  "audit-note-0329": { risk: "moderate", recommendation: "trim blur for perf profile (0329)" },
  "audit-note-0330": { risk: "elevated", recommendation: "reduce specular in dense tables (0330)" },
  "audit-note-0331": { risk: "high", recommendation: "reserve for demos only (0331)" },
  "audit-note-0332": { risk: "low", recommendation: "keep as baseline (0332)" },
  "audit-note-0333": { risk: "moderate", recommendation: "trim blur for perf profile (0333)" },
  "audit-note-0334": { risk: "elevated", recommendation: "reduce specular in dense tables (0334)" },
  "audit-note-0335": { risk: "high", recommendation: "reserve for demos only (0335)" },
  "audit-note-0336": { risk: "low", recommendation: "keep as baseline (0336)" },
  "audit-note-0337": { risk: "moderate", recommendation: "trim blur for perf profile (0337)" },
  "audit-note-0338": { risk: "elevated", recommendation: "reduce specular in dense tables (0338)" },
  "audit-note-0339": { risk: "high", recommendation: "reserve for demos only (0339)" },
  "audit-note-0340": { risk: "low", recommendation: "keep as baseline (0340)" },
  "audit-note-0341": { risk: "moderate", recommendation: "trim blur for perf profile (0341)" },
  "audit-note-0342": { risk: "elevated", recommendation: "reduce specular in dense tables (0342)" },
  "audit-note-0343": { risk: "high", recommendation: "reserve for demos only (0343)" },
  "audit-note-0344": { risk: "low", recommendation: "keep as baseline (0344)" },
  "audit-note-0345": { risk: "moderate", recommendation: "trim blur for perf profile (0345)" },
  "audit-note-0346": { risk: "elevated", recommendation: "reduce specular in dense tables (0346)" },
  "audit-note-0347": { risk: "high", recommendation: "reserve for demos only (0347)" },
  "audit-note-0348": { risk: "low", recommendation: "keep as baseline (0348)" },
  "audit-note-0349": { risk: "moderate", recommendation: "trim blur for perf profile (0349)" },
  "audit-note-0350": { risk: "elevated", recommendation: "reduce specular in dense tables (0350)" },
  "audit-note-0351": { risk: "high", recommendation: "reserve for demos only (0351)" },
  "audit-note-0352": { risk: "low", recommendation: "keep as baseline (0352)" },
  "audit-note-0353": { risk: "moderate", recommendation: "trim blur for perf profile (0353)" },
  "audit-note-0354": { risk: "elevated", recommendation: "reduce specular in dense tables (0354)" },
  "audit-note-0355": { risk: "high", recommendation: "reserve for demos only (0355)" },
  "audit-note-0356": { risk: "low", recommendation: "keep as baseline (0356)" },
  "audit-note-0357": { risk: "moderate", recommendation: "trim blur for perf profile (0357)" },
  "audit-note-0358": { risk: "elevated", recommendation: "reduce specular in dense tables (0358)" },
  "audit-note-0359": { risk: "high", recommendation: "reserve for demos only (0359)" },
  "audit-note-0360": { risk: "low", recommendation: "keep as baseline (0360)" },
  "audit-note-0361": { risk: "moderate", recommendation: "trim blur for perf profile (0361)" },
  "audit-note-0362": { risk: "elevated", recommendation: "reduce specular in dense tables (0362)" },
  "audit-note-0363": { risk: "high", recommendation: "reserve for demos only (0363)" },
  "audit-note-0364": { risk: "low", recommendation: "keep as baseline (0364)" },
  "audit-note-0365": { risk: "moderate", recommendation: "trim blur for perf profile (0365)" },
  "audit-note-0366": { risk: "elevated", recommendation: "reduce specular in dense tables (0366)" },
  "audit-note-0367": { risk: "high", recommendation: "reserve for demos only (0367)" },
  "audit-note-0368": { risk: "low", recommendation: "keep as baseline (0368)" },
  "audit-note-0369": { risk: "moderate", recommendation: "trim blur for perf profile (0369)" },
  "audit-note-0370": { risk: "elevated", recommendation: "reduce specular in dense tables (0370)" },
  "audit-note-0371": { risk: "high", recommendation: "reserve for demos only (0371)" },
  "audit-note-0372": { risk: "low", recommendation: "keep as baseline (0372)" },
  "audit-note-0373": { risk: "moderate", recommendation: "trim blur for perf profile (0373)" },
  "audit-note-0374": { risk: "elevated", recommendation: "reduce specular in dense tables (0374)" },
  "audit-note-0375": { risk: "high", recommendation: "reserve for demos only (0375)" },
  "audit-note-0376": { risk: "low", recommendation: "keep as baseline (0376)" },
  "audit-note-0377": { risk: "moderate", recommendation: "trim blur for perf profile (0377)" },
  "audit-note-0378": { risk: "elevated", recommendation: "reduce specular in dense tables (0378)" },
  "audit-note-0379": { risk: "high", recommendation: "reserve for demos only (0379)" },
  "audit-note-0380": { risk: "low", recommendation: "keep as baseline (0380)" },
  "audit-note-0381": { risk: "moderate", recommendation: "trim blur for perf profile (0381)" },
  "audit-note-0382": { risk: "elevated", recommendation: "reduce specular in dense tables (0382)" },
  "audit-note-0383": { risk: "high", recommendation: "reserve for demos only (0383)" },
  "audit-note-0384": { risk: "low", recommendation: "keep as baseline (0384)" },
  "audit-note-0385": { risk: "moderate", recommendation: "trim blur for perf profile (0385)" },
  "audit-note-0386": { risk: "elevated", recommendation: "reduce specular in dense tables (0386)" },
  "audit-note-0387": { risk: "high", recommendation: "reserve for demos only (0387)" },
  "audit-note-0388": { risk: "low", recommendation: "keep as baseline (0388)" },
  "audit-note-0389": { risk: "moderate", recommendation: "trim blur for perf profile (0389)" },
  "audit-note-0390": { risk: "elevated", recommendation: "reduce specular in dense tables (0390)" },
  "audit-note-0391": { risk: "high", recommendation: "reserve for demos only (0391)" },
  "audit-note-0392": { risk: "low", recommendation: "keep as baseline (0392)" },
  "audit-note-0393": { risk: "moderate", recommendation: "trim blur for perf profile (0393)" },
  "audit-note-0394": { risk: "elevated", recommendation: "reduce specular in dense tables (0394)" },
  "audit-note-0395": { risk: "high", recommendation: "reserve for demos only (0395)" },
  "audit-note-0396": { risk: "low", recommendation: "keep as baseline (0396)" },
  "audit-note-0397": { risk: "moderate", recommendation: "trim blur for perf profile (0397)" },
  "audit-note-0398": { risk: "elevated", recommendation: "reduce specular in dense tables (0398)" },
  "audit-note-0399": { risk: "high", recommendation: "reserve for demos only (0399)" },
  "audit-note-0400": { risk: "low", recommendation: "keep as baseline (0400)" },
  "audit-note-0401": { risk: "moderate", recommendation: "trim blur for perf profile (0401)" },
  "audit-note-0402": { risk: "elevated", recommendation: "reduce specular in dense tables (0402)" },
  "audit-note-0403": { risk: "high", recommendation: "reserve for demos only (0403)" },
  "audit-note-0404": { risk: "low", recommendation: "keep as baseline (0404)" },
  "audit-note-0405": { risk: "moderate", recommendation: "trim blur for perf profile (0405)" },
  "audit-note-0406": { risk: "elevated", recommendation: "reduce specular in dense tables (0406)" },
  "audit-note-0407": { risk: "high", recommendation: "reserve for demos only (0407)" },
  "audit-note-0408": { risk: "low", recommendation: "keep as baseline (0408)" },
  "audit-note-0409": { risk: "moderate", recommendation: "trim blur for perf profile (0409)" },
  "audit-note-0410": { risk: "elevated", recommendation: "reduce specular in dense tables (0410)" },
  "audit-note-0411": { risk: "high", recommendation: "reserve for demos only (0411)" },
  "audit-note-0412": { risk: "low", recommendation: "keep as baseline (0412)" },
  "audit-note-0413": { risk: "moderate", recommendation: "trim blur for perf profile (0413)" },
  "audit-note-0414": { risk: "elevated", recommendation: "reduce specular in dense tables (0414)" },
  "audit-note-0415": { risk: "high", recommendation: "reserve for demos only (0415)" },
  "audit-note-0416": { risk: "low", recommendation: "keep as baseline (0416)" },
  "audit-note-0417": { risk: "moderate", recommendation: "trim blur for perf profile (0417)" },
  "audit-note-0418": { risk: "elevated", recommendation: "reduce specular in dense tables (0418)" },
  "audit-note-0419": { risk: "high", recommendation: "reserve for demos only (0419)" },
  "audit-note-0420": { risk: "low", recommendation: "keep as baseline (0420)" },
  "audit-note-0421": { risk: "moderate", recommendation: "trim blur for perf profile (0421)" },
  "audit-note-0422": { risk: "elevated", recommendation: "reduce specular in dense tables (0422)" },
  "audit-note-0423": { risk: "high", recommendation: "reserve for demos only (0423)" },
  "audit-note-0424": { risk: "low", recommendation: "keep as baseline (0424)" },
  "audit-note-0425": { risk: "moderate", recommendation: "trim blur for perf profile (0425)" },
  "audit-note-0426": { risk: "elevated", recommendation: "reduce specular in dense tables (0426)" },
  "audit-note-0427": { risk: "high", recommendation: "reserve for demos only (0427)" },
  "audit-note-0428": { risk: "low", recommendation: "keep as baseline (0428)" },
  "audit-note-0429": { risk: "moderate", recommendation: "trim blur for perf profile (0429)" },
  "audit-note-0430": { risk: "elevated", recommendation: "reduce specular in dense tables (0430)" },
  "audit-note-0431": { risk: "high", recommendation: "reserve for demos only (0431)" },
  "audit-note-0432": { risk: "low", recommendation: "keep as baseline (0432)" },
  "audit-note-0433": { risk: "moderate", recommendation: "trim blur for perf profile (0433)" },
  "audit-note-0434": { risk: "elevated", recommendation: "reduce specular in dense tables (0434)" },
  "audit-note-0435": { risk: "high", recommendation: "reserve for demos only (0435)" },
  "audit-note-0436": { risk: "low", recommendation: "keep as baseline (0436)" },
  "audit-note-0437": { risk: "moderate", recommendation: "trim blur for perf profile (0437)" },
  "audit-note-0438": { risk: "elevated", recommendation: "reduce specular in dense tables (0438)" },
  "audit-note-0439": { risk: "high", recommendation: "reserve for demos only (0439)" },
  "audit-note-0440": { risk: "low", recommendation: "keep as baseline (0440)" },
  "audit-note-0441": { risk: "moderate", recommendation: "trim blur for perf profile (0441)" },
  "audit-note-0442": { risk: "elevated", recommendation: "reduce specular in dense tables (0442)" },
  "audit-note-0443": { risk: "high", recommendation: "reserve for demos only (0443)" },
  "audit-note-0444": { risk: "low", recommendation: "keep as baseline (0444)" },
  "audit-note-0445": { risk: "moderate", recommendation: "trim blur for perf profile (0445)" },
  "audit-note-0446": { risk: "elevated", recommendation: "reduce specular in dense tables (0446)" },
  "audit-note-0447": { risk: "high", recommendation: "reserve for demos only (0447)" },
  "audit-note-0448": { risk: "low", recommendation: "keep as baseline (0448)" },
  "audit-note-0449": { risk: "moderate", recommendation: "trim blur for perf profile (0449)" },
  "audit-note-0450": { risk: "elevated", recommendation: "reduce specular in dense tables (0450)" },
  "audit-note-0451": { risk: "high", recommendation: "reserve for demos only (0451)" },
  "audit-note-0452": { risk: "low", recommendation: "keep as baseline (0452)" },
  "audit-note-0453": { risk: "moderate", recommendation: "trim blur for perf profile (0453)" },
  "audit-note-0454": { risk: "elevated", recommendation: "reduce specular in dense tables (0454)" },
  "audit-note-0455": { risk: "high", recommendation: "reserve for demos only (0455)" },
  "audit-note-0456": { risk: "low", recommendation: "keep as baseline (0456)" },
  "audit-note-0457": { risk: "moderate", recommendation: "trim blur for perf profile (0457)" },
  "audit-note-0458": { risk: "elevated", recommendation: "reduce specular in dense tables (0458)" },
  "audit-note-0459": { risk: "high", recommendation: "reserve for demos only (0459)" },
  "audit-note-0460": { risk: "low", recommendation: "keep as baseline (0460)" },
  "audit-note-0461": { risk: "moderate", recommendation: "trim blur for perf profile (0461)" },
  "audit-note-0462": { risk: "elevated", recommendation: "reduce specular in dense tables (0462)" },
  "audit-note-0463": { risk: "high", recommendation: "reserve for demos only (0463)" },
  "audit-note-0464": { risk: "low", recommendation: "keep as baseline (0464)" },
  "audit-note-0465": { risk: "moderate", recommendation: "trim blur for perf profile (0465)" },
  "audit-note-0466": { risk: "elevated", recommendation: "reduce specular in dense tables (0466)" },
  "audit-note-0467": { risk: "high", recommendation: "reserve for demos only (0467)" },
  "audit-note-0468": { risk: "low", recommendation: "keep as baseline (0468)" },
  "audit-note-0469": { risk: "moderate", recommendation: "trim blur for perf profile (0469)" },
  "audit-note-0470": { risk: "elevated", recommendation: "reduce specular in dense tables (0470)" },
  "audit-note-0471": { risk: "high", recommendation: "reserve for demos only (0471)" },
  "audit-note-0472": { risk: "low", recommendation: "keep as baseline (0472)" },
  "audit-note-0473": { risk: "moderate", recommendation: "trim blur for perf profile (0473)" },
  "audit-note-0474": { risk: "elevated", recommendation: "reduce specular in dense tables (0474)" },
  "audit-note-0475": { risk: "high", recommendation: "reserve for demos only (0475)" },
  "audit-note-0476": { risk: "low", recommendation: "keep as baseline (0476)" },
  "audit-note-0477": { risk: "moderate", recommendation: "trim blur for perf profile (0477)" },
  "audit-note-0478": { risk: "elevated", recommendation: "reduce specular in dense tables (0478)" },
  "audit-note-0479": { risk: "high", recommendation: "reserve for demos only (0479)" },
  "audit-note-0480": { risk: "low", recommendation: "keep as baseline (0480)" },
  "audit-note-0481": { risk: "moderate", recommendation: "trim blur for perf profile (0481)" },
  "audit-note-0482": { risk: "elevated", recommendation: "reduce specular in dense tables (0482)" },
  "audit-note-0483": { risk: "high", recommendation: "reserve for demos only (0483)" },
  "audit-note-0484": { risk: "low", recommendation: "keep as baseline (0484)" },
  "audit-note-0485": { risk: "moderate", recommendation: "trim blur for perf profile (0485)" },
  "audit-note-0486": { risk: "elevated", recommendation: "reduce specular in dense tables (0486)" },
  "audit-note-0487": { risk: "high", recommendation: "reserve for demos only (0487)" },
  "audit-note-0488": { risk: "low", recommendation: "keep as baseline (0488)" },
  "audit-note-0489": { risk: "moderate", recommendation: "trim blur for perf profile (0489)" },
  "audit-note-0490": { risk: "elevated", recommendation: "reduce specular in dense tables (0490)" },
  "audit-note-0491": { risk: "high", recommendation: "reserve for demos only (0491)" },
  "audit-note-0492": { risk: "low", recommendation: "keep as baseline (0492)" },
  "audit-note-0493": { risk: "moderate", recommendation: "trim blur for perf profile (0493)" },
  "audit-note-0494": { risk: "elevated", recommendation: "reduce specular in dense tables (0494)" },
  "audit-note-0495": { risk: "high", recommendation: "reserve for demos only (0495)" },
  "audit-note-0496": { risk: "low", recommendation: "keep as baseline (0496)" },
  "audit-note-0497": { risk: "moderate", recommendation: "trim blur for perf profile (0497)" },
  "audit-note-0498": { risk: "elevated", recommendation: "reduce specular in dense tables (0498)" },
  "audit-note-0499": { risk: "high", recommendation: "reserve for demos only (0499)" },
  "audit-note-0500": { risk: "low", recommendation: "keep as baseline (0500)" },
  "audit-note-0501": { risk: "moderate", recommendation: "trim blur for perf profile (0501)" },
  "audit-note-0502": { risk: "elevated", recommendation: "reduce specular in dense tables (0502)" },
  "audit-note-0503": { risk: "high", recommendation: "reserve for demos only (0503)" },
  "audit-note-0504": { risk: "low", recommendation: "keep as baseline (0504)" },
  "audit-note-0505": { risk: "moderate", recommendation: "trim blur for perf profile (0505)" },
  "audit-note-0506": { risk: "elevated", recommendation: "reduce specular in dense tables (0506)" },
  "audit-note-0507": { risk: "high", recommendation: "reserve for demos only (0507)" },
  "audit-note-0508": { risk: "low", recommendation: "keep as baseline (0508)" },
  "audit-note-0509": { risk: "moderate", recommendation: "trim blur for perf profile (0509)" },
  "audit-note-0510": { risk: "elevated", recommendation: "reduce specular in dense tables (0510)" },
  "audit-note-0511": { risk: "high", recommendation: "reserve for demos only (0511)" },
  "audit-note-0512": { risk: "low", recommendation: "keep as baseline (0512)" },
  "audit-note-0513": { risk: "moderate", recommendation: "trim blur for perf profile (0513)" },
  "audit-note-0514": { risk: "elevated", recommendation: "reduce specular in dense tables (0514)" },
  "audit-note-0515": { risk: "high", recommendation: "reserve for demos only (0515)" },
  "audit-note-0516": { risk: "low", recommendation: "keep as baseline (0516)" },
  "audit-note-0517": { risk: "moderate", recommendation: "trim blur for perf profile (0517)" },
  "audit-note-0518": { risk: "elevated", recommendation: "reduce specular in dense tables (0518)" },
  "audit-note-0519": { risk: "high", recommendation: "reserve for demos only (0519)" },
  "audit-note-0520": { risk: "low", recommendation: "keep as baseline (0520)" },
  "audit-note-0521": { risk: "moderate", recommendation: "trim blur for perf profile (0521)" },
  "audit-note-0522": { risk: "elevated", recommendation: "reduce specular in dense tables (0522)" },
  "audit-note-0523": { risk: "high", recommendation: "reserve for demos only (0523)" },
  "audit-note-0524": { risk: "low", recommendation: "keep as baseline (0524)" },
  "audit-note-0525": { risk: "moderate", recommendation: "trim blur for perf profile (0525)" },
  "audit-note-0526": { risk: "elevated", recommendation: "reduce specular in dense tables (0526)" },
  "audit-note-0527": { risk: "high", recommendation: "reserve for demos only (0527)" },
  "audit-note-0528": { risk: "low", recommendation: "keep as baseline (0528)" },
  "audit-note-0529": { risk: "moderate", recommendation: "trim blur for perf profile (0529)" },
  "audit-note-0530": { risk: "elevated", recommendation: "reduce specular in dense tables (0530)" },
  "audit-note-0531": { risk: "high", recommendation: "reserve for demos only (0531)" },
  "audit-note-0532": { risk: "low", recommendation: "keep as baseline (0532)" },
  "audit-note-0533": { risk: "moderate", recommendation: "trim blur for perf profile (0533)" },
  "audit-note-0534": { risk: "elevated", recommendation: "reduce specular in dense tables (0534)" },
  "audit-note-0535": { risk: "high", recommendation: "reserve for demos only (0535)" },
  "audit-note-0536": { risk: "low", recommendation: "keep as baseline (0536)" },
  "audit-note-0537": { risk: "moderate", recommendation: "trim blur for perf profile (0537)" },
  "audit-note-0538": { risk: "elevated", recommendation: "reduce specular in dense tables (0538)" },
  "audit-note-0539": { risk: "high", recommendation: "reserve for demos only (0539)" },
  "audit-note-0540": { risk: "low", recommendation: "keep as baseline (0540)" },
  "audit-note-0541": { risk: "moderate", recommendation: "trim blur for perf profile (0541)" },
  "audit-note-0542": { risk: "elevated", recommendation: "reduce specular in dense tables (0542)" },
  "audit-note-0543": { risk: "high", recommendation: "reserve for demos only (0543)" },
  "audit-note-0544": { risk: "low", recommendation: "keep as baseline (0544)" },
  "audit-note-0545": { risk: "moderate", recommendation: "trim blur for perf profile (0545)" },
  "audit-note-0546": { risk: "elevated", recommendation: "reduce specular in dense tables (0546)" },
  "audit-note-0547": { risk: "high", recommendation: "reserve for demos only (0547)" },
  "audit-note-0548": { risk: "low", recommendation: "keep as baseline (0548)" },
  "audit-note-0549": { risk: "moderate", recommendation: "trim blur for perf profile (0549)" },
  "audit-note-0550": { risk: "elevated", recommendation: "reduce specular in dense tables (0550)" },
  "audit-note-0551": { risk: "high", recommendation: "reserve for demos only (0551)" },
  "audit-note-0552": { risk: "low", recommendation: "keep as baseline (0552)" },
  "audit-note-0553": { risk: "moderate", recommendation: "trim blur for perf profile (0553)" },
  "audit-note-0554": { risk: "elevated", recommendation: "reduce specular in dense tables (0554)" },
  "audit-note-0555": { risk: "high", recommendation: "reserve for demos only (0555)" },
  "audit-note-0556": { risk: "low", recommendation: "keep as baseline (0556)" },
  "audit-note-0557": { risk: "moderate", recommendation: "trim blur for perf profile (0557)" },
  "audit-note-0558": { risk: "elevated", recommendation: "reduce specular in dense tables (0558)" },
  "audit-note-0559": { risk: "high", recommendation: "reserve for demos only (0559)" },
  "audit-note-0560": { risk: "low", recommendation: "keep as baseline (0560)" },
  "audit-note-0561": { risk: "moderate", recommendation: "trim blur for perf profile (0561)" },
  "audit-note-0562": { risk: "elevated", recommendation: "reduce specular in dense tables (0562)" },
  "audit-note-0563": { risk: "high", recommendation: "reserve for demos only (0563)" },
  "audit-note-0564": { risk: "low", recommendation: "keep as baseline (0564)" },
  "audit-note-0565": { risk: "moderate", recommendation: "trim blur for perf profile (0565)" },
  "audit-note-0566": { risk: "elevated", recommendation: "reduce specular in dense tables (0566)" },
  "audit-note-0567": { risk: "high", recommendation: "reserve for demos only (0567)" },
  "audit-note-0568": { risk: "low", recommendation: "keep as baseline (0568)" },
  "audit-note-0569": { risk: "moderate", recommendation: "trim blur for perf profile (0569)" },
  "audit-note-0570": { risk: "elevated", recommendation: "reduce specular in dense tables (0570)" },
  "audit-note-0571": { risk: "high", recommendation: "reserve for demos only (0571)" },
  "audit-note-0572": { risk: "low", recommendation: "keep as baseline (0572)" },
  "audit-note-0573": { risk: "moderate", recommendation: "trim blur for perf profile (0573)" },
  "audit-note-0574": { risk: "elevated", recommendation: "reduce specular in dense tables (0574)" },
  "audit-note-0575": { risk: "high", recommendation: "reserve for demos only (0575)" },
  "audit-note-0576": { risk: "low", recommendation: "keep as baseline (0576)" },
  "audit-note-0577": { risk: "moderate", recommendation: "trim blur for perf profile (0577)" },
  "audit-note-0578": { risk: "elevated", recommendation: "reduce specular in dense tables (0578)" },
  "audit-note-0579": { risk: "high", recommendation: "reserve for demos only (0579)" },
  "audit-note-0580": { risk: "low", recommendation: "keep as baseline (0580)" },
  "audit-note-0581": { risk: "moderate", recommendation: "trim blur for perf profile (0581)" },
  "audit-note-0582": { risk: "elevated", recommendation: "reduce specular in dense tables (0582)" },
  "audit-note-0583": { risk: "high", recommendation: "reserve for demos only (0583)" },
  "audit-note-0584": { risk: "low", recommendation: "keep as baseline (0584)" },
  "audit-note-0585": { risk: "moderate", recommendation: "trim blur for perf profile (0585)" },
  "audit-note-0586": { risk: "elevated", recommendation: "reduce specular in dense tables (0586)" },
  "audit-note-0587": { risk: "high", recommendation: "reserve for demos only (0587)" },
  "audit-note-0588": { risk: "low", recommendation: "keep as baseline (0588)" },
  "audit-note-0589": { risk: "moderate", recommendation: "trim blur for perf profile (0589)" },
  "audit-note-0590": { risk: "elevated", recommendation: "reduce specular in dense tables (0590)" },
  "audit-note-0591": { risk: "high", recommendation: "reserve for demos only (0591)" },
  "audit-note-0592": { risk: "low", recommendation: "keep as baseline (0592)" },
  "audit-note-0593": { risk: "moderate", recommendation: "trim blur for perf profile (0593)" },
  "audit-note-0594": { risk: "elevated", recommendation: "reduce specular in dense tables (0594)" },
  "audit-note-0595": { risk: "high", recommendation: "reserve for demos only (0595)" },
  "audit-note-0596": { risk: "low", recommendation: "keep as baseline (0596)" },
  "audit-note-0597": { risk: "moderate", recommendation: "trim blur for perf profile (0597)" },
  "audit-note-0598": { risk: "elevated", recommendation: "reduce specular in dense tables (0598)" },
  "audit-note-0599": { risk: "high", recommendation: "reserve for demos only (0599)" },
  "audit-note-0600": { risk: "low", recommendation: "keep as baseline (0600)" },
  "audit-note-0601": { risk: "moderate", recommendation: "trim blur for perf profile (0601)" },
  "audit-note-0602": { risk: "elevated", recommendation: "reduce specular in dense tables (0602)" },
  "audit-note-0603": { risk: "high", recommendation: "reserve for demos only (0603)" },
  "audit-note-0604": { risk: "low", recommendation: "keep as baseline (0604)" },
  "audit-note-0605": { risk: "moderate", recommendation: "trim blur for perf profile (0605)" },
  "audit-note-0606": { risk: "elevated", recommendation: "reduce specular in dense tables (0606)" },
  "audit-note-0607": { risk: "high", recommendation: "reserve for demos only (0607)" },
  "audit-note-0608": { risk: "low", recommendation: "keep as baseline (0608)" },
  "audit-note-0609": { risk: "moderate", recommendation: "trim blur for perf profile (0609)" },
  "audit-note-0610": { risk: "elevated", recommendation: "reduce specular in dense tables (0610)" },
  "audit-note-0611": { risk: "high", recommendation: "reserve for demos only (0611)" },
  "audit-note-0612": { risk: "low", recommendation: "keep as baseline (0612)" },
  "audit-note-0613": { risk: "moderate", recommendation: "trim blur for perf profile (0613)" },
  "audit-note-0614": { risk: "elevated", recommendation: "reduce specular in dense tables (0614)" },
  "audit-note-0615": { risk: "high", recommendation: "reserve for demos only (0615)" },
  "audit-note-0616": { risk: "low", recommendation: "keep as baseline (0616)" },
  "audit-note-0617": { risk: "moderate", recommendation: "trim blur for perf profile (0617)" },
  "audit-note-0618": { risk: "elevated", recommendation: "reduce specular in dense tables (0618)" },
  "audit-note-0619": { risk: "high", recommendation: "reserve for demos only (0619)" },
  "audit-note-0620": { risk: "low", recommendation: "keep as baseline (0620)" },
  "audit-note-0621": { risk: "moderate", recommendation: "trim blur for perf profile (0621)" },
  "audit-note-0622": { risk: "elevated", recommendation: "reduce specular in dense tables (0622)" },
  "audit-note-0623": { risk: "high", recommendation: "reserve for demos only (0623)" },
  "audit-note-0624": { risk: "low", recommendation: "keep as baseline (0624)" },
  "audit-note-0625": { risk: "moderate", recommendation: "trim blur for perf profile (0625)" },
  "audit-note-0626": { risk: "elevated", recommendation: "reduce specular in dense tables (0626)" },
  "audit-note-0627": { risk: "high", recommendation: "reserve for demos only (0627)" },
  "audit-note-0628": { risk: "low", recommendation: "keep as baseline (0628)" },
  "audit-note-0629": { risk: "moderate", recommendation: "trim blur for perf profile (0629)" },
  "audit-note-0630": { risk: "elevated", recommendation: "reduce specular in dense tables (0630)" },
  "audit-note-0631": { risk: "high", recommendation: "reserve for demos only (0631)" },
  "audit-note-0632": { risk: "low", recommendation: "keep as baseline (0632)" },
  "audit-note-0633": { risk: "moderate", recommendation: "trim blur for perf profile (0633)" },
  "audit-note-0634": { risk: "elevated", recommendation: "reduce specular in dense tables (0634)" },
  "audit-note-0635": { risk: "high", recommendation: "reserve for demos only (0635)" },
  "audit-note-0636": { risk: "low", recommendation: "keep as baseline (0636)" },
  "audit-note-0637": { risk: "moderate", recommendation: "trim blur for perf profile (0637)" },
  "audit-note-0638": { risk: "elevated", recommendation: "reduce specular in dense tables (0638)" },
  "audit-note-0639": { risk: "high", recommendation: "reserve for demos only (0639)" },
  "audit-note-0640": { risk: "low", recommendation: "keep as baseline (0640)" },
  "audit-note-0641": { risk: "moderate", recommendation: "trim blur for perf profile (0641)" },
  "audit-note-0642": { risk: "elevated", recommendation: "reduce specular in dense tables (0642)" },
  "audit-note-0643": { risk: "high", recommendation: "reserve for demos only (0643)" },
  "audit-note-0644": { risk: "low", recommendation: "keep as baseline (0644)" },
  "audit-note-0645": { risk: "moderate", recommendation: "trim blur for perf profile (0645)" },
  "audit-note-0646": { risk: "elevated", recommendation: "reduce specular in dense tables (0646)" },
  "audit-note-0647": { risk: "high", recommendation: "reserve for demos only (0647)" },
  "audit-note-0648": { risk: "low", recommendation: "keep as baseline (0648)" },
  "audit-note-0649": { risk: "moderate", recommendation: "trim blur for perf profile (0649)" },
  "audit-note-0650": { risk: "elevated", recommendation: "reduce specular in dense tables (0650)" },
  "audit-note-0651": { risk: "high", recommendation: "reserve for demos only (0651)" },
  "audit-note-0652": { risk: "low", recommendation: "keep as baseline (0652)" },
  "audit-note-0653": { risk: "moderate", recommendation: "trim blur for perf profile (0653)" },
  "audit-note-0654": { risk: "elevated", recommendation: "reduce specular in dense tables (0654)" },
  "audit-note-0655": { risk: "high", recommendation: "reserve for demos only (0655)" },
  "audit-note-0656": { risk: "low", recommendation: "keep as baseline (0656)" },
  "audit-note-0657": { risk: "moderate", recommendation: "trim blur for perf profile (0657)" },
  "audit-note-0658": { risk: "elevated", recommendation: "reduce specular in dense tables (0658)" },
  "audit-note-0659": { risk: "high", recommendation: "reserve for demos only (0659)" },
  "audit-note-0660": { risk: "low", recommendation: "keep as baseline (0660)" },
  "audit-note-0661": { risk: "moderate", recommendation: "trim blur for perf profile (0661)" },
  "audit-note-0662": { risk: "elevated", recommendation: "reduce specular in dense tables (0662)" },
  "audit-note-0663": { risk: "high", recommendation: "reserve for demos only (0663)" },
  "audit-note-0664": { risk: "low", recommendation: "keep as baseline (0664)" },
  "audit-note-0665": { risk: "moderate", recommendation: "trim blur for perf profile (0665)" },
  "audit-note-0666": { risk: "elevated", recommendation: "reduce specular in dense tables (0666)" },
  "audit-note-0667": { risk: "high", recommendation: "reserve for demos only (0667)" },
  "audit-note-0668": { risk: "low", recommendation: "keep as baseline (0668)" },
  "audit-note-0669": { risk: "moderate", recommendation: "trim blur for perf profile (0669)" },
  "audit-note-0670": { risk: "elevated", recommendation: "reduce specular in dense tables (0670)" },
  "audit-note-0671": { risk: "high", recommendation: "reserve for demos only (0671)" },
  "audit-note-0672": { risk: "low", recommendation: "keep as baseline (0672)" },
  "audit-note-0673": { risk: "moderate", recommendation: "trim blur for perf profile (0673)" },
  "audit-note-0674": { risk: "elevated", recommendation: "reduce specular in dense tables (0674)" },
  "audit-note-0675": { risk: "high", recommendation: "reserve for demos only (0675)" },
  "audit-note-0676": { risk: "low", recommendation: "keep as baseline (0676)" },
  "audit-note-0677": { risk: "moderate", recommendation: "trim blur for perf profile (0677)" },
  "audit-note-0678": { risk: "elevated", recommendation: "reduce specular in dense tables (0678)" },
  "audit-note-0679": { risk: "high", recommendation: "reserve for demos only (0679)" },
  "audit-note-0680": { risk: "low", recommendation: "keep as baseline (0680)" },
  "audit-note-0681": { risk: "moderate", recommendation: "trim blur for perf profile (0681)" },
  "audit-note-0682": { risk: "elevated", recommendation: "reduce specular in dense tables (0682)" },
  "audit-note-0683": { risk: "high", recommendation: "reserve for demos only (0683)" },
  "audit-note-0684": { risk: "low", recommendation: "keep as baseline (0684)" },
  "audit-note-0685": { risk: "moderate", recommendation: "trim blur for perf profile (0685)" },
  "audit-note-0686": { risk: "elevated", recommendation: "reduce specular in dense tables (0686)" },
  "audit-note-0687": { risk: "high", recommendation: "reserve for demos only (0687)" },
  "audit-note-0688": { risk: "low", recommendation: "keep as baseline (0688)" },
  "audit-note-0689": { risk: "moderate", recommendation: "trim blur for perf profile (0689)" },
  "audit-note-0690": { risk: "elevated", recommendation: "reduce specular in dense tables (0690)" },
  "audit-note-0691": { risk: "high", recommendation: "reserve for demos only (0691)" },
  "audit-note-0692": { risk: "low", recommendation: "keep as baseline (0692)" },
  "audit-note-0693": { risk: "moderate", recommendation: "trim blur for perf profile (0693)" },
  "audit-note-0694": { risk: "elevated", recommendation: "reduce specular in dense tables (0694)" },
  "audit-note-0695": { risk: "high", recommendation: "reserve for demos only (0695)" },
  "audit-note-0696": { risk: "low", recommendation: "keep as baseline (0696)" },
  "audit-note-0697": { risk: "moderate", recommendation: "trim blur for perf profile (0697)" },
  "audit-note-0698": { risk: "elevated", recommendation: "reduce specular in dense tables (0698)" },
  "audit-note-0699": { risk: "high", recommendation: "reserve for demos only (0699)" },
  "audit-note-0700": { risk: "low", recommendation: "keep as baseline (0700)" },
  "audit-note-0701": { risk: "moderate", recommendation: "trim blur for perf profile (0701)" },
  "audit-note-0702": { risk: "elevated", recommendation: "reduce specular in dense tables (0702)" },
  "audit-note-0703": { risk: "high", recommendation: "reserve for demos only (0703)" },
  "audit-note-0704": { risk: "low", recommendation: "keep as baseline (0704)" },
  "audit-note-0705": { risk: "moderate", recommendation: "trim blur for perf profile (0705)" },
  "audit-note-0706": { risk: "elevated", recommendation: "reduce specular in dense tables (0706)" },
  "audit-note-0707": { risk: "high", recommendation: "reserve for demos only (0707)" },
  "audit-note-0708": { risk: "low", recommendation: "keep as baseline (0708)" },
  "audit-note-0709": { risk: "moderate", recommendation: "trim blur for perf profile (0709)" },
  "audit-note-0710": { risk: "elevated", recommendation: "reduce specular in dense tables (0710)" },
  "audit-note-0711": { risk: "high", recommendation: "reserve for demos only (0711)" },
  "audit-note-0712": { risk: "low", recommendation: "keep as baseline (0712)" },
  "audit-note-0713": { risk: "moderate", recommendation: "trim blur for perf profile (0713)" },
  "audit-note-0714": { risk: "elevated", recommendation: "reduce specular in dense tables (0714)" },
  "audit-note-0715": { risk: "high", recommendation: "reserve for demos only (0715)" },
  "audit-note-0716": { risk: "low", recommendation: "keep as baseline (0716)" },
  "audit-note-0717": { risk: "moderate", recommendation: "trim blur for perf profile (0717)" },
  "audit-note-0718": { risk: "elevated", recommendation: "reduce specular in dense tables (0718)" },
  "audit-note-0719": { risk: "high", recommendation: "reserve for demos only (0719)" },
  "audit-note-0720": { risk: "low", recommendation: "keep as baseline (0720)" },
  "audit-note-0721": { risk: "moderate", recommendation: "trim blur for perf profile (0721)" },
  "audit-note-0722": { risk: "elevated", recommendation: "reduce specular in dense tables (0722)" },
  "audit-note-0723": { risk: "high", recommendation: "reserve for demos only (0723)" },
  "audit-note-0724": { risk: "low", recommendation: "keep as baseline (0724)" },
  "audit-note-0725": { risk: "moderate", recommendation: "trim blur for perf profile (0725)" },
  "audit-note-0726": { risk: "elevated", recommendation: "reduce specular in dense tables (0726)" },
  "audit-note-0727": { risk: "high", recommendation: "reserve for demos only (0727)" },
  "audit-note-0728": { risk: "low", recommendation: "keep as baseline (0728)" },
  "audit-note-0729": { risk: "moderate", recommendation: "trim blur for perf profile (0729)" },
  "audit-note-0730": { risk: "elevated", recommendation: "reduce specular in dense tables (0730)" },
  "audit-note-0731": { risk: "high", recommendation: "reserve for demos only (0731)" },
  "audit-note-0732": { risk: "low", recommendation: "keep as baseline (0732)" },
  "audit-note-0733": { risk: "moderate", recommendation: "trim blur for perf profile (0733)" },
  "audit-note-0734": { risk: "elevated", recommendation: "reduce specular in dense tables (0734)" },
  "audit-note-0735": { risk: "high", recommendation: "reserve for demos only (0735)" },
  "audit-note-0736": { risk: "low", recommendation: "keep as baseline (0736)" },
  "audit-note-0737": { risk: "moderate", recommendation: "trim blur for perf profile (0737)" },
  "audit-note-0738": { risk: "elevated", recommendation: "reduce specular in dense tables (0738)" },
  "audit-note-0739": { risk: "high", recommendation: "reserve for demos only (0739)" },
  "audit-note-0740": { risk: "low", recommendation: "keep as baseline (0740)" },
  "audit-note-0741": { risk: "moderate", recommendation: "trim blur for perf profile (0741)" },
  "audit-note-0742": { risk: "elevated", recommendation: "reduce specular in dense tables (0742)" },
  "audit-note-0743": { risk: "high", recommendation: "reserve for demos only (0743)" },
  "audit-note-0744": { risk: "low", recommendation: "keep as baseline (0744)" },
  "audit-note-0745": { risk: "moderate", recommendation: "trim blur for perf profile (0745)" },
  "audit-note-0746": { risk: "elevated", recommendation: "reduce specular in dense tables (0746)" },
  "audit-note-0747": { risk: "high", recommendation: "reserve for demos only (0747)" },
  "audit-note-0748": { risk: "low", recommendation: "keep as baseline (0748)" },
  "audit-note-0749": { risk: "moderate", recommendation: "trim blur for perf profile (0749)" },
  "audit-note-0750": { risk: "elevated", recommendation: "reduce specular in dense tables (0750)" },
  "audit-note-0751": { risk: "high", recommendation: "reserve for demos only (0751)" },
  "audit-note-0752": { risk: "low", recommendation: "keep as baseline (0752)" },
  "audit-note-0753": { risk: "moderate", recommendation: "trim blur for perf profile (0753)" },
  "audit-note-0754": { risk: "elevated", recommendation: "reduce specular in dense tables (0754)" },
  "audit-note-0755": { risk: "high", recommendation: "reserve for demos only (0755)" },
  "audit-note-0756": { risk: "low", recommendation: "keep as baseline (0756)" },
  "audit-note-0757": { risk: "moderate", recommendation: "trim blur for perf profile (0757)" },
  "audit-note-0758": { risk: "elevated", recommendation: "reduce specular in dense tables (0758)" },
  "audit-note-0759": { risk: "high", recommendation: "reserve for demos only (0759)" },
  "audit-note-0760": { risk: "low", recommendation: "keep as baseline (0760)" },
  "audit-note-0761": { risk: "moderate", recommendation: "trim blur for perf profile (0761)" },
  "audit-note-0762": { risk: "elevated", recommendation: "reduce specular in dense tables (0762)" },
  "audit-note-0763": { risk: "high", recommendation: "reserve for demos only (0763)" },
  "audit-note-0764": { risk: "low", recommendation: "keep as baseline (0764)" },
  "audit-note-0765": { risk: "moderate", recommendation: "trim blur for perf profile (0765)" },
  "audit-note-0766": { risk: "elevated", recommendation: "reduce specular in dense tables (0766)" },
  "audit-note-0767": { risk: "high", recommendation: "reserve for demos only (0767)" },
  "audit-note-0768": { risk: "low", recommendation: "keep as baseline (0768)" },
  "audit-note-0769": { risk: "moderate", recommendation: "trim blur for perf profile (0769)" },
  "audit-note-0770": { risk: "elevated", recommendation: "reduce specular in dense tables (0770)" },
  "audit-note-0771": { risk: "high", recommendation: "reserve for demos only (0771)" },
  "audit-note-0772": { risk: "low", recommendation: "keep as baseline (0772)" },
  "audit-note-0773": { risk: "moderate", recommendation: "trim blur for perf profile (0773)" },
  "audit-note-0774": { risk: "elevated", recommendation: "reduce specular in dense tables (0774)" },
  "audit-note-0775": { risk: "high", recommendation: "reserve for demos only (0775)" },
  "audit-note-0776": { risk: "low", recommendation: "keep as baseline (0776)" },
  "audit-note-0777": { risk: "moderate", recommendation: "trim blur for perf profile (0777)" },
  "audit-note-0778": { risk: "elevated", recommendation: "reduce specular in dense tables (0778)" },
  "audit-note-0779": { risk: "high", recommendation: "reserve for demos only (0779)" },
  "audit-note-0780": { risk: "low", recommendation: "keep as baseline (0780)" },
  "audit-note-0781": { risk: "moderate", recommendation: "trim blur for perf profile (0781)" },
  "audit-note-0782": { risk: "elevated", recommendation: "reduce specular in dense tables (0782)" },
  "audit-note-0783": { risk: "high", recommendation: "reserve for demos only (0783)" },
  "audit-note-0784": { risk: "low", recommendation: "keep as baseline (0784)" },
  "audit-note-0785": { risk: "moderate", recommendation: "trim blur for perf profile (0785)" },
  "audit-note-0786": { risk: "elevated", recommendation: "reduce specular in dense tables (0786)" },
  "audit-note-0787": { risk: "high", recommendation: "reserve for demos only (0787)" },
  "audit-note-0788": { risk: "low", recommendation: "keep as baseline (0788)" },
  "audit-note-0789": { risk: "moderate", recommendation: "trim blur for perf profile (0789)" },
  "audit-note-0790": { risk: "elevated", recommendation: "reduce specular in dense tables (0790)" },
  "audit-note-0791": { risk: "high", recommendation: "reserve for demos only (0791)" },
  "audit-note-0792": { risk: "low", recommendation: "keep as baseline (0792)" },
  "audit-note-0793": { risk: "moderate", recommendation: "trim blur for perf profile (0793)" },
  "audit-note-0794": { risk: "elevated", recommendation: "reduce specular in dense tables (0794)" },
  "audit-note-0795": { risk: "high", recommendation: "reserve for demos only (0795)" },
  "audit-note-0796": { risk: "low", recommendation: "keep as baseline (0796)" },
  "audit-note-0797": { risk: "moderate", recommendation: "trim blur for perf profile (0797)" },
  "audit-note-0798": { risk: "elevated", recommendation: "reduce specular in dense tables (0798)" },
  "audit-note-0799": { risk: "high", recommendation: "reserve for demos only (0799)" },
  "audit-note-0800": { risk: "low", recommendation: "keep as baseline (0800)" },
  "audit-note-0801": { risk: "moderate", recommendation: "trim blur for perf profile (0801)" },
  "audit-note-0802": { risk: "elevated", recommendation: "reduce specular in dense tables (0802)" },
  "audit-note-0803": { risk: "high", recommendation: "reserve for demos only (0803)" },
  "audit-note-0804": { risk: "low", recommendation: "keep as baseline (0804)" },
  "audit-note-0805": { risk: "moderate", recommendation: "trim blur for perf profile (0805)" },
  "audit-note-0806": { risk: "elevated", recommendation: "reduce specular in dense tables (0806)" },
  "audit-note-0807": { risk: "high", recommendation: "reserve for demos only (0807)" },
  "audit-note-0808": { risk: "low", recommendation: "keep as baseline (0808)" },
  "audit-note-0809": { risk: "moderate", recommendation: "trim blur for perf profile (0809)" },
  "audit-note-0810": { risk: "elevated", recommendation: "reduce specular in dense tables (0810)" },
  "audit-note-0811": { risk: "high", recommendation: "reserve for demos only (0811)" },
  "audit-note-0812": { risk: "low", recommendation: "keep as baseline (0812)" },
  "audit-note-0813": { risk: "moderate", recommendation: "trim blur for perf profile (0813)" },
  "audit-note-0814": { risk: "elevated", recommendation: "reduce specular in dense tables (0814)" },
  "audit-note-0815": { risk: "high", recommendation: "reserve for demos only (0815)" },
  "audit-note-0816": { risk: "low", recommendation: "keep as baseline (0816)" },
  "audit-note-0817": { risk: "moderate", recommendation: "trim blur for perf profile (0817)" },
  "audit-note-0818": { risk: "elevated", recommendation: "reduce specular in dense tables (0818)" },
  "audit-note-0819": { risk: "high", recommendation: "reserve for demos only (0819)" },
  "audit-note-0820": { risk: "low", recommendation: "keep as baseline (0820)" },
  "audit-note-0821": { risk: "moderate", recommendation: "trim blur for perf profile (0821)" },
  "audit-note-0822": { risk: "elevated", recommendation: "reduce specular in dense tables (0822)" },
  "audit-note-0823": { risk: "high", recommendation: "reserve for demos only (0823)" },
  "audit-note-0824": { risk: "low", recommendation: "keep as baseline (0824)" },
  "audit-note-0825": { risk: "moderate", recommendation: "trim blur for perf profile (0825)" },
  "audit-note-0826": { risk: "elevated", recommendation: "reduce specular in dense tables (0826)" },
  "audit-note-0827": { risk: "high", recommendation: "reserve for demos only (0827)" },
  "audit-note-0828": { risk: "low", recommendation: "keep as baseline (0828)" },
  "audit-note-0829": { risk: "moderate", recommendation: "trim blur for perf profile (0829)" },
  "audit-note-0830": { risk: "elevated", recommendation: "reduce specular in dense tables (0830)" },
  "audit-note-0831": { risk: "high", recommendation: "reserve for demos only (0831)" },
  "audit-note-0832": { risk: "low", recommendation: "keep as baseline (0832)" },
  "audit-note-0833": { risk: "moderate", recommendation: "trim blur for perf profile (0833)" },
  "audit-note-0834": { risk: "elevated", recommendation: "reduce specular in dense tables (0834)" },
  "audit-note-0835": { risk: "high", recommendation: "reserve for demos only (0835)" },
  "audit-note-0836": { risk: "low", recommendation: "keep as baseline (0836)" },
  "audit-note-0837": { risk: "moderate", recommendation: "trim blur for perf profile (0837)" },
  "audit-note-0838": { risk: "elevated", recommendation: "reduce specular in dense tables (0838)" },
  "audit-note-0839": { risk: "high", recommendation: "reserve for demos only (0839)" },
  "audit-note-0840": { risk: "low", recommendation: "keep as baseline (0840)" },
  "audit-note-0841": { risk: "moderate", recommendation: "trim blur for perf profile (0841)" },
  "audit-note-0842": { risk: "elevated", recommendation: "reduce specular in dense tables (0842)" },
  "audit-note-0843": { risk: "high", recommendation: "reserve for demos only (0843)" },
  "audit-note-0844": { risk: "low", recommendation: "keep as baseline (0844)" },
  "audit-note-0845": { risk: "moderate", recommendation: "trim blur for perf profile (0845)" },
  "audit-note-0846": { risk: "elevated", recommendation: "reduce specular in dense tables (0846)" },
  "audit-note-0847": { risk: "high", recommendation: "reserve for demos only (0847)" },
  "audit-note-0848": { risk: "low", recommendation: "keep as baseline (0848)" },
  "audit-note-0849": { risk: "moderate", recommendation: "trim blur for perf profile (0849)" },
  "audit-note-0850": { risk: "elevated", recommendation: "reduce specular in dense tables (0850)" },
  "audit-note-0851": { risk: "high", recommendation: "reserve for demos only (0851)" },
  "audit-note-0852": { risk: "low", recommendation: "keep as baseline (0852)" },
  "audit-note-0853": { risk: "moderate", recommendation: "trim blur for perf profile (0853)" },
  "audit-note-0854": { risk: "elevated", recommendation: "reduce specular in dense tables (0854)" },
  "audit-note-0855": { risk: "high", recommendation: "reserve for demos only (0855)" },
  "audit-note-0856": { risk: "low", recommendation: "keep as baseline (0856)" },
  "audit-note-0857": { risk: "moderate", recommendation: "trim blur for perf profile (0857)" },
  "audit-note-0858": { risk: "elevated", recommendation: "reduce specular in dense tables (0858)" },
  "audit-note-0859": { risk: "high", recommendation: "reserve for demos only (0859)" },
  "audit-note-0860": { risk: "low", recommendation: "keep as baseline (0860)" },
  "audit-note-0861": { risk: "moderate", recommendation: "trim blur for perf profile (0861)" },
  "audit-note-0862": { risk: "elevated", recommendation: "reduce specular in dense tables (0862)" },
  "audit-note-0863": { risk: "high", recommendation: "reserve for demos only (0863)" },
  "audit-note-0864": { risk: "low", recommendation: "keep as baseline (0864)" },
  "audit-note-0865": { risk: "moderate", recommendation: "trim blur for perf profile (0865)" },
  "audit-note-0866": { risk: "elevated", recommendation: "reduce specular in dense tables (0866)" },
  "audit-note-0867": { risk: "high", recommendation: "reserve for demos only (0867)" },
  "audit-note-0868": { risk: "low", recommendation: "keep as baseline (0868)" },
  "audit-note-0869": { risk: "moderate", recommendation: "trim blur for perf profile (0869)" },
  "audit-note-0870": { risk: "elevated", recommendation: "reduce specular in dense tables (0870)" },
  "audit-note-0871": { risk: "high", recommendation: "reserve for demos only (0871)" },
  "audit-note-0872": { risk: "low", recommendation: "keep as baseline (0872)" },
  "audit-note-0873": { risk: "moderate", recommendation: "trim blur for perf profile (0873)" },
  "audit-note-0874": { risk: "elevated", recommendation: "reduce specular in dense tables (0874)" },
  "audit-note-0875": { risk: "high", recommendation: "reserve for demos only (0875)" },
  "audit-note-0876": { risk: "low", recommendation: "keep as baseline (0876)" },
  "audit-note-0877": { risk: "moderate", recommendation: "trim blur for perf profile (0877)" },
  "audit-note-0878": { risk: "elevated", recommendation: "reduce specular in dense tables (0878)" },
  "audit-note-0879": { risk: "high", recommendation: "reserve for demos only (0879)" },
  "audit-note-0880": { risk: "low", recommendation: "keep as baseline (0880)" },
  "audit-note-0881": { risk: "moderate", recommendation: "trim blur for perf profile (0881)" },
  "audit-note-0882": { risk: "elevated", recommendation: "reduce specular in dense tables (0882)" },
  "audit-note-0883": { risk: "high", recommendation: "reserve for demos only (0883)" },
  "audit-note-0884": { risk: "low", recommendation: "keep as baseline (0884)" },
  "audit-note-0885": { risk: "moderate", recommendation: "trim blur for perf profile (0885)" },
  "audit-note-0886": { risk: "elevated", recommendation: "reduce specular in dense tables (0886)" },
  "audit-note-0887": { risk: "high", recommendation: "reserve for demos only (0887)" },
  "audit-note-0888": { risk: "low", recommendation: "keep as baseline (0888)" },
  "audit-note-0889": { risk: "moderate", recommendation: "trim blur for perf profile (0889)" },
  "audit-note-0890": { risk: "elevated", recommendation: "reduce specular in dense tables (0890)" },
  "audit-note-0891": { risk: "high", recommendation: "reserve for demos only (0891)" },
  "audit-note-0892": { risk: "low", recommendation: "keep as baseline (0892)" },
  "audit-note-0893": { risk: "moderate", recommendation: "trim blur for perf profile (0893)" },
  "audit-note-0894": { risk: "elevated", recommendation: "reduce specular in dense tables (0894)" },
  "audit-note-0895": { risk: "high", recommendation: "reserve for demos only (0895)" },
  "audit-note-0896": { risk: "low", recommendation: "keep as baseline (0896)" },
  "audit-note-0897": { risk: "moderate", recommendation: "trim blur for perf profile (0897)" },
  "audit-note-0898": { risk: "elevated", recommendation: "reduce specular in dense tables (0898)" },
  "audit-note-0899": { risk: "high", recommendation: "reserve for demos only (0899)" },
  "audit-note-0900": { risk: "low", recommendation: "keep as baseline (0900)" },
} as const;

export function lookupMaterialAudit(noteId: string): { readonly risk: string; readonly recommendation: string } | null {
  return MATERIAL_AUDIT_NOTES[noteId] ?? null;
}

export function listPresetGalleryByStyle(styleId: LuxuryStyleId, limit = 40): readonly LuxuryPreset[] {
  return PRESET_GALLERY.filter((entry) => entry.preset.styleId === styleId)
    .slice(0, limit)
    .map((entry) => entry.preset);
}

export function listSurfaceRecipesForStyle(
  styleId: LuxuryStyleId,
  surfaceId?: SurfaceId,
  limit = 48
): readonly {
  readonly id: string;
  readonly styleId: LuxuryStyleId;
  readonly surfaceId: SurfaceId;
  readonly materialId: string;
  readonly blurStrengthPx: number;
  readonly grainOpacity: number;
  readonly gridOpacity: number;
  readonly specularIntensity: number;
  readonly note: string;
}[] {
  const filtered = SURFACE_RECIPE_CATALOG.filter(
    (entry) => entry.styleId === styleId && (!surfaceId || entry.surfaceId === surfaceId)
  );
  return filtered.slice(0, limit);
}

