#!/usr/bin/env node
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "../..");
const docsDir = path.join(repoRoot, "docs");
const outputFile = path.join(docsDir, "DOCS_INDEX.md");

function toPosix(value) {
  return value.replace(/\\/g, "/");
}

function readDocsFiles() {
  const entries = readdirSync(docsDir, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".md") && entry.name !== "DOCS_INDEX.md")
    .map((entry) => entry.name)
    .sort((left, right) => left.localeCompare(right));
}

function extractTitle(content, fallback) {
  const firstLine = content.split(/\r?\n/, 1)[0] ?? "";
  if (firstLine.startsWith("# ")) {
    return firstLine.slice(2).trim();
  }

  return fallback;
}

function buildIndex() {
  const files = readDocsFiles();
  const rows = files.map((filename) => {
    const absolutePath = path.join(docsDir, filename);
    const content = readFileSync(absolutePath, "utf8");
    const title = extractTitle(content, filename.replace(/\.md$/, ""));
    const bytes = statSync(absolutePath).size;
    const lines = content.split(/\r?\n/).length;

    return {
      filename,
      title,
      bytes,
      lines
    };
  });

  const generated = [
    "# DOCS INDEX",
    "",
    "Deterministic index generated by `tools/scripts/generate_docs_index.mjs`.",
    "",
    "| File | Title | Lines | Bytes |",
    "| --- | --- | ---: | ---: |",
    ...rows.map((row) => `| ${toPosix(path.join("docs", row.filename))} | ${row.title} | ${row.lines} | ${row.bytes} |`),
    ""
  ].join("\n");

  writeFileSync(outputFile, generated, "utf8");
  console.log(`[docs] generated ${toPosix(path.relative(repoRoot, outputFile))}`);
}

buildIndex();
