#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Code Atlas Dependency Visual V04.

Offline HTML viewer for graph JSON generated by code_atlas_dependency_consumer_v03.py.
This tool is intentionally a consumer: it does not re-scan projects, patch Capatch,
or mutate Code Atlas state. It turns a clean graph/report artifact into a navigable
visual report that can be opened in a browser.
"""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Iterable

TOOL_NAME = "code-atlas dependency visual"
TOOL_VERSION = "4.0.0"
DEFAULT_MAX_VISUAL_NODES = 180
DEFAULT_MAX_TABLE_ROWS = 500
EXIT_OK = 0
EXIT_BAD_INPUT = 2
EXIT_VERIFY_FAILED = 3
EXIT_WRITE_FAILED = 4


@dataclass(frozen=True)
class LoadedGraph:
    graph_path: Path
    graph: dict[str, Any]
    summary_path: Path | None
    summary: dict[str, Any] | None


def _clean_text(value: Any) -> str:
    return " ".join(str(value or "").replace("\n", " ").split()).strip()


def _slug(value: str) -> str:
    cleaned = _clean_text(value) or "dependency_graph"
    cleaned = cleaned.replace("\\", "_").replace("/", "_").replace(":", "_")
    cleaned = re.sub(r"[^A-Za-z0-9_.-]+", "_", cleaned).strip("._")
    return cleaned or "dependency_graph"


def _read_json(path: Path) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ValueError(f"JSON file does not exist: {path}") from exc
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON in {path}: {exc}") from exc
    if not isinstance(data, dict):
        raise ValueError(f"Expected JSON object in {path}")
    return data


def load_graph(graph_json: Path, summary_json: Path | None = None) -> LoadedGraph:
    graph_path = graph_json.expanduser().resolve()
    graph = _read_json(graph_path)
    nodes = graph.get("nodes")
    edges = graph.get("edges")
    if not isinstance(nodes, list) or not isinstance(edges, list):
        raise ValueError(
            "Graph JSON must contain list fields 'nodes' and 'edges'. "
            f"Path: {graph_path}"
        )

    loaded_summary: dict[str, Any] | None = None
    resolved_summary_path: Path | None = None
    if summary_json is not None:
        resolved_summary_path = summary_json.expanduser().resolve()
        loaded_summary = _read_json(resolved_summary_path)

    return LoadedGraph(
        graph_path=graph_path,
        graph=graph,
        summary_path=resolved_summary_path,
        summary=loaded_summary,
    )


def _node_workspace(node: dict[str, Any]) -> str:
    metadata = node.get("metadata") if isinstance(node.get("metadata"), dict) else {}
    workspace = _clean_text(metadata.get("workspace"))
    if workspace:
        return workspace
    kind = _clean_text(node.get("kind"))
    path = _clean_text(node.get("path"))
    if kind == "external":
        return "[external]"
    if kind == "unresolved":
        return "[unresolved]"
    if path.startswith("products/mobile/app/"):
        return "products/mobile/app"
    if path.startswith("products/tablet/app/"):
        return "products/tablet/app"
    if path.startswith("products/pc/app/"):
        return "products/pc/app"
    return "(root/tools)"


def _project_profile(summary: dict[str, Any] | None) -> dict[str, Any]:
    if not summary:
        return {}
    profile = summary.get("project_profile")
    return profile if isinstance(profile, dict) else {}


def build_view_model(loaded: LoadedGraph, *, max_visual_nodes: int) -> dict[str, Any]:
    graph = loaded.graph
    summary = loaded.summary
    nodes = [n for n in graph.get("nodes", []) if isinstance(n, dict)]
    edges = [e for e in graph.get("edges", []) if isinstance(e, dict)]

    node_by_id = {_clean_text(n.get("id")): n for n in nodes if _clean_text(n.get("id"))}
    inbound = Counter()
    outbound = Counter()
    edge_class_counts = Counter()
    edge_kind_counts = Counter()
    workspace_counts = Counter()
    external_counts = Counter()
    unresolved_edges: list[dict[str, Any]] = []
    unresolved_weight = 0

    for node in nodes:
        workspace_counts[_node_workspace(node)] += 1

    for edge in edges:
        source = _clean_text(edge.get("source"))
        target = _clean_text(edge.get("target"))
        weight = int(edge.get("weight") or 1)
        classification = _clean_text(edge.get("classification")) or "contains"
        kind = _clean_text(edge.get("kind")) or "edge"
        if source:
            outbound[source] += weight
        if target:
            inbound[target] += weight
        edge_class_counts[classification] += weight
        edge_kind_counts[kind] += weight
        if classification == "external" and target.startswith("external:"):
            external_counts[target.removeprefix("external:")] += weight
        if classification == "unresolved" or "unresolved" in kind:
            unresolved_edges.append(edge)
            unresolved_weight += weight

    enriched_nodes: list[dict[str, Any]] = []
    for node in nodes:
        node_id = _clean_text(node.get("id"))
        degree = inbound[node_id] + outbound[node_id]
        item = dict(node)
        item["workspace"] = _node_workspace(node)
        item["degree"] = degree
        item["inbound"] = int(inbound[node_id])
        item["outbound"] = int(outbound[node_id])
        enriched_nodes.append(item)

    visual_candidates = [n for n in enriched_nodes if n.get("kind") != "project"]
    visual_candidates.sort(
        key=lambda n: (
            -int(n.get("degree") or 0),
            _clean_text(n.get("workspace")).lower(),
            _clean_text(n.get("label")).lower(),
        )
    )
    visual_nodes = visual_candidates[: max(20, max_visual_nodes)]
    visual_ids = {n["id"] for n in visual_nodes if "id" in n}
    visual_edges = [
        e for e in edges
        if _clean_text(e.get("source")) in visual_ids and _clean_text(e.get("target")) in visual_ids
    ]

    dependency_summary = summary.get("dependency_summary") if isinstance(summary, dict) else None
    if not isinstance(dependency_summary, dict):
        dependency_summary = {
            "nodes": len(nodes),
            "edges": len(edges),
            "internal_edges": int(edge_class_counts.get("internal", 0)),
            "external_edges": int(edge_class_counts.get("external", 0)),
            "unresolved_edges": int(edge_class_counts.get("unresolved", 0)),
        }

    profile = _project_profile(summary)
    top_external = [
        {"name": name, "edges": count}
        for name, count in external_counts.most_common(30)
    ]
    top_files = [
        {
            "id": n.get("id"),
            "label": n.get("label"),
            "path": n.get("path"),
            "workspace": n.get("workspace"),
            "kind": n.get("kind"),
            "inbound": n.get("inbound"),
            "outbound": n.get("outbound"),
            "degree": n.get("degree"),
        }
        for n in visual_candidates[:80]
    ]

    return {
        "tool": TOOL_NAME,
        "version": TOOL_VERSION,
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "input_graph": str(loaded.graph_path),
        "input_summary": str(loaded.summary_path) if loaded.summary_path else "",
        "graph_version": graph.get("version"),
        "graph_generated_at": graph.get("generated_at"),
        "project_profile": profile,
        "dependency_summary": dependency_summary,
        "workspace_counts": dict(sorted(workspace_counts.items(), key=lambda item: item[0].lower())),
        "edge_class_counts": dict(edge_class_counts),
        "edge_kind_counts": dict(edge_kind_counts.most_common()),
        "top_external": top_external,
        "top_files": top_files,
        "unresolved_edges": unresolved_edges,
        "unresolved_weight": unresolved_weight,
        "nodes": enriched_nodes,
        "edges": edges,
        "visual_nodes": visual_nodes,
        "visual_edges": visual_edges,
        "max_visual_nodes": max_visual_nodes,
    }


def _json_for_script(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")


def _escape(value: Any) -> str:
    return html.escape(str(value), quote=True)


def render_html(model: dict[str, Any], *, title: str) -> str:
    profile = model.get("project_profile") if isinstance(model.get("project_profile"), dict) else {}
    summary = model.get("dependency_summary") if isinstance(model.get("dependency_summary"), dict) else {}
    package_name = _clean_text(profile.get("package_name")) or "Dependency graph"
    package_manager = _clean_text(profile.get("package_manager")) or "unknown"
    frameworks = profile.get("frameworks") if isinstance(profile.get("frameworks"), list) else []
    languages = profile.get("languages") if isinstance(profile.get("languages"), list) else []

    cards = [
        ("Graph", model.get("graph_version", "-")),
        ("Files", summary.get("source_files", summary.get("nodes", "-"))),
        ("Edges", summary.get("edges", "-")),
        ("Internal", summary.get("internal_edges", "-")),
        ("External", summary.get("external_edges", "-")),
        ("Unresolved", summary.get("unresolved_edges", "-")),
        ("Ignored", summary.get("ignored_edges", "0")),
        ("Salvage", summary.get("salvage_edges", "0")),
    ]
    card_html = "\n".join(
        f'<section class="metric-card"><span>{_escape(label)}</span><strong>{_escape(value)}</strong></section>'
        for label, value in cards
    )

    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{_escape(title)}</title>
  <style>
    :root {{
      --bg: #07090d;
      --panel: rgba(18, 22, 29, 0.88);
      --panel-2: rgba(28, 34, 44, 0.82);
      --line: rgba(219, 231, 255, 0.16);
      --line-strong: rgba(219, 231, 255, 0.28);
      --text: #edf3ff;
      --muted: #9ca9bc;
      --soft: #c4cedd;
      --cyan: #76d7ff;
      --blue: #7a9cff;
      --green: #8de6b1;
      --amber: #ffd089;
      --red: #ff8d9b;
      --shadow: rgba(0,0,0,0.5);
      --radius: 18px;
      --mono: "Cascadia Mono", "SFMono-Regular", Consolas, monospace;
      --sans: "Segoe UI", Aptos, system-ui, sans-serif;
    }}
    * {{ box-sizing: border-box; }}
    html, body {{ min-height: 100%; }}
    body {{
      margin: 0;
      color: var(--text);
      font-family: var(--sans);
      background:
        radial-gradient(circle at 12% 0%, rgba(118, 215, 255, 0.16), transparent 30rem),
        radial-gradient(circle at 88% 10%, rgba(122, 156, 255, 0.15), transparent 34rem),
        linear-gradient(135deg, #05060a 0%, #101723 50%, #06080d 100%);
    }}
    .shell {{ width: min(100%, 1480px); margin: 0 auto; padding: 24px; }}
    .hero, .panel, .metric-card {{
      border: 1px solid var(--line);
      border-radius: var(--radius);
      background: linear-gradient(180deg, rgba(255,255,255,0.07), rgba(255,255,255,0.018)), var(--panel);
      box-shadow: 0 28px 80px var(--shadow), inset 0 1px 0 rgba(255,255,255,0.14);
    }}
    .hero {{ padding: 22px; display: grid; grid-template-columns: 1fr auto; gap: 18px; align-items: end; }}
    .eyebrow {{ margin: 0 0 8px; color: var(--cyan); text-transform: uppercase; letter-spacing: .16em; font-size: 12px; font-weight: 800; }}
    h1 {{ margin: 0; font-size: clamp(28px, 4vw, 56px); line-height: .98; }}
    .subtitle {{ margin: 10px 0 0; color: var(--soft); max-width: 90ch; }}
    .meta {{ color: var(--muted); font-family: var(--mono); font-size: 12px; overflow-wrap: anywhere; }}
    .badges {{ display: flex; gap: 8px; flex-wrap: wrap; justify-content: flex-end; }}
    .badge {{ border: 1px solid var(--line); border-radius: 999px; padding: 7px 10px; background: rgba(255,255,255,0.045); color: var(--soft); font: 700 12px var(--mono); }}
    .metrics {{ display: grid; grid-template-columns: repeat(8, minmax(0, 1fr)); gap: 10px; margin: 14px 0; }}
    .metric-card {{ padding: 14px; min-height: 82px; }}
    .metric-card span {{ display: block; color: var(--muted); font-size: 11px; text-transform: uppercase; letter-spacing: .12em; font-weight: 800; }}
    .metric-card strong {{ display: block; margin-top: 10px; font: 800 24px var(--mono); }}
    .grid {{ display: grid; grid-template-columns: 380px 1fr; gap: 14px; }}
    .panel {{ overflow: hidden; }}
    .panel-header {{ padding: 15px 16px; border-bottom: 1px solid var(--line); display: flex; gap: 10px; align-items: center; justify-content: space-between; }}
    .panel-header h2 {{ margin: 0; font-size: 16px; }}
    .controls {{ display: grid; grid-template-columns: 1fr 1fr; gap: 8px; padding: 12px; border-bottom: 1px solid var(--line); }}
    input, select, button {{
      width: 100%; height: 38px; color: var(--text); border: 1px solid var(--line);
      background: rgba(5, 8, 13, 0.72); border-radius: 10px; padding: 0 11px; outline: none;
      font: 13px var(--sans);
    }}
    button {{ cursor: pointer; font-weight: 800; color: #061018; background: linear-gradient(180deg, #9fe5ff, #76d7ff); border: 0; }}
    input:focus, select:focus {{ border-color: rgba(118,215,255,.7); box-shadow: 0 0 0 3px rgba(118,215,255,.12); }}
    .list {{ max-height: 470px; overflow: auto; }}
    .item {{ padding: 10px 12px; border-bottom: 1px solid rgba(219,231,255,.08); cursor: pointer; }}
    .item:hover, .item.active {{ background: rgba(118,215,255,.08); }}
    .item-title {{ font-weight: 800; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }}
    .item-path {{ margin-top: 3px; color: var(--muted); font: 11px var(--mono); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }}
    .item-stats {{ margin-top: 5px; display: flex; gap: 6px; flex-wrap: wrap; }}
    .pill {{ border-radius: 999px; padding: 3px 7px; font: 700 10px var(--mono); background: rgba(255,255,255,.07); color: var(--soft); }}
    .pill.internal {{ color: var(--green); }} .pill.external {{ color: var(--blue); }} .pill.unresolved {{ color: var(--red); }}
    .graph-wrap {{ position: relative; height: 560px; }}
    canvas {{ display: block; width: 100%; height: 560px; background: radial-gradient(circle at 50% 50%, rgba(118,215,255,.05), transparent 38rem); }}
    .legend {{ position: absolute; left: 14px; bottom: 14px; display: flex; gap: 8px; flex-wrap: wrap; }}
    .legend span {{ padding: 6px 9px; border-radius: 999px; background: rgba(0,0,0,.42); border: 1px solid var(--line); font: 700 11px var(--mono); }}
    .detail {{ padding: 14px 16px; min-height: 180px; border-top: 1px solid var(--line); background: rgba(0,0,0,.16); }}
    .detail h3 {{ margin: 0 0 8px; }}
    .detail-grid {{ display: grid; grid-template-columns: repeat(2, minmax(0,1fr)); gap: 8px; }}
    .kv {{ border: 1px solid rgba(219,231,255,.1); border-radius: 10px; padding: 8px; background: rgba(255,255,255,.03); }}
    .kv span {{ display:block; color: var(--muted); font-size: 11px; }} .kv b {{ font-family: var(--mono); overflow-wrap: anywhere; }}
    .tables {{ display:grid; grid-template-columns: 1fr 1fr; gap: 14px; margin-top: 14px; }}
    table {{ width: 100%; border-collapse: collapse; font-size: 12px; }}
    th, td {{ padding: 9px 10px; border-bottom: 1px solid rgba(219,231,255,.09); text-align:left; vertical-align: top; }}
    th {{ color: var(--muted); text-transform: uppercase; letter-spacing: .1em; font-size: 10px; position: sticky; top: 0; background: rgba(16,22,31,.96); }}
    td.path {{ font-family: var(--mono); color: var(--soft); overflow-wrap: anywhere; }}
    .table-scroll {{ max-height: 420px; overflow: auto; }}
    .footer {{ margin-top: 14px; color: var(--muted); font: 12px var(--mono); }}
    @media (max-width: 1100px) {{ .grid, .tables, .hero {{ grid-template-columns: 1fr; }} .metrics {{ grid-template-columns: repeat(2,1fr); }} .badges {{ justify-content:flex-start; }} }}
  </style>
</head>
<body>
  <main class="shell">
    <header class="hero">
      <section>
        <p class="eyebrow">Code Atlas Visual V04</p>
        <h1>{_escape(title)}</h1>
        <p class="subtitle">Offline browser view over dependency-map consumer graph JSON. This is a visualization layer only: no scan, no patch, no hidden writes.</p>
        <p class="meta">Input graph: {_escape(model.get('input_graph', ''))}</p>
      </section>
      <section class="badges">
        <span class="badge">{_escape(package_name)}</span>
        <span class="badge">{_escape(package_manager)}</span>
        {''.join(f'<span class="badge">{_escape(x)}</span>' for x in frameworks[:8])}
      </section>
    </header>

    <section class="metrics">{card_html}</section>

    <section class="grid">
      <aside class="panel">
        <div class="panel-header"><h2>Files / nodes</h2><span class="meta" id="nodeCount"></span></div>
        <div class="controls">
          <input id="search" placeholder="Search path, label, import" />
          <select id="workspace"></select>
          <select id="kind"><option value="">All kinds</option><option>file</option><option>external</option><option>unresolved</option><option>workspace</option></select>
          <button id="reset">Reset</button>
        </div>
        <div class="list" id="nodeList"></div>
      </aside>

      <section class="panel">
        <div class="panel-header"><h2>Dependency graph preview</h2><span class="meta">Top connected nodes + current filter</span></div>
        <div class="graph-wrap">
          <canvas id="graphCanvas" width="980" height="560"></canvas>
          <div class="legend"><span style="color:var(--green)">file</span><span style="color:var(--blue)">external</span><span style="color:var(--red)">unresolved</span><span style="color:var(--amber)">workspace</span></div>
        </div>
        <div class="detail" id="detail"><h3>Select a node</h3><p class="meta">Click a row or a dot. The graph is intentionally capped so your browser does not start cooking itself like a cheap charger.</p></div>
      </section>
    </section>

    <section class="tables">
      <section class="panel"><div class="panel-header"><h2>Top external imports</h2></div><div class="table-scroll"><table id="externalTable"></table></div></section>
      <section class="panel"><div class="panel-header"><h2>Unresolved imports</h2></div><div class="table-scroll"><table id="unresolvedTable"></table></div></section>
    </section>

    <section class="panel" style="margin-top:14px"><div class="panel-header"><h2>Project profile</h2></div><div class="detail"><div class="detail-grid">
      <div class="kv"><span>Languages</span><b>{_escape(', '.join(map(str, languages)) or '-')}</b></div>
      <div class="kv"><span>Generated</span><b>{_escape(model.get('generated_at', '-'))}</b></div>
      <div class="kv"><span>Graph generated</span><b>{_escape(model.get('graph_generated_at', '-'))}</b></div>
      <div class="kv"><span>Input summary</span><b>{_escape(model.get('input_summary', ''))}</b></div>
    </div></div></section>

    <p class="footer">Generated by {TOOL_NAME} v{TOOL_VERSION}. Keep Capatch generic. Keep Code Atlas as consumer. Avoid turning the repo into spaghetti with a GUI.</p>
  </main>
<script>
const MODEL = {_json_for_script(model)};
const nodes = MODEL.nodes || [];
const edges = MODEL.edges || [];
const byId = new Map(nodes.map(n => [n.id, n]));
let selectedId = "";
const nodeList = document.getElementById('nodeList');
const nodeCount = document.getElementById('nodeCount');
const search = document.getElementById('search');
const workspace = document.getElementById('workspace');
const kind = document.getElementById('kind');
const reset = document.getElementById('reset');
const detail = document.getElementById('detail');
const canvas = document.getElementById('graphCanvas');
const ctx = canvas.getContext('2d');
let visualNodes = [];
let positions = new Map();

function unique(values) {{ return Array.from(new Set(values.filter(Boolean))).sort((a,b)=>String(a).localeCompare(String(b))); }}
function esc(s) {{ return String(s ?? '').replace(/[&<>"]/g, c => ({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}}[c])); }}
function nodeColor(n) {{ if(n.kind === 'external') return '#7a9cff'; if(n.kind === 'unresolved') return '#ff8d9b'; if(n.kind === 'workspace') return '#ffd089'; return '#8de6b1'; }}
function matches(n) {{
  const q = search.value.trim().toLowerCase();
  const ws = workspace.value;
  const k = kind.value;
  if (ws && n.workspace !== ws) return false;
  if (k && n.kind !== k) return false;
  if (!q) return true;
  return `${{n.label||''}} ${{n.path||''}} ${{n.id||''}} ${{n.workspace||''}}`.toLowerCase().includes(q);
}}
function filteredNodes() {{ return nodes.filter(matches).sort((a,b)=>(b.degree||0)-(a.degree||0)).slice(0, MODEL.max_visual_nodes || 180); }}
function renderNodeList() {{
  const list = filteredNodes();
  nodeCount.textContent = `${{list.length}} shown / ${{nodes.length}} total`;
  nodeList.innerHTML = list.map(n => `<div class="item ${{n.id===selectedId?'active':''}}" data-id="${{esc(n.id)}}"><div class="item-title">${{esc(n.label || n.id)}}</div><div class="item-path">${{esc(n.path || '')}}</div><div class="item-stats"><span class="pill ${{esc(n.kind)}}">${{esc(n.kind)}}</span><span class="pill">${{esc(n.workspace)}}</span><span class="pill">in ${{n.inbound||0}}</span><span class="pill">out ${{n.outbound||0}}</span></div></div>`).join('');
  nodeList.querySelectorAll('[data-id]').forEach(el => el.addEventListener('click', () => selectNode(el.dataset.id)));
}}
function selectNode(id) {{ selectedId = id || ''; renderNodeList(); renderDetail(); drawGraph(); }}
function renderDetail() {{
  const n = byId.get(selectedId);
  if (!n) {{ detail.innerHTML = `<h3>Select a node</h3><p class="meta">Click a row or a dot.</p>`; return; }}
  const outgoing = edges.filter(e => e.source === n.id).slice(0, 12);
  const incoming = edges.filter(e => e.target === n.id).slice(0, 12);
  detail.innerHTML = `<h3>${{esc(n.label || n.id)}}</h3><div class="detail-grid"><div class="kv"><span>Path</span><b>${{esc(n.path || '')}}</b></div><div class="kv"><span>Workspace</span><b>${{esc(n.workspace || '')}}</b></div><div class="kv"><span>Inbound</span><b>${{n.inbound||0}}</b></div><div class="kv"><span>Outbound</span><b>${{n.outbound||0}}</b></div></div><p class="meta"><b>Outgoing:</b> ${{outgoing.map(e=>esc((byId.get(e.target)||{{}}).label || e.target)).join(', ') || '-'}}<br><b>Incoming:</b> ${{incoming.map(e=>esc((byId.get(e.source)||{{}}).label || e.source)).join(', ') || '-'}}</p>`;
}}
function layout(nodesToDraw) {{
  positions = new Map();
  const groups = unique(nodesToDraw.map(n => n.workspace || '(none)'));
  const w = canvas.width, h = canvas.height;
  groups.forEach((g, gi) => {{
    const groupNodes = nodesToDraw.filter(n => (n.workspace || '(none)') === g);
    const cx = ((gi + 1) / (groups.length + 1)) * w;
    const cy = h * 0.48;
    const radius = Math.max(45, Math.min(150, 22 + groupNodes.length * 1.2));
    groupNodes.forEach((n, i) => {{
      const angle = (Math.PI * 2 * i / Math.max(1, groupNodes.length)) + gi;
      const r = radius * (0.40 + ((i % 5) * 0.14));
      positions.set(n.id, {{x: cx + Math.cos(angle) * r, y: cy + Math.sin(angle) * r}});
    }});
  }});
}}
function drawGraph() {{
  visualNodes = filteredNodes();
  const ids = new Set(visualNodes.map(n => n.id));
  layout(visualNodes);
  ctx.clearRect(0,0,canvas.width,canvas.height);
  ctx.lineWidth = 1;
  edges.forEach(e => {{
    if(!ids.has(e.source) || !ids.has(e.target)) return;
    const a = positions.get(e.source), b = positions.get(e.target);
    if(!a || !b) return;
    ctx.strokeStyle = e.classification === 'unresolved' ? 'rgba(255,141,155,.55)' : e.classification === 'external' ? 'rgba(122,156,255,.28)' : 'rgba(141,230,177,.24)';
    ctx.beginPath(); ctx.moveTo(a.x,a.y); ctx.lineTo(b.x,b.y); ctx.stroke();
  }});
  visualNodes.forEach(n => {{
    const p = positions.get(n.id); if(!p) return;
    const r = n.id === selectedId ? 8 : Math.max(3, Math.min(7, 3 + Math.sqrt(n.degree||0) * .45));
    ctx.beginPath(); ctx.fillStyle = nodeColor(n); ctx.globalAlpha = n.id === selectedId ? 1 : .86; ctx.arc(p.x,p.y,r,0,Math.PI*2); ctx.fill();
    if(n.id === selectedId) {{ ctx.strokeStyle = '#ffffff'; ctx.lineWidth = 2; ctx.stroke(); }}
    ctx.globalAlpha = 1;
  }});
}}
canvas.addEventListener('click', ev => {{
  const rect = canvas.getBoundingClientRect();
  const x = (ev.clientX - rect.left) * (canvas.width / rect.width);
  const y = (ev.clientY - rect.top) * (canvas.height / rect.height);
  let best = null, dist = Infinity;
  for (const n of visualNodes) {{ const p = positions.get(n.id); if(!p) continue; const d = Math.hypot(p.x-x, p.y-y); if(d < dist) {{ best = n; dist = d; }} }}
  if(best && dist < 18) selectNode(best.id);
}});
function renderExternal() {{
  const rows = (MODEL.top_external || []).map(x => `<tr><td class="path">${{esc(x.name)}}</td><td>${{x.edges}}</td></tr>`).join('');
  document.getElementById('externalTable').innerHTML = `<thead><tr><th>Import</th><th>Edges</th></tr></thead><tbody>${{rows}}</tbody>`;
}}
function renderUnresolved() {{
  const rows = (MODEL.unresolved_edges || []).map(e => `<tr><td class="path">${{esc(e.source)}}</td><td class="path">${{esc(e.raw || e.target)}}</td><td>${{esc(e.kind)}}</td><td>${{e.weight||1}}</td></tr>`).join('') || '<tr><td colspan="4">No unresolved imports. Qué milagro, la ciudad funciona.</td></tr>';
  document.getElementById('unresolvedTable').innerHTML = `<thead><tr><th>Source</th><th>Target</th><th>Kind</th><th>Weight</th></tr></thead><tbody>${{rows}}</tbody>`;
}}
function init() {{
  workspace.innerHTML = '<option value="">All workspaces</option>' + unique(nodes.map(n => n.workspace)).map(w => `<option>${{esc(w)}}</option>`).join('');
  [search, workspace, kind].forEach(el => el.addEventListener('input', () => {{ renderNodeList(); drawGraph(); }}));
  reset.addEventListener('click', () => {{ search.value=''; workspace.value=''; kind.value=''; selectNode(''); renderNodeList(); drawGraph(); }});
  renderNodeList(); renderDetail(); drawGraph(); renderExternal(); renderUnresolved();
}}
init();
</script>
</body>
</html>"""


def default_output_path(output_dir: Path, title: str) -> Path:
    stamp = datetime.now().strftime("%y%m%d_%H%M%S")
    return output_dir / f"code_atlas_dependency_visual_v04_{_slug(title)}_{stamp}.html"


def command_render(args: argparse.Namespace) -> int:
    try:
        loaded = load_graph(Path(args.graph_json), Path(args.summary_json) if args.summary_json else None)
        model = build_view_model(loaded, max_visual_nodes=int(args.max_visual_nodes))
        title = _clean_text(args.title) or "Terminal de Venta Dependency Map"
        output_dir = Path(args.output_dir).expanduser().resolve()
        output_dir.mkdir(parents=True, exist_ok=True)
        output_html = Path(args.output_html).expanduser().resolve() if args.output_html else default_output_path(output_dir, title)
        if not str(output_html).lower().endswith(".html"):
            raise ValueError(f"Output path must end with .html: {output_html}")
        html_text = render_html(model, title=title)
        output_html.write_text(html_text, encoding="utf-8")
    except ValueError as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        return EXIT_BAD_INPUT
    except OSError as exc:
        print(f"[ERROR] could not write visual report: {exc}", file=sys.stderr)
        return EXIT_WRITE_FAILED

    print(json.dumps({
        "ok": True,
        "tool": TOOL_NAME,
        "version": TOOL_VERSION,
        "output_html": str(output_html),
        "graph_json": str(loaded.graph_path),
        "summary_json": str(loaded.summary_path) if loaded.summary_path else "",
        "nodes": len(model.get("nodes", [])),
        "edges": len(model.get("edges", [])),
        "visual_nodes": len(model.get("visual_nodes", [])),
        "visual_edges": len(model.get("visual_edges", [])),
    }, ensure_ascii=False, indent=2))
    return EXIT_OK


def command_verify(args: argparse.Namespace) -> int:
    try:
        loaded = load_graph(Path(args.graph_json), Path(args.summary_json) if args.summary_json else None)
        model = build_view_model(loaded, max_visual_nodes=int(args.max_visual_nodes))
    except ValueError as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        return EXIT_BAD_INPUT

    failures: list[str] = []
    nodes = model.get("nodes", [])
    edges = model.get("edges", [])
    unresolved = model.get("unresolved_edges", [])
    if not nodes:
        failures.append("graph has no nodes")
    if not edges:
        failures.append("graph has no edges")
    unresolved_weight = int(model.get("unresolved_weight") or len(unresolved))
    if unresolved_weight > int(args.max_unresolved):
        failures.append(f"unresolved edges {unresolved_weight} > allowed {args.max_unresolved}")
    for prefix in args.forbid_source_prefix or []:
        bad = [e for e in edges if _clean_text(e.get("source")).removeprefix("file:").startswith(prefix)]
        if bad:
            failures.append(f"forbidden source prefix {prefix!r} appeared {len(bad)} times")
    if args.expect_graph_version:
        got = _clean_text(model.get("graph_version"))
        if got != args.expect_graph_version:
            failures.append(f"graph version {got!r} != expected {args.expect_graph_version!r}")

    result = {
        "ok": not failures,
        "tool": TOOL_NAME,
        "version": TOOL_VERSION,
        "graph_version": model.get("graph_version"),
        "nodes": len(nodes),
        "edges": len(edges),
        "unresolved_edges": unresolved_weight,
        "unresolved_unique_edges": len(unresolved),
        "failures": failures,
    }
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return EXIT_OK if not failures else EXIT_VERIFY_FAILED


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="code_atlas_dependency_visual_v04.py",
        description="Render an offline visual HTML view from Code Atlas dependency consumer graph JSON.",
        epilog=(
            "Examples:\n"
            "  python code_atlas_dependency_visual_v04.py render --graph-json F:\\descargasf\\graph.json --summary-json F:\\descargasf\\summary.json --output-dir F:\\descargasf\n"
            "  python code_atlas_dependency_visual_v04.py verify --graph-json F:\\descargasf\\graph.json --max-unresolved 3 --forbid-source-prefix tools/prisma-salvage"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = parser.add_subparsers(dest="command", required=True)

    render = sub.add_parser("render", help="Generate a standalone HTML visual report.")
    render.add_argument("--graph-json", required=True, help="Graph JSON generated by Code Atlas dependency consumer V03.1.")
    render.add_argument("--summary-json", default="", help="Optional summary JSON generated by Code Atlas dependency consumer V03.1.")
    render.add_argument("--output-dir", required=True, help="Directory where the HTML visual report will be written.")
    render.add_argument("--output-html", default="", help="Optional exact .html output path.")
    render.add_argument("--title", default="Terminal de Venta Dependency Map", help="Human-readable report title.")
    render.add_argument("--max-visual-nodes", type=int, default=DEFAULT_MAX_VISUAL_NODES, help="Max nodes shown in the canvas preview.")
    render.set_defaults(func=command_render)

    verify = sub.add_parser("verify", help="Validate a graph JSON before rendering or UI integration.")
    verify.add_argument("--graph-json", required=True, help="Graph JSON generated by Code Atlas dependency consumer V03.1.")
    verify.add_argument("--summary-json", default="", help="Optional summary JSON.")
    verify.add_argument("--max-unresolved", type=int, default=3, help="Maximum allowed unresolved edges.")
    verify.add_argument("--forbid-source-prefix", action="append", default=[], help="Reject edges whose source path starts with this prefix. Repeatable.")
    verify.add_argument("--expect-graph-version", default="3.1.0", help="Expected graph JSON version.")
    verify.add_argument("--max-visual-nodes", type=int, default=DEFAULT_MAX_VISUAL_NODES, help="Max nodes used for preview model during verification.")
    verify.set_defaults(func=command_verify)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
