from __future__ import annotations

import json
import platform
import subprocess
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

from .paths import GuardianPaths
from .policy import GuardianPolicy
from .state_store import StateStore, utc_now_iso


BOOT_TASK_NAME = "HITECH-EngineGuardian-Boot"
PULSE_TASK_NAME = "HITECH-EngineGuardian-Pulse"
LEGACY_TASK_NAMES = [
    "HITECH-Cloudflared-TunnelGuard",
    "HITECH-Cloudflared-PublicHealth",
]


@dataclass(frozen=True)
class SchedulerTaskSpec:
    name: str
    reason: str
    startup_delay_seconds: int
    repetition_minutes: int | None = None

    def action_arguments(self, python_path: str, cli_path: Path) -> str:
        return f'"{cli_path}" cycle --reason {self.reason}'

    def xml(self, python_path: str, cli_path: Path, working_directory: Path) -> str:
        repetition_xml = ""
        if self.repetition_minutes:
            repetition_xml = (
                "<Repetition>"
                f"<Interval>PT{self.repetition_minutes}M</Interval>"
                "<Duration>P1D</Duration>"
                "<StopAtDurationEnd>false</StopAtDurationEnd>"
                "</Repetition>"
            )
        args = self.action_arguments(python_path, cli_path)
        delay = f"PT{self.startup_delay_seconds}S"
        return f'''<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Author>Engine Guardian</Author>
    <Description>{self.name} generated by engine_guardian scheduler.py</Description>
  </RegistrationInfo>
  <Triggers>
    <BootTrigger>
      <Enabled>true</Enabled>
      <Delay>{delay}</Delay>
      {repetition_xml}
    </BootTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>S-1-5-18</UserId>
      <RunLevel>HighestAvailable</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>false</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT30M</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>{python_path}</Command>
      <Arguments>{args}</Arguments>
      <WorkingDirectory>{working_directory}</WorkingDirectory>
    </Exec>
  </Actions>
</Task>
'''


class SchedulerManager:
    def __init__(self, paths: GuardianPaths, policy: GuardianPolicy, state_store: StateStore) -> None:
        self.paths = paths
        self.policy = policy
        self.state_store = state_store

    def _resolved_tools(self) -> Dict[str, Any]:
        return self.state_store.read_json(self.state_store.resolved_tools_path, {})

    def _python(self) -> str | None:
        return self._resolved_tools().get("python", {}).get("path")

    def _powershell(self) -> str | None:
        tools = self._resolved_tools()
        return tools.get("pwsh", {}).get("path") or tools.get("powershell", {}).get("path")

    def _run(self, cmd: List[str], *, timeout: int = 90) -> Dict[str, Any]:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
        return {
            "command": cmd,
            "returncode": result.returncode,
            "stdout": result.stdout[-4000:],
            "stderr": result.stderr[-4000:],
        }

    def _task_specifications(self) -> List[SchedulerTaskSpec]:
        return [
            SchedulerTaskSpec(
                name=BOOT_TASK_NAME,
                reason="boot",
                startup_delay_seconds=self.policy.startup_delay_seconds,
                repetition_minutes=None,
            ),
            SchedulerTaskSpec(
                name=PULSE_TASK_NAME,
                reason="pulse",
                startup_delay_seconds=self.policy.startup_delay_seconds,
                repetition_minutes=self.policy.pulse_interval_minutes,
            ),
        ]

    def _task_xml_path(self, task_name: str) -> Path:
        safe_name = task_name.replace(" ", "_")
        return self.paths.install_dir / f"{safe_name}.xml"

    def build_contract(self) -> Dict[str, Any]:
        python_path = self._python()
        cli_path = self.paths.python_cli_path
        if not python_path:
            raise RuntimeError("Python interpreter is not resolved. Run bootstrap first.")
        specs = []
        for spec in self._task_specifications():
            xml_text = spec.xml(python_path=python_path, cli_path=cli_path, working_directory=self.paths.repo_root)
            xml_path = self._task_xml_path(spec.name)
            xml_path.write_text(xml_text, encoding="utf-16")
            specs.append(
                {
                    "task_name": spec.name,
                    "reason": spec.reason,
                    "trigger": "AtStartup",
                    "delay_seconds": spec.startup_delay_seconds,
                    "run_as": "SYSTEM",
                    "run_level": "HighestAvailable",
                    "python_path": python_path,
                    "cli_path": str(cli_path),
                    "runtime_root": str(self.paths.runtime_root),
                    "repetition_minutes": spec.repetition_minutes,
                    "xml_path": str(xml_path),
                }
            )
        return {
            "generated_at_utc": utc_now_iso(),
            "contract_version": "engine_guardian_scheduler_v3",
            "os": platform.system(),
            "tasks": specs,
        }

    def _query_task(self, name: str) -> Dict[str, Any]:
        shell = self._powershell()
        if platform.system() != "Windows" or not shell:
            return {
                "task_name": name,
                "exists": False,
                "mode": "preview_only",
                "reason": "Windows ScheduledTasks inspection is unavailable in current environment.",
            }
        command = [
            shell,
            "-NoProfile",
            "-Command",
            (
                f"$task = Get-ScheduledTask -TaskName '{name}' -ErrorAction SilentlyContinue; "
                "if ($null -eq $task) { exit 1 } "
                "$info = Get-ScheduledTaskInfo -TaskName '" + name + "'; "
                "$task | ConvertTo-Json -Depth 6"
            ),
        ]
        payload = self._run(command, timeout=30)
        payload["task_name"] = name
        payload["exists"] = payload["returncode"] == 0
        return payload

    def install_scheduler(self, *, apply: bool = True) -> Dict[str, Any]:
        contract = self.build_contract()
        shell = self._powershell()
        tasks_output = []
        install_failures: List[Dict[str, Any]] = []
        for spec in contract["tasks"]:
            xml_path = Path(spec["xml_path"])
            task_result = {
                "task_name": spec["task_name"],
                "reason": spec["reason"],
                "xml_path": str(xml_path),
                "query_before": self._query_task(spec["task_name"]),
            }
            if apply and platform.system() == "Windows" and shell:
                register_cmd = [
                    shell,
                    "-NoProfile",
                    "-Command",
                    (
                        "$null = Register-ScheduledTask "
                        f"-TaskName '{spec['task_name']}' "
                        f"-Xml (Get-Content -LiteralPath '{xml_path}' -Raw) "
                        "-Force"
                    ),
                ]
                task_result["install"] = self._run(register_cmd, timeout=60)
            else:
                task_result["install"] = {
                    "command": [],
                    "returncode": 0,
                    "stdout": "",
                    "stderr": "",
                    "mode": "preview_only" if not apply else "preview_only_non_windows",
                }
            task_result["query_after"] = self._query_task(spec["task_name"])
            if apply and platform.system() == "Windows":
                install_return = int(task_result["install"].get("returncode", 1))
                exists_after = bool(task_result["query_after"].get("exists"))
                task_result["installed"] = install_return == 0 and exists_after
                if not task_result["installed"]:
                    install_failures.append(
                        {
                            "task_name": spec["task_name"],
                            "install_returncode": install_return,
                            "install_stderr": task_result["install"].get("stderr", ""),
                            "query_exists_after": exists_after,
                        }
                    )
            else:
                task_result["installed"] = None
            tasks_output.append(task_result)
        mode = "apply" if apply and platform.system() == "Windows" else "preview"
        ok = True
        if mode == "apply":
            ok = len(install_failures) == 0
        result = {
            "timestamp_utc": utc_now_iso(),
            "mode": mode,
            "status": "ok" if ok else "error",
            "ok": ok,
            "contract": contract,
            "tasks": tasks_output,
            "install_failures": install_failures,
        }
        self.state_store.write_json(self.paths.reports_dir / "scheduler_install_latest.json", result)
        return result

    def export_and_disable_legacy_cloudflare_tasks(self, *, apply: bool = False) -> Dict[str, Any]:
        shell = self._powershell()
        reports = []
        backups = []
        disabled = []
        for task_name in LEGACY_TASK_NAMES:
            stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
            task_backup = self.paths.backups_dir / f"{task_name}_{stamp}.xml"
            query = self._query_task(task_name)
            report: Dict[str, Any] = {
                "task_name": task_name,
                "query": query,
                "backup_path": str(task_backup),
                "backup": None,
                "disable": None,
                "mode": "apply" if apply else "preview",
            }
            if query.get("exists") and shell and platform.system() == "Windows":
                backup_cmd = [
                    shell,
                    "-NoProfile",
                    "-Command",
                    (
                        f"Export-ScheduledTask -TaskName '{task_name}' | "
                        f"Set-Content -LiteralPath '{task_backup}' -Encoding UTF8"
                    ),
                ]
                report["backup"] = self._run(backup_cmd, timeout=60)
                backups.append(str(task_backup))
                if apply:
                    disable_cmd = [
                        shell,
                        "-NoProfile",
                        "-Command",
                        f"Disable-ScheduledTask -TaskName '{task_name}' -ErrorAction SilentlyContinue",
                    ]
                    report["disable"] = self._run(disable_cmd, timeout=60)
                    if report["disable"].get("returncode") == 0:
                        disabled.append(task_name)
            else:
                report["backup"] = {
                    "command": [],
                    "returncode": 0,
                    "stdout": "",
                    "stderr": "",
                    "mode": "preview_only",
                }
                report["disable"] = {
                    "command": [],
                    "returncode": 0,
                    "stdout": "",
                    "stderr": "",
                    "mode": "preview_only_not_applied",
                }
            reports.append(report)
        result = {
            "timestamp_utc": utc_now_iso(),
            "mode": "apply" if apply and platform.system() == "Windows" else "preview",
            "backups": backups,
            "disabled": disabled,
            "legacy_tasks": reports,
            "note": "Legacy tasks are exported and can be disabled, but they are not deleted.",
        }
        self.state_store.write_json(self.paths.reports_dir / "legacy_cloudflare_task_cutover_latest.json", result)
        return result

    def status(self) -> Dict[str, Any]:
        return {
            "timestamp_utc": utc_now_iso(),
            "boot_task": self._query_task(BOOT_TASK_NAME),
            "pulse_task": self._query_task(PULSE_TASK_NAME),
            "legacy_tasks": [self._query_task(name) for name in LEGACY_TASK_NAMES],
        }
