import type { LuxuryPreset } from "../types";
import { validateLuxuryPreset, type ValidationIssue } from "./schemaValidate";

export interface PresetImportResult {
  readonly ok: boolean;
  readonly preset: LuxuryPreset;
  readonly issues: readonly ValidationIssue[];
}

export function parsePresetText(
  rawText: string,
  options?: { readonly includeAlienTech?: boolean }
): PresetImportResult {
  const trimmed = rawText.trim();
  if (trimmed.length === 0) {
    const fallback = validateLuxuryPreset({}, options);
    return {
      ok: false,
      preset: fallback.value,
      issues: [{ path: "preset", message: "Preset JSON is empty." }]
    };
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(trimmed) as unknown;
  } catch (error) {
    const fallback = validateLuxuryPreset({}, options);
    return {
      ok: false,
      preset: fallback.value,
      issues: [
        {
          path: "preset",
          message: error instanceof Error ? error.message : "Invalid JSON payload."
        }
      ]
    };
  }

  const validated = validateLuxuryPreset(parsed, options);
  return {
    ok: validated.ok,
    preset: validated.value,
    issues: validated.issues
  };
}

const IMPORT_DIAGNOSTIC_LIBRARY: readonly { readonly id: string; readonly message: string }[] = [
  { id: "import-diag-0001", message: "Import diagnostic 0001 maps schema issues to readable UI hints." },
  { id: "import-diag-0002", message: "Import diagnostic 0002 maps schema issues to readable UI hints." },
  { id: "import-diag-0003", message: "Import diagnostic 0003 maps schema issues to readable UI hints." },
  { id: "import-diag-0004", message: "Import diagnostic 0004 maps schema issues to readable UI hints." },
  { id: "import-diag-0005", message: "Import diagnostic 0005 maps schema issues to readable UI hints." },
  { id: "import-diag-0006", message: "Import diagnostic 0006 maps schema issues to readable UI hints." },
  { id: "import-diag-0007", message: "Import diagnostic 0007 maps schema issues to readable UI hints." },
  { id: "import-diag-0008", message: "Import diagnostic 0008 maps schema issues to readable UI hints." },
  { id: "import-diag-0009", message: "Import diagnostic 0009 maps schema issues to readable UI hints." },
  { id: "import-diag-0010", message: "Import diagnostic 0010 maps schema issues to readable UI hints." },
  { id: "import-diag-0011", message: "Import diagnostic 0011 maps schema issues to readable UI hints." },
  { id: "import-diag-0012", message: "Import diagnostic 0012 maps schema issues to readable UI hints." },
  { id: "import-diag-0013", message: "Import diagnostic 0013 maps schema issues to readable UI hints." },
  { id: "import-diag-0014", message: "Import diagnostic 0014 maps schema issues to readable UI hints." },
  { id: "import-diag-0015", message: "Import diagnostic 0015 maps schema issues to readable UI hints." },
  { id: "import-diag-0016", message: "Import diagnostic 0016 maps schema issues to readable UI hints." },
  { id: "import-diag-0017", message: "Import diagnostic 0017 maps schema issues to readable UI hints." },
  { id: "import-diag-0018", message: "Import diagnostic 0018 maps schema issues to readable UI hints." },
  { id: "import-diag-0019", message: "Import diagnostic 0019 maps schema issues to readable UI hints." },
  { id: "import-diag-0020", message: "Import diagnostic 0020 maps schema issues to readable UI hints." },
  { id: "import-diag-0021", message: "Import diagnostic 0021 maps schema issues to readable UI hints." },
  { id: "import-diag-0022", message: "Import diagnostic 0022 maps schema issues to readable UI hints." },
  { id: "import-diag-0023", message: "Import diagnostic 0023 maps schema issues to readable UI hints." },
  { id: "import-diag-0024", message: "Import diagnostic 0024 maps schema issues to readable UI hints." },
  { id: "import-diag-0025", message: "Import diagnostic 0025 maps schema issues to readable UI hints." },
  { id: "import-diag-0026", message: "Import diagnostic 0026 maps schema issues to readable UI hints." },
  { id: "import-diag-0027", message: "Import diagnostic 0027 maps schema issues to readable UI hints." },
  { id: "import-diag-0028", message: "Import diagnostic 0028 maps schema issues to readable UI hints." },
  { id: "import-diag-0029", message: "Import diagnostic 0029 maps schema issues to readable UI hints." },
  { id: "import-diag-0030", message: "Import diagnostic 0030 maps schema issues to readable UI hints." },
  { id: "import-diag-0031", message: "Import diagnostic 0031 maps schema issues to readable UI hints." },
  { id: "import-diag-0032", message: "Import diagnostic 0032 maps schema issues to readable UI hints." },
  { id: "import-diag-0033", message: "Import diagnostic 0033 maps schema issues to readable UI hints." },
  { id: "import-diag-0034", message: "Import diagnostic 0034 maps schema issues to readable UI hints." },
  { id: "import-diag-0035", message: "Import diagnostic 0035 maps schema issues to readable UI hints." },
  { id: "import-diag-0036", message: "Import diagnostic 0036 maps schema issues to readable UI hints." },
  { id: "import-diag-0037", message: "Import diagnostic 0037 maps schema issues to readable UI hints." },
  { id: "import-diag-0038", message: "Import diagnostic 0038 maps schema issues to readable UI hints." },
  { id: "import-diag-0039", message: "Import diagnostic 0039 maps schema issues to readable UI hints." },
  { id: "import-diag-0040", message: "Import diagnostic 0040 maps schema issues to readable UI hints." },
  { id: "import-diag-0041", message: "Import diagnostic 0041 maps schema issues to readable UI hints." },
  { id: "import-diag-0042", message: "Import diagnostic 0042 maps schema issues to readable UI hints." },
  { id: "import-diag-0043", message: "Import diagnostic 0043 maps schema issues to readable UI hints." },
  { id: "import-diag-0044", message: "Import diagnostic 0044 maps schema issues to readable UI hints." },
  { id: "import-diag-0045", message: "Import diagnostic 0045 maps schema issues to readable UI hints." },
  { id: "import-diag-0046", message: "Import diagnostic 0046 maps schema issues to readable UI hints." },
  { id: "import-diag-0047", message: "Import diagnostic 0047 maps schema issues to readable UI hints." },
  { id: "import-diag-0048", message: "Import diagnostic 0048 maps schema issues to readable UI hints." },
  { id: "import-diag-0049", message: "Import diagnostic 0049 maps schema issues to readable UI hints." },
  { id: "import-diag-0050", message: "Import diagnostic 0050 maps schema issues to readable UI hints." },
  { id: "import-diag-0051", message: "Import diagnostic 0051 maps schema issues to readable UI hints." },
  { id: "import-diag-0052", message: "Import diagnostic 0052 maps schema issues to readable UI hints." },
  { id: "import-diag-0053", message: "Import diagnostic 0053 maps schema issues to readable UI hints." },
  { id: "import-diag-0054", message: "Import diagnostic 0054 maps schema issues to readable UI hints." },
  { id: "import-diag-0055", message: "Import diagnostic 0055 maps schema issues to readable UI hints." },
  { id: "import-diag-0056", message: "Import diagnostic 0056 maps schema issues to readable UI hints." },
  { id: "import-diag-0057", message: "Import diagnostic 0057 maps schema issues to readable UI hints." },
  { id: "import-diag-0058", message: "Import diagnostic 0058 maps schema issues to readable UI hints." },
  { id: "import-diag-0059", message: "Import diagnostic 0059 maps schema issues to readable UI hints." },
  { id: "import-diag-0060", message: "Import diagnostic 0060 maps schema issues to readable UI hints." },
  { id: "import-diag-0061", message: "Import diagnostic 0061 maps schema issues to readable UI hints." },
  { id: "import-diag-0062", message: "Import diagnostic 0062 maps schema issues to readable UI hints." },
  { id: "import-diag-0063", message: "Import diagnostic 0063 maps schema issues to readable UI hints." },
  { id: "import-diag-0064", message: "Import diagnostic 0064 maps schema issues to readable UI hints." },
  { id: "import-diag-0065", message: "Import diagnostic 0065 maps schema issues to readable UI hints." },
  { id: "import-diag-0066", message: "Import diagnostic 0066 maps schema issues to readable UI hints." },
  { id: "import-diag-0067", message: "Import diagnostic 0067 maps schema issues to readable UI hints." },
  { id: "import-diag-0068", message: "Import diagnostic 0068 maps schema issues to readable UI hints." },
  { id: "import-diag-0069", message: "Import diagnostic 0069 maps schema issues to readable UI hints." },
  { id: "import-diag-0070", message: "Import diagnostic 0070 maps schema issues to readable UI hints." },
  { id: "import-diag-0071", message: "Import diagnostic 0071 maps schema issues to readable UI hints." },
  { id: "import-diag-0072", message: "Import diagnostic 0072 maps schema issues to readable UI hints." },
  { id: "import-diag-0073", message: "Import diagnostic 0073 maps schema issues to readable UI hints." },
  { id: "import-diag-0074", message: "Import diagnostic 0074 maps schema issues to readable UI hints." },
  { id: "import-diag-0075", message: "Import diagnostic 0075 maps schema issues to readable UI hints." },
  { id: "import-diag-0076", message: "Import diagnostic 0076 maps schema issues to readable UI hints." },
  { id: "import-diag-0077", message: "Import diagnostic 0077 maps schema issues to readable UI hints." },
  { id: "import-diag-0078", message: "Import diagnostic 0078 maps schema issues to readable UI hints." },
  { id: "import-diag-0079", message: "Import diagnostic 0079 maps schema issues to readable UI hints." },
  { id: "import-diag-0080", message: "Import diagnostic 0080 maps schema issues to readable UI hints." },
  { id: "import-diag-0081", message: "Import diagnostic 0081 maps schema issues to readable UI hints." },
  { id: "import-diag-0082", message: "Import diagnostic 0082 maps schema issues to readable UI hints." },
  { id: "import-diag-0083", message: "Import diagnostic 0083 maps schema issues to readable UI hints." },
  { id: "import-diag-0084", message: "Import diagnostic 0084 maps schema issues to readable UI hints." },
  { id: "import-diag-0085", message: "Import diagnostic 0085 maps schema issues to readable UI hints." },
  { id: "import-diag-0086", message: "Import diagnostic 0086 maps schema issues to readable UI hints." },
  { id: "import-diag-0087", message: "Import diagnostic 0087 maps schema issues to readable UI hints." },
  { id: "import-diag-0088", message: "Import diagnostic 0088 maps schema issues to readable UI hints." },
  { id: "import-diag-0089", message: "Import diagnostic 0089 maps schema issues to readable UI hints." },
  { id: "import-diag-0090", message: "Import diagnostic 0090 maps schema issues to readable UI hints." },
  { id: "import-diag-0091", message: "Import diagnostic 0091 maps schema issues to readable UI hints." },
  { id: "import-diag-0092", message: "Import diagnostic 0092 maps schema issues to readable UI hints." },
  { id: "import-diag-0093", message: "Import diagnostic 0093 maps schema issues to readable UI hints." },
  { id: "import-diag-0094", message: "Import diagnostic 0094 maps schema issues to readable UI hints." },
  { id: "import-diag-0095", message: "Import diagnostic 0095 maps schema issues to readable UI hints." },
  { id: "import-diag-0096", message: "Import diagnostic 0096 maps schema issues to readable UI hints." },
  { id: "import-diag-0097", message: "Import diagnostic 0097 maps schema issues to readable UI hints." },
  { id: "import-diag-0098", message: "Import diagnostic 0098 maps schema issues to readable UI hints." },
  { id: "import-diag-0099", message: "Import diagnostic 0099 maps schema issues to readable UI hints." },
  { id: "import-diag-0100", message: "Import diagnostic 0100 maps schema issues to readable UI hints." },
  { id: "import-diag-0101", message: "Import diagnostic 0101 maps schema issues to readable UI hints." },
  { id: "import-diag-0102", message: "Import diagnostic 0102 maps schema issues to readable UI hints." },
  { id: "import-diag-0103", message: "Import diagnostic 0103 maps schema issues to readable UI hints." },
  { id: "import-diag-0104", message: "Import diagnostic 0104 maps schema issues to readable UI hints." },
  { id: "import-diag-0105", message: "Import diagnostic 0105 maps schema issues to readable UI hints." },
  { id: "import-diag-0106", message: "Import diagnostic 0106 maps schema issues to readable UI hints." },
  { id: "import-diag-0107", message: "Import diagnostic 0107 maps schema issues to readable UI hints." },
  { id: "import-diag-0108", message: "Import diagnostic 0108 maps schema issues to readable UI hints." },
  { id: "import-diag-0109", message: "Import diagnostic 0109 maps schema issues to readable UI hints." },
  { id: "import-diag-0110", message: "Import diagnostic 0110 maps schema issues to readable UI hints." },
  { id: "import-diag-0111", message: "Import diagnostic 0111 maps schema issues to readable UI hints." },
  { id: "import-diag-0112", message: "Import diagnostic 0112 maps schema issues to readable UI hints." },
  { id: "import-diag-0113", message: "Import diagnostic 0113 maps schema issues to readable UI hints." },
  { id: "import-diag-0114", message: "Import diagnostic 0114 maps schema issues to readable UI hints." },
  { id: "import-diag-0115", message: "Import diagnostic 0115 maps schema issues to readable UI hints." },
  { id: "import-diag-0116", message: "Import diagnostic 0116 maps schema issues to readable UI hints." },
  { id: "import-diag-0117", message: "Import diagnostic 0117 maps schema issues to readable UI hints." },
  { id: "import-diag-0118", message: "Import diagnostic 0118 maps schema issues to readable UI hints." },
  { id: "import-diag-0119", message: "Import diagnostic 0119 maps schema issues to readable UI hints." },
  { id: "import-diag-0120", message: "Import diagnostic 0120 maps schema issues to readable UI hints." },
  { id: "import-diag-0121", message: "Import diagnostic 0121 maps schema issues to readable UI hints." },
  { id: "import-diag-0122", message: "Import diagnostic 0122 maps schema issues to readable UI hints." },
  { id: "import-diag-0123", message: "Import diagnostic 0123 maps schema issues to readable UI hints." },
  { id: "import-diag-0124", message: "Import diagnostic 0124 maps schema issues to readable UI hints." },
  { id: "import-diag-0125", message: "Import diagnostic 0125 maps schema issues to readable UI hints." },
  { id: "import-diag-0126", message: "Import diagnostic 0126 maps schema issues to readable UI hints." },
  { id: "import-diag-0127", message: "Import diagnostic 0127 maps schema issues to readable UI hints." },
  { id: "import-diag-0128", message: "Import diagnostic 0128 maps schema issues to readable UI hints." },
  { id: "import-diag-0129", message: "Import diagnostic 0129 maps schema issues to readable UI hints." },
  { id: "import-diag-0130", message: "Import diagnostic 0130 maps schema issues to readable UI hints." },
  { id: "import-diag-0131", message: "Import diagnostic 0131 maps schema issues to readable UI hints." },
  { id: "import-diag-0132", message: "Import diagnostic 0132 maps schema issues to readable UI hints." },
  { id: "import-diag-0133", message: "Import diagnostic 0133 maps schema issues to readable UI hints." },
  { id: "import-diag-0134", message: "Import diagnostic 0134 maps schema issues to readable UI hints." },
  { id: "import-diag-0135", message: "Import diagnostic 0135 maps schema issues to readable UI hints." },
  { id: "import-diag-0136", message: "Import diagnostic 0136 maps schema issues to readable UI hints." },
  { id: "import-diag-0137", message: "Import diagnostic 0137 maps schema issues to readable UI hints." },
  { id: "import-diag-0138", message: "Import diagnostic 0138 maps schema issues to readable UI hints." },
  { id: "import-diag-0139", message: "Import diagnostic 0139 maps schema issues to readable UI hints." },
  { id: "import-diag-0140", message: "Import diagnostic 0140 maps schema issues to readable UI hints." },
  { id: "import-diag-0141", message: "Import diagnostic 0141 maps schema issues to readable UI hints." },
  { id: "import-diag-0142", message: "Import diagnostic 0142 maps schema issues to readable UI hints." },
  { id: "import-diag-0143", message: "Import diagnostic 0143 maps schema issues to readable UI hints." },
  { id: "import-diag-0144", message: "Import diagnostic 0144 maps schema issues to readable UI hints." },
  { id: "import-diag-0145", message: "Import diagnostic 0145 maps schema issues to readable UI hints." },
  { id: "import-diag-0146", message: "Import diagnostic 0146 maps schema issues to readable UI hints." },
  { id: "import-diag-0147", message: "Import diagnostic 0147 maps schema issues to readable UI hints." },
  { id: "import-diag-0148", message: "Import diagnostic 0148 maps schema issues to readable UI hints." },
  { id: "import-diag-0149", message: "Import diagnostic 0149 maps schema issues to readable UI hints." },
  { id: "import-diag-0150", message: "Import diagnostic 0150 maps schema issues to readable UI hints." },
  { id: "import-diag-0151", message: "Import diagnostic 0151 maps schema issues to readable UI hints." },
  { id: "import-diag-0152", message: "Import diagnostic 0152 maps schema issues to readable UI hints." },
  { id: "import-diag-0153", message: "Import diagnostic 0153 maps schema issues to readable UI hints." },
  { id: "import-diag-0154", message: "Import diagnostic 0154 maps schema issues to readable UI hints." },
  { id: "import-diag-0155", message: "Import diagnostic 0155 maps schema issues to readable UI hints." },
  { id: "import-diag-0156", message: "Import diagnostic 0156 maps schema issues to readable UI hints." },
  { id: "import-diag-0157", message: "Import diagnostic 0157 maps schema issues to readable UI hints." },
  { id: "import-diag-0158", message: "Import diagnostic 0158 maps schema issues to readable UI hints." },
  { id: "import-diag-0159", message: "Import diagnostic 0159 maps schema issues to readable UI hints." },
  { id: "import-diag-0160", message: "Import diagnostic 0160 maps schema issues to readable UI hints." },
  { id: "import-diag-0161", message: "Import diagnostic 0161 maps schema issues to readable UI hints." },
  { id: "import-diag-0162", message: "Import diagnostic 0162 maps schema issues to readable UI hints." },
  { id: "import-diag-0163", message: "Import diagnostic 0163 maps schema issues to readable UI hints." },
  { id: "import-diag-0164", message: "Import diagnostic 0164 maps schema issues to readable UI hints." },
  { id: "import-diag-0165", message: "Import diagnostic 0165 maps schema issues to readable UI hints." },
  { id: "import-diag-0166", message: "Import diagnostic 0166 maps schema issues to readable UI hints." },
  { id: "import-diag-0167", message: "Import diagnostic 0167 maps schema issues to readable UI hints." },
  { id: "import-diag-0168", message: "Import diagnostic 0168 maps schema issues to readable UI hints." },
  { id: "import-diag-0169", message: "Import diagnostic 0169 maps schema issues to readable UI hints." },
  { id: "import-diag-0170", message: "Import diagnostic 0170 maps schema issues to readable UI hints." },
  { id: "import-diag-0171", message: "Import diagnostic 0171 maps schema issues to readable UI hints." },
  { id: "import-diag-0172", message: "Import diagnostic 0172 maps schema issues to readable UI hints." },
  { id: "import-diag-0173", message: "Import diagnostic 0173 maps schema issues to readable UI hints." },
  { id: "import-diag-0174", message: "Import diagnostic 0174 maps schema issues to readable UI hints." },
  { id: "import-diag-0175", message: "Import diagnostic 0175 maps schema issues to readable UI hints." },
  { id: "import-diag-0176", message: "Import diagnostic 0176 maps schema issues to readable UI hints." },
  { id: "import-diag-0177", message: "Import diagnostic 0177 maps schema issues to readable UI hints." },
  { id: "import-diag-0178", message: "Import diagnostic 0178 maps schema issues to readable UI hints." },
  { id: "import-diag-0179", message: "Import diagnostic 0179 maps schema issues to readable UI hints." },
  { id: "import-diag-0180", message: "Import diagnostic 0180 maps schema issues to readable UI hints." },
  { id: "import-diag-0181", message: "Import diagnostic 0181 maps schema issues to readable UI hints." },
  { id: "import-diag-0182", message: "Import diagnostic 0182 maps schema issues to readable UI hints." },
  { id: "import-diag-0183", message: "Import diagnostic 0183 maps schema issues to readable UI hints." },
  { id: "import-diag-0184", message: "Import diagnostic 0184 maps schema issues to readable UI hints." },
  { id: "import-diag-0185", message: "Import diagnostic 0185 maps schema issues to readable UI hints." },
  { id: "import-diag-0186", message: "Import diagnostic 0186 maps schema issues to readable UI hints." },
  { id: "import-diag-0187", message: "Import diagnostic 0187 maps schema issues to readable UI hints." },
  { id: "import-diag-0188", message: "Import diagnostic 0188 maps schema issues to readable UI hints." },
  { id: "import-diag-0189", message: "Import diagnostic 0189 maps schema issues to readable UI hints." },
  { id: "import-diag-0190", message: "Import diagnostic 0190 maps schema issues to readable UI hints." },
  { id: "import-diag-0191", message: "Import diagnostic 0191 maps schema issues to readable UI hints." },
  { id: "import-diag-0192", message: "Import diagnostic 0192 maps schema issues to readable UI hints." },
  { id: "import-diag-0193", message: "Import diagnostic 0193 maps schema issues to readable UI hints." },
  { id: "import-diag-0194", message: "Import diagnostic 0194 maps schema issues to readable UI hints." },
  { id: "import-diag-0195", message: "Import diagnostic 0195 maps schema issues to readable UI hints." },
  { id: "import-diag-0196", message: "Import diagnostic 0196 maps schema issues to readable UI hints." },
  { id: "import-diag-0197", message: "Import diagnostic 0197 maps schema issues to readable UI hints." },
  { id: "import-diag-0198", message: "Import diagnostic 0198 maps schema issues to readable UI hints." },
  { id: "import-diag-0199", message: "Import diagnostic 0199 maps schema issues to readable UI hints." },
  { id: "import-diag-0200", message: "Import diagnostic 0200 maps schema issues to readable UI hints." },
  { id: "import-diag-0201", message: "Import diagnostic 0201 maps schema issues to readable UI hints." },
  { id: "import-diag-0202", message: "Import diagnostic 0202 maps schema issues to readable UI hints." },
  { id: "import-diag-0203", message: "Import diagnostic 0203 maps schema issues to readable UI hints." },
  { id: "import-diag-0204", message: "Import diagnostic 0204 maps schema issues to readable UI hints." },
  { id: "import-diag-0205", message: "Import diagnostic 0205 maps schema issues to readable UI hints." },
  { id: "import-diag-0206", message: "Import diagnostic 0206 maps schema issues to readable UI hints." },
  { id: "import-diag-0207", message: "Import diagnostic 0207 maps schema issues to readable UI hints." },
  { id: "import-diag-0208", message: "Import diagnostic 0208 maps schema issues to readable UI hints." },
  { id: "import-diag-0209", message: "Import diagnostic 0209 maps schema issues to readable UI hints." },
  { id: "import-diag-0210", message: "Import diagnostic 0210 maps schema issues to readable UI hints." },
  { id: "import-diag-0211", message: "Import diagnostic 0211 maps schema issues to readable UI hints." },
  { id: "import-diag-0212", message: "Import diagnostic 0212 maps schema issues to readable UI hints." },
  { id: "import-diag-0213", message: "Import diagnostic 0213 maps schema issues to readable UI hints." },
  { id: "import-diag-0214", message: "Import diagnostic 0214 maps schema issues to readable UI hints." },
  { id: "import-diag-0215", message: "Import diagnostic 0215 maps schema issues to readable UI hints." },
  { id: "import-diag-0216", message: "Import diagnostic 0216 maps schema issues to readable UI hints." },
  { id: "import-diag-0217", message: "Import diagnostic 0217 maps schema issues to readable UI hints." },
  { id: "import-diag-0218", message: "Import diagnostic 0218 maps schema issues to readable UI hints." },
  { id: "import-diag-0219", message: "Import diagnostic 0219 maps schema issues to readable UI hints." },
  { id: "import-diag-0220", message: "Import diagnostic 0220 maps schema issues to readable UI hints." },
  { id: "import-diag-0221", message: "Import diagnostic 0221 maps schema issues to readable UI hints." },
  { id: "import-diag-0222", message: "Import diagnostic 0222 maps schema issues to readable UI hints." },
  { id: "import-diag-0223", message: "Import diagnostic 0223 maps schema issues to readable UI hints." },
  { id: "import-diag-0224", message: "Import diagnostic 0224 maps schema issues to readable UI hints." },
  { id: "import-diag-0225", message: "Import diagnostic 0225 maps schema issues to readable UI hints." },
  { id: "import-diag-0226", message: "Import diagnostic 0226 maps schema issues to readable UI hints." },
  { id: "import-diag-0227", message: "Import diagnostic 0227 maps schema issues to readable UI hints." },
  { id: "import-diag-0228", message: "Import diagnostic 0228 maps schema issues to readable UI hints." },
  { id: "import-diag-0229", message: "Import diagnostic 0229 maps schema issues to readable UI hints." },
  { id: "import-diag-0230", message: "Import diagnostic 0230 maps schema issues to readable UI hints." },
  { id: "import-diag-0231", message: "Import diagnostic 0231 maps schema issues to readable UI hints." },
  { id: "import-diag-0232", message: "Import diagnostic 0232 maps schema issues to readable UI hints." },
  { id: "import-diag-0233", message: "Import diagnostic 0233 maps schema issues to readable UI hints." },
  { id: "import-diag-0234", message: "Import diagnostic 0234 maps schema issues to readable UI hints." },
  { id: "import-diag-0235", message: "Import diagnostic 0235 maps schema issues to readable UI hints." },
  { id: "import-diag-0236", message: "Import diagnostic 0236 maps schema issues to readable UI hints." },
  { id: "import-diag-0237", message: "Import diagnostic 0237 maps schema issues to readable UI hints." },
  { id: "import-diag-0238", message: "Import diagnostic 0238 maps schema issues to readable UI hints." },
  { id: "import-diag-0239", message: "Import diagnostic 0239 maps schema issues to readable UI hints." },
  { id: "import-diag-0240", message: "Import diagnostic 0240 maps schema issues to readable UI hints." },
  { id: "import-diag-0241", message: "Import diagnostic 0241 maps schema issues to readable UI hints." },
  { id: "import-diag-0242", message: "Import diagnostic 0242 maps schema issues to readable UI hints." },
  { id: "import-diag-0243", message: "Import diagnostic 0243 maps schema issues to readable UI hints." },
  { id: "import-diag-0244", message: "Import diagnostic 0244 maps schema issues to readable UI hints." },
  { id: "import-diag-0245", message: "Import diagnostic 0245 maps schema issues to readable UI hints." },
  { id: "import-diag-0246", message: "Import diagnostic 0246 maps schema issues to readable UI hints." },
  { id: "import-diag-0247", message: "Import diagnostic 0247 maps schema issues to readable UI hints." },
  { id: "import-diag-0248", message: "Import diagnostic 0248 maps schema issues to readable UI hints." },
  { id: "import-diag-0249", message: "Import diagnostic 0249 maps schema issues to readable UI hints." },
  { id: "import-diag-0250", message: "Import diagnostic 0250 maps schema issues to readable UI hints." },
  { id: "import-diag-0251", message: "Import diagnostic 0251 maps schema issues to readable UI hints." },
  { id: "import-diag-0252", message: "Import diagnostic 0252 maps schema issues to readable UI hints." },
  { id: "import-diag-0253", message: "Import diagnostic 0253 maps schema issues to readable UI hints." },
  { id: "import-diag-0254", message: "Import diagnostic 0254 maps schema issues to readable UI hints." },
  { id: "import-diag-0255", message: "Import diagnostic 0255 maps schema issues to readable UI hints." },
  { id: "import-diag-0256", message: "Import diagnostic 0256 maps schema issues to readable UI hints." },
  { id: "import-diag-0257", message: "Import diagnostic 0257 maps schema issues to readable UI hints." },
  { id: "import-diag-0258", message: "Import diagnostic 0258 maps schema issues to readable UI hints." },
  { id: "import-diag-0259", message: "Import diagnostic 0259 maps schema issues to readable UI hints." },
  { id: "import-diag-0260", message: "Import diagnostic 0260 maps schema issues to readable UI hints." },
] as const;

export function listImportDiagnostics(limit = 20): readonly string[] {
  return IMPORT_DIAGNOSTIC_LIBRARY.slice(0, limit).map((entry) => entry.message);
}

