\
"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { DevConsoleSceneStudioBinding } from "../../dev-console/DevConsoleContext";
import {
  KNOWN_PITCH_ROUTES,
  LocalSceneStore,
  buildCanonicalSceneUrl,
  createDefaultSceneLibrary,
  parseSceneUrlState,
  type SceneRecord
} from "../../../lib/scene-studio";

const DEFAULT_QUERY = "debug=1&layerProfile=neutral&layers=none&motion=off";
const ROUTABLE_PITCH_ROUTES = KNOWN_PITCH_ROUTES.filter((route) => route !== "/pitch");
const KNOWN_ROUTE_SET = new Set<string>(KNOWN_PITCH_ROUTES);

function toTitleCase(value: string): string {
  return value.replace(/\b\w/g, (char) => char.toUpperCase());
}

function buildSceneTitle(route: string): string {
  const normalized = route.replace(/^\/+/, "");
  if (!normalized) {
    return "Pitch Runtime";
  }

  const parts = normalized
    .split("/")
    .filter(Boolean)
    .map((part) => part.replace(/^\d+-/, "").replace(/-/g, " ").trim())
    .filter(Boolean)
    .map(toTitleCase);

  return parts.length > 0 ? parts.join(" · ") : "Pitch Runtime";
}

function buildSceneId(route: string): string {
  const normalized = route.replace(/^\/+/, "").replace(/[^a-z0-9]+/gi, "-").replace(/^-+|-+$/g, "").toLowerCase();
  return normalized.length > 0 ? `${normalized}-neutral-desktop` : "pitch-runtime-neutral-desktop";
}

function mergeTags(tags: readonly string[] | undefined): string[] {
  return Array.from(new Set([...(tags ?? []), "pitch", "runtime", "dev-console"])).sort((left, right) =>
    left.localeCompare(right)
  );
}

function buildFallbackSceneRecord(route: string): SceneRecord {
  const urlState = parseSceneUrlState(route, DEFAULT_QUERY);
  const now = new Date().toISOString();

  return {
    schemaVersion: 2,
    id: buildSceneId(urlState.route),
    title: `${buildSceneTitle(urlState.route)} · Runtime`,
    route: urlState.route,
    query: urlState.query,
    viewport: { preset: "desktop" },
    layerProfile: urlState.layerProfile,
    layers: {
      mode: urlState.layersMode,
      layerIds: [...urlState.layerIds]
    },
    motion: urlState.motion,
    notes: "Generated fallback scene so every pitch route is selectable from the Dev Console.",
    tags: mergeTags(["coverage"]),
    createdAt: now,
    updatedAt: now
  };
}

function ensureRouteCoverage(scenes: readonly SceneRecord[]): SceneRecord[] {
  const next = [...scenes];
  const existingRoutes = new Set(next.map((scene) => parseSceneUrlState(scene.route, scene.query).route));

  for (const route of ROUTABLE_PITCH_ROUTES) {
    if (!existingRoutes.has(route)) {
      next.push(buildFallbackSceneRecord(route));
      existingRoutes.add(route);
    }
  }

  return next.sort((left, right) => left.id.localeCompare(right.id));
}

const DEFAULT_LIBRARY = ensureRouteCoverage(createDefaultSceneLibrary("2026-01-01T00:00:00.000Z"));

function findSceneCandidate(scenes: readonly SceneRecord[], route: string, query: string): SceneRecord | undefined {
  const urlState = parseSceneUrlState(route, query);
  const exact = scenes.find((scene) => scene.route === urlState.route && scene.query === urlState.query);
  if (exact) {
    return exact;
  }

  return scenes.find((scene) => scene.route === urlState.route);
}

function buildSceneRecord(route: string, query: string, base?: SceneRecord): SceneRecord {
  const urlState = parseSceneUrlState(route, query);
  const now = new Date().toISOString();

  return {
    schemaVersion: 2,
    id: base?.id ?? buildSceneId(urlState.route),
    title: base?.title ?? `${buildSceneTitle(urlState.route)} · Runtime`,
    route: urlState.route,
    query: urlState.query,
    viewport: base?.viewport ?? { preset: "desktop" },
    layerProfile: urlState.layerProfile,
    layers: {
      mode: urlState.layersMode,
      layerIds: [...urlState.layerIds]
    },
    motion: urlState.motion,
    notes: base?.notes ?? "Route-bound runtime scene generated by the pitch Dev Console binding.",
    tags: mergeTags(base?.tags),
    createdAt: base?.createdAt ?? now,
    updatedAt: now
  };
}

function buildSceneUrl(scene: SceneRecord): string {
  return buildCanonicalSceneUrl({
    route: scene.route,
    query: scene.query,
    layerProfile: scene.layerProfile,
    layersMode: scene.layers.mode,
    layerIds: scene.layers.layerIds,
    motion: scene.motion,
    debug: true
  });
}

export function PitchRouteSceneBinding() {
  const pathname = usePathname() ?? "/pitch";
  const searchParams = useSearchParams();
  const router = useRouter();
  const storeRef = useRef<LocalSceneStore | null>(null);

  const [storeReady, setStoreReady] = useState(false);
  const [scene, setScene] = useState<SceneRecord | undefined>(undefined);

  const rawQuery = useMemo(() => searchParams?.toString() ?? "", [searchParams]);
  const currentUrlState = useMemo(() => parseSceneUrlState(pathname, rawQuery), [pathname, rawQuery]);
  const currentUrl = useMemo(
    () =>
      buildCanonicalSceneUrl({
        route: currentUrlState.route,
        query: currentUrlState.query,
        layerProfile: currentUrlState.layerProfile,
        layersMode: currentUrlState.layersMode,
        layerIds: currentUrlState.layerIds,
        motion: currentUrlState.motion,
        debug: true
      }),
    [currentUrlState]
  );

  useEffect(() => {
    if (storeRef.current) {
      const store = storeRef.current;
      store.replaceAll(ensureRouteCoverage(store.list()));
      setStoreReady(true);
      return;
    }

    const store = new LocalSceneStore();
    const hydrated = store.list();
    store.replaceAll(ensureRouteCoverage(hydrated.length > 0 ? hydrated : DEFAULT_LIBRARY));
    storeRef.current = store;
    setStoreReady(true);
  }, []);

  useEffect(() => {
    if (!storeReady) {
      return;
    }

    const store = storeRef.current;
    if (!store) {
      return;
    }

    const base =
      findSceneCandidate(store.list(), pathname, rawQuery) ??
      findSceneCandidate(DEFAULT_LIBRARY, pathname, rawQuery) ??
      buildFallbackSceneRecord(pathname);

    setScene(buildSceneRecord(pathname, rawQuery, base));
  }, [pathname, rawQuery, storeReady]);

  const persistScene = useCallback((next: SceneRecord) => {
    const store = storeRef.current;
    if (!store) {
      return;
    }

    store.upsert(next);
    store.replaceAll(ensureRouteCoverage(store.list()));
  }, []);

  const navigateToScene = useCallback(
    (next: SceneRecord) => {
      if (!KNOWN_ROUTE_SET.has(next.route)) {
        return;
      }

      const nextUrl = buildSceneUrl(next);
      if (nextUrl === currentUrl) {
        return;
      }

      router.replace(nextUrl, { scroll: false });
    },
    [currentUrl, router]
  );

  const handleSceneChange = useCallback(
    (draft: SceneRecord) => {
      const normalized = buildSceneRecord(draft.route, draft.query, draft);
      setScene(normalized);
      persistScene(normalized);
      navigateToScene(normalized);
    },
    [navigateToScene, persistScene]
  );

  const resetSelectedSceneToDefaults = useCallback(() => {
    const defaultScene =
      findSceneCandidate(DEFAULT_LIBRARY, pathname, rawQuery) ??
      findSceneCandidate(DEFAULT_LIBRARY, pathname, DEFAULT_QUERY) ??
      buildFallbackSceneRecord(pathname);

    const next = buildSceneRecord(defaultScene.route ?? pathname, defaultScene.query ?? rawQuery, defaultScene);
    setScene(next);
    persistScene(next);
    navigateToScene(next);
  }, [navigateToScene, pathname, persistScene, rawQuery]);

  if (!scene) {
    return null;
  }

  return (
    <DevConsoleSceneStudioBinding
      scene={scene}
      onChange={handleSceneChange}
      onResetToDefaults={resetSelectedSceneToDefaults}
    />
  );
}
