import type { PrismaChartPassport } from "../prismaChartAtlas";
import { commonAccessibility, commonDoNotTouch, editPlaybook, knob, supportedStates, validation } from "./passportShared";

export const tabletShiftPulseStripPassport = {
  chartId: "tablet.shift-pulse-strip",
  displayName: "Shift Pulse Strip",
  shortName: "Shift Pulse",
  family: "strip",
  surface: "tablet",
  status: "partial_real",
  questionAnswered: "Can the Tablet keep operating right now?",
  primaryUser: "operator",
  routePreview: "/?chart=tablet.shift-pulse-strip",
  routeProduction: "/?chart=tablet.shift-pulse-strip",
  componentFile: "products/chart-lab/app/src/prisma-charts/components/LabEChartFrame.tsx",
  cardWrapperFile: "products/chart-lab/app/src/components/PrismaChartLabShell.tsx",
  optionBuilderFile: "shared/prisma-charts/prismaChartOptions.ts",
  optionBuilderName: "shiftPulseStripOption",
  contractFile: "shared/prisma-charts/prismaChartContracts.ts",
  contractType: "ShiftPulseBucket[]",
  adapterFile: "shared/prisma-charts/prismaChartAdapters.ts",
  adapterName: "buildTabletShiftPulseStripViewModel",
  mockFile: "shared/prisma-charts/prismaChartMocks.ts",
  mockName: "mockTabletCharts.shiftPulseStrip",
  registryFile: "shared/prisma-charts/prismaChartRegistry.ts",
  qualityModel: "PrismaChartQuality",
  visualRecipe: "stripRecipe",
  visualKnobs: [knob("segmentHeight", "Controls touch strip readability.", "22-42", "bar/line profile", "Too small hurts touch"), knob("touchTargetSize", "Keeps Tablet operational.", "44-56", "card/control layout", "Too small breaks operator flow")],
  states: supportedStates,
  interactions: ["tapFocus", "reset"],
  accessibility: commonAccessibility,
  knownRisks: ["Current safe source is the recorded runtime snapshot, not full shift history.", "The retired Tablet /prisma-pulse customer route must not be restored; this chart is inspected in Chart Lab."],
  doNotTouch: commonDoNotTouch,
  editPlaybook: editPlaybook({ visualRecipe: "stripRecipe", adapterName: "buildTabletShiftPulseStripViewModel", contractType: "ShiftPulseBucket", componentFile: "products/chart-lab/app/src/prisma-charts/components/LabEChartFrame.tsx", deckFile: "products/chart-lab/app/src/components/PrismaChartLabShell.tsx" }),
  validation: validation("/?chart=tablet.shift-pulse-strip")
} satisfies PrismaChartPassport;
