import type { PrismaChartPassport } from "../prismaChartAtlas";
import { commonAccessibility, commonDoNotTouch, editPlaybook, knob, supportedStates, validation } from "./passportShared";

export const tabletSyncOutboxStatusMatrixPassport = {
  chartId: "tablet.sync-outbox-status-matrix",
  displayName: "Sync Outbox Status Matrix",
  shortName: "Outbox Matrix",
  family: "matrix",
  surface: "tablet",
  status: "partial_real",
  questionAnswered: "What local outbox work needs attention before/after sync?",
  primaryUser: "operator",
  routePreview: "/?chart=tablet.sync-outbox-status-matrix",
  routeProduction: "/?chart=tablet.sync-outbox-status-matrix",
  componentFile: "products/chart-lab/app/src/prisma-charts/components/LabEChartFrame.tsx",
  cardWrapperFile: "products/chart-lab/app/src/components/PrismaChartLabShell.tsx",
  optionBuilderFile: "shared/prisma-charts/prismaChartOptions.ts",
  optionBuilderName: "syncOutboxMatrixOption",
  contractFile: "shared/prisma-charts/prismaChartContracts.ts",
  contractType: "SyncOutboxMatrixCell[]",
  adapterFile: "shared/prisma-charts/prismaChartAdapters.ts",
  adapterName: "buildTabletSyncOutboxStatusMatrixViewModel",
  mockFile: "shared/prisma-charts/prismaChartMocks.ts",
  mockName: "mockTabletCharts.syncOutboxStatusMatrix",
  registryFile: "shared/prisma-charts/prismaChartRegistry.ts",
  qualityModel: "PrismaChartQuality",
  visualRecipe: "matrixRecipe",
  visualKnobs: [knob("cellSize", "Controls touch cell size.", "28-44", "heatmap grid", "Too small hurts Tablet"), knob("offlineEmphasis", "Highlights blocked/offline states.", "true-false", "status palette", "Too strong can imply false criticality")],
  states: supportedStates,
  interactions: ["tapTooltip", "tapFocus", "reset"],
  accessibility: commonAccessibility,
  knownRisks: ["Item-type breakdown depends on outbox topics; unknown events remain itemType=event.", "The retired Tablet /prisma-pulse customer route must not be restored; this chart is inspected in Chart Lab."],
  doNotTouch: commonDoNotTouch,
  editPlaybook: editPlaybook({ visualRecipe: "matrixRecipe", adapterName: "buildTabletSyncOutboxStatusMatrixViewModel", contractType: "SyncOutboxMatrixCell", componentFile: "products/chart-lab/app/src/prisma-charts/components/LabEChartFrame.tsx", deckFile: "products/chart-lab/app/src/components/PrismaChartLabShell.tsx" }),
  validation: validation("/?chart=tablet.sync-outbox-status-matrix")
} satisfies PrismaChartPassport;
