// AUTO-GENERATED by prisma_pc_uiux_onepass_hotfix.

export const PC_STATUS_COPY = {
  "live": "Actualizado",
  "mock": "Demo",
  "demo": "Demo",
  "partial": "Incompleto",
  "stale": "Atrasado",
  "offline": "Sin conexión",
  "degraded": "Con problemas",
  "critical": "Crítico",
  "warning": "Requiere atención",
  "healthy": "Bien",
  "ok": "Bien",
  "error": "Con error",
  "pending": "Pendiente",
  "queued": "Pendiente",
  "failed": "Falló",
  "success": "Completado",
  "loading": "Preparando información"
} as const;

export const PC_TERM_COPY = {
  "runtime": "Sistema",
  "ingest": "Recepción de cambios",
  "payload": "Paquete de datos",
  "ack": "Confirmación",
  "dispatcher": "Envío de cambios",
  "canonical": "Base principal",
  "feature gate": "Función disponible",
  "raw": "Detalle técnico",
  "adapter": "Conector",
  "registry": "Registro interno",
  "manifest": "Resumen técnico",
  "tri-db": "Sincronización entre equipos",
  "delta": "Cambios nuevos",
  "endpoint": "Ruta técnica",
  "debug": "Diagnóstico",
  "hydration": "Carga de interfaz"
} as const;

export const PC_EMPTY_STATE_COPY = {
  defaultTitle: "No hay datos para esta vista",
  defaultBody: "Puedes cambiar filtros, actualizar o revisar el detalle técnico si esperabas información.",
  defaultAction: "Actualizar",
} as const;

export const PC_ERROR_STATE_COPY = {
  defaultTitle: "No se pudo cargar esta información",
  defaultBody: "Intenta actualizar. Si continúa, revisa el detalle técnico.",
  defaultAction: "Reintentar",
} as const;

export function translatePcStatus(status: string): string {
  const key = status.toLowerCase() as keyof typeof PC_STATUS_COPY;
  return PC_STATUS_COPY[key] ?? status;
}

export function translatePcTerm(term: string): string {
  const key = term.toLowerCase() as keyof typeof PC_TERM_COPY;
  return PC_TERM_COPY[key] ?? term;
}
