// AUTO-GENERATED by prisma_pc_uiux_onepass_hotfix.

export type PcUiuxGroup =
  | "hoy"
  | "ventas-caja"
  | "inventario"
  | "compras"
  | "proveedores"
  | "sincronizacion"
  | "reportes"
  | "analisis"
  | "sistema"
  | "configuracion"
  | "ayuda";

export type PcUiuxRole = "dueno" | "gerente" | "auditor" | "soporte";

export type PcUiuxBlock =
  | "decisionHeader"
  | "attentionSummary"
  | "nextBestAction"
  | "actionableTable"
  | "evidenceDrawer"
  | "emptyState"
  | "errorState";

export type PcDataSourceKind = "real" | "demo" | "hybrid" | "static";

export type PcPageContract = {
  route: string;
  humanName: string;
  group: PcUiuxGroup;
  primaryQuestion: string;
  userRoles: PcUiuxRole[];
  requiredBlocks: PcUiuxBlock[];
  primaryAction?: string;
  dataSourceKind: PcDataSourceKind;
  allowsTechnicalTermsOnlyInsideEvidence: boolean;
};

export const PC_PAGE_CONTRACTS = [
  {
    "route": "/",
    "humanName": "Hoy",
    "group": "hoy",
    "primaryQuestion": "¿Qué debo atender ahora?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/acciones-masivas",
    "humanName": "Acciones masivas",
    "group": "sistema",
    "primaryQuestion": "¿La plataforma está funcionando bien?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/ajustes-inventario",
    "humanName": "Ajustes de inventario",
    "group": "ventas-caja",
    "primaryQuestion": "¿Cómo va la venta y el dinero?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/alertas-ejecutivas",
    "humanName": "Alertas ejecutivas",
    "group": "hoy",
    "primaryQuestion": "¿Qué debo atender ahora?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/alertas-operativas",
    "humanName": "Alertas operativas",
    "group": "hoy",
    "primaryQuestion": "¿Qué debo atender ahora?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/audit",
    "humanName": "Historial",
    "group": "sistema",
    "primaryQuestion": "¿La plataforma está funcionando bien?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/auditoria-inventario",
    "humanName": "Historial de inventario",
    "group": "ventas-caja",
    "primaryQuestion": "¿Cómo va la venta y el dinero?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/cash-sessions",
    "humanName": "Cortes de caja",
    "group": "ventas-caja",
    "primaryQuestion": "¿Cómo va la venta y el dinero?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/catalog",
    "humanName": "Catálogo",
    "group": "inventario",
    "primaryQuestion": "¿Qué productos necesitan atención?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/catalogo-activo",
    "humanName": "Productos activos",
    "group": "inventario",
    "primaryQuestion": "¿Qué productos necesitan atención?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/conteos-operativos",
    "humanName": "Conteos operativos",
    "group": "inventario",
    "primaryQuestion": "¿Qué productos necesitan atención?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/contratos-reporte",
    "humanName": "Contratos",
    "group": "reportes",
    "primaryQuestion": "¿Qué necesito descargar o compartir?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/counts",
    "humanName": "Conteos",
    "group": "inventario",
    "primaryQuestion": "¿Qué productos necesitan atención?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/dashboard",
    "humanName": "Hoy",
    "group": "hoy",
    "primaryQuestion": "¿Qué debo atender ahora?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/data-quality",
    "humanName": "Revisión de datos",
    "group": "sistema",
    "primaryQuestion": "¿La plataforma está funcionando bien?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/detalle-registros",
    "humanName": "Detalle de registros",
    "group": "sistema",
    "primaryQuestion": "¿La plataforma está funcionando bien?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/devices",
    "humanName": "Equipos",
    "group": "sistema",
    "primaryQuestion": "¿La plataforma está funcionando bien?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/estados-operativos",
    "humanName": "Estados operativos",
    "group": "sistema",
    "primaryQuestion": "¿La plataforma está funcionando bien?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/existencias-criticas",
    "humanName": "Productos críticos",
    "group": "inventario",
    "primaryQuestion": "¿Qué productos necesitan atención?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/exportables",
    "humanName": "Exportables",
    "group": "reportes",
    "primaryQuestion": "¿Qué necesito descargar o compartir?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/filtros-avanzados",
    "humanName": "Filtros avanzados",
    "group": "sistema",
    "primaryQuestion": "¿La plataforma está funcionando bien?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/filtros-fecha",
    "humanName": "Filtros por fecha",
    "group": "sistema",
    "primaryQuestion": "¿La plataforma está funcionando bien?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/forecast-basico",
    "humanName": "Pronóstico básico",
    "group": "compras",
    "primaryQuestion": "¿Qué debo pedir, recibir o cerrar?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/glosario",
    "humanName": "Glosario",
    "group": "ayuda",
    "primaryQuestion": "¿Dónde encuentro explicación de esta parte?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "hybrid",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/gobierno",
    "humanName": "Gobierno",
    "group": "sistema",
    "primaryQuestion": "¿La plataforma está funcionando bien?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/incidencias-recepcion",
    "humanName": "Diferencias de recepción",
    "group": "compras",
    "primaryQuestion": "¿Qué debo pedir, recibir o cerrar?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/integridad-barcodes",
    "humanName": "Códigos repetidos",
    "group": "inventario",
    "primaryQuestion": "¿Qué productos necesitan atención?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/license-runtime",
    "humanName": "Licencia",
    "group": "sistema",
    "primaryQuestion": "¿La plataforma está funcionando bien?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/metricas-dia",
    "humanName": "Métricas del día",
    "group": "ventas-caja",
    "primaryQuestion": "¿Cómo va la venta y el dinero?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/movements",
    "humanName": "Movimientos",
    "group": "inventario",
    "primaryQuestion": "¿Qué productos necesitan atención?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/ordenes-compra",
    "humanName": "Órdenes de compra",
    "group": "compras",
    "primaryQuestion": "¿Qué debo pedir, recibir o cerrar?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/outbox-operativo",
    "humanName": "Cambios pendientes",
    "group": "sincronizacion",
    "primaryQuestion": "¿Todos los equipos tienen la misma información?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/politica-precios",
    "humanName": "Política de precios",
    "group": "inventario",
    "primaryQuestion": "¿Qué productos necesitan atención?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/prisma-insights",
    "humanName": "Análisis",
    "group": "analisis",
    "primaryQuestion": "¿Qué patrón explica lo que está pasando?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "hybrid",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/prisma-insights/chart-lab",
    "humanName": "Chart Lab",
    "group": "analisis",
    "primaryQuestion": "¿Qué patrón explica lo que está pasando?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "hybrid",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/proveedores",
    "humanName": "Proveedores",
    "group": "proveedores",
    "primaryQuestion": "¿Con qué proveedor debo actuar hoy?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/purchasing",
    "humanName": "Pedidos",
    "group": "compras",
    "primaryQuestion": "¿Qué debo pedir, recibir o cerrar?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/receiving",
    "humanName": "Recepción",
    "group": "compras",
    "primaryQuestion": "¿Qué debo pedir, recibir o cerrar?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/recepcion-proveedor",
    "humanName": "Recibir proveedor",
    "group": "compras",
    "primaryQuestion": "¿Qué debo pedir, recibir o cerrar?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/referencia-visual",
    "humanName": "Referencia visual",
    "group": "sistema",
    "primaryQuestion": "¿La plataforma está funcionando bien?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "hybrid",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/replenishment",
    "humanName": "Reabasto",
    "group": "compras",
    "primaryQuestion": "¿Qué debo pedir, recibir o cerrar?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/sales-control",
    "humanName": "Ventas",
    "group": "ventas-caja",
    "primaryQuestion": "¿Cómo va la venta y el dinero?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/salud-barcodes",
    "humanName": "Salud de códigos",
    "group": "inventario",
    "primaryQuestion": "¿Qué productos necesitan atención?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/scorecards-negocio",
    "humanName": "Scorecards",
    "group": "reportes",
    "primaryQuestion": "¿Qué necesito descargar o compartir?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/senal-reabasto",
    "humanName": "Señal de reabasto",
    "group": "compras",
    "primaryQuestion": "¿Qué debo pedir, recibir o cerrar?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/settings",
    "humanName": "Configuración",
    "group": "configuracion",
    "primaryQuestion": "¿Qué puedo ajustar sin romper la operación?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/settings/license",
    "humanName": "Licencia",
    "group": "sistema",
    "primaryQuestion": "¿La plataforma está funcionando bien?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/stock",
    "humanName": "Existencias",
    "group": "inventario",
    "primaryQuestion": "¿Qué productos necesitan atención?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/sync",
    "humanName": "Sincronización",
    "group": "sincronizacion",
    "primaryQuestion": "¿Todos los equipos tienen la misma información?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/sync-operativo",
    "humanName": "Operación de sincronización",
    "group": "sincronizacion",
    "primaryQuestion": "¿Todos los equipos tienen la misma información?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/tablas-operativas",
    "humanName": "Tablas operativas",
    "group": "sistema",
    "primaryQuestion": "¿La plataforma está funcionando bien?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/tablero-kpi",
    "humanName": "Indicadores",
    "group": "reportes",
    "primaryQuestion": "¿Qué necesito descargar o compartir?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/tablet-communication",
    "humanName": "Tablet",
    "group": "sincronizacion",
    "primaryQuestion": "¿Todos los equipos tienen la misma información?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/validacion-catalogo",
    "humanName": "Validación de catálogo",
    "group": "inventario",
    "primaryQuestion": "¿Qué productos necesitan atención?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  },
  {
    "route": "/vistas-ejecutivas",
    "humanName": "Vistas ejecutivas",
    "group": "reportes",
    "primaryQuestion": "¿Qué necesito descargar o compartir?",
    "userRoles": [
      "dueno",
      "gerente",
      "auditor",
      "soporte"
    ],
    "requiredBlocks": [
      "decisionHeader",
      "attentionSummary",
      "nextBestAction",
      "evidenceDrawer",
      "emptyState",
      "errorState"
    ],
    "primaryAction": "Revisar",
    "dataSourceKind": "real",
    "allowsTechnicalTermsOnlyInsideEvidence": true
  }
] satisfies PcPageContract[];

export function getPcPageContract(route: string): PcPageContract | undefined {
  return PC_PAGE_CONTRACTS.find((contract) => contract.route === route);
}
