// AUTO-GENERATED by prisma_pc_uiux_onepass_hotfix.

export type PcRouteStatus = "primary" | "secondary" | "legacy" | "lab" | "internal";

export type PcRouteMapEntry = {
  route: string;
  humanName: string;
  group: string;
  status: PcRouteStatus;
  replacementRoute?: string;
};

export const PC_ROUTE_MAP = [
  {
    "route": "/",
    "humanName": "Hoy",
    "group": "hoy",
    "status": "primary"
  },
  {
    "route": "/acciones-masivas",
    "humanName": "Acciones masivas",
    "group": "sistema",
    "status": "secondary"
  },
  {
    "route": "/ajustes-inventario",
    "humanName": "Ajustes de inventario",
    "group": "ventas-caja",
    "status": "secondary"
  },
  {
    "route": "/alertas-ejecutivas",
    "humanName": "Alertas ejecutivas",
    "group": "hoy",
    "status": "secondary"
  },
  {
    "route": "/alertas-operativas",
    "humanName": "Alertas operativas",
    "group": "hoy",
    "status": "secondary"
  },
  {
    "route": "/audit",
    "humanName": "Historial",
    "group": "sistema",
    "status": "secondary"
  },
  {
    "route": "/auditoria-inventario",
    "humanName": "Historial de inventario",
    "group": "ventas-caja",
    "status": "secondary"
  },
  {
    "route": "/cash-sessions",
    "humanName": "Cortes de caja",
    "group": "ventas-caja",
    "status": "primary"
  },
  {
    "route": "/catalog",
    "humanName": "Catálogo",
    "group": "inventario",
    "status": "primary"
  },
  {
    "route": "/catalogo-activo",
    "humanName": "Productos activos",
    "group": "inventario",
    "status": "secondary"
  },
  {
    "route": "/conteos-operativos",
    "humanName": "Conteos operativos",
    "group": "inventario",
    "status": "secondary"
  },
  {
    "route": "/contratos-reporte",
    "humanName": "Contratos",
    "group": "reportes",
    "status": "secondary"
  },
  {
    "route": "/counts",
    "humanName": "Conteos",
    "group": "inventario",
    "status": "secondary"
  },
  {
    "route": "/dashboard",
    "humanName": "Hoy",
    "group": "hoy",
    "status": "primary"
  },
  {
    "route": "/data-quality",
    "humanName": "Revisión de datos",
    "group": "sistema",
    "status": "secondary"
  },
  {
    "route": "/detalle-registros",
    "humanName": "Detalle de registros",
    "group": "sistema",
    "status": "secondary"
  },
  {
    "route": "/devices",
    "humanName": "Equipos",
    "group": "sistema",
    "status": "secondary"
  },
  {
    "route": "/estados-operativos",
    "humanName": "Estados operativos",
    "group": "sistema",
    "status": "secondary"
  },
  {
    "route": "/existencias-criticas",
    "humanName": "Productos críticos",
    "group": "inventario",
    "status": "secondary"
  },
  {
    "route": "/exportables",
    "humanName": "Exportables",
    "group": "reportes",
    "status": "secondary"
  },
  {
    "route": "/filtros-avanzados",
    "humanName": "Filtros avanzados",
    "group": "sistema",
    "status": "internal"
  },
  {
    "route": "/filtros-fecha",
    "humanName": "Filtros por fecha",
    "group": "sistema",
    "status": "internal"
  },
  {
    "route": "/forecast-basico",
    "humanName": "Pronóstico básico",
    "group": "compras",
    "status": "secondary"
  },
  {
    "route": "/glosario",
    "humanName": "Glosario",
    "group": "ayuda",
    "status": "internal"
  },
  {
    "route": "/gobierno",
    "humanName": "Gobierno",
    "group": "sistema",
    "status": "internal"
  },
  {
    "route": "/incidencias-recepcion",
    "humanName": "Diferencias de recepción",
    "group": "compras",
    "status": "secondary"
  },
  {
    "route": "/integridad-barcodes",
    "humanName": "Códigos repetidos",
    "group": "inventario",
    "status": "secondary"
  },
  {
    "route": "/license-runtime",
    "humanName": "Licencia",
    "group": "sistema",
    "status": "secondary"
  },
  {
    "route": "/metricas-dia",
    "humanName": "Métricas del día",
    "group": "ventas-caja",
    "status": "secondary"
  },
  {
    "route": "/movements",
    "humanName": "Movimientos",
    "group": "inventario",
    "status": "secondary"
  },
  {
    "route": "/ordenes-compra",
    "humanName": "Órdenes de compra",
    "group": "compras",
    "status": "secondary"
  },
  {
    "route": "/outbox-operativo",
    "humanName": "Cambios pendientes",
    "group": "sincronizacion",
    "status": "secondary"
  },
  {
    "route": "/politica-precios",
    "humanName": "Política de precios",
    "group": "inventario",
    "status": "secondary"
  },
  {
    "route": "/prisma-insights",
    "humanName": "Análisis",
    "group": "analisis",
    "status": "primary"
  },
  {
    "route": "/prisma-insights/chart-lab",
    "humanName": "Chart Lab",
    "group": "analisis",
    "status": "lab"
  },
  {
    "route": "/proveedores",
    "humanName": "Proveedores",
    "group": "proveedores",
    "status": "primary"
  },
  {
    "route": "/purchasing",
    "humanName": "Pedidos",
    "group": "compras",
    "status": "primary"
  },
  {
    "route": "/receiving",
    "humanName": "Recepción",
    "group": "compras",
    "status": "primary"
  },
  {
    "route": "/recepcion-proveedor",
    "humanName": "Recibir proveedor",
    "group": "compras",
    "status": "secondary"
  },
  {
    "route": "/referencia-visual",
    "humanName": "Referencia visual",
    "group": "sistema",
    "status": "internal"
  },
  {
    "route": "/replenishment",
    "humanName": "Reabasto",
    "group": "compras",
    "status": "primary"
  },
  {
    "route": "/sales-control",
    "humanName": "Ventas",
    "group": "ventas-caja",
    "status": "primary"
  },
  {
    "route": "/salud-barcodes",
    "humanName": "Salud de códigos",
    "group": "inventario",
    "status": "secondary"
  },
  {
    "route": "/scorecards-negocio",
    "humanName": "Scorecards",
    "group": "reportes",
    "status": "secondary"
  },
  {
    "route": "/senal-reabasto",
    "humanName": "Señal de reabasto",
    "group": "compras",
    "status": "secondary"
  },
  {
    "route": "/settings",
    "humanName": "Configuración",
    "group": "configuracion",
    "status": "primary"
  },
  {
    "route": "/settings/license",
    "humanName": "Licencia",
    "group": "sistema",
    "status": "secondary"
  },
  {
    "route": "/stock",
    "humanName": "Existencias",
    "group": "inventario",
    "status": "primary"
  },
  {
    "route": "/sync",
    "humanName": "Sincronización",
    "group": "sincronizacion",
    "status": "primary"
  },
  {
    "route": "/sync-operativo",
    "humanName": "Operación de sincronización",
    "group": "sincronizacion",
    "status": "secondary"
  },
  {
    "route": "/tablas-operativas",
    "humanName": "Tablas operativas",
    "group": "sistema",
    "status": "internal"
  },
  {
    "route": "/tablero-kpi",
    "humanName": "Indicadores",
    "group": "reportes",
    "status": "secondary"
  },
  {
    "route": "/tablet-communication",
    "humanName": "Tablet",
    "group": "sincronizacion",
    "status": "secondary"
  },
  {
    "route": "/validacion-catalogo",
    "humanName": "Validación de catálogo",
    "group": "inventario",
    "status": "secondary"
  },
  {
    "route": "/vistas-ejecutivas",
    "humanName": "Vistas ejecutivas",
    "group": "reportes",
    "status": "secondary"
  }
] satisfies PcRouteMapEntry[];

export const PC_PRIMARY_NAVIGATION = PC_ROUTE_MAP.filter((route) => route.status === "primary");

export function getPcRouteHumanName(route: string): string {
  return PC_ROUTE_MAP.find((entry) => entry.route === route)?.humanName ?? route;
}
