// AUTO-GENERATED by prisma_pc_uiux_onepass_hotfix.

import { translatePcStatus, translatePcTerm } from "./copy-dictionary";

export type HumanizedStatus = {
  label: string;
  severity: "info" | "attention" | "critical" | "blocking" | "demo" | "technical";
};

export function humanizePcStatus(status: string): HumanizedStatus {
  const normalized = status.toLowerCase();

  if (["critical", "failed", "error", "danger", "blocking"].includes(normalized)) {
    return { label: translatePcStatus(status), severity: "critical" };
  }

  if (["warning", "stale", "degraded", "partial"].includes(normalized)) {
    return { label: translatePcStatus(status), severity: "attention" };
  }

  if (["mock", "demo"].includes(normalized)) {
    return { label: translatePcStatus(status), severity: "demo" };
  }

  if (["runtime", "raw", "debug", "adapter", "registry", "manifest"].includes(normalized)) {
    return { label: translatePcTerm(status), severity: "technical" };
  }

  return { label: translatePcStatus(status), severity: "info" };
}

export function humanizePcTechnicalTerm(term: string): string {
  return translatePcTerm(term);
}
