/*
 * PRISMA Surface Visual Governor · Pilot 02 · Chart Lab Recipe Export
 * Generated by installer. Public-safe constants only.
 * No DB, no deploy, no dependency install, POS protected.
 */

export type PrismaRecipeTarget = "pc" | "tablet" | "mobile" | "shared";

export const PRISMA_SURFACE_GOVERNOR_PILOT_02 = {
  pilot: "02_chart_lab_recipe_export",
  manifestPath: "/surface-visual-governor/recipe-export/latest/index.json",
  recipeBasePath: "/surface-visual-governor/recipe-export/latest",
  atmosphereAssetBasePath: "/surface-visual-governor/atmosphere-assets/backgrounds",
  requiredRecipes: [
    "chart.recipe.json",
    "visual.recipe.json",
    "motion.recipe.json",
    "background.recipe.json",
    "surface.compatibility.json",
  ],
  protectedSurfaces: ["pos"],
  tabletPolicy: "light-first",
} as const;

export type PrismaChartLabRecipeExportManifest = typeof PRISMA_SURFACE_GOVERNOR_PILOT_02;

export async function fetchPrismaChartLabRecipeExport(basePath = "") {
  const manifestUrl = `${basePath}${PRISMA_SURFACE_GOVERNOR_PILOT_02.manifestPath}`;
  const manifest = await fetch(manifestUrl).then((response) => {
    if (!response.ok) {
      throw new Error(`Unable to load PRISMA recipe export manifest: ${response.status}`);
    }
    return response.json();
  });

  const files = manifest?.files ?? {};
  const base = `${basePath}${PRISMA_SURFACE_GOVERNOR_PILOT_02.recipeBasePath}`;
  const load = async (name: string) => fetch(`${base}/${name}`).then((response) => {
    if (!response.ok) {
      throw new Error(`Unable to load PRISMA recipe file ${name}: ${response.status}`);
    }
    return response.json();
  });

  return {
    manifest,
    chart: await load(files.chart_recipe ?? "chart.recipe.json"),
    visual: await load(files.visual_recipe ?? "visual.recipe.json"),
    motion: await load(files.motion_recipe ?? "motion.recipe.json"),
    background: await load(files.background_recipe ?? "background.recipe.json"),
    compatibility: await load(files.surface_compatibility ?? "surface.compatibility.json"),
  };
}

export function isPrismaRecipeTarget(value: string): value is PrismaRecipeTarget {
  return value === "pc" || value === "tablet" || value === "mobile" || value === "shared";
}
