import type { TimelinePresetScript, TimelineTrackType, TimelineValuePoint } from "../types";

const TRACKS: TimelineTrackType[] = [
  "camera",
  "overlay",
  "motion",
  "layers",
  "lighting",
  "subtitle",
  "audio",
  "annotation"
];

function values(input: {
  readonly opacity: number;
  readonly x: number;
  readonly y: number;
  readonly scale: number;
  readonly visible: boolean;
}): TimelineValuePoint[] {
  return [
    { key: "opacity", value: input.opacity },
    { key: "x", value: input.x },
    { key: "y", value: input.y },
    { key: "scale", value: input.scale },
    { key: "visible", value: input.visible }
  ];
}

function buildPreset(input: {
  readonly id: string;
  readonly label: string;
  readonly style: TimelinePresetScript["style"];
  readonly description: string;
  readonly durationMs: number;
  readonly motionFactor: number;
  readonly cameraBias: number;
  readonly overlayBias: number;
}): TimelinePresetScript {
  const markers = [
    {
      type: "Reveal" as const,
      t: Math.round(input.durationMs * 0.2),
      label: "Reveal",
      note: "Reveal marker generated by preset script"
    },
    {
      type: "Settle" as const,
      t: Math.round(input.durationMs * 0.55),
      label: "Settle",
      note: "Settle marker generated by preset script"
    },
    {
      type: "CTA" as const,
      t: Math.round(input.durationMs * 0.82),
      label: "CTA",
      note: "CTA marker generated by preset script"
    }
  ];

  const tracks = TRACKS.map((kind, trackIndex) => {
    const kindFactor = trackIndex + 1;
    const baseX = kind === "camera" ? input.cameraBias : input.overlayBias;

    return {
      kind,
      label: `${kind.toUpperCase()} Track`,
      enabled: true,
      keyframes: [
        {
          t: 0,
          easing: "ease-in" as const,
          values: values({
            opacity: 0,
            x: baseX,
            y: kindFactor * 4,
            scale: 0.92,
            visible: false
          })
        },
        {
          t: Math.round(input.durationMs * 0.25),
          easing: "ease-out" as const,
          values: values({
            opacity: 0.75,
            x: baseX + 14,
            y: kindFactor * 7,
            scale: 1,
            visible: true
          })
        },
        {
          t: Math.round(input.durationMs * 0.5),
          easing: "linear" as const,
          values: values({
            opacity: 1,
            x: baseX + Math.round(24 * input.motionFactor),
            y: kindFactor * 8,
            scale: 1.03,
            visible: true
          })
        },
        {
          t: Math.round(input.durationMs * 0.76),
          easing: "ease-in-out" as const,
          values: values({
            opacity: 1,
            x: baseX + Math.round(31 * input.motionFactor),
            y: kindFactor * 9,
            scale: 1.05,
            visible: true
          })
        },
        {
          t: input.durationMs,
          easing: "ease-out" as const,
          values: values({
            opacity: 1,
            x: baseX + Math.round(38 * input.motionFactor),
            y: kindFactor * 10,
            scale: 1.08,
            visible: true
          })
        }
      ]
    };
  });

  return {
    id: input.id,
    label: input.label,
    style: input.style,
    description: input.description,
    durationMs: input.durationMs,
    markers,
    tracks
  };
}

const cinematicCatalog: Array<{
  readonly id: string;
  readonly label: string;
  readonly style: TimelinePresetScript["style"];
  readonly description: string;
  readonly durationMs: number;
  readonly motionFactor: number;
  readonly cameraBias: number;
  readonly overlayBias: number;
}> = [
  {
    id: "preset-01-01",
    label: "Momentum Reveal",
    style: "cinematic",
    description: "Balanced reveal-settle-cta pattern tuned for wide industrial shots.",
    durationMs: 9600,
    motionFactor: 1,
    cameraBias: 0,
    overlayBias: 2
  },
  {
    id: "preset-01-02",
    label: "Orbit Focus",
    style: "cinematic",
    description: "High camera movement with stabilization in second act.",
    durationMs: 10200,
    motionFactor: 1.08,
    cameraBias: 8,
    overlayBias: 5
  },
  {
    id: "preset-01-03",
    label: "Confident CTA",
    style: "cinematic",
    description: "Shorter reveal with punchy CTA timing.",
    durationMs: 8900,
    motionFactor: 1.12,
    cameraBias: 12,
    overlayBias: 6
  },
  {
    id: "preset-02-01",
    label: "Documentary Glide",
    style: "documentary",
    description: "Moderate transitions and emphasis on subtitles and annotations.",
    durationMs: 10400,
    motionFactor: 0.82,
    cameraBias: -4,
    overlayBias: 3
  },
  {
    id: "preset-02-02",
    label: "Signal Stack",
    style: "product",
    description: "Layer stack build-up for product capability walkthrough.",
    durationMs: 9300,
    motionFactor: 0.94,
    cameraBias: 2,
    overlayBias: 12
  },
  {
    id: "preset-02-03",
    label: "Compliance Ladder",
    style: "compliance",
    description: "Conservative movement with strict annotation cadence.",
    durationMs: 10800,
    motionFactor: 0.72,
    cameraBias: -6,
    overlayBias: 10
  },
  {
    id: "preset-03-01",
    label: "Ramped Spotlight",
    style: "cinematic",
    description: "Camera-first reveal with late overlay stack.",
    durationMs: 10100,
    motionFactor: 1.05,
    cameraBias: 16,
    overlayBias: 4
  },
  {
    id: "preset-03-02",
    label: "Narrative Rails",
    style: "documentary",
    description: "Subtitle anchor and smooth layer transitions.",
    durationMs: 9700,
    motionFactor: 0.88,
    cameraBias: 1,
    overlayBias: 9
  },
  {
    id: "preset-03-03",
    label: "Peak Conversion",
    style: "product",
    description: "Strong CTA acceleration and overlay spotlight.",
    durationMs: 9150,
    motionFactor: 1.15,
    cameraBias: 10,
    overlayBias: 14
  },
  {
    id: "preset-04-01",
    label: "Audit Corridor",
    style: "compliance",
    description: "Compliance-safe transition pace for review sessions.",
    durationMs: 11200,
    motionFactor: 0.66,
    cameraBias: -10,
    overlayBias: 8
  },
  {
    id: "preset-04-02",
    label: "Precision Arc",
    style: "cinematic",
    description: "Careful arc motion tuned for low-noise previews.",
    durationMs: 9800,
    motionFactor: 0.93,
    cameraBias: 5,
    overlayBias: 6
  },
  {
    id: "preset-04-03",
    label: "Calm Finale",
    style: "documentary",
    description: "Low-velocity ending template for executive close.",
    durationMs: 10600,
    motionFactor: 0.75,
    cameraBias: -2,
    overlayBias: 7
  }
];

export const TIMELINE_PRESET_SCRIPTS: TimelinePresetScript[] = cinematicCatalog.map((preset) =>
  buildPreset(preset)
);

export function findPresetById(presetId: string): TimelinePresetScript | null {
  for (const preset of TIMELINE_PRESET_SCRIPTS) {
    if (preset.id === presetId) {
      return preset;
    }
  }

  return null;
}

export function ensurePreset(presetId: string): TimelinePresetScript {
  const preset = findPresetById(presetId);
  if (preset) {
    return preset;
  }

  return TIMELINE_PRESET_SCRIPTS[0];
}
