import { readFileSync } from 'node:fs';
import { join } from 'node:path';
const root = process.argv[2];
if (!root) process.exit(2);
const read = (rel) => readFileSync(join(root, rel), 'utf8');
const has = (rel, text) => { if (!read(rel).includes(text)) throw new Error(`${rel} no contiene ${text}`); console.log(`OK ${rel} contiene ${text}`); };
const lacks = (rel, text) => { if (read(rel).includes(text)) throw new Error(`${rel} todavía contiene ${text}`); console.log(`OK ${rel} no contiene ${text}`); };
const removedSidebarScroll = 'sidebar-' + 'main-scroll';
lacks('components/layout/app-shell.tsx', removedSidebarScroll); has('components/layout/app-shell.tsx','data-prisma-component="SurfaceContextStrip"'); has('components/layout/app-shell.tsx','aria-label="Navegación principal PC"'); lacks('components/layout/app-shell.tsx','title="Dashboard"'); lacks('components/layout/app-shell.tsx','KPIs y sync');
has('app/globals.css','PRISMA_PC_READABILITY_SCROLL_ESMX_04 START'); lacks('app/globals.css', `.${removedSidebarScroll}`);
has('components/suppliers/smart-purchase-workbench.tsx','supplier-readable-v07'); has('components/suppliers/smart-purchase-workbench.tsx','calendar-board-v07'); has('components/suppliers/supplier-action-cockpit.tsx','supplier-action-command-v12'); has('components/suppliers/smart-purchase-workbench.tsx','calendarKindLabel'); lacks('components/suppliers/smart-purchase-workbench.tsx','POST'); lacks('components/suppliers/smart-purchase-workbench.tsx','/api/proveedores/compra-inteligente'); lacks('components/suppliers/smart-purchase-workbench.tsx','order_cutoff'); lacks('components/suppliers/smart-purchase-workbench.tsx','expected_receiving');
has('app/suppliers.css','supplier-readable-v07'); has('app/suppliers.css','.calendar-board-v07');
has('app/suppliers-ux-v08.css','PRISMA PC Suppliers UX v08'); has('app/suppliers-ux-v08.css','.supplier-action-command-v12');
has('src/lib/suppliers/server.ts','Revisar antes de comprar'); has('src/lib/suppliers/server.ts','Fecha límite de pedido'); lacks('src/lib/suppliers/server.ts','Bloqueada'); lacks('src/lib/suppliers/server.ts','Bloqueado');
has('src/lib/suppliers/lifecycle-engine.ts','${kind}_${supplierId}_${title}_${startsAt}'); has('src/lib/suppliers/lifecycle-engine.ts','Recepción esperada'); has('src/lib/suppliers/smart-purchase-engine.ts','Compra para revisar');
console.log('VERIFY OK prisma pc suppliers readability scroll esmx v04');
