import {
  actionInboxPriorityStackOption,
  causalFlowRibbonOption,
  confidenceMeterBandsOption,
  decisionLedgerTimelineOption,
  financialOperationalWaterfallOption,
  freshnessBeaconGridOption,
  healthRadarCompactOption,
  incidentSparkOption,
  inventoryRiskTreemapOption,
  operationalDensityFieldOption,
  ownerPulseTimelineOption,
  serviceDependencyGraphOption,
  shiftPulseStripOption,
  syncOutboxMatrixOption
} from "../../../../../shared/prisma-charts/prismaChartOptions";
import { mockMobileCharts, mockPcCharts, mockTabletCharts } from "../../../../../shared/prisma-charts/prismaChartMocks";
import { ExampleFutureChart } from "./components/ExampleFutureChart";
import type { LabChartEntry } from "./chart-lab-types";

const registryPath = "products/chart-lab/app/src/prisma-charts/chart-lab-registry.tsx";
const sharedMockPath = "shared/prisma-charts/prismaChartMocks.ts";
const productPromotionBoundary = "Lab code is staging. Product promotion must copy/import through an explicit surface adapter and run that surface validation.";

export const chartOpsChartIds = [
  "pc.causal-flow-ribbon",
  "pc.operational-density-field",
  "pc.service-dependency-graph",
  "pc.inventory-risk-treemap",
  "pc.decision-ledger-timeline",
  "pc.financial-operational-waterfall",
  "tablet.shift-pulse-strip",
  "tablet.sync-outbox-status-matrix",
  "mobile.owner-pulse-timeline",
  "mobile.action-inbox-priority-stack",
  "mobile.health-radar-compact",
  "mobile.freshness-beacon-grid",
  "mobile.incident-spark-cards",
  "mobile.confidence-meter-bands"
] as const;

export const chartLabRegistry: LabChartEntry[] = [
  {
    id: "pc.causal-flow-ribbon",
    title: "Causal Flow Ribbon",
    shortName: "Causal Ribbon",
    surface: "pc",
    family: "flow",
    chartType: "Sankey",
    description: "Premium light Sankey ribbon connecting module, cause, effect, and action target.",
    operationalQuestion: "What caused the operational degradation and where should governance act first?",
    readiness: "working",
    dataStatus: "shared/mock",
    mockDataLabel: "Deterministic ChartOps mock from shared/prisma-charts.",
    confidence: 72,
    freshnessLabel: "Mock generated at the shared deterministic timestamp.",
    promotionTarget: "PC governance / prisma-insights",
    promotionBoundary: productPromotionBoundary,
    sourceModule: "shared/prisma-charts",
    componentPath: "products/chart-lab/app/src/prisma-charts/components/LabEChartFrame.tsx",
    mockPath: sharedMockPath,
    registryPath,
    optionBuilderName: "causalFlowRibbonOption",
    renderer: "canvas",
    defaultHeight: 420,
    getOption: () => causalFlowRibbonOption(mockPcCharts.causalFlowRibbon)
  },
  {
    id: "pc.operational-density-field",
    title: "Operational Density Field",
    shortName: "Density",
    surface: "pc",
    family: "density",
    chartType: "Heatmap",
    description: "Operational pressure field by module and time bucket.",
    operationalQuestion: "Where is operational pressure concentrating over time?",
    readiness: "working",
    dataStatus: "shared/mock",
    mockDataLabel: "Deterministic module pressure cells.",
    confidence: 66,
    freshnessLabel: "Mock freshness; real adapter can replace source later.",
    promotionTarget: "PC governance / prisma-insights",
    promotionBoundary: productPromotionBoundary,
    sourceModule: "shared/prisma-charts",
    componentPath: "products/chart-lab/app/src/prisma-charts/components/LabEChartFrame.tsx",
    mockPath: sharedMockPath,
    registryPath,
    optionBuilderName: "operationalDensityFieldOption",
    renderer: "canvas",
    defaultHeight: 390,
    getOption: () => operationalDensityFieldOption(mockPcCharts.operationalDensityField)
  },
  {
    id: "pc.service-dependency-graph",
    title: "Service Dependency Graph",
    shortName: "Dependency Graph",
    surface: "pc",
    family: "network",
    chartType: "Graph",
    description: "Force graph for apps, services, endpoints, database, and public edges.",
    operationalQuestion: "Which service dependency is degrading the PRISMA operating surface?",
    readiness: "working",
    dataStatus: "shared/mock",
    mockDataLabel: "Deterministic service topology.",
    confidence: 70,
    freshnessLabel: "Mock topology; safe for visual design.",
    promotionTarget: "PC governance / Control audit",
    promotionBoundary: productPromotionBoundary,
    sourceModule: "shared/prisma-charts",
    componentPath: "products/chart-lab/app/src/prisma-charts/components/LabEChartFrame.tsx",
    mockPath: sharedMockPath,
    registryPath,
    optionBuilderName: "serviceDependencyGraphOption",
    renderer: "canvas",
    defaultHeight: 420,
    getOption: () => serviceDependencyGraphOption(mockPcCharts.serviceDependencyGraph)
  },
  {
    id: "pc.inventory-risk-treemap",
    title: "Inventory Risk Treemap",
    shortName: "Inventory Risk",
    surface: "pc",
    family: "treemap",
    chartType: "Treemap",
    description: "Treemap for stockout, margin, and revenue-at-risk exploration.",
    operationalQuestion: "Which inventory pockets threaten continuity or money first?",
    readiness: "working",
    dataStatus: "shared/mock",
    mockDataLabel: "Deterministic risk hierarchy.",
    confidence: 58,
    freshnessLabel: "Mock inventory state; promotion requires canonical inventory adapter.",
    promotionTarget: "PC backoffice inventory governance",
    promotionBoundary: productPromotionBoundary,
    sourceModule: "shared/prisma-charts",
    componentPath: "products/chart-lab/app/src/prisma-charts/components/LabEChartFrame.tsx",
    mockPath: sharedMockPath,
    registryPath,
    optionBuilderName: "inventoryRiskTreemapOption",
    renderer: "canvas",
    defaultHeight: 420,
    getOption: () => inventoryRiskTreemapOption(mockPcCharts.inventoryRiskTreemap)
  },
  {
    id: "pc.decision-ledger-timeline",
    title: "Decision Ledger Timeline",
    shortName: "Decision Ledger",
    surface: "pc",
    family: "timeline",
    chartType: "Line + Scatter",
    description: "Auditable timeline for incidents, decisions, evidence, and resolutions.",
    operationalQuestion: "Which decisions changed operational health and with what evidence?",
    readiness: "working",
    dataStatus: "shared/mock",
    mockDataLabel: "Deterministic decision ledger points.",
    confidence: 64,
    freshnessLabel: "Mock ledger state.",
    promotionTarget: "PC governance and Control audit",
    promotionBoundary: productPromotionBoundary,
    sourceModule: "shared/prisma-charts",
    componentPath: "products/chart-lab/app/src/prisma-charts/components/LabEChartFrame.tsx",
    mockPath: sharedMockPath,
    registryPath,
    optionBuilderName: "decisionLedgerTimelineOption",
    renderer: "canvas",
    defaultHeight: 360,
    getOption: () => decisionLedgerTimelineOption(mockPcCharts.decisionLedgerTimeline)
  },
  {
    id: "pc.financial-operational-waterfall",
    title: "Financial / Operational Waterfall",
    shortName: "Waterfall",
    surface: "pc",
    family: "waterfall",
    chartType: "Waterfall Bar",
    description: "Waterfall that links operating effects with money impact.",
    operationalQuestion: "How did operational events move money from gross to net?",
    readiness: "working",
    dataStatus: "shared/mock",
    mockDataLabel: "Deterministic financial steps.",
    confidence: 55,
    freshnessLabel: "Mock money bridge.",
    promotionTarget: "PC executive governance",
    promotionBoundary: productPromotionBoundary,
    sourceModule: "shared/prisma-charts",
    componentPath: "products/chart-lab/app/src/prisma-charts/components/LabEChartFrame.tsx",
    mockPath: sharedMockPath,
    registryPath,
    optionBuilderName: "financialOperationalWaterfallOption",
    renderer: "canvas",
    defaultHeight: 380,
    getOption: () => financialOperationalWaterfallOption(mockPcCharts.financialOperationalWaterfall)
  },
  {
    id: "tablet.shift-pulse-strip",
    title: "Shift Pulse Strip",
    shortName: "Shift Pulse",
    surface: "tablet",
    family: "strip",
    chartType: "Bar + Line Strip",
    description: "Touch-friendly operational strip for current shift pressure.",
    operationalQuestion: "Can the operator keep selling right now?",
    readiness: "working",
    dataStatus: "shared/mock",
    mockDataLabel: "Deterministic shift buckets.",
    confidence: 74,
    freshnessLabel: "Mock shift pulse.",
    promotionTarget: "Tablet operations pulse",
    promotionBoundary: productPromotionBoundary,
    sourceModule: "shared/prisma-charts",
    componentPath: "products/chart-lab/app/src/prisma-charts/components/LabEChartFrame.tsx",
    mockPath: sharedMockPath,
    registryPath,
    optionBuilderName: "shiftPulseStripOption",
    renderer: "svg",
    defaultHeight: 320,
    getOption: () => shiftPulseStripOption(mockTabletCharts.shiftPulseStrip)
  },
  {
    id: "tablet.sync-outbox-status-matrix",
    title: "Sync Outbox Status Matrix",
    shortName: "Outbox Matrix",
    surface: "tablet",
    family: "matrix",
    chartType: "Heatmap Matrix",
    description: "Touch-readable matrix for local outbox pressure.",
    operationalQuestion: "What needs sync attention without blocking local sales?",
    readiness: "working",
    dataStatus: "shared/mock",
    mockDataLabel: "Deterministic outbox matrix.",
    confidence: 68,
    freshnessLabel: "Mock sync state.",
    promotionTarget: "Tablet operations pulse",
    promotionBoundary: productPromotionBoundary,
    sourceModule: "shared/prisma-charts",
    componentPath: "products/chart-lab/app/src/prisma-charts/components/LabEChartFrame.tsx",
    mockPath: sharedMockPath,
    registryPath,
    optionBuilderName: "syncOutboxMatrixOption",
    renderer: "svg",
    defaultHeight: 340,
    getOption: () => syncOutboxMatrixOption(mockTabletCharts.syncOutboxStatusMatrix)
  },
  {
    id: "mobile.owner-pulse-timeline",
    title: "Owner Pulse Timeline",
    shortName: "Owner Pulse",
    surface: "mobile",
    family: "timeline",
    chartType: "Line + Incident Points",
    description: "Compact owner timeline for supervision.",
    operationalQuestion: "Is the operation improving or degrading recently?",
    readiness: "working",
    dataStatus: "shared/mock",
    mockDataLabel: "Deterministic owner pulse points.",
    confidence: 61,
    freshnessLabel: "Mock mobile timeline.",
    promotionTarget: "Mobile owner command",
    promotionBoundary: productPromotionBoundary,
    sourceModule: "shared/prisma-charts",
    componentPath: "products/chart-lab/app/src/prisma-charts/components/LabEChartFrame.tsx",
    mockPath: sharedMockPath,
    registryPath,
    optionBuilderName: "ownerPulseTimelineOption",
    renderer: "svg",
    defaultHeight: 320,
    getOption: () => ownerPulseTimelineOption(mockMobileCharts.ownerPulseTimeline)
  },
  {
    id: "mobile.action-inbox-priority-stack",
    title: "Action Inbox Priority Stack",
    shortName: "Action Stack",
    surface: "mobile",
    family: "stack",
    chartType: "Horizontal Stack",
    description: "Priority stack for action owners.",
    operationalQuestion: "Who owns the most urgent unresolved work?",
    readiness: "working",
    dataStatus: "shared/mock",
    mockDataLabel: "Deterministic action inbox stacks.",
    confidence: 63,
    freshnessLabel: "Mock action inbox.",
    promotionTarget: "Mobile action inbox",
    promotionBoundary: productPromotionBoundary,
    sourceModule: "shared/prisma-charts",
    componentPath: "products/chart-lab/app/src/prisma-charts/components/LabEChartFrame.tsx",
    mockPath: sharedMockPath,
    registryPath,
    optionBuilderName: "actionInboxPriorityStackOption",
    renderer: "svg",
    defaultHeight: 330,
    getOption: () => actionInboxPriorityStackOption(mockMobileCharts.actionInboxPriorityStack)
  },
  {
    id: "mobile.health-radar-compact",
    title: "Health Radar Compact",
    shortName: "Health Radar",
    surface: "mobile",
    family: "radar",
    chartType: "Radar",
    description: "Compact health dimensions without wrapping the main score.",
    operationalQuestion: "Which dimension explains the current health state?",
    readiness: "working",
    dataStatus: "shared/mock",
    mockDataLabel: "Deterministic radar axes.",
    confidence: 58,
    freshnessLabel: "Mock health dimensions.",
    promotionTarget: "Mobile owner command",
    promotionBoundary: productPromotionBoundary,
    sourceModule: "shared/prisma-charts",
    componentPath: "products/chart-lab/app/src/prisma-charts/components/LabEChartFrame.tsx",
    mockPath: sharedMockPath,
    registryPath,
    optionBuilderName: "healthRadarCompactOption",
    renderer: "svg",
    defaultHeight: 360,
    getOption: () => healthRadarCompactOption(mockMobileCharts.healthRadarCompact)
  },
  {
    id: "mobile.freshness-beacon-grid",
    title: "Freshness Rings",
    shortName: "Freshness",
    surface: "mobile",
    family: "rings",
    chartType: "Pictorial Beacon Grid",
    description: "Freshness beacons for data state and TTL.",
    operationalQuestion: "Can the owner trust the freshness of each module?",
    readiness: "working",
    dataStatus: "shared/mock",
    mockDataLabel: "Deterministic freshness beacons.",
    confidence: 57,
    freshnessLabel: "Mock freshness state.",
    promotionTarget: "Mobile source status",
    promotionBoundary: productPromotionBoundary,
    sourceModule: "shared/prisma-charts",
    componentPath: "products/chart-lab/app/src/prisma-charts/components/LabEChartFrame.tsx",
    mockPath: sharedMockPath,
    registryPath,
    optionBuilderName: "freshnessBeaconGridOption",
    renderer: "svg",
    defaultHeight: 320,
    getOption: () => freshnessBeaconGridOption(mockMobileCharts.freshnessBeaconGrid)
  },
  {
    id: "mobile.incident-spark-cards",
    title: "Incident Spark Cards",
    shortName: "Incident Sparks",
    surface: "mobile",
    family: "sparks",
    chartType: "Sparkline",
    description: "Small incident trend card for owner supervision.",
    operationalQuestion: "Which active incident is getting better or worse?",
    readiness: "working",
    dataStatus: "shared/mock",
    mockDataLabel: "First deterministic incident spark card.",
    confidence: 60,
    freshnessLabel: "Mock incident trend.",
    promotionTarget: "Mobile incident cards",
    promotionBoundary: productPromotionBoundary,
    sourceModule: "shared/prisma-charts",
    componentPath: "products/chart-lab/app/src/prisma-charts/components/LabEChartFrame.tsx",
    mockPath: sharedMockPath,
    registryPath,
    optionBuilderName: "incidentSparkOption",
    renderer: "svg",
    defaultHeight: 280,
    getOption: () => incidentSparkOption(mockMobileCharts.incidentSparkCards[0])
  },
  {
    id: "mobile.confidence-meter-bands",
    title: "Confidence Meter Bands",
    shortName: "Confidence Bands",
    surface: "mobile",
    family: "bands",
    chartType: "Linear Bands",
    description: "Linear confidence explanation without circular score ornament.",
    operationalQuestion: "Why should the owner trust or distrust the snapshot?",
    readiness: "working",
    dataStatus: "shared/mock",
    mockDataLabel: "Deterministic confidence bands.",
    confidence: 62,
    freshnessLabel: "Mock confidence state.",
    promotionTarget: "Mobile data quality panel",
    promotionBoundary: productPromotionBoundary,
    sourceModule: "shared/prisma-charts",
    componentPath: "products/chart-lab/app/src/prisma-charts/components/LabEChartFrame.tsx",
    mockPath: sharedMockPath,
    registryPath,
    optionBuilderName: "confidenceMeterBandsOption",
    renderer: "svg",
    defaultHeight: 320,
    getOption: () => confidenceMeterBandsOption(mockMobileCharts.confidenceMeterBands)
  },
  {
    id: "example.future-chart",
    title: "Example Future Chart",
    shortName: "Future",
    surface: "web",
    family: "future",
    chartType: "Placeholder Component",
    description: "A registered placeholder proving new charts can join without changing the lab shell.",
    operationalQuestion: "Can a future chart be added by creating one component, one mock provider, and one registry entry?",
    readiness: "placeholder",
    dataStatus: "lab/mock",
    mockDataLabel: "Lab-local placeholder mock.",
    confidence: 100,
    freshnessLabel: "Static extension example.",
    promotionTarget: "Any future PRISMA surface after explicit promotion.",
    promotionBoundary: productPromotionBoundary,
    sourceModule: "products/chart-lab/app",
    componentPath: "products/chart-lab/app/src/prisma-charts/components/ExampleFutureChart.tsx",
    mockPath: "products/chart-lab/app/src/prisma-charts/example-future.mock.ts",
    registryPath,
    defaultHeight: 320,
    Component: ExampleFutureChart,
    unavailableReason: "Placeholder only; create a real option builder or component before promotion."
  }
];

export const chartLabSurfaces = ["all", "pc", "tablet", "mobile", "web"] as const;
export const chartLabFamilies = ["all", ...Array.from(new Set(chartLabRegistry.map((chart) => chart.family)))] as const;
