// Bridge generated by playmam arr3.
// The Playwright entrypoint stays inside products/pc/app so @playwright/test resolves correctly.
const path = require("path");
const Module = require("module");
const pcRoot = path.resolve(__dirname, "..", "..");
const terminalRoot = path.resolve(pcRoot, "..", "..", "..");
const extraNodePaths = [
  path.join(pcRoot, "node_modules"),
  path.join(terminalRoot, "node_modules"),
  process.env.NODE_PATH || "",
].filter(Boolean);
process.env.NODE_PATH = extraNodePaths.join(path.delimiter);
Module._initPaths();

const { test, expect } = require("@playwright/test");
const { registerSurf8Tests } = require("F:/repos/hitech-os/tools/Plawright Mamastrophic/tests/surf8.all-surfaces.engine.cjs");
registerSurf8Tests(test, expect);
