// @generated by zerogate2 package
// Zero priority override governance gate.
// This source avoids spelling the forbidden bang-priority token literally.
// Runtime code builds the pattern from separate parts.

import path from 'node:path';
import process from 'node:process';
import { EXIT, MODES } from './constants.mjs';
import { findGitRoot } from './git-utils.mjs';
import { loadConfig, printConfigSummary } from './config.mjs';
import { scanRepository } from './scanner.mjs';
import { printConsoleReport, writeReports } from './reporters.mjs';
import { runSelfTest } from './self-test.mjs';
export async function main(argv=process.argv.slice(2)){ try{ const args=parseArgs(argv); if(args.selfTest)return await runSelfTest(); const repoRoot=path.resolve(args.root||findGitRoot(process.cwd())); const config=loadConfig(repoRoot,args.config); if(args.printConfig){ console.log(JSON.stringify(printConfigSummary(config),null,2)); return EXIT.PASS; } const scan=await scanRepository({repoRoot,mode:args.mode||config.behavior?.scanModeDefault||MODES.TRACKED,config,explain:args.explain||config.behavior?.explainByDefault,files:args.files}); let reports=null; if(args.writeReports||args.reportDir||scan.findings.length>0)reports=writeReports(scan,{reportDir:args.reportDir,maxMarkdownFindings:args.maxMarkdownFindings}); const code=printConsoleReport(scan,{quiet:args.quiet,maxConsoleFindings:args.maxConsoleFindings||config.behavior?.maxConsoleFindings||60}); if(reports&&!args.quiet)console.log(`Reports: ${reports.reportDir}`); return code; }catch(e){ console.error('ZERO PRIORITY GATE: ERROR'); console.error(e?.stack||String(e)); return EXIT.ERROR; } }
export function parseArgs(argv){ const a={mode:'',root:'',config:'',reportDir:'',explain:false,quiet:false,selfTest:false,printConfig:false,writeReports:false,files:[],maxConsoleFindings:60,maxMarkdownFindings:120}; for(let i=0;i<argv.length;i++){ const x=argv[i]; if(x==='--root')a.root=argv[++i]||''; else if(x==='--config')a.config=argv[++i]||''; else if(x==='--mode')a.mode=argv[++i]||''; else if(x==='--report-dir')a.reportDir=argv[++i]||''; else if(x==='--explain')a.explain=true; else if(x==='--quiet')a.quiet=true; else if(x==='--self-test')a.selfTest=true; else if(x==='--print-config')a.printConfig=true; else if(x==='--write-reports')a.writeReports=true; else if(x==='--tracked')a.mode=MODES.TRACKED; else if(x==='--staged')a.mode=MODES.STAGED; else if(x==='--repo-tree')a.mode=MODES.REPO_TREE; else if(x==='--changed')a.mode=MODES.CHANGED; else if(x==='--max-console-findings')a.maxConsoleFindings=Number(argv[++i]||60); else if(x==='--max-markdown-findings')a.maxMarkdownFindings=Number(argv[++i]||120); else if(x==='--file')a.files.push(argv[++i]||''); else if(x.startsWith('--file='))a.files.push(x.slice(7)); else if(x==='--help'||x==='-h'){ printHelp(); process.exit(0); } else a.files.push(x); } return a; }
export function printHelp(){ console.log(`Zero Priority Gate\n\nUsage: node tools/quality/verify-zero-important.mjs [options]\n\n--tracked --staged --repo-tree --changed\n--explain --write-reports --report-dir <path>\n--self-test --print-config --file <path>`); }
