// @generated by zerogate2 package
// Zero priority override governance gate.
// This source avoids spelling the forbidden bang-priority token literally.
// Runtime code builds the pattern from separate parts.

import path from 'node:path';
import { DEFAULT_CONFIG_NAME, DEFAULT_EXCLUDED_DIRS, DEFAULT_INCLUDED_EXTENSIONS } from './constants.mjs';
import { parseJson, pathExists, writeJson } from './fs-utils.mjs';
export function defaultConfig(){ return {version:2,policyName:'Zero Priority Override Gate',excludeDirs:[...DEFAULT_EXCLUDED_DIRS],excludeGlobs:['**/.git/**','**/node_modules/**','**/.next/**','**/dist/**','**/build/**','**/coverage/**','**/.turbo/**','**/out/**'],includedExtensions:[...DEFAULT_INCLUDED_EXTENSIONS],includeDocs:true,includeExtensionless:false,maxFileBytes:2_000_000,report:{writeJson:true,writeMarkdown:true,writeCsv:true},behavior:{failOnAnyFinding:true,explainByDefault:false,scanModeDefault:'tracked',maxConsoleFindings:60},surfaceRules:[]}; }
export function loadConfig(repoRoot,configPath=''){ const resolved=configPath?path.resolve(configPath):path.join(repoRoot,DEFAULT_CONFIG_NAME); const user=pathExists(resolved)?parseJson(resolved,{}):{}; return normalizeConfig({...defaultConfig(),...user,configPath:resolved}); }
export function normalizeConfig(c){ c.excludeDirs=unique(c.excludeDirs); c.excludeGlobs=unique(c.excludeGlobs); c.includedExtensions=unique(c.includedExtensions).map(e=>e.startsWith('.')?e:`.${e}`); c.report=c.report||{}; c.behavior=c.behavior||{}; c.surfaceRules=c.surfaceRules||[]; return c; }
export function unique(items){ return [...new Set((items||[]).map(String).filter(Boolean))]; }
export function writeDefaultConfig(repoRoot){ const p=path.join(repoRoot,DEFAULT_CONFIG_NAME); if(!pathExists(p))writeJson(p,defaultConfig()); return p; }
export function printConfigSummary(c){ return {configPath:c.configPath,includedExtensions:c.includedExtensions?.length||0,excludeDirs:c.excludeDirs?.length||0,excludeGlobs:c.excludeGlobs?.length||0,includeDocs:c.includeDocs,maxFileBytes:c.maxFileBytes}; }
