// @generated by zerogate2 package
// Zero priority override governance gate.
// This source avoids spelling the forbidden bang-priority token literally.
// Runtime code builds the pattern from separate parts.

export const TOOL_NAME = 'zero-important-gate';
export const TOOL_VERSION = '2.0.0';
export const BANG = String.fromCharCode(33);
export const WORD = 'important';
export const TOKEN_LABEL = 'priority override token';
export const DEFAULT_CONFIG_NAME = '.zero-important.json';
export const MODES = Object.freeze({ TRACKED:'tracked', STAGED:'staged', REPO_TREE:'repo-tree', CHANGED:'changed' });
export const EXIT = Object.freeze({ PASS:0, FOUND:1, CONFIG:2, ERROR:3, SELFTEST:4 });
export const DEFAULT_EXCLUDED_DIRS = Object.freeze(['.git','node_modules','.next','.turbo','dist','build','coverage','out','.cache','.parcel-cache','.vite','__pycache__','.venv','venv','vendor','target','.gradle','.idea','.vscode']);
export const DEFAULT_INCLUDED_EXTENSIONS = Object.freeze(['.css','.scss','.sass','.less','.pcss','.postcss','.ts','.tsx','.js','.jsx','.mjs','.cjs','.html','.htm','.mdx','.md','.json','.jsonc','.svg','.yml','.yaml','.vue','.svelte','.astro','.py']);
export const DEFAULT_BINARY_EXTENSIONS = Object.freeze(['.png','.jpg','.jpeg','.gif','.webp','.ico','.pdf','.woff','.woff2','.ttf','.eot','.otf','.mp4','.mov','.zip','.7z','.rar','.tar','.gz','.exe','.dll','.node']);
export const DEFAULT_SURFACE_RULES = Object.freeze([
  ['Tablet', /(^|\/)apps\/terminal-de-venta-system\/products\/tablet\//i],
  ['PC', /(^|\/)apps\/terminal-de-venta-system\/products\/pc\//i],
  ['Mobile', /(^|\/)apps\/terminal-de-venta-system\/products\/mobile\//i],
  ['Chart Lab', /(^|\/)apps\/terminal-de-venta-system\/products\/chart-lab\//i],
  ['Control Center', /(^|\/)apps\/terminal-de-venta-system\/prisma-control-center\//i],
  ['Shared UI', /(^|\/)apps\/terminal-de-venta-system\/products\/shared-ui\//i],
  ['Governance', /(^|\/)apps\/terminal-de-venta-system\/\.governance\//i],
  ['Docs', /(^|\/)(docs|apps\/terminal-de-venta-system\/docs)\//i],
  ['Tools', /(^|\/)(tools|apps\/terminal-de-venta-system\/tools)\//i],
  ['Packages', /(^|\/)packages\//i],
  ['Root', /^[^/]+$/i],
]);
export function buildForbiddenRegex(){ return new RegExp('\\' + BANG + '\\s*' + WORD, 'gi'); }
export function buildExactTokenForTempOnly(){ return BANG + WORD; }
