// @generated by zerogate2 package
// Zero priority override governance gate.
// This source avoids spelling the forbidden bang-priority token literally.
// Runtime code builds the pattern from separate parts.

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
export const normalizePath = (input) => String(input || '').replace(/\\/g,'/');
export const toNativePath = (input) => normalizePath(input).split('/').join(path.sep);
export function pathExists(p){ try{ fs.accessSync(p); return true; }catch{return false;} }
export function ensureDir(p){ fs.mkdirSync(p,{recursive:true}); }
export function readText(p){ return fs.readFileSync(p,'utf8'); }
export function writeText(p,t){ ensureDir(path.dirname(p)); fs.writeFileSync(p,String(t),'utf8'); }
export function writeJson(p,o){ writeText(p, JSON.stringify(o,null,2)+os.EOL); }
export function parseJson(p,fallback={}){ try{return JSON.parse(readText(p));}catch{return fallback;} }
export function looksBinary(buffer){ const sample=buffer.subarray(0,Math.min(buffer.length,4096)); if(!sample.length)return false; let zero=0, control=0; for(const b of sample){ if(b===0)zero++; if(b<8||(b>13&&b<32))control++; } return zero>0 || control/sample.length>0.12; }
export function safeReadText(p,maxBytes=2_000_000){ const st=fs.statSync(p); if(st.size>maxBytes)return {ok:false,reason:`file too large: ${st.size}`,text:'',size:st.size}; const buf=fs.readFileSync(p); if(looksBinary(buf))return {ok:false,reason:'binary-looking file skipped',text:'',size:st.size}; return {ok:true,reason:'',text:buf.toString('utf8'),size:st.size}; }
export const safeReadTextFile = safeReadText;
export function listFilesRecursive(root, excluded=new Set(), maxFiles=200000){ const out=[], stack=[root]; while(stack.length){ const dir=stack.pop(); let entries=[]; try{ entries=fs.readdirSync(dir,{withFileTypes:true}); }catch{ continue; } for(const e of entries){ const full=path.join(dir,e.name); if(e.isDirectory()){ if(!excluded.has(e.name)) stack.push(full); } else if(e.isFile()){ out.push(full); if(out.length>=maxFiles)return out; } } } return out; }
export function relativeTo(root,p){ return normalizePath(path.relative(root,p)); }
export function splitLines(t){ return String(t).split(/\r?\n/); }
export function getLineColumn(text,index){ let line=1,column=1; for(let i=0;i<index;i++){ if(text.charCodeAt(i)===10){ line++; column=1; } else column++; } return {line,column}; }
export function getLineAt(text,n){ return splitLines(text)[Math.max(0,n-1)] || ''; }
export function getLineRange(text,start,end){ const lines=splitLines(text), out=[]; for(let i=Math.max(1,start); i<=Math.min(lines.length,end); i++) out.push({line:i,text:lines[i-1]}); return out; }
export function createDefaultReportDir(repoRoot,label='zero-important-gate'){ const win='F:\\descargasf'; const stamp=new Date().toISOString().replace(/[-:T]/g,'').slice(0,12); if(process.platform==='win32' && pathExists(win)) return path.join(win,`${label} ${stamp}`); return path.join(repoRoot,'reports',label,stamp); }
export function csvEscape(v){ const t=String(v ?? ''); return /[",\r\n]/.test(t) ? `"${t.replace(/"/g,'""')}"` : t; }
export function writeCsv(p,rows,headers){ const lines=[headers.join(',')]; for(const r of rows) lines.push(headers.map(h=>csvEscape(r[h])).join(',')); writeText(p,lines.join(os.EOL)+os.EOL); }
export function escapeMarkdown(t){ return String(t).replace(/\|/g,'\\|').replace(/\r?\n/g,' '); }
export function unique(items){ return [...new Set(items.filter(Boolean))]; }
