// @generated by zerogate2 package
// Zero priority override governance gate.
// This source avoids spelling the forbidden bang-priority token literally.
// Runtime code builds the pattern from separate parts.

import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { normalizePath, pathExists } from './fs-utils.mjs';
export function runGit(args,cwd,options={}){ const r=spawnSync('git',args,{cwd,encoding:'utf8',errors:'replace',maxBuffer:options.maxBuffer||128*1024*1024}); return {code:r.status??1,stdout:r.stdout||'',stderr:r.stderr||'',args}; }
export function findGitRoot(start=process.cwd()){ const r=runGit(['rev-parse','--show-toplevel'],start); if(r.code===0&&r.stdout.trim())return r.stdout.trim(); let c=path.resolve(start); while(true){ if(pathExists(path.join(c,'.git')))return c; const n=path.dirname(c); if(n===c)break; c=n; } throw new Error('Could not locate git root'); }
export function listTrackedFiles(root){ const r=runGit(['ls-files','-z'],root); if(r.code!==0)throw new Error(`git ls-files failed: ${r.stderr||r.stdout}`); return r.stdout.split('\0').filter(Boolean).map(normalizePath); }
export function listStagedFiles(root){ const r=runGit(['diff','--cached','--name-only','-z'],root); if(r.code!==0)throw new Error(`git diff cached failed: ${r.stderr||r.stdout}`); return r.stdout.split('\0').filter(Boolean).map(normalizePath); }
export function listChangedFiles(root){ const r=runGit(['status','--porcelain=v1','-z'],root); if(r.code!==0)throw new Error(`git status failed: ${r.stderr||r.stdout}`); const raw=r.stdout.split('\0').filter(Boolean), files=[]; for(let i=0;i<raw.length;i++){ const st=raw[i].slice(0,2), file=raw[i].slice(3); files.push(normalizePath(file)); if(st.trim().startsWith('R')||st.trim().startsWith('C'))i++; } return files; }
export const getBranch=(root)=>runGit(['branch','--show-current'],root).stdout.trim();
export const getHead=(root)=>runGit(['rev-parse','HEAD'],root).stdout.trim();
export const getStatusShort=(root)=>runGit(['status','--short'],root).stdout;
