// @generated by zerogate2 package
// Zero priority override governance gate.
// This source avoids spelling the forbidden bang-priority token literally.
// Runtime code builds the pattern from separate parts.

import path from 'node:path';
import { DEFAULT_BINARY_EXTENSIONS, DEFAULT_EXCLUDED_DIRS, DEFAULT_INCLUDED_EXTENSIONS } from './constants.mjs';
import { normalizePath } from './fs-utils.mjs';
export function globToRegex(glob){ let s=String(glob).replace(/[.+^${}()|[\]\\]/g,'\\$&').replace(/\*\*/g,'§§').replace(/\*/g,'[^/]*').replace(/§§/g,'.*'); return new RegExp(`^${s}$`,'i'); }
export function buildIgnoreMatcher(config={}){ const excludedDirs=new Set(config.excludeDirs||DEFAULT_EXCLUDED_DIRS); const excludedGlobs=(config.excludeGlobs||[]).map(globToRegex); const includedExt=new Set(config.includedExtensions||DEFAULT_INCLUDED_EXTENSIONS); const binaryExt=new Set(config.binaryExtensions||DEFAULT_BINARY_EXTENSIONS); return { excludedDirNames:excludedDirs, shouldScan(relPath){ const rel=normalizePath(relPath); if(!rel||rel.startsWith('../'))return false; for(const part of rel.split('/')) if(excludedDirs.has(part)) return false; for(const rx of excludedGlobs) if(rx.test(rel)) return false; const ext=path.extname(rel).toLowerCase(); if(binaryExt.has(ext))return false; if(includedExt.has(ext))return true; return !ext && config.includeExtensionless; }, shouldIgnoreDirName(name){ return excludedDirs.has(name); } }; }
export function classifyFileKind(relPath){ const ext=path.extname(normalizePath(relPath).toLowerCase()); if(['.css','.scss','.sass','.less','.pcss','.postcss'].includes(ext))return 'style'; if(['.tsx','.jsx'].includes(ext))return 'component'; if(['.ts','.js','.mjs','.cjs'].includes(ext))return 'script'; if(['.html','.htm','.svg'].includes(ext))return 'markup'; if(['.md','.mdx'].includes(ext))return 'documentation'; if(['.json','.jsonc','.yml','.yaml'].includes(ext))return 'configuration'; if(ext==='.py')return 'python'; return 'other'; }
export function isLikelyGeneratedOrEvidence(relPath){ const rel=normalizePath(relPath).toLowerCase(); return ['/backup/','/backups/','/evidence/','/result/','/fail/','/failed/','/diagnostic/','/tmp/','/_local/','/rollback/','/snapshots/','/old/','/obsoletos/'].some(n=>rel.includes(n)); }
