// @generated by zerogate2 package
// Zero priority override governance gate.
// This source avoids spelling the forbidden bang-priority token literally.
// Runtime code builds the pattern from separate parts.

import path from 'node:path';
import { MODES } from './constants.mjs';
import { listTrackedFiles, listStagedFiles, listChangedFiles } from './git-utils.mjs';
import { listFilesRecursive, relativeTo, safeReadTextFile, toNativePath } from './fs-utils.mjs';
import { buildIgnoreMatcher } from './ignore.mjs';
import { detectForbiddenTokens } from './token-detector.mjs';
export async function scanRepository({repoRoot,mode=MODES.TRACKED,config={},explain=false,files=[]}){ const matcher=buildIgnoreMatcher(config); const relFiles=resolveFileSet({repoRoot,mode,matcher,files}); const findings=[], skipped=[], scanned=[]; for(const rel of relFiles){ if(!matcher.shouldScan(rel)){ skipped.push({relativePath:rel,reason:'ignored by config'}); continue; } const abs=path.join(repoRoot,toNativePath(rel)); const read=safeReadTextFile(abs,config.maxFileBytes||2_000_000); if(!read.ok){ skipped.push({relativePath:rel,reason:read.reason,size:read.size}); continue; } scanned.push({relativePath:rel,size:read.size}); findings.push(...detectForbiddenTokens({text:read.text,relativePath:rel,config,explain})); } return {repoRoot,mode,scannedFileCount:scanned.length,skippedFileCount:skipped.length,candidateFileCount:relFiles.length,scanned,skipped,findings}; }
export function resolveFileSet({repoRoot,mode,matcher,files=[]}){ if(files.length)return files.map(f=>normalizeRelFromAny(repoRoot,f)); if(mode===MODES.TRACKED)return listTrackedFiles(repoRoot); if(mode===MODES.STAGED)return listStagedFiles(repoRoot); if(mode===MODES.CHANGED||mode==='changed')return listChangedFiles(repoRoot); if(mode===MODES.REPO_TREE)return listFilesRecursive(repoRoot,matcher.excludedDirNames).map(abs=>relativeTo(repoRoot,abs)); throw new Error(`Unsupported scan mode: ${mode}`); }
export function normalizeRelFromAny(repoRoot,filePath){ if(path.isAbsolute(filePath))return relativeTo(repoRoot,filePath); return String(filePath).replace(/\\/g,'/'); }
export function buildScanStats(scanResult){ const byFile=new Map(), bySurface=new Map(); for(const f of scanResult.findings){ byFile.set(f.relativePath,(byFile.get(f.relativePath)||0)+1); bySurface.set(f.surface,(bySurface.get(f.surface)||0)+1); } return {scannedFileCount:scanResult.scannedFileCount,skippedFileCount:scanResult.skippedFileCount,occurrenceCount:scanResult.findings.length,fileCount:byFile.size,byFile:[...byFile.entries()].map(([relativePath,count])=>({relativePath,count})).sort((a,b)=>b.count-a.count),bySurface:[...bySurface.entries()].map(([surface,count])=>({surface,count})).sort((a,b)=>b.count-a.count)}; }
