// @generated by zerogate2 package
// Zero priority override governance gate.
// This source avoids spelling the forbidden bang-priority token literally.
// Runtime code builds the pattern from separate parts.

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { buildExactTokenForTempOnly, EXIT } from './constants.mjs';
import { detectForbiddenTokens } from './token-detector.mjs';
import { getCssContextForIndex } from './css-context.mjs';
import { detectNearbyPatterns } from './pattern-detector.mjs';
export async function runSelfTest(){ const token=buildExactTokenForTempOnly(); const cases=[['clean css','.panel { color: red; }',0],['basic',`.panel { color: red ${token}; }`,1],['spaced',`.panel { color: red ${token.slice(0,1)} ${token.slice(1)}; }`,1],['upper',`.panel { color: red ${token.toUpperCase()}; }`,1],['tsx',`export const x = <div style={{ color: "red ${token}" }} />;`,1]]; const failures=[]; for(const [name,text,expected] of cases){ const findings=detectForbiddenTokens({text,relativePath:`${name}.css`,explain:true}); if(findings.length!==expected)failures.push(`${name}: expected ${expected}, got ${findings.length}`); } const css=`.a { color: red; }\n.b::before { display: none ${token}; position: absolute; inset: 0; }`, idx=css.indexOf(token); if(!getCssContextForIndex(css,idx).selector.includes('.b::before'))failures.push('css context missed pseudo selector'); if(!detectNearbyPatterns(css,idx).some(p=>p.id==='display-none'))failures.push('pattern detector missed display none'); const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'zero-priority-self-test-')); fs.writeFileSync(path.join(tmp,'README.txt'),'self test temp','utf8'); fs.rmSync(tmp,{recursive:true,force:true}); if(failures.length){ console.error('ZERO PRIORITY GATE SELF TEST: FAIL'); for(const f of failures)console.error(`- ${f}`); return EXIT.SELFTEST; } console.log('ZERO PRIORITY GATE SELF TEST: PASS'); return EXIT.PASS; }
