#!/usr/bin/env python3
"""Generate the self-contained PRISMA Tablet visual runtime from RIFAT authority."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

SCRIPT_PATH = Path(__file__).resolve()
PRISMA_HTML_ROOT = SCRIPT_PATH.parents[1]
REPO_ROOT = PRISMA_HTML_ROOT.parent
AUTHORITY_ROOT = PRISMA_HTML_ROOT / "authority" / "rifat"
TABLET_AUTHORITY = AUTHORITY_ROOT / "tablet"
TABLET_APP = REPO_ROOT / "apps" / "terminal-de-venta-system" / "products" / "tablet" / "app"
RUNTIME_ROOT = TABLET_APP / "generated" / "prisma-visual-runtime"
PRISMA_UI_SOURCE = AUTHORITY_ROOT / "prisma-ui"
PRISMA_UI_OUTPUT = REPO_ROOT / "apps" / "terminal-de-venta-system" / ".prisma-ui"
AUTHORITY_REPO = "hitech-os-prisma-html/prisma-html"
HEX40 = re.compile(r"^[0-9a-f]{40}$")


def canonical_json(value: Any) -> bytes:
    return (json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n").encode("utf-8")


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def rel_repo(path: Path) -> str:
    return path.relative_to(REPO_ROOT).as_posix()


def git_head() -> str:
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=REPO_ROOT,
        check=True,
        text=True,
        capture_output=True,
    )
    return result.stdout.strip().lower()


def generated_header(source: str) -> bytes:
    return (
        "/* @generated by prisma-html/tools/generate_tablet_visual_runtime.py\n"
        f" * canonical-source: prisma-html/authority/rifat/{source}\n"
        " * manual-edits-forbidden: true\n"
        " */\n"
    ).encode("utf-8")


def tokens_typescript(contract: dict[str, Any]) -> bytes:
    responsive = contract["responsive"]
    colors = contract["tokens"]["color"]
    radii = contract["tokens"]["radii"]
    spacing = contract["tokens"]["spacing"]
    payload = {
        "name": "PRISMA RIFAT Atlas Tablet Runtime",
        "dataAttribute": "PRISMA_RIFAT_ATLAS_TABLET_V1",
        "version": contract["version"],
        "canonicalViewport": responsive["canonicalViewport"],
        "responsiveZoomChecks": responsive["zoomChecks"],
        "touchTargetPx": contract["tokens"]["touchTargetPx"],
        "bodyTextMinPx": contract["tokens"]["typography"]["bodyMinPx"],
        "criticalLabelMinPx": contract["tokens"]["typography"]["criticalLabelMinPx"],
        "actionTextMinPx": contract["tokens"]["typography"]["actionMinPx"],
        "tokens": colors,
        "scale": {
            "radiusControl": radii["control"],
            "radiusPanel": radii["panel"],
            "panelPadding": spacing["panel"],
            "shellGap": spacing["gap"],
        },
    }
    text = (
        "// @generated by prisma-html/tools/generate_tablet_visual_runtime.py\n"
        "// Manual edits are forbidden; edit prisma-html/authority/rifat instead.\n"
        f"export const PRISMA_TABLET_VISUAL_RUNTIME = {json.dumps(payload, indent=2, ensure_ascii=False)} as const;\n\n"
        "export const PRISMA_TABLET_VISUAL_V2 = PRISMA_TABLET_VISUAL_RUNTIME;\n"
        "export type PrismaTabletVisualRuntimeToken = typeof PRISMA_TABLET_VISUAL_RUNTIME;\n"
    )
    return text.encode("utf-8")


def collect_expected(authority_commit: str) -> tuple[dict[Path, bytes], dict[str, Any], dict[str, Any]]:
    contract = load_json(TABLET_AUTHORITY / "runtime.contract.json")
    routes = load_json(TABLET_AUTHORITY / "routes.json")
    sources = load_json(TABLET_AUTHORITY / "css-source-manifest.json")
    expected: dict[Path, bytes] = {}

    core_parts: list[bytes] = []
    for source in sources["coreFragments"]:
        source_path = AUTHORITY_ROOT / source
        core_parts.append(generated_header(source))
        core_parts.append(source_path.read_bytes().replace(b"\r\n", b"\n").rstrip() + b"\n")
    expected[REPO_ROOT / sources["coreOutput"]] = b"\n".join(core_parts)

    for entry in sources["moduleSources"]:
        source_path = AUTHORITY_ROOT / entry["source"]
        expected[REPO_ROOT / entry["output"]] = (
            generated_header(entry["source"])
            + source_path.read_bytes().replace(b"\r\n", b"\n").lstrip(b"\xef\xbb\xbf")
        )

    for entry in sources["adapterSources"]:
        source_path = AUTHORITY_ROOT / entry["source"]
        extension = source_path.suffix
        prefix = (
            "// @generated by prisma-html/tools/generate_tablet_visual_runtime.py\n"
            "// Manual edits are forbidden; edit prisma-html/authority/rifat instead.\n"
        ).encode("utf-8") if extension in {".ts", ".tsx"} else b""
        expected[REPO_ROOT / entry["output"]] = prefix + source_path.read_bytes().replace(b"\r\n", b"\n")

    expected[RUNTIME_ROOT / "tokens.ts"] = tokens_typescript(contract)
    expected[RUNTIME_ROOT / "route-bindings.json"] = canonical_json(routes)
    expected[RUNTIME_ROOT / "materials.json"] = canonical_json(
        {
            "schema": "prisma.rifat.tablet.materials.v1",
            "version": contract["version"],
            "materials": contract["materials"],
            "accessibility": contract["accessibility"],
        }
    )
    expected[RUNTIME_ROOT / "assets.json"] = canonical_json(
        {
            "schema": "prisma.rifat.tablet.assets.v1",
            "version": contract["version"],
            "assets": contract["assets"],
        }
    )

    if PRISMA_UI_SOURCE.exists():
        for source_path in sorted(path for path in PRISMA_UI_SOURCE.rglob("*") if path.is_file()):
            relative = source_path.relative_to(PRISMA_UI_SOURCE)
            expected[PRISMA_UI_OUTPUT / relative] = source_path.read_bytes().replace(b"\r\n", b"\n")

    tracked_entries = [
        {
            "path": rel_repo(path),
            "bytes": len(content),
            "sha256": sha256_bytes(content),
        }
        for path, content in sorted(expected.items(), key=lambda item: rel_repo(item[0]))
    ]
    manifest = {
        "schema": "prisma.rifat.tablet.runtime-manifest.v1",
        "authority_repo": AUTHORITY_REPO,
        "authority_commit": authority_commit,
        "visual_runtime_version": contract["version"],
        "surface": "tablet",
        "generated": True,
        "manual_edits_forbidden": True,
        "route_count": routes["detected"],
        "customer_visible_route_count": routes["customerVisible"],
        "files": tracked_entries,
    }
    manifest_bytes = canonical_json(manifest)
    lock = {
        "authority_repo": AUTHORITY_REPO,
        "authority_commit": authority_commit,
        "visual_runtime_version": contract["version"],
        "surface": "tablet",
        "generated": True,
        "manual_edits_forbidden": True,
        "manifest_sha256": sha256_bytes(manifest_bytes),
    }
    expected[RUNTIME_ROOT / "runtime-manifest.json"] = manifest_bytes
    expected[RUNTIME_ROOT / "authority-lock.json"] = canonical_json(lock)
    expected[PRISMA_UI_OUTPUT / "AUTHORITY_LOCK.json"] = canonical_json(lock)
    return expected, manifest, lock


def verify_atlas(contract: dict[str, Any]) -> None:
    for path_key, hash_key in (("tokens", "tokensSha256"), ("css", "cssSha256")):
        target = PRISMA_HTML_ROOT / contract["atlas"][path_key]
        actual = hashlib.sha256(target.read_bytes()).hexdigest()
        expected = contract["atlas"][hash_key]
        if actual != expected:
            raise RuntimeError(f"Atlas hash mismatch for {target.relative_to(PRISMA_HTML_ROOT)}: {actual} != {expected}")


def write_or_check(expected: dict[Path, bytes], check: bool) -> list[str]:
    problems: list[str] = []
    for path, content in sorted(expected.items(), key=lambda item: rel_repo(item[0])):
        if check:
            if not path.exists():
                problems.append(f"missing:{rel_repo(path)}")
            elif path.read_bytes() != content:
                problems.append(f"drift:{rel_repo(path)}")
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_bytes() != content:
            path.write_bytes(content)
    return problems


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--authority-commit", default="")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    contract = load_json(TABLET_AUTHORITY / "runtime.contract.json")
    verify_atlas(contract)

    authority_commit = args.authority_commit.lower()
    if args.check and not authority_commit:
        lock_path = RUNTIME_ROOT / "authority-lock.json"
        if not lock_path.exists():
            print("RIFAT_RUNTIME_CHECK_FAIL: missing authority lock", file=sys.stderr)
            return 1
        authority_commit = load_json(lock_path)["authority_commit"]
    if not HEX40.fullmatch(authority_commit):
        print("RIFAT_RUNTIME_FAIL: --authority-commit must be a 40-character lowercase Git SHA", file=sys.stderr)
        return 2

    expected, manifest, lock = collect_expected(authority_commit)
    problems = write_or_check(expected, args.check)
    if problems:
        print(json.dumps({"status": "FAIL", "problems": problems}, indent=2))
        return 1

    result = {
        "status": "PASS",
        "mode": "check" if args.check else "generate",
        "authority_commit": authority_commit,
        "visual_runtime_version": lock["visual_runtime_version"],
        "manifest_sha256": lock["manifest_sha256"],
        "generated_file_count": len(manifest["files"]),
        "route_count": manifest["route_count"],
        "customer_visible_route_count": manifest["customer_visible_route_count"],
        "head": git_head(),
    }
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
