from __future__ import annotations

from pathlib import Path
from .common import SCHEMA_VERSION, ensure_dir, utc_now, write_json, write_text
from .config import load_path_policies, load_system_config, load_parallel_manifest


def _baseline_refs(project_id: str, repo_root: Path) -> list[str]:
    system = load_system_config(repo_root)
    project_root = f"{system['projects_root']}/{project_id}"
    return [
        f"{project_root}/project_manifest.json",
        f"{project_root}/homologation_record.md",
        f"{project_root}/canonical_source_register.md",
        f"{project_root}/contract_register.md",
    ]


def build_run_manifest(project_id: str, run_id: str, objective: str, repo_root: Path) -> dict:
    system = load_system_config(repo_root)
    return {
        'schema_version': SCHEMA_VERSION,
        'project_id': project_id,
        'run_id': run_id,
        'created_at_utc': utc_now(),
        'status': 'planned',
        'objective': objective,
        'package_ids': system['active_package_ids'],
        'mission_control': system['mission_control']['id'],
        'project_root': f"{system['projects_root']}/{project_id}",
        'baseline_refs': _baseline_refs(project_id, repo_root),
        'communication_policy_ref': '00-governance-core/docs/control/inter_chat_communication_policy.md',
        'readiness_gates_ref': '00-governance-core/docs/control/framework_readiness_gates.md',
        'notes': 'Generated by universal_execution_framework.',
    }


def build_round_manifest(project_id: str, run_id: str, round_id: str, repo_root: Path) -> dict:
    system = load_system_config(repo_root)
    return {
        'schema_version': SCHEMA_VERSION,
        'project_id': project_id,
        'run_id': run_id,
        'round_id': round_id,
        'created_at_utc': utc_now(),
        'status': 'planned',
        'package_ids': system['active_package_ids'],
        'mission_control': system['mission_control']['id'],
        'baseline_refs': _baseline_refs(project_id, repo_root),
        'communication_policy_ref': '00-governance-core/docs/control/inter_chat_communication_policy.md',
        'waiver_policy_ref': '00-governance-core/docs/control/waiver_and_exception_policy.md',
        'notes': 'Generated by universal_execution_framework.',
    }


def build_work_packet(project_id: str, run_id: str, round_id: str, package_id: str, repo_root: Path) -> dict:
    policies = load_path_policies(repo_root)
    manifest = load_parallel_manifest(repo_root)
    policy = policies[package_id]
    package = manifest[package_id]
    return {
        'schema_version': SCHEMA_VERSION,
        'project_id': project_id,
        'run_id': run_id,
        'round_id': round_id,
        'package_id': package_id,
        'objective': package['goal'],
        'dependencies': package['depends_on'],
        'allowed_paths': policy['allowed_paths'],
        'forbidden_paths': policy['forbidden_paths'],
        'required_outputs': [
            'bundle_manifest.json',
            'package_report.json',
            'notes/summary.md',
            'payload/**',
        ],
        'frozen_input_refs': [
            '00-governance-core/**',
            f'{package_id}/**',
        ],
        'baseline_refs': _baseline_refs(project_id, repo_root),
        'contract_refs': [],
        'waiver_refs': [],
        'communication_rules': [
            'Do not communicate directly with other package chats.',
            'Route cross-package questions through governance using artifact references.',
        ],
        'rules': [
            'Do not delete files unless explicitly authorized by a decision record.',
            'Do not edit paths outside ownership.',
            'Keep output deterministic.',
        ],
    }


def initialize_run(project_id: str, run_id: str, objective: str, repo_root: Path) -> dict:
    system = load_system_config(repo_root)
    run_root = repo_root / system['runs_root'] / run_id
    ensure_dir(run_root / system['rounds_dir_name'])
    ensure_dir(run_root / system['decisions_dir_name'])
    manifest = build_run_manifest(project_id, run_id, objective, repo_root)
    write_json(run_root / 'run_manifest.json', manifest)
    write_text(
        run_root / 'README.md',
        f"# {run_id}\n\nThis folder stores the run manifest, decisions, rounds, and integration evidence for the run.\n",
    )
    return manifest


def initialize_round(project_id: str, run_id: str, round_id: str, repo_root: Path) -> dict:
    system = load_system_config(repo_root)
    round_root = repo_root / system['runs_root'] / run_id / system['rounds_dir_name'] / round_id
    ensure_dir(round_root / system['incoming_dir_name'])
    ensure_dir(round_root / system['reports_dir_name'])
    ensure_dir(round_root / system['packets_dir_name'])
    ensure_dir(round_root / system['prompts_dir_name'])
    manifest = build_round_manifest(project_id, run_id, round_id, repo_root)
    write_json(round_root / 'round_manifest.json', manifest)
    write_text(
        round_root / 'README.md',
        f"# {round_id}\n\nThis folder stores packets, bundles, and reports for the round.\n",
    )
    return manifest
