# Bridge generated by playmam arr3.
# Source of truth:
# F:\repos\hitech-os\tools\Plawright Mamastrophic\core\surf8_discovery.py

import runpy
from pathlib import Path

target = Path(r"F:\repos\hitech-os\tools\Plawright Mamastrophic\core\surf8_discovery.py")
if not target.exists():
    raise SystemExit(f"Central surf8_discovery.py missing: {target}")
runpy.run_path(str(target), run_name="__main__")
