from __future__ import annotations

import datetime as dt
import json
from pathlib import Path
from .errors import GitHubError

PR_TITLE = "PRISMA curated recovery: automated AutoGit batch"


def _policy_blocked(text: str) -> bool:
    low = (text or "").lower()
    return (
        "base branch policy prohibits" in low
        or "add the `--auto` flag" in low
        or "add the --auto flag" in low
        or "not mergeable" in low
    )


def _auto_merge_disabled(text: str) -> bool:
    low = (text or "").lower()
    return (
        "auto merge is not allowed" in low
        or "enablepullrequestautomerge" in low
        or "auto-merge is disabled" in low
        or "auto merge is disabled" in low
    )


def _read_latest_state(ctx) -> dict:
    try:
        p = ctx.out / "autogit latest state.json"
        if p.exists():
            return json.loads(p.read_text(encoding="utf-8"))
    except Exception as exc:
        ctx.artifact("latest_state_read_warning.txt").write_text(repr(exc), encoding="utf-8")
    return {}


def _try_reuse_open_pr(ctx, gh, head_sha: str):
    state = _read_latest_state(ctx)
    opened = state.get("opened_pr") or {}
    url = opened.get("url") or ""
    if not url:
        return None
    view = gh.view(url)
    ctx.artifact("gh_pr_reuse_candidate.json").write_text(json.dumps(view, indent=2, ensure_ascii=False), encoding="utf-8")
    state_name = str(view.get("state", "")).upper()
    head_oid = str(view.get("headRefOid") or "")
    if state_name == "OPEN" and head_oid and head_oid == head_sha:
        return {"url": url, "number": opened.get("number", ""), "head": opened.get("head", view.get("headRefName", "")), "base": opened.get("base", view.get("baseRefName", "")), "reused": True}
    return None


def _write_pr_summary(ctx, name: str, data: dict) -> None:
    ctx.artifact(name).write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")


def run_pr_gate(ctx, git, gh):
    git.assert_clean()
    remote = ctx.policy.remote
    base = ctx.policy.repo_expected_branch
    git.fetch(remote, base)
    origin = f"{remote}/{base}"
    if not git.is_ancestor(origin, "HEAD"):
        raise GitHubError("origin/main is not ancestor of HEAD; divergence detected", phase="pr-gate")

    ahead = git.ahead_count(origin, "HEAD")
    if ahead <= 0:
        return {"result": "nothing_to_push", "ahead": 0}

    git.diff_check(f"{origin}..HEAD")
    head_sha = git.rev_parse("HEAD")

    commits = ctx.shell.run(["git", "log", "--oneline", f"{origin}..HEAD"], check=True, name="git_log_pr_commits").stdout
    pr_body = ctx.artifact("PR_BODY.md")
    pr_body.write_text(
        "## AutoGit curated batch\n\n"
        "```text\n"
        f"{commits.strip()}\n"
        "```\n\n"
        f"Ahead commits: {ahead}\n\n"
        "This PR was generated by AutoGit Curator. Immediate merge is attempted only after local validation and GitHub gate checks.\n",
        encoding="utf-8",
    )

    reused = _try_reuse_open_pr(ctx, gh, head_sha)
    if reused:
        pr = reused
        ctx.opened_pr = pr
        ctx.write_state("pr-reused", pr)
    else:
        branch = f"{ctx.policy.remote_branch_prefix}-{dt.datetime.now().strftime('%Y%m%d-%H%M%S')}"
        git.push_head(branch, remote)
        pr_obj = gh.create_pr(PR_TITLE, str(pr_body), base, branch)
        pr = pr_obj.__dict__
        pr["reused"] = False
        ctx.opened_pr = pr
        ctx.write_state("pr-created", pr)

    ok, checks = gh.checks_watch(pr["url"])
    ctx.artifact("gh_checks_watch.txt").write_text(checks, encoding="utf-8")
    if not ok:
        gh.capture_failed_check_logs(pr["url"], ctx.report_dir, "checks_failed")
        raise GitHubError("GitHub checks failed", phase="pr-gate")

    merged, text = gh.merge(pr["url"], auto=False, delete_branch=True)
    ctx.artifact("gh_merge_attempt.txt").write_text(text, encoding="utf-8")
    auto = False
    admin = False

    if not merged:
        if not _policy_blocked(text):
            gh.capture_failed_check_logs(pr["url"], ctx.report_dir, "merge_failed")
            raise GitHubError("PR merge failed", phase="pr-gate", detail={"text": text})

        auto = True
        ok_auto, text_auto = gh.merge(pr["url"], auto=True, delete_branch=True)
        ctx.artifact("gh_auto_merge_enable.txt").write_text(text_auto, encoding="utf-8")

        if ok_auto:
            status, view = gh.wait_merged(pr["url"], ctx.policy.auto_merge_wait_seconds, 30)
            _write_pr_summary(ctx, "gh_auto_merge_final.json", {"status": status, "view": view})
            if status == "merged":
                merged = True
            elif status == "pending":
                # This is not fake green: PR is left open and auto-merge is enabled.
                result = {"result": "auto_merge_pending", "pr": pr, "auto": True, "view": view, "ahead": ahead}
                ctx.write_state("auto-merge-pending", result)
                return result
            else:
                raise GitHubError("Auto-merge reached terminal state without merge", phase="pr-gate", detail={"status": status, "view": view})
        else:
            # Auto-merge is not enabled for this repo. Do not close PR or delete branch.
            view = gh.view(pr["url"])
            policy_payload = {"merge_attempt": text, "auto_merge_attempt": text_auto, "pr_view": view, "pr": pr, "ahead": ahead}
            _write_pr_summary(ctx, "branch_policy_blocked_auto_disabled.json", policy_payload)

            if ctx.policy.allow_admin_merge:
                admin = True
                ok_admin, text_admin = gh.merge(pr["url"], admin=True, delete_branch=True)
                ctx.artifact("gh_admin_merge_attempt.txt").write_text(text_admin, encoding="utf-8")
                if not ok_admin:
                    raise GitHubError("Admin merge failed after auto-merge was unavailable", phase="pr-gate", detail={"text": text_admin})
                merged = True
            else:
                result = {
                    "result": "merge_blocked_auto_merge_disabled",
                    "pr": pr,
                    "auto": False,
                    "admin_merge_allowed": False,
                    "view": view,
                    "ahead": ahead,
                    "next": "Enable repository auto-merge, manually merge the PR, or rerun with AUTOGIT_ALLOW_ADMIN_MERGE=1 if you intentionally want admin bypass.",
                }
                ctx.write_state("merge-blocked-auto-disabled", result)
                return result

    if not merged:
        raise GitHubError("Internal PR gate state error: merge path ended without merged=true", phase="pr-gate")

    git.fetch(remote, base)
    git.ff_only(origin)
    ctx.final_head = git.rev_parse("HEAD")
    ctx.write_state("merged", {"pr": pr, "auto": auto, "admin": admin, "final_head": ctx.final_head})
    return {"result": "merged", "pr": pr, "auto_merge_enabled": auto, "admin_merge_used": admin, "final_head": ctx.final_head, "ahead": ahead}
