from __future__ import annotations

import unittest

from tools.hos.git_sentinel_modular.shared.contracts import (
    ArtifactFinding,
    CleanupAction,
    CleanupPlan,
    PredictionResult,
    RepairAction,
    RepairPlan,
    ScanResult,
    ScanStats,
    SecurityFinding,
    SentinelReport,
)


class ContractsTestCase(unittest.TestCase):
    def test_artifact_finding_validates(self):
        finding = ArtifactFinding(
            path="tools/_local/output.json",
            category="report",
            reason="generated by internal tool",
            confidence=0.95,
            tracked=False,
        ).validate()
        self.assertEqual(finding.category, "report")

    def test_artifact_finding_rejects_bad_confidence(self):
        with self.assertRaises(ValueError):
            ArtifactFinding(
                path="x",
                category="unknown",
                reason="bad",
                confidence=1.5,
            ).validate()

    def test_security_finding_rejects_bad_severity(self):
        with self.assertRaises(ValueError):
            SecurityFinding(
                rule_id="SEC001",
                path="secret.txt",
                severity="mega",
                message="bad severity",
            ).validate()

    def test_scan_result_roundtrip_shape(self):
        scan = ScanResult(
            repo_root="F:/repos/hitech-os",
            scan_id="scan-001",
            artifact_findings=[
                ArtifactFinding(
                    path="tools/_local/tmp.bin",
                    category="temporary",
                    reason="tmp output",
                    confidence=0.88,
                )
            ],
            security_findings=[
                SecurityFinding(
                    rule_id="SEC001",
                    path="apps/api/.env",
                    severity="high",
                    message="secret-like token",
                    secret_like=True,
                )
            ],
            stats=ScanStats(scanned_files=10, scanned_directories=3, artifact_findings=1, security_findings=1),
        ).validate()

        payload = scan.to_dict()
        self.assertEqual(payload["repo_root"], "F:/repos/hitech-os")
        self.assertEqual(len(payload["artifact_findings"]), 1)
        self.assertEqual(len(payload["security_findings"]), 1)

    def test_report_validates_nested_payloads(self):
        report = SentinelReport(
            report_id="report-001",
            repo_root="F:/repos/hitech-os",
            scan_result=ScanResult(
                repo_root="F:/repos/hitech-os",
                scan_id="scan-001",
                stats=ScanStats(scanned_files=1, scanned_directories=1),
            ),
            predictions=[
                PredictionResult(
                    candidate_path="apps/keystone/app/page.tsx",
                    risk_score=0.40,
                    confidence=0.75,
                    rationale=["recent churn", "ui surface"],
                )
            ],
            repair_plan=RepairPlan(
                dry_run=True,
                safe_actions=[
                    RepairAction(kind="notify", target_path="tools/report.md", reason="report-only")
                ],
            ),
            cleanup_plan=CleanupPlan(
                dry_run=True,
                actions=[
                    CleanupAction(
                        kind="quarantine",
                        target_path="tools/_local/out.bin",
                        reason="generated artifact",
                        quarantine_first=True,
                    )
                ],
            ),
        ).validate()

        self.assertTrue(report.repair_plan.dry_run)
        self.assertEqual(report.cleanup_plan.actions[0].kind, "quarantine")


if __name__ == "__main__":
    unittest.main()
