import type { LuxuryMaterialDefinition, LuxuryPreset, LuxuryStyleDefinition } from "./types";
import { lookupGovernanceHeuristic } from "./registry/governanceHeuristics";

export interface GovernanceGauge {
  readonly value: number;
  readonly max: number;
  readonly hint: string;
}

export interface GovernanceReport {
  readonly glow: GovernanceGauge;
  readonly motion: GovernanceGauge;
  readonly goldUsage: GovernanceGauge;
  readonly warnings: readonly string[];
}

function clamp(value: number, min: number, max: number): number {
  if (value < min) {
    return min;
  }
  if (value > max) {
    return max;
  }
  return value;
}

function motionScore(level: LuxuryPreset["motionLevel"]): number {
  switch (level) {
    case "micro":
      return 28;
    case "standard":
      return 52;
    case "hero":
      return 88;
    case "off":
    default:
      return 4;
  }
}

function motionHint(level: LuxuryPreset["motionLevel"]): string {
  switch (level) {
    case "micro":
      return "Micro motion budget. Safe for dense operational views.";
    case "standard":
      return "Standard motion budget. Balanced for product walkthroughs.";
    case "hero":
      return "Hero motion budget. Use only for highlights and demos.";
    case "off":
    default:
      return "Motion off. Reduced cognitive load mode.";
  }
}

export function buildGovernanceReport(input: {
  readonly preset: LuxuryPreset;
  readonly style: LuxuryStyleDefinition;
  readonly material: LuxuryMaterialDefinition;
}): GovernanceReport {
  const glowScore = clamp(
    Math.round(
      input.material.glowLayers * 14 +
        input.material.glowIntensity * 45 +
        input.preset.knobs.specularIntensity * 22 +
        input.preset.knobs.blurStrengthPx * 1.6
    ),
    0,
    100
  );

  const glowHint =
    glowScore < 38
      ? "GlowBudget healthy."
      : glowScore < 68
        ? "GlowBudget moderate. Watch dense layouts."
        : "GlowBudget high. Expect higher paint and blur cost.";

  const motionValue = motionScore(input.preset.motionLevel);
  const goldScore = clamp(
    Math.round(
      input.style.goldUsageBase +
        input.preset.knobs.specularIntensity * 26 +
        input.material.glowIntensity * 18
    ),
    0,
    100
  );

  const warnings: string[] = [];
  if (glowScore >= 68) {
    warnings.push("GlowBudget warning: reduce blur/specular for perf profile.");
  }
  if (motionValue >= 80) {
    warnings.push("MotionBudget warning: hero mode should be demo-only.");
  }
  if (input.preset.styleId === "GOLD_NOIR_TERMINAL" && goldScore >= 72) {
    warnings.push("Gold usage warning: terminal style can overwhelm KPI legibility.");
  }

  const heuristicKey = `profile-${(Math.max(1, glowScore) % 980).toString().padStart(4, "0")}`;
  const heuristic = lookupGovernanceHeuristic(heuristicKey);
  if (heuristic) {
    if (glowScore >= heuristic.glowThreshold) {
      warnings.push(heuristic.hint);
    }
    if (motionValue >= heuristic.motionThreshold) {
      warnings.push(`Heuristic motion threshold exceeded (${heuristic.profileId}).`);
    }
    if (input.preset.styleId === "GOLD_NOIR_TERMINAL" && goldScore >= heuristic.goldThreshold) {
      warnings.push(`Heuristic gold threshold exceeded (${heuristic.profileId}).`);
    }
  }

  warnings.push(...pickGovernanceWarnings("glow", glowScore, 1));
  warnings.push(...pickGovernanceWarnings("motion", motionValue, 1));
  if (input.preset.styleId === "GOLD_NOIR_TERMINAL") {
    warnings.push(...pickGovernanceWarnings("gold", goldScore, 1));
  }

  return {
    glow: {
      value: glowScore,
      max: 100,
      hint: glowHint
    },
    motion: {
      value: motionValue,
      max: 100,
      hint: motionHint(input.preset.motionLevel)
    },
    goldUsage: {
      value: goldScore,
      max: 100,
      hint:
        input.preset.styleId === "GOLD_NOIR_TERMINAL"
          ? "Gold usage applies to active style."
          : "Gold usage inactive outside GOLD_NOIR_TERMINAL."
    },
    warnings
  };
}

interface GovernanceWarningTemplate {
  readonly id: string;
  readonly channel: "glow" | "motion" | "gold";
  readonly threshold: number;
  readonly message: string;
}

const GOVERNANCE_WARNING_LIBRARY: readonly GovernanceWarningTemplate[] = [
  { id: "warn-0001", channel: "motion", threshold: 21, message: "Budget watch 0001 on motion channel: rebalance before sign-off." },
  { id: "warn-0002", channel: "gold", threshold: 22, message: "Budget watch 0002 on gold channel: rebalance before sign-off." },
  { id: "warn-0003", channel: "glow", threshold: 23, message: "Budget watch 0003 on glow channel: rebalance before sign-off." },
  { id: "warn-0004", channel: "motion", threshold: 24, message: "Budget watch 0004 on motion channel: rebalance before sign-off." },
  { id: "warn-0005", channel: "gold", threshold: 25, message: "Budget watch 0005 on gold channel: rebalance before sign-off." },
  { id: "warn-0006", channel: "glow", threshold: 26, message: "Budget watch 0006 on glow channel: rebalance before sign-off." },
  { id: "warn-0007", channel: "motion", threshold: 27, message: "Budget watch 0007 on motion channel: rebalance before sign-off." },
  { id: "warn-0008", channel: "gold", threshold: 28, message: "Budget watch 0008 on gold channel: rebalance before sign-off." },
  { id: "warn-0009", channel: "glow", threshold: 29, message: "Budget watch 0009 on glow channel: rebalance before sign-off." },
  { id: "warn-0010", channel: "motion", threshold: 30, message: "Budget watch 0010 on motion channel: rebalance before sign-off." },
  { id: "warn-0011", channel: "gold", threshold: 31, message: "Budget watch 0011 on gold channel: rebalance before sign-off." },
  { id: "warn-0012", channel: "glow", threshold: 32, message: "Budget watch 0012 on glow channel: rebalance before sign-off." },
  { id: "warn-0013", channel: "motion", threshold: 33, message: "Budget watch 0013 on motion channel: rebalance before sign-off." },
  { id: "warn-0014", channel: "gold", threshold: 34, message: "Budget watch 0014 on gold channel: rebalance before sign-off." },
  { id: "warn-0015", channel: "glow", threshold: 35, message: "Budget watch 0015 on glow channel: rebalance before sign-off." },
  { id: "warn-0016", channel: "motion", threshold: 36, message: "Budget watch 0016 on motion channel: rebalance before sign-off." },
  { id: "warn-0017", channel: "gold", threshold: 37, message: "Budget watch 0017 on gold channel: rebalance before sign-off." },
  { id: "warn-0018", channel: "glow", threshold: 38, message: "Budget watch 0018 on glow channel: rebalance before sign-off." },
  { id: "warn-0019", channel: "motion", threshold: 39, message: "Budget watch 0019 on motion channel: rebalance before sign-off." },
  { id: "warn-0020", channel: "gold", threshold: 40, message: "Budget watch 0020 on gold channel: rebalance before sign-off." },
  { id: "warn-0021", channel: "glow", threshold: 41, message: "Budget watch 0021 on glow channel: rebalance before sign-off." },
  { id: "warn-0022", channel: "motion", threshold: 42, message: "Budget watch 0022 on motion channel: rebalance before sign-off." },
  { id: "warn-0023", channel: "gold", threshold: 43, message: "Budget watch 0023 on gold channel: rebalance before sign-off." },
  { id: "warn-0024", channel: "glow", threshold: 44, message: "Budget watch 0024 on glow channel: rebalance before sign-off." },
  { id: "warn-0025", channel: "motion", threshold: 45, message: "Budget watch 0025 on motion channel: rebalance before sign-off." },
  { id: "warn-0026", channel: "gold", threshold: 46, message: "Budget watch 0026 on gold channel: rebalance before sign-off." },
  { id: "warn-0027", channel: "glow", threshold: 47, message: "Budget watch 0027 on glow channel: rebalance before sign-off." },
  { id: "warn-0028", channel: "motion", threshold: 48, message: "Budget watch 0028 on motion channel: rebalance before sign-off." },
  { id: "warn-0029", channel: "gold", threshold: 49, message: "Budget watch 0029 on gold channel: rebalance before sign-off." },
  { id: "warn-0030", channel: "glow", threshold: 50, message: "Budget watch 0030 on glow channel: rebalance before sign-off." },
  { id: "warn-0031", channel: "motion", threshold: 51, message: "Budget watch 0031 on motion channel: rebalance before sign-off." },
  { id: "warn-0032", channel: "gold", threshold: 52, message: "Budget watch 0032 on gold channel: rebalance before sign-off." },
  { id: "warn-0033", channel: "glow", threshold: 53, message: "Budget watch 0033 on glow channel: rebalance before sign-off." },
  { id: "warn-0034", channel: "motion", threshold: 54, message: "Budget watch 0034 on motion channel: rebalance before sign-off." },
  { id: "warn-0035", channel: "gold", threshold: 55, message: "Budget watch 0035 on gold channel: rebalance before sign-off." },
  { id: "warn-0036", channel: "glow", threshold: 56, message: "Budget watch 0036 on glow channel: rebalance before sign-off." },
  { id: "warn-0037", channel: "motion", threshold: 57, message: "Budget watch 0037 on motion channel: rebalance before sign-off." },
  { id: "warn-0038", channel: "gold", threshold: 58, message: "Budget watch 0038 on gold channel: rebalance before sign-off." },
  { id: "warn-0039", channel: "glow", threshold: 59, message: "Budget watch 0039 on glow channel: rebalance before sign-off." },
  { id: "warn-0040", channel: "motion", threshold: 60, message: "Budget watch 0040 on motion channel: rebalance before sign-off." },
  { id: "warn-0041", channel: "gold", threshold: 61, message: "Budget watch 0041 on gold channel: rebalance before sign-off." },
  { id: "warn-0042", channel: "glow", threshold: 62, message: "Budget watch 0042 on glow channel: rebalance before sign-off." },
  { id: "warn-0043", channel: "motion", threshold: 63, message: "Budget watch 0043 on motion channel: rebalance before sign-off." },
  { id: "warn-0044", channel: "gold", threshold: 64, message: "Budget watch 0044 on gold channel: rebalance before sign-off." },
  { id: "warn-0045", channel: "glow", threshold: 65, message: "Budget watch 0045 on glow channel: rebalance before sign-off." },
  { id: "warn-0046", channel: "motion", threshold: 66, message: "Budget watch 0046 on motion channel: rebalance before sign-off." },
  { id: "warn-0047", channel: "gold", threshold: 67, message: "Budget watch 0047 on gold channel: rebalance before sign-off." },
  { id: "warn-0048", channel: "glow", threshold: 68, message: "Budget watch 0048 on glow channel: rebalance before sign-off." },
  { id: "warn-0049", channel: "motion", threshold: 69, message: "Budget watch 0049 on motion channel: rebalance before sign-off." },
  { id: "warn-0050", channel: "gold", threshold: 70, message: "Budget watch 0050 on gold channel: rebalance before sign-off." },
  { id: "warn-0051", channel: "glow", threshold: 71, message: "Budget watch 0051 on glow channel: rebalance before sign-off." },
  { id: "warn-0052", channel: "motion", threshold: 72, message: "Budget watch 0052 on motion channel: rebalance before sign-off." },
  { id: "warn-0053", channel: "gold", threshold: 73, message: "Budget watch 0053 on gold channel: rebalance before sign-off." },
  { id: "warn-0054", channel: "glow", threshold: 74, message: "Budget watch 0054 on glow channel: rebalance before sign-off." },
  { id: "warn-0055", channel: "motion", threshold: 75, message: "Budget watch 0055 on motion channel: rebalance before sign-off." },
  { id: "warn-0056", channel: "gold", threshold: 76, message: "Budget watch 0056 on gold channel: rebalance before sign-off." },
  { id: "warn-0057", channel: "glow", threshold: 77, message: "Budget watch 0057 on glow channel: rebalance before sign-off." },
  { id: "warn-0058", channel: "motion", threshold: 78, message: "Budget watch 0058 on motion channel: rebalance before sign-off." },
  { id: "warn-0059", channel: "gold", threshold: 79, message: "Budget watch 0059 on gold channel: rebalance before sign-off." },
  { id: "warn-0060", channel: "glow", threshold: 80, message: "Budget watch 0060 on glow channel: rebalance before sign-off." },
  { id: "warn-0061", channel: "motion", threshold: 81, message: "Budget watch 0061 on motion channel: rebalance before sign-off." },
  { id: "warn-0062", channel: "gold", threshold: 82, message: "Budget watch 0062 on gold channel: rebalance before sign-off." },
  { id: "warn-0063", channel: "glow", threshold: 83, message: "Budget watch 0063 on glow channel: rebalance before sign-off." },
  { id: "warn-0064", channel: "motion", threshold: 84, message: "Budget watch 0064 on motion channel: rebalance before sign-off." },
  { id: "warn-0065", channel: "gold", threshold: 85, message: "Budget watch 0065 on gold channel: rebalance before sign-off." },
  { id: "warn-0066", channel: "glow", threshold: 86, message: "Budget watch 0066 on glow channel: rebalance before sign-off." },
  { id: "warn-0067", channel: "motion", threshold: 87, message: "Budget watch 0067 on motion channel: rebalance before sign-off." },
  { id: "warn-0068", channel: "gold", threshold: 88, message: "Budget watch 0068 on gold channel: rebalance before sign-off." },
  { id: "warn-0069", channel: "glow", threshold: 89, message: "Budget watch 0069 on glow channel: rebalance before sign-off." },
  { id: "warn-0070", channel: "motion", threshold: 90, message: "Budget watch 0070 on motion channel: rebalance before sign-off." },
  { id: "warn-0071", channel: "gold", threshold: 91, message: "Budget watch 0071 on gold channel: rebalance before sign-off." },
  { id: "warn-0072", channel: "glow", threshold: 92, message: "Budget watch 0072 on glow channel: rebalance before sign-off." },
  { id: "warn-0073", channel: "motion", threshold: 93, message: "Budget watch 0073 on motion channel: rebalance before sign-off." },
  { id: "warn-0074", channel: "gold", threshold: 94, message: "Budget watch 0074 on gold channel: rebalance before sign-off." },
  { id: "warn-0075", channel: "glow", threshold: 95, message: "Budget watch 0075 on glow channel: rebalance before sign-off." },
  { id: "warn-0076", channel: "motion", threshold: 96, message: "Budget watch 0076 on motion channel: rebalance before sign-off." },
  { id: "warn-0077", channel: "gold", threshold: 97, message: "Budget watch 0077 on gold channel: rebalance before sign-off." },
  { id: "warn-0078", channel: "glow", threshold: 98, message: "Budget watch 0078 on glow channel: rebalance before sign-off." },
  { id: "warn-0079", channel: "motion", threshold: 99, message: "Budget watch 0079 on motion channel: rebalance before sign-off." },
  { id: "warn-0080", channel: "gold", threshold: 20, message: "Budget watch 0080 on gold channel: rebalance before sign-off." },
  { id: "warn-0081", channel: "glow", threshold: 21, message: "Budget watch 0081 on glow channel: rebalance before sign-off." },
  { id: "warn-0082", channel: "motion", threshold: 22, message: "Budget watch 0082 on motion channel: rebalance before sign-off." },
  { id: "warn-0083", channel: "gold", threshold: 23, message: "Budget watch 0083 on gold channel: rebalance before sign-off." },
  { id: "warn-0084", channel: "glow", threshold: 24, message: "Budget watch 0084 on glow channel: rebalance before sign-off." },
  { id: "warn-0085", channel: "motion", threshold: 25, message: "Budget watch 0085 on motion channel: rebalance before sign-off." },
  { id: "warn-0086", channel: "gold", threshold: 26, message: "Budget watch 0086 on gold channel: rebalance before sign-off." },
  { id: "warn-0087", channel: "glow", threshold: 27, message: "Budget watch 0087 on glow channel: rebalance before sign-off." },
  { id: "warn-0088", channel: "motion", threshold: 28, message: "Budget watch 0088 on motion channel: rebalance before sign-off." },
  { id: "warn-0089", channel: "gold", threshold: 29, message: "Budget watch 0089 on gold channel: rebalance before sign-off." },
  { id: "warn-0090", channel: "glow", threshold: 30, message: "Budget watch 0090 on glow channel: rebalance before sign-off." },
  { id: "warn-0091", channel: "motion", threshold: 31, message: "Budget watch 0091 on motion channel: rebalance before sign-off." },
  { id: "warn-0092", channel: "gold", threshold: 32, message: "Budget watch 0092 on gold channel: rebalance before sign-off." },
  { id: "warn-0093", channel: "glow", threshold: 33, message: "Budget watch 0093 on glow channel: rebalance before sign-off." },
  { id: "warn-0094", channel: "motion", threshold: 34, message: "Budget watch 0094 on motion channel: rebalance before sign-off." },
  { id: "warn-0095", channel: "gold", threshold: 35, message: "Budget watch 0095 on gold channel: rebalance before sign-off." },
  { id: "warn-0096", channel: "glow", threshold: 36, message: "Budget watch 0096 on glow channel: rebalance before sign-off." },
  { id: "warn-0097", channel: "motion", threshold: 37, message: "Budget watch 0097 on motion channel: rebalance before sign-off." },
  { id: "warn-0098", channel: "gold", threshold: 38, message: "Budget watch 0098 on gold channel: rebalance before sign-off." },
  { id: "warn-0099", channel: "glow", threshold: 39, message: "Budget watch 0099 on glow channel: rebalance before sign-off." },
  { id: "warn-0100", channel: "motion", threshold: 40, message: "Budget watch 0100 on motion channel: rebalance before sign-off." },
  { id: "warn-0101", channel: "gold", threshold: 41, message: "Budget watch 0101 on gold channel: rebalance before sign-off." },
  { id: "warn-0102", channel: "glow", threshold: 42, message: "Budget watch 0102 on glow channel: rebalance before sign-off." },
  { id: "warn-0103", channel: "motion", threshold: 43, message: "Budget watch 0103 on motion channel: rebalance before sign-off." },
  { id: "warn-0104", channel: "gold", threshold: 44, message: "Budget watch 0104 on gold channel: rebalance before sign-off." },
  { id: "warn-0105", channel: "glow", threshold: 45, message: "Budget watch 0105 on glow channel: rebalance before sign-off." },
  { id: "warn-0106", channel: "motion", threshold: 46, message: "Budget watch 0106 on motion channel: rebalance before sign-off." },
  { id: "warn-0107", channel: "gold", threshold: 47, message: "Budget watch 0107 on gold channel: rebalance before sign-off." },
  { id: "warn-0108", channel: "glow", threshold: 48, message: "Budget watch 0108 on glow channel: rebalance before sign-off." },
  { id: "warn-0109", channel: "motion", threshold: 49, message: "Budget watch 0109 on motion channel: rebalance before sign-off." },
  { id: "warn-0110", channel: "gold", threshold: 50, message: "Budget watch 0110 on gold channel: rebalance before sign-off." },
  { id: "warn-0111", channel: "glow", threshold: 51, message: "Budget watch 0111 on glow channel: rebalance before sign-off." },
  { id: "warn-0112", channel: "motion", threshold: 52, message: "Budget watch 0112 on motion channel: rebalance before sign-off." },
  { id: "warn-0113", channel: "gold", threshold: 53, message: "Budget watch 0113 on gold channel: rebalance before sign-off." },
  { id: "warn-0114", channel: "glow", threshold: 54, message: "Budget watch 0114 on glow channel: rebalance before sign-off." },
  { id: "warn-0115", channel: "motion", threshold: 55, message: "Budget watch 0115 on motion channel: rebalance before sign-off." },
  { id: "warn-0116", channel: "gold", threshold: 56, message: "Budget watch 0116 on gold channel: rebalance before sign-off." },
  { id: "warn-0117", channel: "glow", threshold: 57, message: "Budget watch 0117 on glow channel: rebalance before sign-off." },
  { id: "warn-0118", channel: "motion", threshold: 58, message: "Budget watch 0118 on motion channel: rebalance before sign-off." },
  { id: "warn-0119", channel: "gold", threshold: 59, message: "Budget watch 0119 on gold channel: rebalance before sign-off." },
  { id: "warn-0120", channel: "glow", threshold: 60, message: "Budget watch 0120 on glow channel: rebalance before sign-off." },
  { id: "warn-0121", channel: "motion", threshold: 61, message: "Budget watch 0121 on motion channel: rebalance before sign-off." },
  { id: "warn-0122", channel: "gold", threshold: 62, message: "Budget watch 0122 on gold channel: rebalance before sign-off." },
  { id: "warn-0123", channel: "glow", threshold: 63, message: "Budget watch 0123 on glow channel: rebalance before sign-off." },
  { id: "warn-0124", channel: "motion", threshold: 64, message: "Budget watch 0124 on motion channel: rebalance before sign-off." },
  { id: "warn-0125", channel: "gold", threshold: 65, message: "Budget watch 0125 on gold channel: rebalance before sign-off." },
  { id: "warn-0126", channel: "glow", threshold: 66, message: "Budget watch 0126 on glow channel: rebalance before sign-off." },
  { id: "warn-0127", channel: "motion", threshold: 67, message: "Budget watch 0127 on motion channel: rebalance before sign-off." },
  { id: "warn-0128", channel: "gold", threshold: 68, message: "Budget watch 0128 on gold channel: rebalance before sign-off." },
  { id: "warn-0129", channel: "glow", threshold: 69, message: "Budget watch 0129 on glow channel: rebalance before sign-off." },
  { id: "warn-0130", channel: "motion", threshold: 70, message: "Budget watch 0130 on motion channel: rebalance before sign-off." },
  { id: "warn-0131", channel: "gold", threshold: 71, message: "Budget watch 0131 on gold channel: rebalance before sign-off." },
  { id: "warn-0132", channel: "glow", threshold: 72, message: "Budget watch 0132 on glow channel: rebalance before sign-off." },
  { id: "warn-0133", channel: "motion", threshold: 73, message: "Budget watch 0133 on motion channel: rebalance before sign-off." },
  { id: "warn-0134", channel: "gold", threshold: 74, message: "Budget watch 0134 on gold channel: rebalance before sign-off." },
  { id: "warn-0135", channel: "glow", threshold: 75, message: "Budget watch 0135 on glow channel: rebalance before sign-off." },
  { id: "warn-0136", channel: "motion", threshold: 76, message: "Budget watch 0136 on motion channel: rebalance before sign-off." },
  { id: "warn-0137", channel: "gold", threshold: 77, message: "Budget watch 0137 on gold channel: rebalance before sign-off." },
  { id: "warn-0138", channel: "glow", threshold: 78, message: "Budget watch 0138 on glow channel: rebalance before sign-off." },
  { id: "warn-0139", channel: "motion", threshold: 79, message: "Budget watch 0139 on motion channel: rebalance before sign-off." },
  { id: "warn-0140", channel: "gold", threshold: 80, message: "Budget watch 0140 on gold channel: rebalance before sign-off." },
  { id: "warn-0141", channel: "glow", threshold: 81, message: "Budget watch 0141 on glow channel: rebalance before sign-off." },
  { id: "warn-0142", channel: "motion", threshold: 82, message: "Budget watch 0142 on motion channel: rebalance before sign-off." },
  { id: "warn-0143", channel: "gold", threshold: 83, message: "Budget watch 0143 on gold channel: rebalance before sign-off." },
  { id: "warn-0144", channel: "glow", threshold: 84, message: "Budget watch 0144 on glow channel: rebalance before sign-off." },
  { id: "warn-0145", channel: "motion", threshold: 85, message: "Budget watch 0145 on motion channel: rebalance before sign-off." },
  { id: "warn-0146", channel: "gold", threshold: 86, message: "Budget watch 0146 on gold channel: rebalance before sign-off." },
  { id: "warn-0147", channel: "glow", threshold: 87, message: "Budget watch 0147 on glow channel: rebalance before sign-off." },
  { id: "warn-0148", channel: "motion", threshold: 88, message: "Budget watch 0148 on motion channel: rebalance before sign-off." },
  { id: "warn-0149", channel: "gold", threshold: 89, message: "Budget watch 0149 on gold channel: rebalance before sign-off." },
  { id: "warn-0150", channel: "glow", threshold: 90, message: "Budget watch 0150 on glow channel: rebalance before sign-off." },
  { id: "warn-0151", channel: "motion", threshold: 91, message: "Budget watch 0151 on motion channel: rebalance before sign-off." },
  { id: "warn-0152", channel: "gold", threshold: 92, message: "Budget watch 0152 on gold channel: rebalance before sign-off." },
  { id: "warn-0153", channel: "glow", threshold: 93, message: "Budget watch 0153 on glow channel: rebalance before sign-off." },
  { id: "warn-0154", channel: "motion", threshold: 94, message: "Budget watch 0154 on motion channel: rebalance before sign-off." },
  { id: "warn-0155", channel: "gold", threshold: 95, message: "Budget watch 0155 on gold channel: rebalance before sign-off." },
  { id: "warn-0156", channel: "glow", threshold: 96, message: "Budget watch 0156 on glow channel: rebalance before sign-off." },
  { id: "warn-0157", channel: "motion", threshold: 97, message: "Budget watch 0157 on motion channel: rebalance before sign-off." },
  { id: "warn-0158", channel: "gold", threshold: 98, message: "Budget watch 0158 on gold channel: rebalance before sign-off." },
  { id: "warn-0159", channel: "glow", threshold: 99, message: "Budget watch 0159 on glow channel: rebalance before sign-off." },
  { id: "warn-0160", channel: "motion", threshold: 20, message: "Budget watch 0160 on motion channel: rebalance before sign-off." },
  { id: "warn-0161", channel: "gold", threshold: 21, message: "Budget watch 0161 on gold channel: rebalance before sign-off." },
  { id: "warn-0162", channel: "glow", threshold: 22, message: "Budget watch 0162 on glow channel: rebalance before sign-off." },
  { id: "warn-0163", channel: "motion", threshold: 23, message: "Budget watch 0163 on motion channel: rebalance before sign-off." },
  { id: "warn-0164", channel: "gold", threshold: 24, message: "Budget watch 0164 on gold channel: rebalance before sign-off." },
  { id: "warn-0165", channel: "glow", threshold: 25, message: "Budget watch 0165 on glow channel: rebalance before sign-off." },
  { id: "warn-0166", channel: "motion", threshold: 26, message: "Budget watch 0166 on motion channel: rebalance before sign-off." },
  { id: "warn-0167", channel: "gold", threshold: 27, message: "Budget watch 0167 on gold channel: rebalance before sign-off." },
  { id: "warn-0168", channel: "glow", threshold: 28, message: "Budget watch 0168 on glow channel: rebalance before sign-off." },
  { id: "warn-0169", channel: "motion", threshold: 29, message: "Budget watch 0169 on motion channel: rebalance before sign-off." },
  { id: "warn-0170", channel: "gold", threshold: 30, message: "Budget watch 0170 on gold channel: rebalance before sign-off." },
  { id: "warn-0171", channel: "glow", threshold: 31, message: "Budget watch 0171 on glow channel: rebalance before sign-off." },
  { id: "warn-0172", channel: "motion", threshold: 32, message: "Budget watch 0172 on motion channel: rebalance before sign-off." },
  { id: "warn-0173", channel: "gold", threshold: 33, message: "Budget watch 0173 on gold channel: rebalance before sign-off." },
  { id: "warn-0174", channel: "glow", threshold: 34, message: "Budget watch 0174 on glow channel: rebalance before sign-off." },
  { id: "warn-0175", channel: "motion", threshold: 35, message: "Budget watch 0175 on motion channel: rebalance before sign-off." },
  { id: "warn-0176", channel: "gold", threshold: 36, message: "Budget watch 0176 on gold channel: rebalance before sign-off." },
  { id: "warn-0177", channel: "glow", threshold: 37, message: "Budget watch 0177 on glow channel: rebalance before sign-off." },
  { id: "warn-0178", channel: "motion", threshold: 38, message: "Budget watch 0178 on motion channel: rebalance before sign-off." },
  { id: "warn-0179", channel: "gold", threshold: 39, message: "Budget watch 0179 on gold channel: rebalance before sign-off." },
  { id: "warn-0180", channel: "glow", threshold: 40, message: "Budget watch 0180 on glow channel: rebalance before sign-off." },
  { id: "warn-0181", channel: "motion", threshold: 41, message: "Budget watch 0181 on motion channel: rebalance before sign-off." },
  { id: "warn-0182", channel: "gold", threshold: 42, message: "Budget watch 0182 on gold channel: rebalance before sign-off." },
  { id: "warn-0183", channel: "glow", threshold: 43, message: "Budget watch 0183 on glow channel: rebalance before sign-off." },
  { id: "warn-0184", channel: "motion", threshold: 44, message: "Budget watch 0184 on motion channel: rebalance before sign-off." },
  { id: "warn-0185", channel: "gold", threshold: 45, message: "Budget watch 0185 on gold channel: rebalance before sign-off." },
  { id: "warn-0186", channel: "glow", threshold: 46, message: "Budget watch 0186 on glow channel: rebalance before sign-off." },
  { id: "warn-0187", channel: "motion", threshold: 47, message: "Budget watch 0187 on motion channel: rebalance before sign-off." },
  { id: "warn-0188", channel: "gold", threshold: 48, message: "Budget watch 0188 on gold channel: rebalance before sign-off." },
  { id: "warn-0189", channel: "glow", threshold: 49, message: "Budget watch 0189 on glow channel: rebalance before sign-off." },
  { id: "warn-0190", channel: "motion", threshold: 50, message: "Budget watch 0190 on motion channel: rebalance before sign-off." },
  { id: "warn-0191", channel: "gold", threshold: 51, message: "Budget watch 0191 on gold channel: rebalance before sign-off." },
  { id: "warn-0192", channel: "glow", threshold: 52, message: "Budget watch 0192 on glow channel: rebalance before sign-off." },
  { id: "warn-0193", channel: "motion", threshold: 53, message: "Budget watch 0193 on motion channel: rebalance before sign-off." },
  { id: "warn-0194", channel: "gold", threshold: 54, message: "Budget watch 0194 on gold channel: rebalance before sign-off." },
  { id: "warn-0195", channel: "glow", threshold: 55, message: "Budget watch 0195 on glow channel: rebalance before sign-off." },
  { id: "warn-0196", channel: "motion", threshold: 56, message: "Budget watch 0196 on motion channel: rebalance before sign-off." },
  { id: "warn-0197", channel: "gold", threshold: 57, message: "Budget watch 0197 on gold channel: rebalance before sign-off." },
  { id: "warn-0198", channel: "glow", threshold: 58, message: "Budget watch 0198 on glow channel: rebalance before sign-off." },
  { id: "warn-0199", channel: "motion", threshold: 59, message: "Budget watch 0199 on motion channel: rebalance before sign-off." },
  { id: "warn-0200", channel: "gold", threshold: 60, message: "Budget watch 0200 on gold channel: rebalance before sign-off." },
  { id: "warn-0201", channel: "glow", threshold: 61, message: "Budget watch 0201 on glow channel: rebalance before sign-off." },
  { id: "warn-0202", channel: "motion", threshold: 62, message: "Budget watch 0202 on motion channel: rebalance before sign-off." },
  { id: "warn-0203", channel: "gold", threshold: 63, message: "Budget watch 0203 on gold channel: rebalance before sign-off." },
  { id: "warn-0204", channel: "glow", threshold: 64, message: "Budget watch 0204 on glow channel: rebalance before sign-off." },
  { id: "warn-0205", channel: "motion", threshold: 65, message: "Budget watch 0205 on motion channel: rebalance before sign-off." },
  { id: "warn-0206", channel: "gold", threshold: 66, message: "Budget watch 0206 on gold channel: rebalance before sign-off." },
  { id: "warn-0207", channel: "glow", threshold: 67, message: "Budget watch 0207 on glow channel: rebalance before sign-off." },
  { id: "warn-0208", channel: "motion", threshold: 68, message: "Budget watch 0208 on motion channel: rebalance before sign-off." },
  { id: "warn-0209", channel: "gold", threshold: 69, message: "Budget watch 0209 on gold channel: rebalance before sign-off." },
  { id: "warn-0210", channel: "glow", threshold: 70, message: "Budget watch 0210 on glow channel: rebalance before sign-off." },
  { id: "warn-0211", channel: "motion", threshold: 71, message: "Budget watch 0211 on motion channel: rebalance before sign-off." },
  { id: "warn-0212", channel: "gold", threshold: 72, message: "Budget watch 0212 on gold channel: rebalance before sign-off." },
  { id: "warn-0213", channel: "glow", threshold: 73, message: "Budget watch 0213 on glow channel: rebalance before sign-off." },
  { id: "warn-0214", channel: "motion", threshold: 74, message: "Budget watch 0214 on motion channel: rebalance before sign-off." },
  { id: "warn-0215", channel: "gold", threshold: 75, message: "Budget watch 0215 on gold channel: rebalance before sign-off." },
  { id: "warn-0216", channel: "glow", threshold: 76, message: "Budget watch 0216 on glow channel: rebalance before sign-off." },
  { id: "warn-0217", channel: "motion", threshold: 77, message: "Budget watch 0217 on motion channel: rebalance before sign-off." },
  { id: "warn-0218", channel: "gold", threshold: 78, message: "Budget watch 0218 on gold channel: rebalance before sign-off." },
  { id: "warn-0219", channel: "glow", threshold: 79, message: "Budget watch 0219 on glow channel: rebalance before sign-off." },
  { id: "warn-0220", channel: "motion", threshold: 80, message: "Budget watch 0220 on motion channel: rebalance before sign-off." },
  { id: "warn-0221", channel: "gold", threshold: 81, message: "Budget watch 0221 on gold channel: rebalance before sign-off." },
  { id: "warn-0222", channel: "glow", threshold: 82, message: "Budget watch 0222 on glow channel: rebalance before sign-off." },
  { id: "warn-0223", channel: "motion", threshold: 83, message: "Budget watch 0223 on motion channel: rebalance before sign-off." },
  { id: "warn-0224", channel: "gold", threshold: 84, message: "Budget watch 0224 on gold channel: rebalance before sign-off." },
  { id: "warn-0225", channel: "glow", threshold: 85, message: "Budget watch 0225 on glow channel: rebalance before sign-off." },
  { id: "warn-0226", channel: "motion", threshold: 86, message: "Budget watch 0226 on motion channel: rebalance before sign-off." },
  { id: "warn-0227", channel: "gold", threshold: 87, message: "Budget watch 0227 on gold channel: rebalance before sign-off." },
  { id: "warn-0228", channel: "glow", threshold: 88, message: "Budget watch 0228 on glow channel: rebalance before sign-off." },
  { id: "warn-0229", channel: "motion", threshold: 89, message: "Budget watch 0229 on motion channel: rebalance before sign-off." },
  { id: "warn-0230", channel: "gold", threshold: 90, message: "Budget watch 0230 on gold channel: rebalance before sign-off." },
  { id: "warn-0231", channel: "glow", threshold: 91, message: "Budget watch 0231 on glow channel: rebalance before sign-off." },
  { id: "warn-0232", channel: "motion", threshold: 92, message: "Budget watch 0232 on motion channel: rebalance before sign-off." },
  { id: "warn-0233", channel: "gold", threshold: 93, message: "Budget watch 0233 on gold channel: rebalance before sign-off." },
  { id: "warn-0234", channel: "glow", threshold: 94, message: "Budget watch 0234 on glow channel: rebalance before sign-off." },
  { id: "warn-0235", channel: "motion", threshold: 95, message: "Budget watch 0235 on motion channel: rebalance before sign-off." },
  { id: "warn-0236", channel: "gold", threshold: 96, message: "Budget watch 0236 on gold channel: rebalance before sign-off." },
  { id: "warn-0237", channel: "glow", threshold: 97, message: "Budget watch 0237 on glow channel: rebalance before sign-off." },
  { id: "warn-0238", channel: "motion", threshold: 98, message: "Budget watch 0238 on motion channel: rebalance before sign-off." },
  { id: "warn-0239", channel: "gold", threshold: 99, message: "Budget watch 0239 on gold channel: rebalance before sign-off." },
  { id: "warn-0240", channel: "glow", threshold: 20, message: "Budget watch 0240 on glow channel: rebalance before sign-off." },
  { id: "warn-0241", channel: "motion", threshold: 21, message: "Budget watch 0241 on motion channel: rebalance before sign-off." },
  { id: "warn-0242", channel: "gold", threshold: 22, message: "Budget watch 0242 on gold channel: rebalance before sign-off." },
  { id: "warn-0243", channel: "glow", threshold: 23, message: "Budget watch 0243 on glow channel: rebalance before sign-off." },
  { id: "warn-0244", channel: "motion", threshold: 24, message: "Budget watch 0244 on motion channel: rebalance before sign-off." },
  { id: "warn-0245", channel: "gold", threshold: 25, message: "Budget watch 0245 on gold channel: rebalance before sign-off." },
  { id: "warn-0246", channel: "glow", threshold: 26, message: "Budget watch 0246 on glow channel: rebalance before sign-off." },
  { id: "warn-0247", channel: "motion", threshold: 27, message: "Budget watch 0247 on motion channel: rebalance before sign-off." },
  { id: "warn-0248", channel: "gold", threshold: 28, message: "Budget watch 0248 on gold channel: rebalance before sign-off." },
  { id: "warn-0249", channel: "glow", threshold: 29, message: "Budget watch 0249 on glow channel: rebalance before sign-off." },
  { id: "warn-0250", channel: "motion", threshold: 30, message: "Budget watch 0250 on motion channel: rebalance before sign-off." },
  { id: "warn-0251", channel: "gold", threshold: 31, message: "Budget watch 0251 on gold channel: rebalance before sign-off." },
  { id: "warn-0252", channel: "glow", threshold: 32, message: "Budget watch 0252 on glow channel: rebalance before sign-off." },
  { id: "warn-0253", channel: "motion", threshold: 33, message: "Budget watch 0253 on motion channel: rebalance before sign-off." },
  { id: "warn-0254", channel: "gold", threshold: 34, message: "Budget watch 0254 on gold channel: rebalance before sign-off." },
  { id: "warn-0255", channel: "glow", threshold: 35, message: "Budget watch 0255 on glow channel: rebalance before sign-off." },
  { id: "warn-0256", channel: "motion", threshold: 36, message: "Budget watch 0256 on motion channel: rebalance before sign-off." },
  { id: "warn-0257", channel: "gold", threshold: 37, message: "Budget watch 0257 on gold channel: rebalance before sign-off." },
  { id: "warn-0258", channel: "glow", threshold: 38, message: "Budget watch 0258 on glow channel: rebalance before sign-off." },
  { id: "warn-0259", channel: "motion", threshold: 39, message: "Budget watch 0259 on motion channel: rebalance before sign-off." },
  { id: "warn-0260", channel: "gold", threshold: 40, message: "Budget watch 0260 on gold channel: rebalance before sign-off." },
  { id: "warn-0261", channel: "glow", threshold: 41, message: "Budget watch 0261 on glow channel: rebalance before sign-off." },
  { id: "warn-0262", channel: "motion", threshold: 42, message: "Budget watch 0262 on motion channel: rebalance before sign-off." },
  { id: "warn-0263", channel: "gold", threshold: 43, message: "Budget watch 0263 on gold channel: rebalance before sign-off." },
  { id: "warn-0264", channel: "glow", threshold: 44, message: "Budget watch 0264 on glow channel: rebalance before sign-off." },
  { id: "warn-0265", channel: "motion", threshold: 45, message: "Budget watch 0265 on motion channel: rebalance before sign-off." },
  { id: "warn-0266", channel: "gold", threshold: 46, message: "Budget watch 0266 on gold channel: rebalance before sign-off." },
  { id: "warn-0267", channel: "glow", threshold: 47, message: "Budget watch 0267 on glow channel: rebalance before sign-off." },
  { id: "warn-0268", channel: "motion", threshold: 48, message: "Budget watch 0268 on motion channel: rebalance before sign-off." },
  { id: "warn-0269", channel: "gold", threshold: 49, message: "Budget watch 0269 on gold channel: rebalance before sign-off." },
  { id: "warn-0270", channel: "glow", threshold: 50, message: "Budget watch 0270 on glow channel: rebalance before sign-off." },
  { id: "warn-0271", channel: "motion", threshold: 51, message: "Budget watch 0271 on motion channel: rebalance before sign-off." },
  { id: "warn-0272", channel: "gold", threshold: 52, message: "Budget watch 0272 on gold channel: rebalance before sign-off." },
  { id: "warn-0273", channel: "glow", threshold: 53, message: "Budget watch 0273 on glow channel: rebalance before sign-off." },
  { id: "warn-0274", channel: "motion", threshold: 54, message: "Budget watch 0274 on motion channel: rebalance before sign-off." },
  { id: "warn-0275", channel: "gold", threshold: 55, message: "Budget watch 0275 on gold channel: rebalance before sign-off." },
  { id: "warn-0276", channel: "glow", threshold: 56, message: "Budget watch 0276 on glow channel: rebalance before sign-off." },
  { id: "warn-0277", channel: "motion", threshold: 57, message: "Budget watch 0277 on motion channel: rebalance before sign-off." },
  { id: "warn-0278", channel: "gold", threshold: 58, message: "Budget watch 0278 on gold channel: rebalance before sign-off." },
  { id: "warn-0279", channel: "glow", threshold: 59, message: "Budget watch 0279 on glow channel: rebalance before sign-off." },
  { id: "warn-0280", channel: "motion", threshold: 60, message: "Budget watch 0280 on motion channel: rebalance before sign-off." },
  { id: "warn-0281", channel: "gold", threshold: 61, message: "Budget watch 0281 on gold channel: rebalance before sign-off." },
  { id: "warn-0282", channel: "glow", threshold: 62, message: "Budget watch 0282 on glow channel: rebalance before sign-off." },
  { id: "warn-0283", channel: "motion", threshold: 63, message: "Budget watch 0283 on motion channel: rebalance before sign-off." },
  { id: "warn-0284", channel: "gold", threshold: 64, message: "Budget watch 0284 on gold channel: rebalance before sign-off." },
  { id: "warn-0285", channel: "glow", threshold: 65, message: "Budget watch 0285 on glow channel: rebalance before sign-off." },
  { id: "warn-0286", channel: "motion", threshold: 66, message: "Budget watch 0286 on motion channel: rebalance before sign-off." },
  { id: "warn-0287", channel: "gold", threshold: 67, message: "Budget watch 0287 on gold channel: rebalance before sign-off." },
  { id: "warn-0288", channel: "glow", threshold: 68, message: "Budget watch 0288 on glow channel: rebalance before sign-off." },
  { id: "warn-0289", channel: "motion", threshold: 69, message: "Budget watch 0289 on motion channel: rebalance before sign-off." },
  { id: "warn-0290", channel: "gold", threshold: 70, message: "Budget watch 0290 on gold channel: rebalance before sign-off." },
  { id: "warn-0291", channel: "glow", threshold: 71, message: "Budget watch 0291 on glow channel: rebalance before sign-off." },
  { id: "warn-0292", channel: "motion", threshold: 72, message: "Budget watch 0292 on motion channel: rebalance before sign-off." },
  { id: "warn-0293", channel: "gold", threshold: 73, message: "Budget watch 0293 on gold channel: rebalance before sign-off." },
  { id: "warn-0294", channel: "glow", threshold: 74, message: "Budget watch 0294 on glow channel: rebalance before sign-off." },
  { id: "warn-0295", channel: "motion", threshold: 75, message: "Budget watch 0295 on motion channel: rebalance before sign-off." },
  { id: "warn-0296", channel: "gold", threshold: 76, message: "Budget watch 0296 on gold channel: rebalance before sign-off." },
  { id: "warn-0297", channel: "glow", threshold: 77, message: "Budget watch 0297 on glow channel: rebalance before sign-off." },
  { id: "warn-0298", channel: "motion", threshold: 78, message: "Budget watch 0298 on motion channel: rebalance before sign-off." },
  { id: "warn-0299", channel: "gold", threshold: 79, message: "Budget watch 0299 on gold channel: rebalance before sign-off." },
  { id: "warn-0300", channel: "glow", threshold: 80, message: "Budget watch 0300 on glow channel: rebalance before sign-off." },
  { id: "warn-0301", channel: "motion", threshold: 81, message: "Budget watch 0301 on motion channel: rebalance before sign-off." },
  { id: "warn-0302", channel: "gold", threshold: 82, message: "Budget watch 0302 on gold channel: rebalance before sign-off." },
  { id: "warn-0303", channel: "glow", threshold: 83, message: "Budget watch 0303 on glow channel: rebalance before sign-off." },
  { id: "warn-0304", channel: "motion", threshold: 84, message: "Budget watch 0304 on motion channel: rebalance before sign-off." },
  { id: "warn-0305", channel: "gold", threshold: 85, message: "Budget watch 0305 on gold channel: rebalance before sign-off." },
  { id: "warn-0306", channel: "glow", threshold: 86, message: "Budget watch 0306 on glow channel: rebalance before sign-off." },
  { id: "warn-0307", channel: "motion", threshold: 87, message: "Budget watch 0307 on motion channel: rebalance before sign-off." },
  { id: "warn-0308", channel: "gold", threshold: 88, message: "Budget watch 0308 on gold channel: rebalance before sign-off." },
  { id: "warn-0309", channel: "glow", threshold: 89, message: "Budget watch 0309 on glow channel: rebalance before sign-off." },
  { id: "warn-0310", channel: "motion", threshold: 90, message: "Budget watch 0310 on motion channel: rebalance before sign-off." },
  { id: "warn-0311", channel: "gold", threshold: 91, message: "Budget watch 0311 on gold channel: rebalance before sign-off." },
  { id: "warn-0312", channel: "glow", threshold: 92, message: "Budget watch 0312 on glow channel: rebalance before sign-off." },
  { id: "warn-0313", channel: "motion", threshold: 93, message: "Budget watch 0313 on motion channel: rebalance before sign-off." },
  { id: "warn-0314", channel: "gold", threshold: 94, message: "Budget watch 0314 on gold channel: rebalance before sign-off." },
  { id: "warn-0315", channel: "glow", threshold: 95, message: "Budget watch 0315 on glow channel: rebalance before sign-off." },
  { id: "warn-0316", channel: "motion", threshold: 96, message: "Budget watch 0316 on motion channel: rebalance before sign-off." },
  { id: "warn-0317", channel: "gold", threshold: 97, message: "Budget watch 0317 on gold channel: rebalance before sign-off." },
  { id: "warn-0318", channel: "glow", threshold: 98, message: "Budget watch 0318 on glow channel: rebalance before sign-off." },
  { id: "warn-0319", channel: "motion", threshold: 99, message: "Budget watch 0319 on motion channel: rebalance before sign-off." },
  { id: "warn-0320", channel: "gold", threshold: 20, message: "Budget watch 0320 on gold channel: rebalance before sign-off." },
  { id: "warn-0321", channel: "glow", threshold: 21, message: "Budget watch 0321 on glow channel: rebalance before sign-off." },
  { id: "warn-0322", channel: "motion", threshold: 22, message: "Budget watch 0322 on motion channel: rebalance before sign-off." },
  { id: "warn-0323", channel: "gold", threshold: 23, message: "Budget watch 0323 on gold channel: rebalance before sign-off." },
  { id: "warn-0324", channel: "glow", threshold: 24, message: "Budget watch 0324 on glow channel: rebalance before sign-off." },
  { id: "warn-0325", channel: "motion", threshold: 25, message: "Budget watch 0325 on motion channel: rebalance before sign-off." },
  { id: "warn-0326", channel: "gold", threshold: 26, message: "Budget watch 0326 on gold channel: rebalance before sign-off." },
  { id: "warn-0327", channel: "glow", threshold: 27, message: "Budget watch 0327 on glow channel: rebalance before sign-off." },
  { id: "warn-0328", channel: "motion", threshold: 28, message: "Budget watch 0328 on motion channel: rebalance before sign-off." },
  { id: "warn-0329", channel: "gold", threshold: 29, message: "Budget watch 0329 on gold channel: rebalance before sign-off." },
  { id: "warn-0330", channel: "glow", threshold: 30, message: "Budget watch 0330 on glow channel: rebalance before sign-off." },
  { id: "warn-0331", channel: "motion", threshold: 31, message: "Budget watch 0331 on motion channel: rebalance before sign-off." },
  { id: "warn-0332", channel: "gold", threshold: 32, message: "Budget watch 0332 on gold channel: rebalance before sign-off." },
  { id: "warn-0333", channel: "glow", threshold: 33, message: "Budget watch 0333 on glow channel: rebalance before sign-off." },
  { id: "warn-0334", channel: "motion", threshold: 34, message: "Budget watch 0334 on motion channel: rebalance before sign-off." },
  { id: "warn-0335", channel: "gold", threshold: 35, message: "Budget watch 0335 on gold channel: rebalance before sign-off." },
  { id: "warn-0336", channel: "glow", threshold: 36, message: "Budget watch 0336 on glow channel: rebalance before sign-off." },
  { id: "warn-0337", channel: "motion", threshold: 37, message: "Budget watch 0337 on motion channel: rebalance before sign-off." },
  { id: "warn-0338", channel: "gold", threshold: 38, message: "Budget watch 0338 on gold channel: rebalance before sign-off." },
  { id: "warn-0339", channel: "glow", threshold: 39, message: "Budget watch 0339 on glow channel: rebalance before sign-off." },
  { id: "warn-0340", channel: "motion", threshold: 40, message: "Budget watch 0340 on motion channel: rebalance before sign-off." },
  { id: "warn-0341", channel: "gold", threshold: 41, message: "Budget watch 0341 on gold channel: rebalance before sign-off." },
  { id: "warn-0342", channel: "glow", threshold: 42, message: "Budget watch 0342 on glow channel: rebalance before sign-off." },
  { id: "warn-0343", channel: "motion", threshold: 43, message: "Budget watch 0343 on motion channel: rebalance before sign-off." },
  { id: "warn-0344", channel: "gold", threshold: 44, message: "Budget watch 0344 on gold channel: rebalance before sign-off." },
  { id: "warn-0345", channel: "glow", threshold: 45, message: "Budget watch 0345 on glow channel: rebalance before sign-off." },
  { id: "warn-0346", channel: "motion", threshold: 46, message: "Budget watch 0346 on motion channel: rebalance before sign-off." },
  { id: "warn-0347", channel: "gold", threshold: 47, message: "Budget watch 0347 on gold channel: rebalance before sign-off." },
  { id: "warn-0348", channel: "glow", threshold: 48, message: "Budget watch 0348 on glow channel: rebalance before sign-off." },
  { id: "warn-0349", channel: "motion", threshold: 49, message: "Budget watch 0349 on motion channel: rebalance before sign-off." },
  { id: "warn-0350", channel: "gold", threshold: 50, message: "Budget watch 0350 on gold channel: rebalance before sign-off." },
  { id: "warn-0351", channel: "glow", threshold: 51, message: "Budget watch 0351 on glow channel: rebalance before sign-off." },
  { id: "warn-0352", channel: "motion", threshold: 52, message: "Budget watch 0352 on motion channel: rebalance before sign-off." },
  { id: "warn-0353", channel: "gold", threshold: 53, message: "Budget watch 0353 on gold channel: rebalance before sign-off." },
  { id: "warn-0354", channel: "glow", threshold: 54, message: "Budget watch 0354 on glow channel: rebalance before sign-off." },
  { id: "warn-0355", channel: "motion", threshold: 55, message: "Budget watch 0355 on motion channel: rebalance before sign-off." },
  { id: "warn-0356", channel: "gold", threshold: 56, message: "Budget watch 0356 on gold channel: rebalance before sign-off." },
  { id: "warn-0357", channel: "glow", threshold: 57, message: "Budget watch 0357 on glow channel: rebalance before sign-off." },
  { id: "warn-0358", channel: "motion", threshold: 58, message: "Budget watch 0358 on motion channel: rebalance before sign-off." },
  { id: "warn-0359", channel: "gold", threshold: 59, message: "Budget watch 0359 on gold channel: rebalance before sign-off." },
  { id: "warn-0360", channel: "glow", threshold: 60, message: "Budget watch 0360 on glow channel: rebalance before sign-off." },
  { id: "warn-0361", channel: "motion", threshold: 61, message: "Budget watch 0361 on motion channel: rebalance before sign-off." },
  { id: "warn-0362", channel: "gold", threshold: 62, message: "Budget watch 0362 on gold channel: rebalance before sign-off." },
  { id: "warn-0363", channel: "glow", threshold: 63, message: "Budget watch 0363 on glow channel: rebalance before sign-off." },
  { id: "warn-0364", channel: "motion", threshold: 64, message: "Budget watch 0364 on motion channel: rebalance before sign-off." },
  { id: "warn-0365", channel: "gold", threshold: 65, message: "Budget watch 0365 on gold channel: rebalance before sign-off." },
  { id: "warn-0366", channel: "glow", threshold: 66, message: "Budget watch 0366 on glow channel: rebalance before sign-off." },
  { id: "warn-0367", channel: "motion", threshold: 67, message: "Budget watch 0367 on motion channel: rebalance before sign-off." },
  { id: "warn-0368", channel: "gold", threshold: 68, message: "Budget watch 0368 on gold channel: rebalance before sign-off." },
  { id: "warn-0369", channel: "glow", threshold: 69, message: "Budget watch 0369 on glow channel: rebalance before sign-off." },
  { id: "warn-0370", channel: "motion", threshold: 70, message: "Budget watch 0370 on motion channel: rebalance before sign-off." },
  { id: "warn-0371", channel: "gold", threshold: 71, message: "Budget watch 0371 on gold channel: rebalance before sign-off." },
  { id: "warn-0372", channel: "glow", threshold: 72, message: "Budget watch 0372 on glow channel: rebalance before sign-off." },
  { id: "warn-0373", channel: "motion", threshold: 73, message: "Budget watch 0373 on motion channel: rebalance before sign-off." },
  { id: "warn-0374", channel: "gold", threshold: 74, message: "Budget watch 0374 on gold channel: rebalance before sign-off." },
  { id: "warn-0375", channel: "glow", threshold: 75, message: "Budget watch 0375 on glow channel: rebalance before sign-off." },
  { id: "warn-0376", channel: "motion", threshold: 76, message: "Budget watch 0376 on motion channel: rebalance before sign-off." },
  { id: "warn-0377", channel: "gold", threshold: 77, message: "Budget watch 0377 on gold channel: rebalance before sign-off." },
  { id: "warn-0378", channel: "glow", threshold: 78, message: "Budget watch 0378 on glow channel: rebalance before sign-off." },
  { id: "warn-0379", channel: "motion", threshold: 79, message: "Budget watch 0379 on motion channel: rebalance before sign-off." },
  { id: "warn-0380", channel: "gold", threshold: 80, message: "Budget watch 0380 on gold channel: rebalance before sign-off." },
  { id: "warn-0381", channel: "glow", threshold: 81, message: "Budget watch 0381 on glow channel: rebalance before sign-off." },
  { id: "warn-0382", channel: "motion", threshold: 82, message: "Budget watch 0382 on motion channel: rebalance before sign-off." },
  { id: "warn-0383", channel: "gold", threshold: 83, message: "Budget watch 0383 on gold channel: rebalance before sign-off." },
  { id: "warn-0384", channel: "glow", threshold: 84, message: "Budget watch 0384 on glow channel: rebalance before sign-off." },
  { id: "warn-0385", channel: "motion", threshold: 85, message: "Budget watch 0385 on motion channel: rebalance before sign-off." },
  { id: "warn-0386", channel: "gold", threshold: 86, message: "Budget watch 0386 on gold channel: rebalance before sign-off." },
  { id: "warn-0387", channel: "glow", threshold: 87, message: "Budget watch 0387 on glow channel: rebalance before sign-off." },
  { id: "warn-0388", channel: "motion", threshold: 88, message: "Budget watch 0388 on motion channel: rebalance before sign-off." },
  { id: "warn-0389", channel: "gold", threshold: 89, message: "Budget watch 0389 on gold channel: rebalance before sign-off." },
  { id: "warn-0390", channel: "glow", threshold: 90, message: "Budget watch 0390 on glow channel: rebalance before sign-off." },
  { id: "warn-0391", channel: "motion", threshold: 91, message: "Budget watch 0391 on motion channel: rebalance before sign-off." },
  { id: "warn-0392", channel: "gold", threshold: 92, message: "Budget watch 0392 on gold channel: rebalance before sign-off." },
  { id: "warn-0393", channel: "glow", threshold: 93, message: "Budget watch 0393 on glow channel: rebalance before sign-off." },
  { id: "warn-0394", channel: "motion", threshold: 94, message: "Budget watch 0394 on motion channel: rebalance before sign-off." },
  { id: "warn-0395", channel: "gold", threshold: 95, message: "Budget watch 0395 on gold channel: rebalance before sign-off." },
  { id: "warn-0396", channel: "glow", threshold: 96, message: "Budget watch 0396 on glow channel: rebalance before sign-off." },
  { id: "warn-0397", channel: "motion", threshold: 97, message: "Budget watch 0397 on motion channel: rebalance before sign-off." },
  { id: "warn-0398", channel: "gold", threshold: 98, message: "Budget watch 0398 on gold channel: rebalance before sign-off." },
  { id: "warn-0399", channel: "glow", threshold: 99, message: "Budget watch 0399 on glow channel: rebalance before sign-off." },
  { id: "warn-0400", channel: "motion", threshold: 20, message: "Budget watch 0400 on motion channel: rebalance before sign-off." },
  { id: "warn-0401", channel: "gold", threshold: 21, message: "Budget watch 0401 on gold channel: rebalance before sign-off." },
  { id: "warn-0402", channel: "glow", threshold: 22, message: "Budget watch 0402 on glow channel: rebalance before sign-off." },
  { id: "warn-0403", channel: "motion", threshold: 23, message: "Budget watch 0403 on motion channel: rebalance before sign-off." },
  { id: "warn-0404", channel: "gold", threshold: 24, message: "Budget watch 0404 on gold channel: rebalance before sign-off." },
  { id: "warn-0405", channel: "glow", threshold: 25, message: "Budget watch 0405 on glow channel: rebalance before sign-off." },
  { id: "warn-0406", channel: "motion", threshold: 26, message: "Budget watch 0406 on motion channel: rebalance before sign-off." },
  { id: "warn-0407", channel: "gold", threshold: 27, message: "Budget watch 0407 on gold channel: rebalance before sign-off." },
  { id: "warn-0408", channel: "glow", threshold: 28, message: "Budget watch 0408 on glow channel: rebalance before sign-off." },
  { id: "warn-0409", channel: "motion", threshold: 29, message: "Budget watch 0409 on motion channel: rebalance before sign-off." },
  { id: "warn-0410", channel: "gold", threshold: 30, message: "Budget watch 0410 on gold channel: rebalance before sign-off." },
  { id: "warn-0411", channel: "glow", threshold: 31, message: "Budget watch 0411 on glow channel: rebalance before sign-off." },
  { id: "warn-0412", channel: "motion", threshold: 32, message: "Budget watch 0412 on motion channel: rebalance before sign-off." },
  { id: "warn-0413", channel: "gold", threshold: 33, message: "Budget watch 0413 on gold channel: rebalance before sign-off." },
  { id: "warn-0414", channel: "glow", threshold: 34, message: "Budget watch 0414 on glow channel: rebalance before sign-off." },
  { id: "warn-0415", channel: "motion", threshold: 35, message: "Budget watch 0415 on motion channel: rebalance before sign-off." },
  { id: "warn-0416", channel: "gold", threshold: 36, message: "Budget watch 0416 on gold channel: rebalance before sign-off." },
  { id: "warn-0417", channel: "glow", threshold: 37, message: "Budget watch 0417 on glow channel: rebalance before sign-off." },
  { id: "warn-0418", channel: "motion", threshold: 38, message: "Budget watch 0418 on motion channel: rebalance before sign-off." },
  { id: "warn-0419", channel: "gold", threshold: 39, message: "Budget watch 0419 on gold channel: rebalance before sign-off." },
  { id: "warn-0420", channel: "glow", threshold: 40, message: "Budget watch 0420 on glow channel: rebalance before sign-off." },
  { id: "warn-0421", channel: "motion", threshold: 41, message: "Budget watch 0421 on motion channel: rebalance before sign-off." },
  { id: "warn-0422", channel: "gold", threshold: 42, message: "Budget watch 0422 on gold channel: rebalance before sign-off." },
  { id: "warn-0423", channel: "glow", threshold: 43, message: "Budget watch 0423 on glow channel: rebalance before sign-off." },
  { id: "warn-0424", channel: "motion", threshold: 44, message: "Budget watch 0424 on motion channel: rebalance before sign-off." },
  { id: "warn-0425", channel: "gold", threshold: 45, message: "Budget watch 0425 on gold channel: rebalance before sign-off." },
  { id: "warn-0426", channel: "glow", threshold: 46, message: "Budget watch 0426 on glow channel: rebalance before sign-off." },
  { id: "warn-0427", channel: "motion", threshold: 47, message: "Budget watch 0427 on motion channel: rebalance before sign-off." },
  { id: "warn-0428", channel: "gold", threshold: 48, message: "Budget watch 0428 on gold channel: rebalance before sign-off." },
  { id: "warn-0429", channel: "glow", threshold: 49, message: "Budget watch 0429 on glow channel: rebalance before sign-off." },
  { id: "warn-0430", channel: "motion", threshold: 50, message: "Budget watch 0430 on motion channel: rebalance before sign-off." },
  { id: "warn-0431", channel: "gold", threshold: 51, message: "Budget watch 0431 on gold channel: rebalance before sign-off." },
  { id: "warn-0432", channel: "glow", threshold: 52, message: "Budget watch 0432 on glow channel: rebalance before sign-off." },
  { id: "warn-0433", channel: "motion", threshold: 53, message: "Budget watch 0433 on motion channel: rebalance before sign-off." },
  { id: "warn-0434", channel: "gold", threshold: 54, message: "Budget watch 0434 on gold channel: rebalance before sign-off." },
  { id: "warn-0435", channel: "glow", threshold: 55, message: "Budget watch 0435 on glow channel: rebalance before sign-off." },
  { id: "warn-0436", channel: "motion", threshold: 56, message: "Budget watch 0436 on motion channel: rebalance before sign-off." },
  { id: "warn-0437", channel: "gold", threshold: 57, message: "Budget watch 0437 on gold channel: rebalance before sign-off." },
  { id: "warn-0438", channel: "glow", threshold: 58, message: "Budget watch 0438 on glow channel: rebalance before sign-off." },
  { id: "warn-0439", channel: "motion", threshold: 59, message: "Budget watch 0439 on motion channel: rebalance before sign-off." },
  { id: "warn-0440", channel: "gold", threshold: 60, message: "Budget watch 0440 on gold channel: rebalance before sign-off." },
  { id: "warn-0441", channel: "glow", threshold: 61, message: "Budget watch 0441 on glow channel: rebalance before sign-off." },
  { id: "warn-0442", channel: "motion", threshold: 62, message: "Budget watch 0442 on motion channel: rebalance before sign-off." },
  { id: "warn-0443", channel: "gold", threshold: 63, message: "Budget watch 0443 on gold channel: rebalance before sign-off." },
  { id: "warn-0444", channel: "glow", threshold: 64, message: "Budget watch 0444 on glow channel: rebalance before sign-off." },
  { id: "warn-0445", channel: "motion", threshold: 65, message: "Budget watch 0445 on motion channel: rebalance before sign-off." },
  { id: "warn-0446", channel: "gold", threshold: 66, message: "Budget watch 0446 on gold channel: rebalance before sign-off." },
  { id: "warn-0447", channel: "glow", threshold: 67, message: "Budget watch 0447 on glow channel: rebalance before sign-off." },
  { id: "warn-0448", channel: "motion", threshold: 68, message: "Budget watch 0448 on motion channel: rebalance before sign-off." },
  { id: "warn-0449", channel: "gold", threshold: 69, message: "Budget watch 0449 on gold channel: rebalance before sign-off." },
  { id: "warn-0450", channel: "glow", threshold: 70, message: "Budget watch 0450 on glow channel: rebalance before sign-off." },
  { id: "warn-0451", channel: "motion", threshold: 71, message: "Budget watch 0451 on motion channel: rebalance before sign-off." },
  { id: "warn-0452", channel: "gold", threshold: 72, message: "Budget watch 0452 on gold channel: rebalance before sign-off." },
  { id: "warn-0453", channel: "glow", threshold: 73, message: "Budget watch 0453 on glow channel: rebalance before sign-off." },
  { id: "warn-0454", channel: "motion", threshold: 74, message: "Budget watch 0454 on motion channel: rebalance before sign-off." },
  { id: "warn-0455", channel: "gold", threshold: 75, message: "Budget watch 0455 on gold channel: rebalance before sign-off." },
  { id: "warn-0456", channel: "glow", threshold: 76, message: "Budget watch 0456 on glow channel: rebalance before sign-off." },
  { id: "warn-0457", channel: "motion", threshold: 77, message: "Budget watch 0457 on motion channel: rebalance before sign-off." },
  { id: "warn-0458", channel: "gold", threshold: 78, message: "Budget watch 0458 on gold channel: rebalance before sign-off." },
  { id: "warn-0459", channel: "glow", threshold: 79, message: "Budget watch 0459 on glow channel: rebalance before sign-off." },
  { id: "warn-0460", channel: "motion", threshold: 80, message: "Budget watch 0460 on motion channel: rebalance before sign-off." },
  { id: "warn-0461", channel: "gold", threshold: 81, message: "Budget watch 0461 on gold channel: rebalance before sign-off." },
  { id: "warn-0462", channel: "glow", threshold: 82, message: "Budget watch 0462 on glow channel: rebalance before sign-off." },
  { id: "warn-0463", channel: "motion", threshold: 83, message: "Budget watch 0463 on motion channel: rebalance before sign-off." },
  { id: "warn-0464", channel: "gold", threshold: 84, message: "Budget watch 0464 on gold channel: rebalance before sign-off." },
  { id: "warn-0465", channel: "glow", threshold: 85, message: "Budget watch 0465 on glow channel: rebalance before sign-off." },
  { id: "warn-0466", channel: "motion", threshold: 86, message: "Budget watch 0466 on motion channel: rebalance before sign-off." },
  { id: "warn-0467", channel: "gold", threshold: 87, message: "Budget watch 0467 on gold channel: rebalance before sign-off." },
  { id: "warn-0468", channel: "glow", threshold: 88, message: "Budget watch 0468 on glow channel: rebalance before sign-off." },
  { id: "warn-0469", channel: "motion", threshold: 89, message: "Budget watch 0469 on motion channel: rebalance before sign-off." },
  { id: "warn-0470", channel: "gold", threshold: 90, message: "Budget watch 0470 on gold channel: rebalance before sign-off." },
  { id: "warn-0471", channel: "glow", threshold: 91, message: "Budget watch 0471 on glow channel: rebalance before sign-off." },
  { id: "warn-0472", channel: "motion", threshold: 92, message: "Budget watch 0472 on motion channel: rebalance before sign-off." },
  { id: "warn-0473", channel: "gold", threshold: 93, message: "Budget watch 0473 on gold channel: rebalance before sign-off." },
  { id: "warn-0474", channel: "glow", threshold: 94, message: "Budget watch 0474 on glow channel: rebalance before sign-off." },
  { id: "warn-0475", channel: "motion", threshold: 95, message: "Budget watch 0475 on motion channel: rebalance before sign-off." },
  { id: "warn-0476", channel: "gold", threshold: 96, message: "Budget watch 0476 on gold channel: rebalance before sign-off." },
  { id: "warn-0477", channel: "glow", threshold: 97, message: "Budget watch 0477 on glow channel: rebalance before sign-off." },
  { id: "warn-0478", channel: "motion", threshold: 98, message: "Budget watch 0478 on motion channel: rebalance before sign-off." },
  { id: "warn-0479", channel: "gold", threshold: 99, message: "Budget watch 0479 on gold channel: rebalance before sign-off." },
  { id: "warn-0480", channel: "glow", threshold: 20, message: "Budget watch 0480 on glow channel: rebalance before sign-off." },
  { id: "warn-0481", channel: "motion", threshold: 21, message: "Budget watch 0481 on motion channel: rebalance before sign-off." },
  { id: "warn-0482", channel: "gold", threshold: 22, message: "Budget watch 0482 on gold channel: rebalance before sign-off." },
  { id: "warn-0483", channel: "glow", threshold: 23, message: "Budget watch 0483 on glow channel: rebalance before sign-off." },
  { id: "warn-0484", channel: "motion", threshold: 24, message: "Budget watch 0484 on motion channel: rebalance before sign-off." },
  { id: "warn-0485", channel: "gold", threshold: 25, message: "Budget watch 0485 on gold channel: rebalance before sign-off." },
  { id: "warn-0486", channel: "glow", threshold: 26, message: "Budget watch 0486 on glow channel: rebalance before sign-off." },
  { id: "warn-0487", channel: "motion", threshold: 27, message: "Budget watch 0487 on motion channel: rebalance before sign-off." },
  { id: "warn-0488", channel: "gold", threshold: 28, message: "Budget watch 0488 on gold channel: rebalance before sign-off." },
  { id: "warn-0489", channel: "glow", threshold: 29, message: "Budget watch 0489 on glow channel: rebalance before sign-off." },
  { id: "warn-0490", channel: "motion", threshold: 30, message: "Budget watch 0490 on motion channel: rebalance before sign-off." },
  { id: "warn-0491", channel: "gold", threshold: 31, message: "Budget watch 0491 on gold channel: rebalance before sign-off." },
  { id: "warn-0492", channel: "glow", threshold: 32, message: "Budget watch 0492 on glow channel: rebalance before sign-off." },
  { id: "warn-0493", channel: "motion", threshold: 33, message: "Budget watch 0493 on motion channel: rebalance before sign-off." },
  { id: "warn-0494", channel: "gold", threshold: 34, message: "Budget watch 0494 on gold channel: rebalance before sign-off." },
  { id: "warn-0495", channel: "glow", threshold: 35, message: "Budget watch 0495 on glow channel: rebalance before sign-off." },
  { id: "warn-0496", channel: "motion", threshold: 36, message: "Budget watch 0496 on motion channel: rebalance before sign-off." },
  { id: "warn-0497", channel: "gold", threshold: 37, message: "Budget watch 0497 on gold channel: rebalance before sign-off." },
  { id: "warn-0498", channel: "glow", threshold: 38, message: "Budget watch 0498 on glow channel: rebalance before sign-off." },
  { id: "warn-0499", channel: "motion", threshold: 39, message: "Budget watch 0499 on motion channel: rebalance before sign-off." },
  { id: "warn-0500", channel: "gold", threshold: 40, message: "Budget watch 0500 on gold channel: rebalance before sign-off." },
  { id: "warn-0501", channel: "glow", threshold: 41, message: "Budget watch 0501 on glow channel: rebalance before sign-off." },
  { id: "warn-0502", channel: "motion", threshold: 42, message: "Budget watch 0502 on motion channel: rebalance before sign-off." },
  { id: "warn-0503", channel: "gold", threshold: 43, message: "Budget watch 0503 on gold channel: rebalance before sign-off." },
  { id: "warn-0504", channel: "glow", threshold: 44, message: "Budget watch 0504 on glow channel: rebalance before sign-off." },
  { id: "warn-0505", channel: "motion", threshold: 45, message: "Budget watch 0505 on motion channel: rebalance before sign-off." },
  { id: "warn-0506", channel: "gold", threshold: 46, message: "Budget watch 0506 on gold channel: rebalance before sign-off." },
  { id: "warn-0507", channel: "glow", threshold: 47, message: "Budget watch 0507 on glow channel: rebalance before sign-off." },
  { id: "warn-0508", channel: "motion", threshold: 48, message: "Budget watch 0508 on motion channel: rebalance before sign-off." },
  { id: "warn-0509", channel: "gold", threshold: 49, message: "Budget watch 0509 on gold channel: rebalance before sign-off." },
  { id: "warn-0510", channel: "glow", threshold: 50, message: "Budget watch 0510 on glow channel: rebalance before sign-off." },
  { id: "warn-0511", channel: "motion", threshold: 51, message: "Budget watch 0511 on motion channel: rebalance before sign-off." },
  { id: "warn-0512", channel: "gold", threshold: 52, message: "Budget watch 0512 on gold channel: rebalance before sign-off." },
  { id: "warn-0513", channel: "glow", threshold: 53, message: "Budget watch 0513 on glow channel: rebalance before sign-off." },
  { id: "warn-0514", channel: "motion", threshold: 54, message: "Budget watch 0514 on motion channel: rebalance before sign-off." },
  { id: "warn-0515", channel: "gold", threshold: 55, message: "Budget watch 0515 on gold channel: rebalance before sign-off." },
  { id: "warn-0516", channel: "glow", threshold: 56, message: "Budget watch 0516 on glow channel: rebalance before sign-off." },
  { id: "warn-0517", channel: "motion", threshold: 57, message: "Budget watch 0517 on motion channel: rebalance before sign-off." },
  { id: "warn-0518", channel: "gold", threshold: 58, message: "Budget watch 0518 on gold channel: rebalance before sign-off." },
  { id: "warn-0519", channel: "glow", threshold: 59, message: "Budget watch 0519 on glow channel: rebalance before sign-off." },
  { id: "warn-0520", channel: "motion", threshold: 60, message: "Budget watch 0520 on motion channel: rebalance before sign-off." },
  { id: "warn-0521", channel: "gold", threshold: 61, message: "Budget watch 0521 on gold channel: rebalance before sign-off." },
  { id: "warn-0522", channel: "glow", threshold: 62, message: "Budget watch 0522 on glow channel: rebalance before sign-off." },
  { id: "warn-0523", channel: "motion", threshold: 63, message: "Budget watch 0523 on motion channel: rebalance before sign-off." },
  { id: "warn-0524", channel: "gold", threshold: 64, message: "Budget watch 0524 on gold channel: rebalance before sign-off." },
  { id: "warn-0525", channel: "glow", threshold: 65, message: "Budget watch 0525 on glow channel: rebalance before sign-off." },
  { id: "warn-0526", channel: "motion", threshold: 66, message: "Budget watch 0526 on motion channel: rebalance before sign-off." },
  { id: "warn-0527", channel: "gold", threshold: 67, message: "Budget watch 0527 on gold channel: rebalance before sign-off." },
  { id: "warn-0528", channel: "glow", threshold: 68, message: "Budget watch 0528 on glow channel: rebalance before sign-off." },
  { id: "warn-0529", channel: "motion", threshold: 69, message: "Budget watch 0529 on motion channel: rebalance before sign-off." },
  { id: "warn-0530", channel: "gold", threshold: 70, message: "Budget watch 0530 on gold channel: rebalance before sign-off." },
  { id: "warn-0531", channel: "glow", threshold: 71, message: "Budget watch 0531 on glow channel: rebalance before sign-off." },
  { id: "warn-0532", channel: "motion", threshold: 72, message: "Budget watch 0532 on motion channel: rebalance before sign-off." },
  { id: "warn-0533", channel: "gold", threshold: 73, message: "Budget watch 0533 on gold channel: rebalance before sign-off." },
  { id: "warn-0534", channel: "glow", threshold: 74, message: "Budget watch 0534 on glow channel: rebalance before sign-off." },
  { id: "warn-0535", channel: "motion", threshold: 75, message: "Budget watch 0535 on motion channel: rebalance before sign-off." },
  { id: "warn-0536", channel: "gold", threshold: 76, message: "Budget watch 0536 on gold channel: rebalance before sign-off." },
  { id: "warn-0537", channel: "glow", threshold: 77, message: "Budget watch 0537 on glow channel: rebalance before sign-off." },
  { id: "warn-0538", channel: "motion", threshold: 78, message: "Budget watch 0538 on motion channel: rebalance before sign-off." },
  { id: "warn-0539", channel: "gold", threshold: 79, message: "Budget watch 0539 on gold channel: rebalance before sign-off." },
  { id: "warn-0540", channel: "glow", threshold: 80, message: "Budget watch 0540 on glow channel: rebalance before sign-off." },
  { id: "warn-0541", channel: "motion", threshold: 81, message: "Budget watch 0541 on motion channel: rebalance before sign-off." },
  { id: "warn-0542", channel: "gold", threshold: 82, message: "Budget watch 0542 on gold channel: rebalance before sign-off." },
  { id: "warn-0543", channel: "glow", threshold: 83, message: "Budget watch 0543 on glow channel: rebalance before sign-off." },
  { id: "warn-0544", channel: "motion", threshold: 84, message: "Budget watch 0544 on motion channel: rebalance before sign-off." },
  { id: "warn-0545", channel: "gold", threshold: 85, message: "Budget watch 0545 on gold channel: rebalance before sign-off." },
  { id: "warn-0546", channel: "glow", threshold: 86, message: "Budget watch 0546 on glow channel: rebalance before sign-off." },
  { id: "warn-0547", channel: "motion", threshold: 87, message: "Budget watch 0547 on motion channel: rebalance before sign-off." },
  { id: "warn-0548", channel: "gold", threshold: 88, message: "Budget watch 0548 on gold channel: rebalance before sign-off." },
  { id: "warn-0549", channel: "glow", threshold: 89, message: "Budget watch 0549 on glow channel: rebalance before sign-off." },
  { id: "warn-0550", channel: "motion", threshold: 90, message: "Budget watch 0550 on motion channel: rebalance before sign-off." },
  { id: "warn-0551", channel: "gold", threshold: 91, message: "Budget watch 0551 on gold channel: rebalance before sign-off." },
  { id: "warn-0552", channel: "glow", threshold: 92, message: "Budget watch 0552 on glow channel: rebalance before sign-off." },
  { id: "warn-0553", channel: "motion", threshold: 93, message: "Budget watch 0553 on motion channel: rebalance before sign-off." },
  { id: "warn-0554", channel: "gold", threshold: 94, message: "Budget watch 0554 on gold channel: rebalance before sign-off." },
  { id: "warn-0555", channel: "glow", threshold: 95, message: "Budget watch 0555 on glow channel: rebalance before sign-off." },
  { id: "warn-0556", channel: "motion", threshold: 96, message: "Budget watch 0556 on motion channel: rebalance before sign-off." },
  { id: "warn-0557", channel: "gold", threshold: 97, message: "Budget watch 0557 on gold channel: rebalance before sign-off." },
  { id: "warn-0558", channel: "glow", threshold: 98, message: "Budget watch 0558 on glow channel: rebalance before sign-off." },
  { id: "warn-0559", channel: "motion", threshold: 99, message: "Budget watch 0559 on motion channel: rebalance before sign-off." },
  { id: "warn-0560", channel: "gold", threshold: 20, message: "Budget watch 0560 on gold channel: rebalance before sign-off." },
  { id: "warn-0561", channel: "glow", threshold: 21, message: "Budget watch 0561 on glow channel: rebalance before sign-off." },
  { id: "warn-0562", channel: "motion", threshold: 22, message: "Budget watch 0562 on motion channel: rebalance before sign-off." },
  { id: "warn-0563", channel: "gold", threshold: 23, message: "Budget watch 0563 on gold channel: rebalance before sign-off." },
  { id: "warn-0564", channel: "glow", threshold: 24, message: "Budget watch 0564 on glow channel: rebalance before sign-off." },
  { id: "warn-0565", channel: "motion", threshold: 25, message: "Budget watch 0565 on motion channel: rebalance before sign-off." },
  { id: "warn-0566", channel: "gold", threshold: 26, message: "Budget watch 0566 on gold channel: rebalance before sign-off." },
  { id: "warn-0567", channel: "glow", threshold: 27, message: "Budget watch 0567 on glow channel: rebalance before sign-off." },
  { id: "warn-0568", channel: "motion", threshold: 28, message: "Budget watch 0568 on motion channel: rebalance before sign-off." },
  { id: "warn-0569", channel: "gold", threshold: 29, message: "Budget watch 0569 on gold channel: rebalance before sign-off." },
  { id: "warn-0570", channel: "glow", threshold: 30, message: "Budget watch 0570 on glow channel: rebalance before sign-off." },
  { id: "warn-0571", channel: "motion", threshold: 31, message: "Budget watch 0571 on motion channel: rebalance before sign-off." },
  { id: "warn-0572", channel: "gold", threshold: 32, message: "Budget watch 0572 on gold channel: rebalance before sign-off." },
  { id: "warn-0573", channel: "glow", threshold: 33, message: "Budget watch 0573 on glow channel: rebalance before sign-off." },
  { id: "warn-0574", channel: "motion", threshold: 34, message: "Budget watch 0574 on motion channel: rebalance before sign-off." },
  { id: "warn-0575", channel: "gold", threshold: 35, message: "Budget watch 0575 on gold channel: rebalance before sign-off." },
  { id: "warn-0576", channel: "glow", threshold: 36, message: "Budget watch 0576 on glow channel: rebalance before sign-off." },
  { id: "warn-0577", channel: "motion", threshold: 37, message: "Budget watch 0577 on motion channel: rebalance before sign-off." },
  { id: "warn-0578", channel: "gold", threshold: 38, message: "Budget watch 0578 on gold channel: rebalance before sign-off." },
  { id: "warn-0579", channel: "glow", threshold: 39, message: "Budget watch 0579 on glow channel: rebalance before sign-off." },
  { id: "warn-0580", channel: "motion", threshold: 40, message: "Budget watch 0580 on motion channel: rebalance before sign-off." },
  { id: "warn-0581", channel: "gold", threshold: 41, message: "Budget watch 0581 on gold channel: rebalance before sign-off." },
  { id: "warn-0582", channel: "glow", threshold: 42, message: "Budget watch 0582 on glow channel: rebalance before sign-off." },
  { id: "warn-0583", channel: "motion", threshold: 43, message: "Budget watch 0583 on motion channel: rebalance before sign-off." },
  { id: "warn-0584", channel: "gold", threshold: 44, message: "Budget watch 0584 on gold channel: rebalance before sign-off." },
  { id: "warn-0585", channel: "glow", threshold: 45, message: "Budget watch 0585 on glow channel: rebalance before sign-off." },
  { id: "warn-0586", channel: "motion", threshold: 46, message: "Budget watch 0586 on motion channel: rebalance before sign-off." },
  { id: "warn-0587", channel: "gold", threshold: 47, message: "Budget watch 0587 on gold channel: rebalance before sign-off." },
  { id: "warn-0588", channel: "glow", threshold: 48, message: "Budget watch 0588 on glow channel: rebalance before sign-off." },
  { id: "warn-0589", channel: "motion", threshold: 49, message: "Budget watch 0589 on motion channel: rebalance before sign-off." },
  { id: "warn-0590", channel: "gold", threshold: 50, message: "Budget watch 0590 on gold channel: rebalance before sign-off." },
  { id: "warn-0591", channel: "glow", threshold: 51, message: "Budget watch 0591 on glow channel: rebalance before sign-off." },
  { id: "warn-0592", channel: "motion", threshold: 52, message: "Budget watch 0592 on motion channel: rebalance before sign-off." },
  { id: "warn-0593", channel: "gold", threshold: 53, message: "Budget watch 0593 on gold channel: rebalance before sign-off." },
  { id: "warn-0594", channel: "glow", threshold: 54, message: "Budget watch 0594 on glow channel: rebalance before sign-off." },
  { id: "warn-0595", channel: "motion", threshold: 55, message: "Budget watch 0595 on motion channel: rebalance before sign-off." },
  { id: "warn-0596", channel: "gold", threshold: 56, message: "Budget watch 0596 on gold channel: rebalance before sign-off." },
  { id: "warn-0597", channel: "glow", threshold: 57, message: "Budget watch 0597 on glow channel: rebalance before sign-off." },
  { id: "warn-0598", channel: "motion", threshold: 58, message: "Budget watch 0598 on motion channel: rebalance before sign-off." },
  { id: "warn-0599", channel: "gold", threshold: 59, message: "Budget watch 0599 on gold channel: rebalance before sign-off." },
  { id: "warn-0600", channel: "glow", threshold: 60, message: "Budget watch 0600 on glow channel: rebalance before sign-off." },
  { id: "warn-0601", channel: "motion", threshold: 61, message: "Budget watch 0601 on motion channel: rebalance before sign-off." },
  { id: "warn-0602", channel: "gold", threshold: 62, message: "Budget watch 0602 on gold channel: rebalance before sign-off." },
  { id: "warn-0603", channel: "glow", threshold: 63, message: "Budget watch 0603 on glow channel: rebalance before sign-off." },
  { id: "warn-0604", channel: "motion", threshold: 64, message: "Budget watch 0604 on motion channel: rebalance before sign-off." },
  { id: "warn-0605", channel: "gold", threshold: 65, message: "Budget watch 0605 on gold channel: rebalance before sign-off." },
  { id: "warn-0606", channel: "glow", threshold: 66, message: "Budget watch 0606 on glow channel: rebalance before sign-off." },
  { id: "warn-0607", channel: "motion", threshold: 67, message: "Budget watch 0607 on motion channel: rebalance before sign-off." },
  { id: "warn-0608", channel: "gold", threshold: 68, message: "Budget watch 0608 on gold channel: rebalance before sign-off." },
  { id: "warn-0609", channel: "glow", threshold: 69, message: "Budget watch 0609 on glow channel: rebalance before sign-off." },
  { id: "warn-0610", channel: "motion", threshold: 70, message: "Budget watch 0610 on motion channel: rebalance before sign-off." },
  { id: "warn-0611", channel: "gold", threshold: 71, message: "Budget watch 0611 on gold channel: rebalance before sign-off." },
  { id: "warn-0612", channel: "glow", threshold: 72, message: "Budget watch 0612 on glow channel: rebalance before sign-off." },
  { id: "warn-0613", channel: "motion", threshold: 73, message: "Budget watch 0613 on motion channel: rebalance before sign-off." },
  { id: "warn-0614", channel: "gold", threshold: 74, message: "Budget watch 0614 on gold channel: rebalance before sign-off." },
  { id: "warn-0615", channel: "glow", threshold: 75, message: "Budget watch 0615 on glow channel: rebalance before sign-off." },
  { id: "warn-0616", channel: "motion", threshold: 76, message: "Budget watch 0616 on motion channel: rebalance before sign-off." },
  { id: "warn-0617", channel: "gold", threshold: 77, message: "Budget watch 0617 on gold channel: rebalance before sign-off." },
  { id: "warn-0618", channel: "glow", threshold: 78, message: "Budget watch 0618 on glow channel: rebalance before sign-off." },
  { id: "warn-0619", channel: "motion", threshold: 79, message: "Budget watch 0619 on motion channel: rebalance before sign-off." },
  { id: "warn-0620", channel: "gold", threshold: 80, message: "Budget watch 0620 on gold channel: rebalance before sign-off." },
  { id: "warn-0621", channel: "glow", threshold: 81, message: "Budget watch 0621 on glow channel: rebalance before sign-off." },
  { id: "warn-0622", channel: "motion", threshold: 82, message: "Budget watch 0622 on motion channel: rebalance before sign-off." },
  { id: "warn-0623", channel: "gold", threshold: 83, message: "Budget watch 0623 on gold channel: rebalance before sign-off." },
  { id: "warn-0624", channel: "glow", threshold: 84, message: "Budget watch 0624 on glow channel: rebalance before sign-off." },
  { id: "warn-0625", channel: "motion", threshold: 85, message: "Budget watch 0625 on motion channel: rebalance before sign-off." },
  { id: "warn-0626", channel: "gold", threshold: 86, message: "Budget watch 0626 on gold channel: rebalance before sign-off." },
  { id: "warn-0627", channel: "glow", threshold: 87, message: "Budget watch 0627 on glow channel: rebalance before sign-off." },
  { id: "warn-0628", channel: "motion", threshold: 88, message: "Budget watch 0628 on motion channel: rebalance before sign-off." },
  { id: "warn-0629", channel: "gold", threshold: 89, message: "Budget watch 0629 on gold channel: rebalance before sign-off." },
  { id: "warn-0630", channel: "glow", threshold: 90, message: "Budget watch 0630 on glow channel: rebalance before sign-off." },
  { id: "warn-0631", channel: "motion", threshold: 91, message: "Budget watch 0631 on motion channel: rebalance before sign-off." },
  { id: "warn-0632", channel: "gold", threshold: 92, message: "Budget watch 0632 on gold channel: rebalance before sign-off." },
  { id: "warn-0633", channel: "glow", threshold: 93, message: "Budget watch 0633 on glow channel: rebalance before sign-off." },
  { id: "warn-0634", channel: "motion", threshold: 94, message: "Budget watch 0634 on motion channel: rebalance before sign-off." },
  { id: "warn-0635", channel: "gold", threshold: 95, message: "Budget watch 0635 on gold channel: rebalance before sign-off." },
  { id: "warn-0636", channel: "glow", threshold: 96, message: "Budget watch 0636 on glow channel: rebalance before sign-off." },
  { id: "warn-0637", channel: "motion", threshold: 97, message: "Budget watch 0637 on motion channel: rebalance before sign-off." },
  { id: "warn-0638", channel: "gold", threshold: 98, message: "Budget watch 0638 on gold channel: rebalance before sign-off." },
  { id: "warn-0639", channel: "glow", threshold: 99, message: "Budget watch 0639 on glow channel: rebalance before sign-off." },
  { id: "warn-0640", channel: "motion", threshold: 20, message: "Budget watch 0640 on motion channel: rebalance before sign-off." },
  { id: "warn-0641", channel: "gold", threshold: 21, message: "Budget watch 0641 on gold channel: rebalance before sign-off." },
  { id: "warn-0642", channel: "glow", threshold: 22, message: "Budget watch 0642 on glow channel: rebalance before sign-off." },
  { id: "warn-0643", channel: "motion", threshold: 23, message: "Budget watch 0643 on motion channel: rebalance before sign-off." },
  { id: "warn-0644", channel: "gold", threshold: 24, message: "Budget watch 0644 on gold channel: rebalance before sign-off." },
  { id: "warn-0645", channel: "glow", threshold: 25, message: "Budget watch 0645 on glow channel: rebalance before sign-off." },
  { id: "warn-0646", channel: "motion", threshold: 26, message: "Budget watch 0646 on motion channel: rebalance before sign-off." },
  { id: "warn-0647", channel: "gold", threshold: 27, message: "Budget watch 0647 on gold channel: rebalance before sign-off." },
  { id: "warn-0648", channel: "glow", threshold: 28, message: "Budget watch 0648 on glow channel: rebalance before sign-off." },
  { id: "warn-0649", channel: "motion", threshold: 29, message: "Budget watch 0649 on motion channel: rebalance before sign-off." },
  { id: "warn-0650", channel: "gold", threshold: 30, message: "Budget watch 0650 on gold channel: rebalance before sign-off." },
  { id: "warn-0651", channel: "glow", threshold: 31, message: "Budget watch 0651 on glow channel: rebalance before sign-off." },
  { id: "warn-0652", channel: "motion", threshold: 32, message: "Budget watch 0652 on motion channel: rebalance before sign-off." },
  { id: "warn-0653", channel: "gold", threshold: 33, message: "Budget watch 0653 on gold channel: rebalance before sign-off." },
  { id: "warn-0654", channel: "glow", threshold: 34, message: "Budget watch 0654 on glow channel: rebalance before sign-off." },
  { id: "warn-0655", channel: "motion", threshold: 35, message: "Budget watch 0655 on motion channel: rebalance before sign-off." },
  { id: "warn-0656", channel: "gold", threshold: 36, message: "Budget watch 0656 on gold channel: rebalance before sign-off." },
  { id: "warn-0657", channel: "glow", threshold: 37, message: "Budget watch 0657 on glow channel: rebalance before sign-off." },
  { id: "warn-0658", channel: "motion", threshold: 38, message: "Budget watch 0658 on motion channel: rebalance before sign-off." },
  { id: "warn-0659", channel: "gold", threshold: 39, message: "Budget watch 0659 on gold channel: rebalance before sign-off." },
  { id: "warn-0660", channel: "glow", threshold: 40, message: "Budget watch 0660 on glow channel: rebalance before sign-off." },
  { id: "warn-0661", channel: "motion", threshold: 41, message: "Budget watch 0661 on motion channel: rebalance before sign-off." },
  { id: "warn-0662", channel: "gold", threshold: 42, message: "Budget watch 0662 on gold channel: rebalance before sign-off." },
  { id: "warn-0663", channel: "glow", threshold: 43, message: "Budget watch 0663 on glow channel: rebalance before sign-off." },
  { id: "warn-0664", channel: "motion", threshold: 44, message: "Budget watch 0664 on motion channel: rebalance before sign-off." },
  { id: "warn-0665", channel: "gold", threshold: 45, message: "Budget watch 0665 on gold channel: rebalance before sign-off." },
  { id: "warn-0666", channel: "glow", threshold: 46, message: "Budget watch 0666 on glow channel: rebalance before sign-off." },
  { id: "warn-0667", channel: "motion", threshold: 47, message: "Budget watch 0667 on motion channel: rebalance before sign-off." },
  { id: "warn-0668", channel: "gold", threshold: 48, message: "Budget watch 0668 on gold channel: rebalance before sign-off." },
  { id: "warn-0669", channel: "glow", threshold: 49, message: "Budget watch 0669 on glow channel: rebalance before sign-off." },
  { id: "warn-0670", channel: "motion", threshold: 50, message: "Budget watch 0670 on motion channel: rebalance before sign-off." },
  { id: "warn-0671", channel: "gold", threshold: 51, message: "Budget watch 0671 on gold channel: rebalance before sign-off." },
  { id: "warn-0672", channel: "glow", threshold: 52, message: "Budget watch 0672 on glow channel: rebalance before sign-off." },
  { id: "warn-0673", channel: "motion", threshold: 53, message: "Budget watch 0673 on motion channel: rebalance before sign-off." },
  { id: "warn-0674", channel: "gold", threshold: 54, message: "Budget watch 0674 on gold channel: rebalance before sign-off." },
  { id: "warn-0675", channel: "glow", threshold: 55, message: "Budget watch 0675 on glow channel: rebalance before sign-off." },
  { id: "warn-0676", channel: "motion", threshold: 56, message: "Budget watch 0676 on motion channel: rebalance before sign-off." },
  { id: "warn-0677", channel: "gold", threshold: 57, message: "Budget watch 0677 on gold channel: rebalance before sign-off." },
  { id: "warn-0678", channel: "glow", threshold: 58, message: "Budget watch 0678 on glow channel: rebalance before sign-off." },
  { id: "warn-0679", channel: "motion", threshold: 59, message: "Budget watch 0679 on motion channel: rebalance before sign-off." },
  { id: "warn-0680", channel: "gold", threshold: 60, message: "Budget watch 0680 on gold channel: rebalance before sign-off." },
  { id: "warn-0681", channel: "glow", threshold: 61, message: "Budget watch 0681 on glow channel: rebalance before sign-off." },
  { id: "warn-0682", channel: "motion", threshold: 62, message: "Budget watch 0682 on motion channel: rebalance before sign-off." },
  { id: "warn-0683", channel: "gold", threshold: 63, message: "Budget watch 0683 on gold channel: rebalance before sign-off." },
  { id: "warn-0684", channel: "glow", threshold: 64, message: "Budget watch 0684 on glow channel: rebalance before sign-off." },
  { id: "warn-0685", channel: "motion", threshold: 65, message: "Budget watch 0685 on motion channel: rebalance before sign-off." },
  { id: "warn-0686", channel: "gold", threshold: 66, message: "Budget watch 0686 on gold channel: rebalance before sign-off." },
  { id: "warn-0687", channel: "glow", threshold: 67, message: "Budget watch 0687 on glow channel: rebalance before sign-off." },
  { id: "warn-0688", channel: "motion", threshold: 68, message: "Budget watch 0688 on motion channel: rebalance before sign-off." },
  { id: "warn-0689", channel: "gold", threshold: 69, message: "Budget watch 0689 on gold channel: rebalance before sign-off." },
  { id: "warn-0690", channel: "glow", threshold: 70, message: "Budget watch 0690 on glow channel: rebalance before sign-off." },
  { id: "warn-0691", channel: "motion", threshold: 71, message: "Budget watch 0691 on motion channel: rebalance before sign-off." },
  { id: "warn-0692", channel: "gold", threshold: 72, message: "Budget watch 0692 on gold channel: rebalance before sign-off." },
  { id: "warn-0693", channel: "glow", threshold: 73, message: "Budget watch 0693 on glow channel: rebalance before sign-off." },
  { id: "warn-0694", channel: "motion", threshold: 74, message: "Budget watch 0694 on motion channel: rebalance before sign-off." },
  { id: "warn-0695", channel: "gold", threshold: 75, message: "Budget watch 0695 on gold channel: rebalance before sign-off." },
  { id: "warn-0696", channel: "glow", threshold: 76, message: "Budget watch 0696 on glow channel: rebalance before sign-off." },
  { id: "warn-0697", channel: "motion", threshold: 77, message: "Budget watch 0697 on motion channel: rebalance before sign-off." },
  { id: "warn-0698", channel: "gold", threshold: 78, message: "Budget watch 0698 on gold channel: rebalance before sign-off." },
  { id: "warn-0699", channel: "glow", threshold: 79, message: "Budget watch 0699 on glow channel: rebalance before sign-off." },
  { id: "warn-0700", channel: "motion", threshold: 80, message: "Budget watch 0700 on motion channel: rebalance before sign-off." },
] as const;

export function pickGovernanceWarnings(channel: "glow" | "motion" | "gold", value: number, limit = 3): readonly string[] {
  return GOVERNANCE_WARNING_LIBRARY.filter((item) => item.channel === channel && value >= item.threshold).slice(0, limit).map((item) => item.message);
}

